### ISSUE TITLE
Reloading in iOS simulator exits app and goes to expo screen

### ISSUE THREAD

**Issue by ericvicenti** [react-community/create-react-native-app#103]
I'm having a bad time in my fresh CRNA when I run `npm run ios`. It works, but on every refresh I get booted to the expo project screen, and I need to tap back into my app.

RN scripts `v0.0.22`
Expo `1.14.1.106624`

Is this a known problem, or am I doing something wrong?

**Comment by dikaiosune** [comment]
Thanks for the report!

Can you try resetting your simulator's content and settings?

**Comment by ericvicenti** [comment]
Welp, that fixed it!

Is this something that might happen again in the future? Is there a way to protect against this bad state?

**Comment by dikaiosune** [comment]
Cool!

I've not seen this specific issue before, but we've had enough weird issues like this with the Expo app in the simulator that it's kind of my default troubleshooting step.

**Comment by ericvicenti** [comment]
Gotcha. For what its worth, I was developing something in node_modules and hence had to restart the server frequently because of https://github.com/facebook/react-native/issues/13019

**Comment by dikaiosune** [comment]
I'm being told that this nuclear option usually isn't needed, but that there may be an issue with the latest update to the app. Will investigate tomorrow.
