### ISSUE TITLE
Expose the ability to run packager on custom port

### ISSUE THREAD

**Issue by axemclion** [react-community/create-react-native-app#108]
The packager hostname would be configurable using `REACT_NATIVE_PACKAGER_HOSTNAME`. Would be great to have it specify a port too. 

Today, an open port above 19001 is used and the packager is started there. However, there may be firewall rules that may prevent incoming connections to that port. Making it configurable would help.

**Comment by mhsjlw** [comment]
Progress on this?

**Comment by VincentKLX** [comment]
My firewall block me too, and I find have a custom port is a good idea.
Something new about it ?

**Comment by brentvatne** [comment]
A PR to support this would be very welcome :)

**Comment by sladec** [comment]
Need this option to run on Cloud9 IDE http://c9.io,   they only allow port 8080/1/2

**Comment by nickcarenza** [comment]
Make a .exprc file like this with whatever port you want.

```
{
	"manifestPort": 8000
}
```

It seems to be an undocumented config file.

**Comment by grange74** [comment]
Adding _manifestPort_ to a _.exprc_ file as suggested above seems to change the _expoServerPort_ from its default of 19000. Still not sure how to change _packagerPort_ from default 19001.
Also tried running `npm start -- --port=8081` but that doesn't seem to help.

**Comment by murugaratham** [comment]
this is a really great addition, my corporate network guys do not like opening ports and exactly like what @axemclion said, CRNA already have a environment value that let us configure hostname, what about port?

**Comment by fson** [comment]
The Metro bundler port is currently configurable through the `expo.packagerOpts.port` property in `app.json`, e.g.:
```json5
{
  "expo": {
    "sdkVersion": "25.0.0",
    "packagerOpts": {
      "port": 8787
    }
  }
}
```

**Comment by dawnmist** [comment]
@fson Your solution does not work, because expo doesn't reset its auto-created port to what is in the app.json file prior to starting the packager.

Packager port is set here:
https://github.com/expo/xdl/blob/ec7560e3d884afa02f728ac30a4a7f3a20ad2200/src/Project.js#L1088

User settings is set here:
https://github.com/expo/xdl/blob/ec7560e3d884afa02f728ac30a4a7f3a20ad2200/src/Project.js#L1107-L1124

And they use the `packagerPort` variable directly without having checked for user settings to have changed it when creating the server here:
https://github.com/expo/xdl/blob/ec7560e3d884afa02f728ac30a4a7f3a20ad2200/src/Project.js#L1167-L1170

**Comment by dawnmist** [comment]
@evansmusomi The server doesn't actually get started until https://github.com/expo/xdl/blob/62e4601665f88b411969cfb8b929801798c03478/src/Project.js#L1171 - the line you've marked is where a default free port value gets set. The PR I sent then overwrites that default value with whatever is found in the userPackagerOpts in the section where those userPackagerOpts are being processed prior to actually starting the server. So by the time the server start at L1171 is being called, the original default value has been replaced with your own custom one.

**Comment by fkereki** [comment]
I'm trying the latest version of CRNA, and even setting app.json to:

{
    "expo": {
        "sdkVersion": "27.0.0",
        "packagerOpts": {
            "port": 8787
        }
    }
}

when I do `npm start`, the .expo/packager-info.json file shows the packager port to be 19001:

{
`  "expoServerPort": 19000,`
`  "packagerPort": 19001,`
`  "packagerPid": 15856`
}

**Comment by Ben888GitHub** [comment]
@fson Hello Sir, How do I change the expoServerPort to 3000?

**Comment by Mray000** [comment]
@fson Hello Sir, How do I change the webpackServerPort to 3000?

**Comment by eddyhdzg** [comment]
How do I change the webpackServerPort to 3000?

**Comment by paramsiddharth** [comment]
> How do I change the webpackServerPort to 3000?

Same here. How can I change the Webpack port?
