### ISSUE TITLE
Error in trying to run demo app

### ISSUE THREAD

**Issue by philggg** [react-community/create-react-native-app#110]
## Description

I am following the instructions to run the sample app.  It fails both using an Android and IOS device with the same error.

## Observed Behavior

Error

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
9:51:53 PM: (node:13992) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection
olveError: Unable to resolve module `@expo/vector-icons/glyphmaps/Entypo.json` from `C:\react\my-
xpo\vector-icons\Entypo.js`: Module does not exist in the module map or in these directories:
  C:\react\my-project\node_modules\@expo\vector-icons\node_modules\@expo\vector-icons\glyphmaps
,   C:\react\my-project\node_modules\@expo\vector-icons\glyphmaps

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start --reset-cache`.

```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:-- react-native-scripts@0.0.22
* `npm ls react-native`:-- react-native@0.42.3
* `npm ls expo`:-- react-native@0.42.3
* `node -v`:v7.7.4
* `npm -v`:4.1.2
* `yarn -v`:v0.21.3

Also specify:

1. Operating system: Windows 8.1
2. Phone/emulator/simulator & version:
IOS 10,2,,   Samsung Tab 3 running KitKat.

**Comment by dikaiosune** [comment]
Hi! Thanks for the report. I'll mark this as `awaiting-reply`, pending a reproducible demo as requested in the issue template. Please feel free to paste the code that caused this in a reply to this comment inside of a code block. Thanks!

**Comment by kartheekgj** [comment]
Hi i tried using npm but unable to run the demo project  by using command 
"npm install -g create-react-native-app" , "create-react-native-app my-app"
Node version 6.10.1
npm version 4.4.1

**Comment by philggg** [comment]
I used the instructions on the Introduction page.  https://facebook.github.io/react-native/blog/2017/03/13/introducing-create-react-native-app.html

$ npm i -g create-react-native-app
$ create-react-native-app my-project
$ cd my-project
$ npm start

**Comment by dikaiosune** [comment]
Hm, interesting. I tried to reproduce this in a very similar environment (Windows 10, yarn 0.21.3, react-native-scripts 0.0.23, react-native 0.42.3) and wasn't able to with the bare template project. Can you upload your project to a github repository so that I can see if something went wrong in creating the project?

**Comment by philggg** [comment]
Here is a git repository with the directory.. 
https://github.com/philggg/create-react-native-bug

BTW, one thing I noticed is that the way the directories/files get built  it is very easy to trigger a Windows error  for path names too long  (there are many deeply nested directories).  If I take this directory and nest it one level deeper in my filesystem I start to get the errors.  I have not seen the errors with this directory, but I have a concern that that might be an issue for some people depending on where in the filesystem they put their projects.

**Comment by dikaiosune** [comment]
Do you have watchman installed? Can you run `watchman version` in cmd/powershell (wherever you're running the packager scripts) and let me know what the output is?

Also, does this change if you delete your node_modules folder and reinstall your dependencies?

**Comment by philggg** [comment]
First regarding Watchman.  I heard that the Windows version is Alpha so I did not install previously.  But I loaded the windows version.  It is version 3.7.0 (but I am not sure if it is functioning correctly).

When I delete the node_modules folder and reinstall I get a new error:

7:43:44 PM: (node:12508) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): NotFoundError:
 Cannot find entry file node_modules/react-native-scripts/build/bin/crna-entry.js in any of the roots: ["C:\\react\\my-a
pp"]


BTW, I get the same errors when running in the Android simulator in Genymotion.

**Comment by dikaiosune** [comment]
Does that file exist in node_modules? Does the scripts package exist in your package.json?

**Comment by philggg** [comment]
Yes that file exists in the correct spot.
thanks

**Comment by dikaiosune** [comment]
Can you try the steps [here](https://github.com/react-community/create-react-native-app/issues/136#issuecomment-290201523)?

**Comment by delianides** [comment]
Having this issue as well on a new [project](https://github.com/NewSpring/Junction-Native). Running all the last but I'm building on Mac not windows.

**Comment by philggg** [comment]
I tried the steps in the linked page and I continue to get the same error.
I guess this illustrates the issues of developing on a platform (Windows) that is different than the mainline developers are on.  I will probably have to move to Mac.
thanks
Phil

**Comment by dikaiosune** [comment]
@philggg we actually do quite a lot of testing on Windows and I care a lot about making sure that Windows developers are able to use CRNA, but I've been unable to reproduce this error. Can you try updating to `react-native-scripts` 0.0.26? There are a few fixes for caching issues there.

**Comment by philggg** [comment]
I updated to react-native-scripts 0.0.26.  Unfortunately same error.
thanks

**Comment by lukecwilliams** [comment]
I'm still getting this with Expo 16.0 - thread on it here, apparently an issue with babel-preset-expo.
https://github.com/tleunen/babel-plugin-module-resolver/issues/167

**Comment by brentvatne** [comment]
this was a bug with babel-plugin-module-resolver and it was.. ahem. resolved.

**Comment by suuuuuuuuperman** [comment]
macos also exists the problems:(

**Comment by adrian4uno** [comment]
you must install watchman

npm install -g watchman

it works for me

**Comment by eric-grab** [comment]
Similar problem:
```
Determining test suites to run...Error: This promise must be present when running with -o.
    at /Users/eric.nguyen/ReactNativeProjects/AwesomeProject/node_modules/jest/node_modules/jest-cli/build/search_source.js:202:17
    at Generator.next (<anonymous>)
    at step (/Users/eric.nguyen/ReactNativeProjects/AwesomeProject/node_modules/jest/node_modules/jest-cli/build/search_source.js:19:362)
    at /Users/eric.nguyen/ReactNativeProjects/AwesomeProject/node_modules/jest/node_modules/jest-cli/build/search_source.js:19:592
    at Promise (<anonymous>)
    at /Users/eric.nguyen/ReactNativeProjects/AwesomeProject/node_modules/jest/node_modules/jest-cli/build/search_source.js:19:273
    at SearchSource.getTestPaths (/Users/eric.nguyen/ReactNativeProjects/AwesomeProject/node_modules/jest/node_modules/jest-cli/build/search_source.js:216:10)
    at /Users/eric.nguyen/ReactNativeProjects/AwesomeProject/node_modules/jest/node_modules/jest-cli/build/run_jest.js:44:29
    at Generator.next (<anonymous>)
    at step (/Users/eric.nguyen/ReactNativeProjects/AwesomeProject/node_modules/jest/node_modules/jest-cli/build/run_jest.js:23:380)
```

npm version 4.6.1
packaged.json (not modified):
```
{
  "name": "AwesomeProject",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "1.8.1",
    "jest-expo": "23.0.0",
    "react-test-renderer": "16.0.0"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^23.0.4",
    "react": "16.0.0",
    "react-native": "0.50.3"
  }
}
```

**Comment by RomeoMo** [comment]
@adrian4uno Thank you SO MUCH! It works for me!

**Comment by webdevinci** [comment]
Isn't watchman deprecated now? I have this issue now. Going to the npm clear cache and remove node_modules route now. I really dislike the expo + react-native experience. I spend an hour updating, or deleting/re-installing node_modules every day that I work on my project (on my mac or PC). Anyone else have this? Or am I just not meant to be part of the community? :(

**Comment by ThatGuySam** [comment]
Installing watchmen didn't really help. 

Not a permanent solution, but this is what got me going again. 

`rm -rf node_modules/ yarn.lock package-lock.json && npm install`
