### ISSUE TITLE
Upgrade guide for 14.x.x to 15.x.x

### ISSUE THREAD

**Issue by kdenz** [react-community/create-react-native-app#111]
I've started using CRNA for a couple of days when it's 0.19. Now it's 0.22. When I updated to 0.22, expo sdk from 14.x.x to 15.x.x in package.json, as well as dependencies such as react-native, it broke my app. It turns out that I need to update sdkVersion from 14.0.0 to 15.0.0 in app.json manually.

Perhaps a small section can added to the docs here about how to update expo sdk for CRNA users? Something like this: https://blog.expo.io/expo-sdk-v15-0-0-is-now-available-2132538fd4fb#.609dr4x6oa

**Comment by kdenz** [comment]
It turns out there is already one here, lol.

**Comment by babenzele** [comment]
> It turns out there is already one here, lol.
Where?

**Comment by dikaiosune** [comment]
@babenzele https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/template/README.md#updating-to-new-releases
