### ISSUE TITLE
'create-react-native-app' failing on my iOS device

### ISSUE THREAD

**Issue by GerardVee** [react-community/create-react-native-app#113]
## Description

I followed the "get started" instructions, but I'm unable to open the app on iOS.

## Observed Behavior

I ran "npm start," navigated to exp://192.168.0.8:19000 (QR method times out) on my iOS device in the Expo app. There was no terminal output. However, there was this error in the Expo app:

```
"This experience uses an unsupported version of Expo (SDK 15.0.0). You may need to update Expo." (code undefined).
```

## Environment

* `npm ls react-native-scripts`: react-native-scripts@0.0.25
* `npm ls react-native`: react-native@0.42.3
* `npm ls expo`: expo@15.1.2
* `node -v`: v6.0.0
* `npm -v`: 3.8.6
* `yarn --version`: n/a
* `watchman version`: n/a

1. Operating system: Windows 10
2. Phone/emulator/simulator & version: iPhone 6 Plus 10.2 (14C92)

**Comment by terribleben** [comment]
Hi, your project uses the newest Expo SDK, but you may have an older version of Expo Client app on your device which predates that SDK. The [latest version in the app store](https://itunes.apple.com/us/app/expo-client/id982107779?mt=8) is 1.14.1 at the moment. Can you try updating?

Either way, the error message you encountered is definitely ambiguous and could be clarified. We'll fix this in the next update.

**Comment by dikaiosune** [comment]
@GerardVee thanks for the report! As @terribleben noted above, this error message should be improved soon. Please reopen this issue if updating the Expo app on your phone doesn't resolve the error you're seeing.

**Comment by GerardVee** [comment]
Hello. After updating the app, I've ran into different issues now. The terminal now states when starting packager:

```
Starting packager...
***ERROR STARTING PACKAGER***
Starting React Native packager...
```

and in the Expo app, it errors out, an states the following:

```
"Error while loading: The request timed out.." (code -1001)
```

Yet, the device can easily access http://192.168.0.8:19000, and the object is printed out perfectly well. 
I thank you for your assistance and hope this can be sorted out soon.

**Comment by dikaiosune** [comment]
Can you paste the full terminal output that includes the error starting the packager?

**Comment by GerardVee** [comment]
The output is:

```
> react-native-scripts start

Starting packager...
***ERROR STARTING PACKAGER***
Starting React Native packager...

'yarn' is not recognized as an internal or external command,
operable program or batch file.

Packager started!

To view your app with live reloading, point the Expo app to this QR code.
You'll find the QR scanner on the Projects tab of the app.
[QR Code]

Or enter this address in the Expo app's search bar:

  exp://192.168.130.1:19000 (this only works if I go to the IP of my computer: 192.168.0.8:19000)

Your phone will need to be on the same local network as this computer.

For links to install the Expo app, please visit https://expo.io.

Logs from serving your app will appear here. Press Ctrl+C at any time to stop.
```

**Comment by dikaiosune** [comment]
Interesting. Do you see the same error if you start the packager with `npm start`?

**Comment by GerardVee** [comment]
Yes, as I was starting the above with ``` npm start ```.

**Comment by juanmnl** [comment]
I have this same issue, but on the iOS emulator.
I started a brand new project and there's no error in the console.

`Node v7.7.4` `Npm 4.1.2` on macOS Sierra 10.12.3.

<img width="351" alt="screen shot 2017-03-26 at 2 43 50 pm" src="https://cloud.githubusercontent.com/assets/699945/24333691/f97ce13e-1232-11e7-9b30-7ed528e0d2c0.png">

**Comment by davidlee1435** [comment]
+1; I have the same issue as @juanmnl

**Comment by dikaiosune** [comment]
@GerardVee does your project have a yarn.lock file in the root directory? If the lockfile exists and you have yarn installed, can you try using `yarn start` to run the packager? If you don't have yarn installed, can you try deleting the yarn.lock file?

**Comment by GerardVee** [comment]
@dikaiosune I don't have yarn installed, and a yarn.lock file does not exist.

**Comment by GerardVee** [comment]
Thanks for the help everyone! I'm happy to say, I've found a solution: By running

```
set REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.8
```

I've managed to clear up a conflict where in my app would connect to the correct IP (192.168.0.8) but look for some (packager?) info at (192.168.130.1:19001) which it would fail to connect to. Maybe it should be added to the README that after failing to connect, try manually setting the IP? Anyways, thank you lots!

**Comment by dikaiosune** [comment]
Wonderful! Thanks for letting us know!

**Comment by CodyBrouwers** [comment]
I ran into the same issue as @GerardVee on my iPhone, even after updating the Expo app. What ended up working was deleting the app entirely and re-downloading from the app store just as suggested above on the simulator.

**Comment by anabaei** [comment]
I had same issue, just remove the Expo app by holding `alt` and `tab` then everything works fine!

**Comment by vidhyeshp** [comment]
Hi,

I am running the native app on IOS device (connected on WIFI), connected with my system on LAN. But I am not able to run this app.

**Comment by vidhyeshp** [comment]
Error : exp://192.168.100.108:19000
Error while loading: The request timed out (code - 10001)

Please do help, its getting little frustrating.

Also guide with the steps for running it properly and share some other techniques.

**Comment by brentvatne** [comment]
@vidhyeshp - try downloading exp and running the project through that -- `npm i -g exp` and then `exp start`
