### ISSUE TITLE
Must specify a java package in order to build this experience for Android. Please specify one in app.json at "expo.android.package"

### ISSUE THREAD

**Issue by kenpeter** [react-community/create-react-native-app#114]
## Description

Must specify a java package in order to build this experience for Android. Please specify one in app.json at "expo.android.package"

## Expected Behavior

git clone my personal project: https://github.com/kenpeter/osmosis_seek_android
run exp build:android
Expect it build successfully.

## Observed Behavior

git clone my personal project: https://github.com/kenpeter/osmosis_seek_android
run exp build:android

```
Must specify a java package in order to build this experience for Android. Please specify one in app.json at "expo.android.package"
```
More detail here: Detail here: https://stackoverflow.com/questions/42967465/created-an-app-with-create-react-native-app-how-to-publish-it-to-the-google-pla

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:

osmosis-seek-android@0.1.0 /var/www/html/test/testme/seekandroid
├── UNMET PEER DEPENDENCY react-native@0.42.3
└── react-native-scripts@0.0.22 

npm ERR! peer dep missing: react-native@0.41.2, required by react-native-scalable-image@0.1.0

* `npm ls react-native`:

osmosis-seek-android@0.1.0 /var/www/html/test/testme/seekandroid
└── UNMET PEER DEPENDENCY react-native@0.42.3

npm ERR! peer dep missing: react-native@0.41.2, required by react-native-scalable-image@0.1.0
npm ERR! code 1

* `npm ls expo`:

├── expo@15.1.2 
└── UNMET PEER DEPENDENCY react-native@0.42.3

npm ERR! peer dep missing: react-native@0.41.2, required by react-native-scalable-image@0.1.0

* `node -v`:

v6.10.0

* `npm -v`:

3.10.10

* `yarn --version`:

0.21.3

* `watchman version`:
none

Also specify:

1. Operating system: ubuntu 16.04, 64 bit

2. Phone/emulator/simulator & version: nexus 6p or emulator

## Reproducible Demo

https://github.com/kenpeter/osmosis_seek_android

**Comment by dikaiosune** [comment]
Hi! Thanks for the detailed report! The issue here appears to be that your project has both app.json and expo.json files, which aren't correctly merged right now. If you delete app.json, building your project should work.

Since this is an issue with the `exp` tool, I've opened an issue there: https://github.com/exponent/exp/issues/41, and am closing this one.

**Comment by dikaiosune** [comment]
Also, if you delete app.json, you'll also need to rename `expo.json` to `exp.json`, I believe.

**Comment by dbMundada** [comment]
Got similar issue:
**Must specify a java package in order to build this experience for Android. Please specify one in app.json at "expo.android.package"**
with 
node: v8.5.0
npm: 5.3.0
expo: 19.0.1

**I have only app.json in my project. Not have exp.json/expo.json.**
Can anyone please help me regarding this.

**Comment by freundallein** [comment]
Check if your app.json is look like this: 
 ```
{
   "expo": {
    "name": "Your App Name",
    "icon": "./path/to/your/app-icon.png",
    "version": "1.0.0",
    "slug": "your-app-slug",
    "sdkVersion": "17.0.0",
    "ios": {
      "bundleIdentifier": "com.yourcompany.yourappname"
    },
    "android": {
      "package": "com.yourcompany.yourappname"
    }
   }
 }

**Comment by figitaki** [comment]
@freundallein I'm having the same issue and my `app.json` has the exact same password as you provided. Same order, the only changes are the values.

**Comment by omarshiha** [comment]
same problem here
' Must specify a java package in order to build this experience for Android. Please specify one in app.json at "expo.android.package" '

**Comment by freundallein** [comment]
@figitaki, it's strange, because i had the same issue and solve it after check my braces be like:
`{
    "expo": {
        "android": {
            "package": "anything"
        }
    }
}`

**Comment by omarshiha** [comment]
i am having the same exact structure, dont know why it cant find the android package name

**Comment by organicnz** [comment]
On the same stage :( Can anyone give a thought?

**Comment by brentvatne** [comment]
here's an example of a valid android package in app.json https://github.com/brentvatne/growler-prowler/blob/master/app.json

**Comment by organicnz** [comment]
Maybe the build error was related to `versionCode` line that's why it caused a build issue. I've just tried to delete this record then rebuild again, however this error `[exp] Cannot start new build, as there is a build in progress.` still appears.  

```
 "android": {
      "package": "com.cleanme.cleanme",
      "versionCode": "16.8"  
    }
```

**Comment by armyofda12mnkeys** [comment]
try creating a unique package name, i think i was using one from a tutorial and it errored until i changed to something like com.$myname.$appname so com.johnasmithablah.fitnessapp

**Comment by TAHERx** [comment]
i change this code:

>     "ios": {
>       "supportsTablet": true,
>       "bundleIdentifier": "com.T.RS"
>     },
>     "android": {
>       "package": "com.T.RS"
>     }

to this code:

>     "ios": {
>       "supportsTablet": true,
>       "bundleIdentifier": "com.yourcompany.yourappname"
>     },
>     "android": {
>       "package": "com.yourcompany.yourappname"
>     }

the problem solved to me

**Comment by kyriakos** [comment]
for anyone else having the same issue I solved it by moving the "android" portion in app.json inside "expo" key.
