### ISSUE TITLE
Could not load

### ISSUE THREAD

**Issue by rizwanahmed19** [react-community/create-react-native-app#115]
## Description

After running packager when I scan the QR code I get a blue screen saying something went wrong. Could not load exp://192.168.99.109:19000

## Observed Behavior

I get a blue screen saying could not connect to the server.

Here's the console error message
```
Uncaught Error: java.net.ConnectException: Failed to connect to /192.168.99.109:19000
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: -- react-native-scripts@0.0.25
* `npm ls react-native`: -- react-native-scripts@0.0.25
* `npm ls expo`: -- expo@15.1.2
* `node -v`: v6.9.1
* `npm -v`: 3.10.9
* `yarn --version`: 0.18.1
* `watchman version`:

Also specify:

1. Operating system: Window 8.1
2. Phone/emulator/simulator & version: I am using expo app on Moto X 1st generation with Android 5.1

**Comment by rizwanahmed19** [comment]
I tried to reinstall the expo app and now after fetching js bundle the app is stuck at the expo splash screen.

**Comment by dikaiosune** [comment]
Hi! Thanks for the report! Once you've started the packager, are you able to reach the URL it prints in your phone's browser if you replace `exp://` with `http://`?

**Comment by qualitydixon** [comment]
Hi! I am experiencing a very similar issue, though my environment is a little different:

* `npm ls react-native-scripts`: react-native-scripts@0.0.25
* `npm ls react-native`: react-native@0.42.3
* `npm ls expo`: expo@15.1.2
* `node -v`: v6.9.1
* `npm -v`: 3.10.8
* `yarn --version`: 0.21.3
* `watchman version`: "4.5.0"

1. Operating system: MacOS Sierra 10.12.3
2. Phone/emulator/simulator & version: Pixel XL - Android 7.1.1

`Once you've started the packager, are you able to reach the URL it prints in your phone's browser if you replace exp:// with http://?`

- No, the request times out and chrome shows "This site can't be reached"

I'm happy to help debug/test any potential solutions! Thanks!

**Comment by dikaiosune** [comment]
@qualitydixon thanks for the info -- are your phone and computer on the same network? You can often force this by using your phone's mobile hotspot or tethering feature.

**Comment by qualitydixon** [comment]
@dikaiosune Thanks for the help. I confirmed the phone and computer are on the same network and also tried it via tethering. Same result. I also tried to connecting my phone to my computer and running `yarn start android` but that also did not work.

**Comment by qualitydixon** [comment]
@dikaiosune After stepping away for a bit and coming back I noticed that the project was being served over my machines loopback address (`lo0`) by default. Once I set `REACT_NATIVE_PACKAGER_HOSTNAME` to my actual ip address (`en0`) everything works normally. Thanks for the help and let me know if there's any other information or assistance I can provide.

**Comment by dikaiosune** [comment]
@qualitydixon glad to hear that's working! Please let us know if there are other issues you run into 😁 

@rizwanahmed19 closing this for now, please ping me if you are still running into this issue. It's almost always related to network connectivity or configuration.
