### ISSUE TITLE
How many concurrent connections of Expo?

### ISSUE THREAD

**Issue by besutome** [react-community/create-react-native-app#119]
I want to know the number of simultaneous connections for use in a DEMO.
What is the maximum number of concurrent connections at Expo?

**Comment by dikaiosune** [comment]
I would expect the number of concurrent connections possible to the dev server to be very high (dozens or hundreds, probably?) but I haven't tested this myself. If you just want to share the demo after you've built it, you can create an Expo account and publish your project to share: https://blog.expo.io/publishing-on-exponent-790493660d24. Colleagues can then install the Expo app and load your project from the URL you get when publishing.
