### ISSUE TITLE
Clean up exiting the start script

### ISSUE THREAD

**Issue by dikaiosune** [react-community/create-react-native-app#12]
This is ugly in every way imaginable:

```
^C
Stopping packager...


130 adam@iceblade ~/testcrna
$ Packager stopped.
```

Need to return a 0 exit code if the user initiated the shutdown, and need to print 'Packager stopped.' before the new prompt is printed.

**Comment by grabbou** [comment]
Happy to take it

**Comment by dikaiosune** [comment]
This issue isn't present when I run the scripts directly. I think I need to improve the SIGINT handler for the scripts entry point.

**Comment by dikaiosune** [comment]
I think this is just due to yarn's implementation, and there's no way AFAIK for us to install a SIGINT handler within yarn. When running the script outside of yarn:

<img width="268" alt="screen shot 2017-02-14 at 4 39 41 pm" src="https://cloud.githubusercontent.com/assets/6812281/22956018/3cb6b764-f2d4-11e6-8f10-ddcbf47b63b8.png">
