### ISSUE TITLE
Support for victory-native (https://github.com/FormidableLabs/victory-native)

### ISSUE THREAD

**Issue by nikhilag** [react-community/create-react-native-app#121]
Is victory-native supported with create-react-native-app? 

I tried this example https://github.com/sibelius/victory-native-demo-crna which uses create-react-native-app but it didn't work. I got the following error message - "Error while updating property 'd' in shadow node of type:RNSVGPath" (see attached image).

I am already discussing this with the author but I just wanted to check in case it's a known issue that victory-native doesn't work with create-react-native-app.

![screenshot_20170327-161515](https://cloud.githubusercontent.com/assets/5186055/24357382/268cc16a-131b-11e7-89c9-54cfbc6fc7c7.png)

**Comment by dikaiosune** [comment]
Hi! victory-native does work when loaded in Expo, we use it in one of our test projects:

https://github.com/expo/native-component-list/blob/master/screens/SVGScreen.js

with this package.json:

https://github.com/expo/native-component-list/blob/master/package.json#L17

You can load the app in the Expo client at this URL:

https://expo.io/@community/native-component-list

You can find the victory-native example if you tap the `^` icon in the top right and scroll down to the SVG example.

I'd recommend trying this with the latest RN and SDK versions supported, the example project you linked [uses SDK 14](https://github.com/sibelius/victory-native-demo-crna/blob/master/package.json#L5). See the [versions guide](https://github.com/react-community/create-react-native-app/blob/master/VERSIONS.md) for information about upgrading.

cc @sibelius

**Comment by AvijitDutta95** [comment]
Hi! I'm also getting the same error message, but after saw your comment I just look over your test project, but I cannot understand the usage of react-native-svg in your SVGScreen.js file.
And I'm just trying with your code for render victory chart and getting this error:

![capture](https://cloud.githubusercontent.com/assets/26165120/24899835/650c97bc-1ebf-11e7-9c9a-8652a9b2c5f1.JPG)
