### ISSUE TITLE
Can't connect to exp://

### ISSUE THREAD

**Issue by rogerwf259** [react-community/create-react-native-app#123]
I've been fiddling with this problem since the release of CRNA, already tried setting my REACT_NATIVE_HOST_NAME environment variable to my actual IP address and also giving priority to my Wifi connection

**Comment by dikaiosune** [comment]
Hi! Sorry to hear that you're having problems. Make sure that environment variable you're setting is `REACT_NATIVE_PACKAGER_HOSTNAME`.

Also, in the future please make sure to use the issue template, it is much more difficult to help you with this without the information that's requested there.
