### ISSUE TITLE
React-devtools not working

### ISSUE THREAD

**Issue by florianpnn** [react-community/create-react-native-app#124]
Hi everyone,

I usually use `react-devtools` to help me navigate my react project and inspect what is going on in my project. It's a really helpful piece to debug.

Is there a way to have it working on the boilerplate without much efforts? And are you planning to implement it out of the box?

**Comment by dikaiosune** [comment]
I just created a fresh project and followed the instructions here: https://github.com/facebook/react-devtools/blob/master/packages/react-devtools/README.md

1. Created a fresh CRNA project
2. `yarn add --dev react-devtools`
3. added `"devtools": "react-devtools"` to my package.json's scripts section
4. `yarn run ios`, followed by `yarn run devtools` in a separate tab once the app had opened

And it seems to be mostly working:

<img width="1504" alt="screen shot 2017-03-28 at 1 32 39 pm" src="https://cloud.githubusercontent.com/assets/6812281/24426052/1f8d20f8-13bb-11e7-9a33-f2c35ba564f4.png">

Can you provide more details about what you tried and what didn't work? It may be a good idea to refer to the issue template for information that normally helps in debugging these issues.

If we can settle on a good set of steps to follow for getting this working, then I'd be very happy to add this to the user guide.

cc @gaearon

**Comment by florianpnn** [comment]
I went through the same process on a freshly created project and the dev tool app stays on the `Waiting for React to connect…` screen.

My guess would be the fact that expo is serving on the port `19000` while the dev tool is listening to `8097`.

**Comment by gaearon** [comment]
Which RN version does Expo use?

**Comment by florianpnn** [comment]
@gaearon according to the [docs](https://docs.expo.io/versions/v15.0.0/sdk/index.html#expo-sdk) (and if CRNA is using the latest SDK) it should run on 0.42.0.

**Comment by gaearon** [comment]
OK, this doesn't contain my React DevTools integration fix yet.
Please wait for these commits to land in a stable version:

https://github.com/facebook/react-native/commit/7a3ab96d94073b22853992b5e0b3f8e26b8cfd51 and https://github.com/facebook/react-native/commit/934cd82941d2b4fa49e49517acd454a775fe94b8 (looks like they landed in `v0.43.0-rc.0`)

**Comment by epitaphmike** [comment]
The above updates worked great. Thanks @gaearon. 
Just curious though, why aren't react-devtools part or CRNA by default. They seem like they should be available out of the box.

**Comment by dikaiosune** [comment]
@epitaphmike I'm not sure exactly what you mean -- those updates only went stable recently (less than 2 weeks ago, IIRC?), and I intend to release a new CRNA version in the next couple of days that includes them.

**Comment by dikaiosune** [comment]
@florianpnn @epitaphmike the new version of the CRNA template I released today includes RN 0.43, so this should all work. Let me know if you get a chance to try it, it'd be great to document in the user guide!

**Comment by epitaphmike** [comment]
I'll give it a run this weekend. Thanks for the work you've put into to
this project.

**Comment by gsklee** [comment]
I'm using `react-native@0.45.0-rc.0` and this doesn't seem to work; situation is the same with what @florianpnn described, the devtool app stays on the "Waiting for React to connect…" screen and says its listening to 8097.

**Comment by dikaiosune** [comment]
@gsklee note that 0.45 isn't yet compatible with CRNA, I'm not surprised you're having issues there. We'll probably support that in a few weeks.

**Comment by gsklee** [comment]
@dikaiosune got it, thanks!

**Comment by florianpnn** [comment]
@dikaiosune take the initiative to close this ticket if you think it shouldn't stay open. The last CRNA seems to work fine with the devtools.

**Comment by dikaiosune** [comment]
@florianpnn cool, thanks! Closing, but if you had to do anything special to get the devtools working let me know and we can document.

**Comment by gsklee** [comment]
@dikaiosune Okay, I think I've found out my problem. It works if I open the project with the iOS simulator (`yarn run ios`), but not when I open it with the Expo client (`yarn start`). Is it possible to make the devtools autoconnect when using the Expo client as well?

**Comment by brentvatne** [comment]
@gsklee - react-devtools with react-native only works in simulator currently. you can look into the `setupDevtools()` function in react-native and maybe modify it accordingly to work for you outside of the simulator: https://github.com/facebook/react-native/blob/29846283579a35abdd6a5e236c747736563fa200/Libraries/Core/Devtools/setupDevtools.js

**Comment by gaearon** [comment]
Maybe we can make [both of these](https://github.com/facebook/react-native/blob/29846283579a35abdd6a5e236c747736563fa200/Libraries/Core/Devtools/setupDevtools.js#L31-L36) configurable. Try hardcoding your computer's IP there, and if it works, we can provide some way to override the setting.

**Comment by brentvatne** [comment]
This actually worked just fine for me on my Android device without making any changes. I don't have an iOS device handy but did a quick search through the react-native source and noticed that `PlatformConstants.ServerHost` isn't defined on iOS, so it will always use `'localhost'` instead, which is why it only works in the simulator it seems. I think by just adding `PlatformConstants.ServerHost` to iOS this would work in most cases.

**Comment by happy-thorny** [comment]
My solution: [comment](https://github.com/expo/expo/issues/849#issuecomment-357455841)
