### ISSUE TITLE
Create interactive mode for packager?

### ISSUE THREAD

**Issue by anp** [react-community/create-react-native-app#126]
In addition to clearing the console, we could provide keyboard shortcuts for opening on Android/iOS, displaying QR code again, resetting packager cache, etc.

@brentvatne had this idea but was apparently too lazy to open an issue :P

**Comment by brentvatne** [comment]
- open android
- open ios
- display qr code
- reset packager
- reset packager & clear cache

**Comment by Palisand** [comment]
- dev / no-dev mode (#321)
