### ISSUE TITLE
About android and ios directories

### ISSUE THREAD

**Issue by davidgit75** [react-community/create-react-native-app#131]
Hello, How can I watch android and ios directories with the project to modify bundle (and other files) after I install some packages?
Thanks

## Description

I don't know how can I modify files like bundle because I don't know how generate android or ios directory.

## Environment

1. Operating system: MacOS
2. Phone/emulator/simulator & version: Motorola Moto G4 Plus.

**Comment by dikaiosune** [comment]
Can you explain more about what you're looking for? CRNA doesn't include ios or android directories because the native code isn't available to modify -- it's prebuilt in the Expo client.

**Comment by davidgit75** [comment]
@dikaiosune So, How I include aditional libraries, for examples react-native-firebase-analytics, so this library need add some information on bundle.
And this is the structure:

```
  - .expo
  - .idea
  - node_modules 
  .babelrc
  .flowconfig
  .gitignore
  .watchmanconfig
  App.js
  app.json
  App.test.js
  package.json
  README.md
  yarn.lock
```

**Comment by dikaiosune** [comment]
Ah, I see. You'll need to either eject (`npm run eject`) or create a new project with react-native-cli, as it's not possible to include custom native code in a CRNA project. For more information see [the README](https://github.com/react-community/create-react-native-app#what-are-the-limitations-of-create-react-native-app).
