### ISSUE TITLE
AppRegistry is not a registerd callable module. After publish to exp

### ISSUE THREAD

**Issue by msdark** [react-community/create-react-native-app#134]
## Description

After publishing the app to exp using `exp publish` the app doesn't load in the expo client showing errors about AppRegistry and babeHelpers

## Expected Behavior

The app should run in the expo client

## Observed Behavior

![img_0871](https://cloud.githubusercontent.com/assets/282006/24438055/2c85f54a-141b-11e7-8f33-d4fa5ae3b510.PNG)

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@0.0.18
* `npm ls react-native`: react-native@0.41.2
* `npm ls expo`: expo@14.0.2
* `node -v`: v7.7.2
* `npm -v`: 4.1.2
* `yarn --version`: 0.21.3
* `watchman version`: 4.7.0

Also specify:

1. Operating system: MacOS
2. Phone/emulator/simulator & version: iPhone 7

## Reproducible Demo

https://exp.host/@matiasfh/logros

**Comment by dikaiosune** [comment]
Thanks for the report! I'm currently able to load this demo on iOS and Android (see below, respectively). Did you change anything on the published copy of this since reporting this issue?

<img width="150" alt="screen shot 2017-03-29 at 2 28 35 pm" src="https://cloud.githubusercontent.com/assets/6812281/24477491/086ac412-148c-11e7-93bb-8bae4fb36459.png">

<img width="150" src="https://cloud.githubusercontent.com/assets/6812281/24477512/1de6f0ae-148c-11e7-8fcb-1b46ce46ae8f.png">

**Comment by msdark** [comment]
I did a change.
I think the issue was because I update some of the dependencies.

Finally I recreate the app and works good.
You can close it.

Matias Hernández Arellano
Desde el móvil

**Comment by dikaiosune** [comment]
Glad to hear it's working for you now!

**Comment by slorber** [comment]
I also got this error.

Surprisingly 2 days later I didn't touch anything and run "exp publish" and my app was not crashing anymore on Expo app. This is weird :)

**Comment by slorber** [comment]
Note that my looked quite related to default stories made available with storybook (like the "hello button" story). I was shipping storybook to prod actually. But now everything works fine, even when shipping Storybook to prod so it seems unrelated. Quite weird :)

**Comment by slorber** [comment]
@dikaiosune I'm able to reproduce this issue again. This time it only happens on iOS devices and the Android version works fine.

You can see for example the problem in my [published app](https://exp.host/@slorber/shoootin-photographers)

**Comment by slorber** [comment]
Just redeployed and the problem went away, it's the same code as before so I don't know what was causing the problem :o unfortunatly

**Comment by brentvatne** [comment]
@slorber - weren't we discussing this on slack? I think it was related your babelrc / react-optimize plugin
