### ISSUE TITLE
Cant reach exp:// on expo app 

### ISSUE THREAD

**Issue by rogerwf259** [react-community/create-react-native-app#138]
## Description
Can't access app/project from the expo app on my phone neither from the pc i am using as a server.

What action did you perform, and what did you expect to happen?

Set the REACT_NATIVE_PACKAGER_HOSTNAME to my ip address
and gave preference to wifi over any other network, but it still didn't work.

If there's an error message, please paste the *full terminal output and error message* in this code block:
```
There aren't any errors showing on the terminal.
```

## Environment

* `npm ls react-native-scripts`: react-native-scripts@0.0.26
* `npm ls react-native`: react-native@0.42.3
* `npm ls expo`: expo@15.1.2
* `node -v`: v7.3.0
* `npm -v`: 3.10.10
* `yarn --version`: 0.21.3
* `watchman version`: not installed

1. Operating system: Windows 10
2. Phone/emulator/simulator & version: expo app on IOS 10.0.2

![69576417-6afa-455b-805b-22b5228aae33](https://cloud.githubusercontent.com/assets/15176421/24467218/e745746e-1470-11e7-987b-75a9889df36f.jpg)

**Comment by dikaiosune** [comment]
Hi! Thanks for the report. Are you able to, after starting the packager (npm/yarn start) reach 192.168.1.68:19000 from a web browser on the computer and your phone?

**Comment by rogerwf259** [comment]
Thanks for replying.

Yes and this is what i get:

{
sdkVersion: "15.0.0",
name: "expo_test",
slug: "expo_test",
version: "0.1.0",
xde: true,
developer: {
tool: "crna"
},
packagerOpts: {
hostType: "tunnel",
lanType: "ip",
dev: true,
strict: false,
minify: false,
urlType: "exp",
urlRandomness: null
},
env: { },
bundleUrl: "http://192.168.1.68:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles",
debuggerHost: "192.168.1.68:19001",
mainModuleName: "./node_modules/react-native-scripts/build/bin/crna-entry",
logUrl: "http://192.168.1.68:19000/logs",
id: "@anonymous/expo_test-be701b24-38f0-45f8-a678-c970fbc05cc3"
}

And now i'm also getting this error (for the first time) : 20:16:10: Warning: Problem in app.json. See https://docs.expo.io/versions/v15.0.0/guides/configuration.html.
  - slug does not match pattern "^[a-zA-Z0-9\\-]+$".

**Comment by dikaiosune** [comment]
I'm looking into why the underscore isn't supported -- can you try changing your package name to include a dash instead of an underscore?

**Comment by JeremyBYU** [comment]
I'm having the same issue:

Heres output of `ipconfig`
```
Ethernet adapter VirtualBox Host-Only Network #2:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::2d7f:5be8:237f:e2cc%3
   IPv4 Address. . . . . . . . . . . : 192.168.56.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

Ethernet adapter VirtualBox Host-Only Network #3:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::4c1f:50b2:61bb:75f9%5
   IPv4 Address. . . . . . . . . . . : 192.168.99.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

Wireless LAN adapter Wi-Fi:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : Belkin

Wireless LAN adapter Local Area Connection* 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : Belkin
   Link-local IPv6 Address . . . . . : fe80::e059:f5:f98d:2418%11
   IPv4 Address. . . . . . . . . . . : 192.168.2.2
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.2.1
```

My actual IP address is the last adapter.  I have tried setting the environment variable `REACT_NATIVE_PACKAGER_HOSTNAME` to 192.168.2.2 but create-react-native-app doesn't seem to take it.  It simply takes the first virtualbox host adapter.

Heres the output of `yarn start` 
```
Or enter this address in the Expo app's search bar:

  exp://192.168.56.1:19000

Your phone will need to be on the same local network as this computer.
```
That address is reachable from my *host* computer but will not be reachable my phone on the same network using the expo app.

**Comment by rogerwf259** [comment]
No still not working for me, i've even created another project with the recent update and i still cant reach it in my phone's expo app

**Comment by dikaiosune** [comment]
@rogerwf259 if you fetch the manifest (like you did in above comment), are you able to reach the `bundleUrl` from your phone's browser?

**Comment by rogerwf259** [comment]
Can't reach it from my phone, but i can from my pc and this is some of the output:
![git](https://cloud.githubusercontent.com/assets/15176421/24889544/27b96578-1e30-11e7-9079-94c5ee3f23f4.png)

**Comment by dikaiosune** [comment]
@rogerwf259 OK to make sure I understand:

* You can reach the URL with port 19000 from your phone's web browser *and* from your computer
* When you retrieve the bundle URL from your computer, you get JavaScript in your screenshot back
* When you try to retrieve the bundle URL from your phone's browser, it times out or is refused?

Am I right in thinking that you can reach the manifest (port 19000) from your phone but not the bundle (port 19001)?

**Comment by rogerwf259** [comment]
- I can reach the URL with ports 19000 and 19001 from my pc, but i cant reach neither on my phone
- Yes i get Javascript from the bundle URL
- This is what i get trying to reach the URL with both ports from my phone: 
![80094dd4-57b1-439e-9d1f-a94c1d7d9b98](https://cloud.githubusercontent.com/assets/15176421/24926482/520cc9fa-1ec1-11e7-8cc2-981315cfa091.jpg)

And i keep getting the request timed out from the expo app.

**Comment by dikaiosune** [comment]
If you can't reach the dev server in your phone's browser, that definitely points to your phone not being able to reach your computer in general -- something that CRNA can't really fix for you, unfortunately 😦 .

I'd suggest:

* check the [Network troubleshooting guide](https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/template/README.md#networking)
* making sure your phone and computer are on the same local network
* if your phone supports "Mobile Hotspot" or "Tethering" try turning one of those on and joining your phone's WiFi network on your computer
* maybe following Expo's [Genymotion guide](https://docs.expo.io/versions/v15.0.0/guides/genymotion.html) and running your project with `yarn run android`

Alternatively, if you're comfortable signing up for an Expo account, [XDE](https://docs.expo.io/versions/v15.0.0/introduction/installation.html) can use our backend services to create network tunnels for you. Your CRNA project should work fine when opened in XDE.

Unfortunately we don't have time to troubleshoot every specific networking issue, so I'm going to give this a close. That said, if you continue digging and discover something which is in fact broken in CRNA's dev server, please post back so that I can resolve the issue for other users.
