### ISSUE TITLE
Header overlap with StatusBar

### ISSUE THREAD

**Issue by halallahh** [react-community/create-react-native-app#139]
## Description

I had this problem when I using react-navigation or nativebase header. same like this issue [expo](https://github.com/expo/expo/issues/71)

**Comment by dikaiosune** [comment]
Hi! Without the information from the issue template and a reproducible demo, it's very difficult to help with these issues. Note that in general, you need to specify how your application avoids rendering under the status bar. For example, you could use https://docs.expo.io/versions/v15.0.0/sdk/constants.html#expoconstantsstatusbarheight to pad the top of your UI.

**Comment by Marcus122** [comment]
I think this is linked to https://github.com/facebook/react-native/issues/6876, but when running through expo there isn't a Platform.Version property.
