### ISSUE TITLE
Setup template project's tests to actually test something

### ISSUE THREAD

**Issue by dikaiosune** [react-community/create-react-native-app#14]
It might be good to improve tests in the template project so that they actually serve as an example to a new user how to test their app/components/etc. Right now there's just a no-op test.

**Comment by Kureev** [comment]
What kind of tests do you want? Which parts of the codebase requires tests first? Which technology stack for testing you have in mind?

**Comment by dikaiosune** [comment]
The template project is currently set up to use jest, and there's an example test (see https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/template/__tests__/mainTest.js). However, this doesn't test anything other than `1 == 1`.

This isn't incredibly high priority, but I think it would be excellent to use the template project to set user expectations about what a good test-first strategy looks like. Perhaps a small component test or something else. Open to ideas here.

Also note that the template project currently doesn't test properly when yarn is installed, because yarn doesn't (yet) hoist executables of transitive dependencies into the `node_modules/.bin` directory of the project. This should be fixed whenever https://github.com/yarnpkg/yarn/issues/760 is resolved.
