### ISSUE TITLE
How do you enable Geolocation?

### ISSUE THREAD

**Issue by hysan** [react-community/create-react-native-app#141]
## Description

I'm currently trying to add Geolocation [as described in the React Native docs](https://facebook.github.io/react-native/docs/geolocation.html). However with CRNA neither the Xcode nor Android projects are exposed like with react-native init. So how does one go about enabling this when using CRNA?

## Expected Behavior

Some method of editing _Info.plist_ (for iOS) or _AndroidManifest.xml_ (for Android).

## Observed Behavior

You cannot use Geolocation.

The only workarounds I've figured out are:

- eject the project which defeats the purpose of using CRNA, or
- use the Expo SDK to explicitly ask for permissions in your code (not ideal if you want to avoid using Expo).

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@0.0.26
* `npm ls react-native`: react-native@0.42.3
* `npm ls expo`: expo@15.1.3
* `node -v`: v7.7.4
* `npm -v`: 4.1.2
* `yarn --version`: zsh: command not found: yarn
* `watchman version`: "version": "4.7.0"

Also specify:

1. Operating system: macOS 10.12.4
2. Phone/emulator/simulator & version:
  - Android: Various emulators + Nexus 5X running Android 7.1.1
  - iOS: iPhone 6 emulator

## Reproducible Demo

Attempt to follow the instructions here: https://facebook.github.io/react-native/docs/geolocation.html

**Comment by dikaiosune** [comment]
Hi!

This is one of a couple of areas where CRNA doesn't yet have complete parity with a plain React Native project, but in the near future we should have a polyfill for the geolocation API (cc @brentvatne).

Because the Expo client is already compiled and distributed through the app and play stores, there's no way to edit Info.plist or the Android manifest files, unfortunately. But there should be a path soon to using the React Native geolocation API. I'll leave this open as a tracking issue for that support.

**Comment by hysan** [comment]
Hi @dikaiosune 

Thanks for the quick reply. What do you suggest in the meantime for people who want to use Geolocation in conjunction with CRNA?

**Comment by dikaiosune** [comment]
Until we support the polyfill (I believe it's been built, just not fully tested or released yet) the options you listed under observed behavior are accurate. In addition to the Expo permissions, you'd probably use the [Location API](https://docs.expo.io/versions/v15.0.0/sdk/location.html).

**Comment by lucasbento** [comment]
@dikaiosune: is it possible to edit native files if you eject?

**Comment by dikaiosune** [comment]
@lucasbento yeah -- ejecting gives you a project very similar to one created by `react-native init`.

**Comment by dikaiosune** [comment]
The new template project (RN 0.43, Expo SDK 16) includes a polyfill of the Geolocation API that uses the Expo API under the hood.

**Comment by joshcartme** [comment]
Apologies for the thread necro, but I wasn't sure where to go with this.  I recently start a project with `create-react-native-app`.  I'm using expo 17.0.0 and react-native 0.44.3.  I have code like:

```
  function success(pos) {
    var crd = pos.coords;

    console.log('Your current position is:');
    console.log(`Latitude : ${crd.latitude}`);
    console.log(`Longitude: ${crd.longitude}`);
    console.log(`More or less ${crd.accuracy} meters.`);
  };

  function error(err) {
    console.warn(`ERROR(${err.code}): ${err.message}`);
  };

  navigator.geolocation.getCurrentPosition(success, error);
```

which always results in:

![2017-06-19 22 14 28](https://user-images.githubusercontent.com/764456/27308566-105c4f34-5504-11e7-9e57-d528639b1bda.png)

Any ideas on where to go with this?

**Comment by brentvatne** [comment]
@joshcartme - it looks like on android the third option, `arguments`, is required right now: `navigator.geolocation.getCurrentPosition(success, error, {});` will work (tested it). will fix this in our next release

**Comment by joshcartme** [comment]
@brentvatne brilliant, the error message actually makes sense to me now!
