### ISSUE TITLE
command not found: create-react-native-app

### ISSUE THREAD

**Issue by davidpaulsson** [react-community/create-react-native-app#142]
## Description

I can't run the init command as per the documentation. What could it be?

## Expected Behavior

I ran `create-react-native-app my-app`, expected it to scaffold the app structure, but instead i get this error msg `command not found: create-react-native-app`

## Observed Behavior

```
command not found: create-react-native-app
```

![screen shot 2017-03-31 at 08 52 24](https://cloud.githubusercontent.com/assets/779321/24539645/cbe2ab58-15ef-11e7-8b5b-efccdbcb48bc.png)

**Comment by ccheever** [comment]
When you `npm install -g` other node packages, are you able to run them? My first guess would be that you have w `PATH` issue where the globally installed npm packages are put in a directory that isn't in your PATH and that's why you can't run them by just typing their names into the shell.

**Comment by dikaiosune** [comment]
Can you provide the output of running `echo $PATH` on this computer?

**Comment by davidpaulsson** [comment]
@dikaiosune Sure, I get this seemingly weird path 🤔  I've probably messed this up somehow...
```
$ echo $PATH
/usr/local/heroku/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin
```

**Comment by dikaiosune** [comment]
This seems pretty normal for the PATH env var.

It looks like you need to add NPM's global modules to your PATH. Since you appear to be on a Unix system, [this SO question](https://stackoverflow.com/questions/13465829/node-js-modules-path) should work.

**Comment by davidpaulsson** [comment]
Thank you!
