### ISSUE TITLE
APK permissions

### ISSUE THREAD

**Issue by antonybudianto** [react-community/create-react-native-app#143]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

When building standalone Android APK, and submit to the developer console. I got these warnings:
```
Your app has an apk with version code 1 that requests the following permission(s): android.permission.CAMERA,android.permission.READ_PHONE_STATE,android.permission.READ_CONTACTS. Apps using these permissions in an APK are required to have a privacy policy set.
```

And my app doesn't even use camera, access contacts, or phone state.

## Expected Behavior

I've control over these permissions

## Observed Behavior

```
Your app has an apk with version code 1 that requests the following permission(s): android.permission.CAMERA,android.permission.READ_PHONE_STATE,android.permission.READ_CONTACTS. Apps using these permissions in an APK are required to have a privacy policy set.
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@0.0.26
* `npm ls react-native`: react-native@0.42.3
* `npm ls expo`: expo@15.1.3
* `node -v`: 7.6
* `npm -v`: 4.1.2
* `yarn --version`: 0.21.3
* `watchman version`: 4.7.0

Also specify:

1. Operating system: macOS Sierra
2. Phone/emulator/simulator & version: iPhone 6s

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by antonybudianto** [comment]
I've asked Expo guy that I need to eject my app to do that

**Comment by Papipo** [comment]
Awful. Will there be a way in the future to disable unneeded permissions?

**Comment by dikaiosune** [comment]
Note for future reference: Please discuss issues with Expo's build service on the Expo forums or slack.
