### ISSUE TITLE
Append warning string to plain RN eject option selection if we displayed a warning above

### ISSUE THREAD

**Issue by JeremyBYU** [react-community/create-react-native-app#145]
## Description

Freshly ejected project (that relies upon `expo` module) has errors when bundling JavaScript code. The specific complaint is `./fonts/Entypo.ttf` not being found. I am using react-native-cli to bundle. 

## Expected Behavior

Everything should work after a clean eject.  My code is the exact same as the default project template except the addition of this one line:
```
import {
  Gyroscope,
} from 'expo';
```

Removing this line and all is well, meaning no errors.

## Observed Behavior
This file and directory path it lists do indeed exist on my system.  Through just a note, the dependency on expo is not captured in my package.json, though its in the yarn.lock.

![image](https://cloud.githubusercontent.com/assets/6628085/24588139/ae3def70-1790-11e7-912d-fc9f3ffcda97.png)

```
Loading dependency graph, done.
Bundling `index.android.js`
  Transforming modules  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░  92.3% (634/660)...(node:10096) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1242): UnableToResolveError: Unable to resolve module `./fonts/Entypo.ttf` from `C:\Users\Jerem\Documents\webdev\react\test\node_modules\@expo\vector-icons\Entypo.js`: Directory C:\Users\Jerem\Documents\webdev\react\test\node_modules\@expo\vector-icons\fonts\Entypo.ttf doesn't exist
(node:10096) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that areBundling `index.android.js`
```

## Environment

Please run these commands in the project folder and fill in their results:

On windows 10 64 bit.
Android Simulator through AVD.

* `npm ls react-native-scripts`: react-native-scripts@0.0.26  extraneous
* `npm ls react-native`: react-native@0.42.3
* `npm ls expo`: expo@15.1.3  extraneous
* `node -v`: v7.0.0
* `npm -v`: 3.10.8
* `yarn --version`: 0.18.1
* `watchman version`: non

## Reproducible Demo

Default project, just import the 'expo' module.

**Comment by dikaiosune** [comment]
When you ejected, did you choose ExpoKit or a plain react native project?

**Comment by JeremyBYU** [comment]
Plain react native project.

**Comment by brentvatne** [comment]
@JeremyBYU - you can't import `expo` on a plain react-native project, you need to eject to ExpoKit if you want that.

**Comment by brentvatne** [comment]
Re-open actually because I wanted to ask @JeremyBYU, how can we make this more clear?

**Comment by JeremyBYU** [comment]
I didn't see anywhere where it expressed that a working build can break if you eject. I only saw warnings that you can never come back to the create-react-native ecosystem.  

My understanding of these tools (`create-react-app` and `create-react-native-app`) is they allow individuals to get started on a project quickly. However, if the time comes where the ecosystem can't offer something that's missing, the `eject` function is provided to reduce the system to its 'base components' to allow full control.  Its seems strange that in this specific case (the included `expo` module), it can't be be reduced to a react native module and your left with a broken build. 

If this is not in the plan to be fixed, I would recommend compiling a list of included modules known to be incompatible with the `eject` command. It would be a shame if an individual spent a lot of time working within the create-react-native ecosystem, while holding the assumption that they could always eject and get a proper build.

However, I do have to say that what you have done so far with this whole setup is pretty incredible and saves a lot of time for simply desiring to `try` things out.

**Comment by dikaiosune** [comment]
@JeremyBYU I agree completely! The expo package is a bit of a special case because the Expo client needs to be present (either in a custom ExpoKit build or pre-ejecting) to provide a lot of the functionality.

Because of this, CRNA does warn you when ejecting if you have an Expo dependency that your build will break:

<img width="752" alt="screen shot 2017-04-02 at 1 15 21 pm" src="https://cloud.githubusercontent.com/assets/6812281/24590722/243f74f8-17a7-11e7-90f3-8ea791fbc88b.png">

If you didn't see this warning, that's a bug! If that's the case, I'd really appreciate it if you could help us reproduce a situation where the warning doesn't appear so that I can fix it.

> However, I do have to say that what you have done so far with this whole setup is pretty incredible and saves a lot of time for simply desiring to try things out.

Really appreciate the kind words. Sorry the eject process didn't match your expectations.

**Comment by JeremyBYU** [comment]
Very nice error message, I most likely missed it. I was focused on the input on the selection, and paid close attention to its options.  I even looked into what they entailed, but I didn't understand the significance of the expo apis being broken.  After looking through the documentation more (not the top level readme, but the user guide) I also see that you do include information about this. Sorry about the hassle!

**Comment by dikaiosune** [comment]
You make a very good point about focusing on the options for selection. It may be a good idea to add a warning string to the plain RN option if we displayed the warning above.
