### ISSUE TITLE
Migrate existing apps to use create-react-native-app?

### ISSUE THREAD

**Issue by hedgerh** [react-community/create-react-native-app#146]
I have an existing React Native app that I would love to migrate to using create-react-native-app so that I don't need to get on OSX to do any iOS development.

Is this already possible?  If so, I'd be down to write some documentation for it, if there isn't already some.  If it's not possible yet, I think it'd be fantastic if I could run the CLI in the root of an existing project and convert it so I could develop on any platform.  If anyone has any idea of how I could go about implementing it, I could see if I can figure it out and put a PR in.

**Comment by ccheever** [comment]
You can use the `exp convert` command of the `exp` command line tool to basically do this.
https://docs.expo.io/versions/v15.0.0/guides/exp-cli.html#commands

It's not super well documented and sometimes doesn't work quite right (since arbitrary react-native projects can be setup in a bunch of different ways), but it's a good starting place for converting ove ryour pure JS RN app.

**Comment by aep** [comment]
that doesnt work anymore.

```
'exp convert' is temporarily under maintenance and not available
The easiest way to convert a project at the moment is to create a new project with 'exp init' and copy your project files into it.
```

unfortunatly every react native project i found uses some "local cli" thing, and react does not explain how to use that, instead they refer to create-react-native-app, so it would be great if that project had docs on how to run those "cli" projects.

**Comment by yarism** [comment]
Yeah got the same message, shouldn't this be re-opened?

**Comment by arapocket** [comment]
Why is this closed?

**Comment by brentvatne** [comment]
`exp convert` no longer exists. just create a new project with `create-react-native-app` and copy your files over.

**Comment by Ivanca** [comment]
"copy your files over" just creates a ton of cryptic errors ; oh how much I hate react.
