### ISSUE TITLE
console.log in the context of an onPress handler does not log and causes UI delays

### ISSUE THREAD

**Issue by mark0978** [react-community/create-react-native-app#147]
## Description

        return (
            <TouchableOpacity onPress={ (a,b,c) => { console.log(a,b,c); } } key={ item } style={ viewStyle }>
                <Text style={ textStyle }>Touch me</Text>
            </TouchableOpacity>
        );

Touching that element dims it. onPress function appears to not get called, no logging happens.

Swapping to react-native-router and moving the logging out of the onPress context seems to fix things.

## Expected Behavior

I'd expect the log message to display something even if it was undefined.

## Observed Behavior

Touching the "button" causes a "hang" that times out and then the next touch goes thru a similar lag.  I'm expecting to find out that logging during the onPress handler isn't supported.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@0.0.26
* `npm ls react-native`: react-native@0.42.3
* `npm ls expo`: expo@15.1.3
* `node -v`: v6.9.4
* `npm -v`: 4.1.2
* `yarn --version`: command not found
* `watchman version`: command not found

Also specify:

1. Operating system: OSX El Capitan  10.11.6
2. Iphone 6, Nexus 6

## Reproducible Demo

https://github.com/mark0978/react-native-bug-report

**Comment by dikaiosune** [comment]
Thanks for the detailed report and repro!

I've seen similarly strange behavior in the past due to the fact that console.log is overridden to call JSON.stringify on arguments in order to send them back to the terminal -- maybe that's related somehow? cc @brentvatne

**Comment by brentvatne** [comment]
we're working on improving logging in expo (which is the tool that powers this for crna), you can track it here: https://github.com/expo/expo/issues/168

**Comment by freshtonic** [comment]
@brentvatne can you explain why this issue has been closed? It's still a problem as far as I can tell, and the linked issue expo/expo#168 does not seem to be addressing it.
