### ISSUE TITLE
npm start does not work on windows machine

### ISSUE THREAD

**Issue by Joeyrodrigues92** [react-community/create-react-native-app#148]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description
im trying to run a react native app. this is what shows in my terminal:
[22:10:40] Starting default
[22:10:40] Watching files...
[22:10:40] Finished default in 78ms

and nothing happens after.
1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior
a react-native qpr code should appear
What action did you perform, and what did you expect to happen?
i typed npm start and then the tim stamps appearded. a qpr cde would appear for react-native.
## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:
-----------------
Joey@LAPTOP-P32LIFNF MINGW64 ~/Desktop/RCB/React-Native/create-react-native-app/create-react-native-app (master)
$ npm start

> create-react-native-app@0.0.6 start C:\Users\Joey\Desktop\RCB\React-Native\create-react-native-app\create-react-native-app
> fly

[23:41:14] Flying with C:\Users\Joey\Desktop\RCB\React-Native\create-react-native-app\create-react-native-app\flyfile.js
[23:41:14] Starting default
[23:41:14] Watching files...
[23:41:17] Finished default in 78ms
------------------------------
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
* `npm ls react-native`:
* `npm ls expo`:
* `node -v`:v6.9.4
* `npm -v`:3.10.10
* `yarn --version`:
* `watchman version`:

Also specify:

1. Operating system: windows 8
2. Phone/emulator/simulator & version: iphone/10.2.1

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by dikaiosune** [comment]
Hi! It looks like you've maybe cloned the repository and tried to run the dev build? Can you try the [install instructions](https://github.com/react-community/create-react-native-app#quick-overview) on the README?
