### ISSUE TITLE
entryPoint key in app.json is not respected

### ISSUE THREAD

**Issue by Meberem** [react-community/create-react-native-app#152]
## Description

`entryPoint` in `app.json` does not work or I have made some assumptions that are not correct. Based on [the documentation](https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/template/README.md#customizing-app-display-name-and-icon) I assumed that I can setup `app.json` in the same way as I can with an `exp.json`. From the full list of values [here](https://docs.expo.io/versions/v15.0.0/guides/configuration.html) I assumed I can alter the the `entryPoint` to something else i.e. `'./src/app.js'`. However changing this to anything breaks the app.

## Expected Behavior

I can have my `App.js` in a place other than the default by changing the `entryPoint` key in `app.json`

## Observed Behavior

If I change `entryPoint` to `./App.js` or anything else I get

```
Module AppRegistry is not a registered callable module (calling runApplication)
__callFunction
MessageQueue.js:233:6

<unknown>
MessageQueue.js:108:26

guard
MessageQueue.js:46:4

callFunctionReturnFlushedQueue
MessageQueue.js:107:10
```

## Environment

* `npm ls react-native-scripts`: `react-native-scripts@0.0.26`
* `npm ls react-native`: `react-native@0.42.3`
* `npm ls expo`: `expo@15.1.3`
* `node -v`: `v7.4.0`
* `npm -v`: `4.1.2`
* `yarn --version`: `0.22.0`
* `watchman version`: `{
    "version": "4.7.0"
}`

1. Operating system: macOs Sierra 10.12.3
2. Phone/emulator/simulator & version: Simulator 10.0 (SimulatorApp-745.10)

## Workaround

I have found a simple workaround, in `./App.js`
```
import AppRoot from './src/AppRoot.js;
export default AppRoot;
```

and in './src/AppRoot.js':
```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default class AppRoot extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
        <Text>Changes you make will automatically reload.</Text>
        <Text>Shake your phone to open the developer menu.</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

**Comment by dikaiosune** [comment]
Hi! Thanks for the report. You're right that this is surprising behavior!

If I'm reading this report correctly (and thanks so much for the thorough explanation!) I think this is due to a combination of a few factors:

* CRNA provides it's own entry point to React Native, which you can see as the `main` key in your package.json. This file initializes a few important things in the React Native client (including telling the native code which JS component to load).
* the `entryPoint` key in app.json/exp.json can be used to override the main key in package.json
* overriding the main key in package.json without copying the entry point from the react-native-scripts package will probably break your app (as it did in this case)

You can definitely replicate the contents of the hidden entry point in your app's code if you want, and either change `main` in package.json or add `entryPoint` to app.json, and it should work.

So what about being able to do what it looks like you tried, changing the filename you use for your root component? This is actually really challenging to support, because of the strategy we use for the hidden entry point. There's currently no method that I'm aware of to have dynamic module names in a require when using the React Native packager, which means that unless you eject, we need a default component to be exported from App.js.

Since projects should be setting a main key in package.json instead of using the entryPoint key in app.json, we'll remove this config item from the next release of the docs to prevent future confusion.

**Comment by nsisodiya** [comment]
@dikaiosune It will be great, if we should be able to move App.js into desired folder. In my case, I use to keep all files under `src` folder.

**Comment by nsisodiya** [comment]
@dikaiosune - I guess, this is the source code.
https://github.com/react-community/create-react-native-app/blob/6760d7126f1c8ed5320cab682ea67d842e1b9486/react-native-scripts/src/bin/crna-entry.js

I think if we support dynamic path, it will be easy thing.

```import Expo from 'expo';
import EXPJSON from '../../../../exp.json';
import React from 'react';
import { View } from 'react-native';

//TODO - check of exp.json exist or app.json exist. check if mainEntryPoint is undefined or not.

var App = require('../../../../' + EXPJSON.mainEntryPoint);

class AwakeInDevApp extends React.Component {
  render() {
    return React.createElement(
      View,
      {
        style: {
          flex: 1,
        },
      },
      React.createElement(App, this.props),
      React.createElement(process.env.NODE_ENV === 'development' ? Expo.KeepAwake : View)
    );
  }
}

Expo.registerRootComponent(AwakeInDevApp);
```
I left if/else case, just for sake of readability !

**Comment by dikaiosune** [comment]
@nsisodiya please see my comment from when this was closed for an explanation of why this won't work - dynamic requires aren't possible with the RN packager today unfortunately :(.

**Comment by nsisodiya** [comment]
@dikaiosune , then it that case, we can modify crna-entry.js file to Kind of `HOC` or function instead of class.

**Comment by nsisodiya** [comment]
content of `src/App.js`

```js
import {AwakeInDevApp} from "expo"
export default class App extends Component {
  render() {
    return (
      <AwakeInDevApp style={styles.container}>
        <Our App Code />
      </AwakeInDevApp>
    );
  }
}
```

**Comment by dikaiosune** [comment]
@nsisodiya unfortunately that would mean that every CRNA project which ejects to "raw" React Native would have to modify their source code for their project to continue working after ejecting, which is a poor fit for a "getting started" tool.

**Comment by lzrski** [comment]
Hello. We are also keeping our code in `src/`. Our workaround is to have `App.js` in main directory that just exports everything from `src/App.js`, like that:

```js
import App from './src/App';
export default App;
export * from './src/App';
```

**Comment by raarts** [comment]
@lzrski What does the last line accomplish?

**Comment by lzrski** [comment]
@raarts it ensures that `App.js` is a fully transparent *proxy* to `src/App.js`. 

Most likely the application would still work without this line, but it doesn't hurt to have it and once it's there, I can just forget about this whole hack and pretend that `src/App.js` is my entry point. If we will ever need to export from `App` module anything in addition to the default export, it will be covered.

**Comment by oshalygin** [comment]
@raarts && @lzrski , the whole `entryPoint` deal is super confusing and should be removed from the documentation, that said this guide was super useful:
https://docs.expo.io/versions/v18.0.0/sdk/register-root-component.html

**Comment by ptvandi** [comment]
Similar to the instructions @oshalygin linked to, I did the following to match the folder structure of our React web app:

1. Created a `src` folder.
2. Moved `App.js` and `App.test.js` into the `src` folder.
3. Copied the contents of the template [crna-entry.js](https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/src/bin/crna-entry.js) into `src/index.js`. 
4. Modified the `package.json` `main` property to point to this new entry point script `./src/index.js`.

**package.json**
```
{
  "name": "App",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    ...
  },
  "main": "./src/index.js",
  "scripts": {
    ...
  },
  "dependencies": {
    ...
  }
}
```

**src/index.js**
```
import Expo from 'expo';
import App from './App';
import React, { Component } from 'react';
import { View } from 'react-native';

if (process.env.NODE_ENV === 'development') {
  Expo.KeepAwake.activate();
}

Expo.registerRootComponent(App);
```

**Comment by andreyluiz** [comment]
This solution is perfect, for me. However, I am having the following error:

```
Failed to compile.
./src/index.js
10:0-4 "export 'default' (imported as 'Expo') was not found in 'expo'
```

I am using the exact same structure you're using. My deps:

```
"dependencies": {
    "expo": "^28.0.0",
    "react": "^16.4.0",
    "react-art": "^16.4.0",
    "react-dom": "^16.4.0",
    "react-native": "^0.55.0",
    "react-native-web": "^0.8.3",
    "react-scripts": "^1.1.4"
  },
```

**Comment by navotera** [comment]
i run step : 
1. stop the expo 
2. run this command : `npm install react --save`
3. run the expo again
