### ISSUE TITLE
fetch request to localhost server

### ISSUE THREAD

**Issue by telmen** [react-community/create-react-native-app#154]
## Description

I'm trying to call HTTP request from a real device to my local network computer which is running server. 
## Expected Behavior

fetch request to localhost, eg: localhost:8000 to get or post some data.

## Observed Behavior

It keeps saying Network Request failed. But when I tried it on android emulator I would change server address to http://10.0.3.2:8000 something like this and it works. Yeah I've already changed my server address to internal server address like 192.168.1.x when I tried on a real device. 

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@0.0.19
* `npm ls react-native`: react-native@0.42.3
* `npm ls expo`: expo@15.1.2
* `node -v`: v6.9.0
* `npm -v`: 3.10.8
* `yarn --version`: 0.17.10
* `watchman version`:

Also specify:

1. Operating system: Windows 10/Linux Ubuntu 16.04
2. Phone/emulator/simulator & version: iOS 10.3

**Comment by dikaiosune** [comment]
Can you paste an example of the exact code that's failing? Are you able to reach these URLs in a web browser on your phone?

**Comment by telmen** [comment]
Nevermind, Thanks. [#60](https://github.com/react-community/create-react-native-app/issues/60 did the trick for me

**Comment by brbrr** [comment]
Hi @telmen 
Could you post your solution? 

I run in to same problem while trying to POST to localhost server from CRNA. GET request from https://facebook.github.io/react-native/docs/network.html works fine

**Comment by telmen** [comment]
Hi @brbrr, sorry for late reply. Glad that you have solved it. Yeah it was needed to use internal IP address instead of localhost. 👍

**Comment by zacharygcook** [comment]
@telmen still don't totally understand this problem or why the solution fixes it, but thanks for posting that tip to "use the internal IP address" on here! Solved my problems

**Comment by kenshinman** [comment]
@zacharygcook same here
example code...
```
fetch("http://localhost:3000/api/data")
.then( res => res.json() )
....bla bla bla 
``` 

the above code doesn't work, but when you represent `localhost` with your system's ip address (IPv4 address) it works.

Really don't know why this happens. I always have to change the IP address whenever it changes.

Sighs...

**Comment by NickyMwangi** [comment]
This doesnt work for me. I am using Linux mint and Xampp which when installed is Lampp. This is my code
`DBRegistration = (uid) => {
    fetch("http://192.168.0.102:80/TinyvideosAPI/users.php", {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        fbuid: uid, 
        usermail: this.state.emailaddr,
        userpass: this.state.pass
      }),
    }).then((response) => response.json())
    .then((responseJson) => {
      Alert.alert(responseJson);
      this.props.navigation.navigate("Login")
    }).catch((error) => {
      console.error('MySQL error' + error);
    });
  }`

**Comment by NickyMwangi** [comment]
DBRegistration = (uid) => {
    fetch("http://192.168.0.102:80/TinyvideosAPI/users.php", {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        fbuid: uid, 
        usermail: this.state.emailaddr,
        userpass: this.state.pass
      }),
    }).then((response) => response.json())
    .then((responseJson) => {
      Alert.alert(responseJson);
      this.props.navigation.navigate("Login")
    }).catch((error) => {
      console.error('MySQL error' + error);
    });
  }

**Comment by RimashMohomed** [comment]
I had the similar issue using 10.0.2.2 as the IP solved, This is due to android emulator see [https://developer.android.com/studio/run/emulator-networking ](android emulator document)

**Comment by TopDragon523** [comment]
I am working with two local pc , 
One pc  supports for backend and other one supports for expo project, 
So, on expo project, I call fetch with local server ip address, but failed , 
How can I fix this issue  ?

**Comment by Ebaboo** [comment]
You can tell your server, to listen to listen to your local IP. Solved the issue for emulator and for device also. Then you just point to this IP. 
![image](https://github.com/expo/create-react-native-app/assets/19646648/a5d5be01-f5b5-46f3-a11e-f5a454d7b0d8)
