### ISSUE TITLE
Adding support for realm

### ISSUE THREAD

**Issue by nikhilag** [react-community/create-react-native-app#155]
Is there any plan to add support for realm database in expo so that we can use it with create-react-native-app without ejecting? If not, I would request you to add this feature.
https://realm.io/news/introducing-realm-react-native/

**Comment by dikaiosune** [comment]
Hi! We're definitely considering adding Realm support at some point. In the meantime, there should be a release soon with support for SQLite.

**Comment by robinia1200** [comment]
Hi,
How is process of adding support for Realm to Expo?

**Comment by soriyath** [comment]
is there any progress on this feature?

**Comment by dirtyredz** [comment]
Im in the process of starting a react-native application and am curious if its possible to use the Realm DB with react-native. Are there any updates to this issue?
