### ISSUE TITLE
react-navigation deep linking

### ISSUE THREAD

**Issue by halallahh** [react-community/create-react-native-app#162]
## Description

I used [react-navigation](https://reactnavigation.org) for my CRNA navigator. I have a one question about deep linking. I need to eject to use it or any other way to make it work?

## Expected Behavior

react-navigation deep linking

## Observed Behavior

no idea.

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@0.0.27 
* `npm ls react-native`: react-native@0.42.3
* `npm ls expo`:  expo@15.1.3
* `node -v`: v6.10.2
* `npm -v`: 3.10.10
* `yarn --version`: 0.20.3
* `watchman version`: 4.7.0

Also specify:

1. Operating system: OS X 10.11.6
2. Phone/emulator/simulator & version: Asus Zenfone 5

**Comment by dikaiosune** [comment]
Deep linking works right now, but it's not fully documented yet and might change. I *believe* you can use the API as documented in the [React Native docs](https://facebook.github.io/react-native/docs/linking.html) without doing any of the native-side configuration. But I could be horribly wrong.

cc @terribleben @jesseruder
