### ISSUE TITLE
Crashing when running on simulator

### ISSUE THREAD

**Issue by pbassut** [react-community/create-react-native-app#163]
## Description
I try to run the project on the android simulator and it crashes right away.

## Expected Behavior
Launch without crashing

## Observed Behavior
It crashes right away with the following stacktrace:
```
04-13 13:23:51.753  2094  2094 D AndroidRuntime: Shutting down VM
04-13 13:23:51.754  2094  2094 E AndroidRuntime: FATAL EXCEPTION: main
04-13 13:23:51.754  2094  2094 E AndroidRuntime: Process: br.com.beebo.android, PID: 2094
04-13 13:23:51.754  2094  2094 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object host.exp.exponent.RNObject.call(java.lang.String, java.lang.Object[])' on a null object reference
04-13 13:23:51.754  2094  2094 E AndroidRuntime: 	at host.exp.expoview.Exponent.startReactInstance(Exponent.java:637)
04-13 13:23:51.754  2094  2094 E AndroidRuntime: 	at host.exp.expoview.ExponentActivity$3.onSuccess(ExponentActivity.java:223)
04-13 13:23:51.754  2094  2094 E AndroidRuntime: 	at host.exp.expoview.Exponent$3$1.run(Exponent.java:592)
04-13 13:23:51.754  2094  2094 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
04-13 13:23:51.754  2094  2094 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-13 13:23:51.754  2094  2094 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
04-13 13:23:51.754  2094  2094 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
04-13 13:23:51.754  2094  2094 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-13 13:23:51.754  2094  2094 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
04-13 13:23:51.754  2094  2094 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
04-13 13:23:51.758  1585  2140 W ActivityManager:   Force finishing activity br.com.beebo.android/.MainActivity
```

## Environment

* `npm ls react-native-scripts`: 
├── UNMET PEER DEPENDENCY react@15.4.2
└── react-native-scripts@0.0.25

npm ERR! peer dep missing: react@^15.5.4, required by react-dom@15.5.4

* `npm ls react-native`: 
├── UNMET PEER DEPENDENCY react@15.4.2
└── react-native@0.42.0

npm ERR! peer dep missing: react@^15.5.4, required by react-dom@15.5.4

* `npm ls expo`:
├── expo@15.1.3
└── UNMET PEER DEPENDENCY react@15.4.2

npm ERR! peer dep missing: react@^15.5.4, required by react-dom@15.5.4
* `node -v`: v7.7.3
* `npm -v`: 4.1.2
* `yarn --version`: 0.21.3
* `watchman version`:
{
    "version": "4.7.0"
}

Also specify:
1. Operating system: OSX El Capitan
2. Phone/emulator/simulator & version: Android Galaxy Nexus API 25

**Comment by dikaiosune** [comment]
Are you running this with `yarn run android`?

**Comment by pbassut** [comment]
@dikaiosune It's a detached project.

**Comment by pbassut** [comment]
Yes. I am running `yarn run android` and that error keeps popping up

**Comment by dikaiosune** [comment]
Is this a detached app? Make sure to follow the docs for ExpoKit and use XDE/exp.
