### ISSUE TITLE
Extra Quote?

### ISSUE THREAD

**Issue by bleonard** [react-community/create-react-native-app#170]
I Expo-ejected a new project out of curiosity and noticed a few things with an extra quote at the end of the filename.
Maybe a typo.

![screen shot 2017-04-18 at 8 25 01 pm](https://cloud.githubusercontent.com/assets/36106/25162172/7cd308c0-2475-11e7-88e2-377d1db22db3.png)

**Comment by dikaiosune** [comment]
cc @terribleben

**Comment by brentvatne** [comment]
re-cc @terribleben

**Comment by terribleben** [comment]
What is this a screenshot of? Your filesystem? I haven't seen this behavior.

**Comment by terribleben** [comment]
Actually managed to repro using a much older copy of our tooling. It doesn't appear to happen using the latest, so I guess this was resolved (the code powering this has been rewritten in the last month).
