### ISSUE TITLE
Unable to connect to the application using the QR Code

### ISSUE THREAD

**Issue by DiegoBM** [react-community/create-react-native-app#173]
Description

Created a single application by running create-react-native-app. When finished the automatic process I did run
REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.20 npm start

The automatic process started with no abormal messages beyond:

`Starting packager...
ERROR STARTING PACKAGER
Starting React Native packager...

'yarn' is not recognized as an internal or external command,
operable program or batch file.
`

At the end I can see a huge QR code and a message stating:
`Or enter this address in the Expo app's search bar:

exp://192.168.0.20:19000
`
Finally I opened Expo in my mobile device and tried to scan the QR code

Expected Behavior

I was expecting to see the application on my mobile device after scanning the QR Code

Observed Behavior

A blue screen was presented stating:
Something went wrong.
Could not load exp://192.168.0.20:19000

After pressing "View error log" I can see:
Uncaught Error: java.net.ConnectException: Failed to connect to /192.168.0.20:19000
Time: 6:51:28 Fatal Error

No errors or messages at all in the terminal

Environment

npm ls react-native-scripts: react-native-scripts@0.0.27
npm ls react-native: react-native@0.42.3
npm ls expo: expo@15.1.3
node -v: v7.9.0
npm -v: 4.2.0
yarn --version: --
watchman version: --
Operating system: Windows 10 Professional - Creators Update
Phone/emulator/simulator & version: Google Nexus 5. Android 5.1.1
Phone IP: 192.168.0.9
Expo Client version: 1.15.0

Reproducible Demo

Not sure what to fill in here

---------------------------------------------
Trying to access http://192.168.0.20:19000 and http://192.168.0.20:19001 in my phone browser. In both cases I can see a message "This site can't be reached"

I used to have Expo XDE installed but I did uninstall it since Kaspersky Internet Security 2017 was reporting ngrok as malicious and automatically deleting it. With XDE I was able to connect using my device before installing Kaspersky, but even if I pause it I won't be able to connect.
If I disable Kaspersky (so that it doesn't delete ngrok) and connect throught XDE, then I can connect ok. But create-react-native-app will still fail without further explanaton, and it's still not really a good solution for me

**Comment by pirey** [comment]
why are you closing this issue?
i'm facing the same issue, how did you managed to solve it?
