### ISSUE TITLE
Where to store Secrets

### ISSUE THREAD

**Issue by CandyOgre** [react-community/create-react-native-app#176]
Where to store secrets like mongoUri, server API, Google API keys? What is the best practice for create-react-native-app?

**Comment by dikaiosune** [comment]
Hi! That's a very good question, and unfortunately it's not something that CRNA can help very much with. You shouldn't ever store secrets in a client that is running on a user's device, unless you're OK with the user having access to those secrets. Here's an excerpt from some [excellent docs at Facebook](https://developers.facebook.com/docs/facebook-login/security#appsecret) on the subject (they are specifically talking about FB App Secrets, but this applies to any secret that you don't want your users to have):

> ... the App Secret or an App Access token should never be included in any code that could be accessed by anyone other than a developer of the app. This applies to all methods of code that are not secured like client-side code (such as HTML or Javascript) or native apps (such as iOS, Android or Windows desktop apps) that could be decompiled.

> ...

> We recommend that App Access Tokens should only be used directly from your app's servers in order to provide the best security.
