### ISSUE TITLE
Linking (phone, email, geo)

### ISSUE THREAD

**Issue by msdark** [react-community/create-react-native-app#183]
It's is possible to use Linking interface with this tool?
In the documentation https://facebook.github.io/react-native/docs/linking.html there is an advice

> NOTE: On iOS you'll need to link RCTLinking to your project by following the steps described here. In case you also want to listen to incoming app links during your app's execution you'll need to add the following lines to you *AppDelegate.m:

> NOTE: As of iOS 9, your app needs to provide the LSApplicationQueriesSchemes key inside Info.plist or canOpenURL will always return false

it's possible to implement Linking using create-react-app/Expo ?

**Comment by dikaiosune** [comment]
It should work without making any of the native-side changes, but we don't officially support it yet. The docs should be clearer in the near future and we'll have a guide on the Expo site at some point soon.

**Comment by brentvatne** [comment]
indeed it will just work out of the box without adding any of those things on the native side
