### ISSUE TITLE
Support of v16 API Expo

### ISSUE THREAD

**Issue by pierre-H** [react-community/create-react-native-app#186]
Thanks to react community : CRNA is great !

I noticed that CRNA uses v15 of Expo API which means we can't use things like SQLite.

Will it be possible to use the v16 API ?

**Comment by yash2code** [comment]
CRNA already using v16 :  https://github.com/react-community/create-react-native-app/blob/master/VERSIONS.md

**Comment by pierre-H** [comment]
@yash2code Thank you ! I probably have an old crna version.

**Comment by dikaiosune** [comment]
@pierre-H the version of CRNA itself shouldn't matter, but if npm or yarn is installing an old/cached version of the `react-native-scripts` package, I can see how you might not get the RN 0.43/SDK 16 code.
