### ISSUE TITLE
Symlink to src folder

### ISSUE THREAD

**Issue by CandyOgre** [react-community/create-react-native-app#188]
Can I use symlinks somehow in create-react-native-app?
```
// inside Webpack config object
{
  resolve: {
    modules: ['node_modules', 'src'],
    extensions: ['.js', '.jsx'],
  }
}
```

**Comment by dikaiosune** [comment]
Right now the React Native packager (which we use under the hood) attempts to resolve symlinks within node_modules, and I *think* it does so for your source roots as well. But I'd have to double-check.

Note that webpack configuration won't have any effect for RN, as we don't currently use Webpack to bundle your app.

**Comment by CandyOgre** [comment]
@dikaiosune thank you for responce!
