### ISSUE TITLE
good first time issues

### ISSUE THREAD

**Issue by tarang9211** [react-community/create-react-native-app#19]
Hey new to this repo and the react native ecosystem. what's the best way to get started?

**Comment by dikaiosune** [comment]
Hi! We've been working on this project for a couple of months now, but it's not ready to use yet. I would describe its current state of readiness as "pre-alpha," so you almost certainly want to hold off on using it. We'll be making some announcements once that changes. Stay tuned!

**Comment by dikaiosune** [comment]
Oh I'm sorry, I just re-read this and realized I misunderstood. If you want to contribute to the repo, you can look for issues tagged `help wanted` that no one has spoken for yet.
