### ISSUE TITLE
Rendering .svg files on iOS

### ISSUE THREAD

**Issue by karamazzov** [react-community/create-react-native-app#194]
I'm experiencing weird issue, whenever I put .svg file - app preview on iPhone crashes instantly. 
I'm using expo for simulating directly on phone. 
Please help, thank you in advance

**Comment by brentvatne** [comment]
The Image component does not support svg files and there is no plan to change this -- still, it sucks that it just hard crashes. Additionally, it looks like the supported formats are not documented. Can you create an issue on facebook/react-native for crashing when loading SVG? I'll add some documentation about supported formats. Thanks!
