### ISSUE TITLE
Add a non-interactive eject option

### ISSUE THREAD

**Issue by amingilani** [react-community/create-react-native-app#196]
## Description

I'm trying to deploy via CI/CD and need to build a native APK file. I'd like to keep create-react-native-app for development purposes, but building the APK in my CI/CD requires non-interactive eject options

## Expected Behavior

```
yarn eject --non-interactive
Ejected
```

## Observed Behavior

```
yarn eject --non-interactive
yarn eject v0.22.0
$ react-native-scripts eject

We didn't find any uses of the Expo SDK in your project, so you should be fine to eject to
"Plain" React Native. (This check isn't very sophisticated, though.)

We strongly recommend that you read this document before you proceed:
  https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md

Ejecting is permanent! Please be careful with your selection.

? How would you like to eject from create-react-native-app? (Use arrow keys)
❯ React Native: I'd like a regular React Native project.
  ExpoKit: I'll create or log in with an Expo account to use React Native and th
e Expo SDK.
  Cancel: I'll continue with my current project structure.
```

**Comment by bigosmallm** [comment]
We have the same requirement as well.  Is there a workaround we could use in the meantime?

**Comment by brentvatne** [comment]
Hello! This isn't a high priority for me but if you want to tackle this yourself and submit a PR I'm happy to review it.

Another option, by the way, is to use Expo to build your app for you, [check out this guide for more info](https://docs.expo.io/versions/v16.0.0/guides/building-standalone-apps.html).

**Comment by amingilani** [comment]
I may have some time over the weekend, I'll try putting in a PR, in the meantime if someone else wants to take this up they're welcome!

**Comment by bigosmallm** [comment]
Created a PR here: https://github.com/react-community/create-react-native-app/pull/202

**Comment by gigaga** [comment]
Hi,

Can you check and merge the PR?

Thx!

**Comment by Zomis** [comment]
Last PR was rejected, but I'm trying with a new one that is hopefully more to the maintainer's liking. See #346.

**Comment by androidfanatic** [comment]
+1; do we've a workaround in the meanwhile?

**Comment by Zomis** [comment]
@androidfanatic I am using the modifications in #346 . I built my own version that I'm using on my Jenkins machine. Works fine for me.
