### ISSUE TITLE
CRNA and Ignite

### ISSUE THREAD

**Issue by jmuziki** [react-community/create-react-native-app#198]
## Description

App is stuck at the the starting packager stage on trying to add ignite to CRNA project. Not sure if this is possible as the underlying issues seems to be dependency issues with the react-native package. Is it possible to get CRNA working with Ignite?

## Expected Behavior

I updated `package.json` ran `npm install` then `npm install`. Expected application to start. 

## Observed Behavior

Application stuck while starting package

![screen shot 2017-05-08 at 11 46 28 am](https://cloud.githubusercontent.com/assets/7222660/25799102/0f0e6b12-33e4-11e7-9f12-94d03aa457ef.png)

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: 
IgniteExpo@0.1.0 /Users/josephmuziki/dev/IgniteExpo
├── UNMET PEER DEPENDENCY react@15.4.2
└── react-native-scripts@0.0.29  extraneous

npm ERR! peer dep missing: react@^15.5.4, required by react-dom@15.5.4
npm ERR! extraneous: react-native-scripts@0.0.29 /Users/josephmuziki/dev/IgniteExpo/node_modules/react-native-scripts

* `npm ls react-native`:
├── UNMET PEER DEPENDENCY react@15.4.2
├── react-native@0.42.0 
└─┬ react-native-router-flux@3.38.1
  └── react-native@0.41.2 

npm ERR! peer dep missing: react@^15.5.4, required by react-dom@15.5.4

* `npm ls expo`:
├── expo@15.1.3 
└── UNMET PEER DEPENDENCY react@15.4.2

npm ERR! peer dep missing: react@^15.5.4, required by react-dom@15.5.4

* `node -v`: v7.8.0
* `npm -v`: 4.20
* `yarn --version`: 0.21.3
* `watchman version`:
{
    "version": "4.7.0"
}

Package.json:
 "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "apisauce": "^0.11.0",
    "expo": "^15.0.2",
    "format-json": "^1.0.3",
    "querystringify": "^1.0.0",
    "ramda": "^0.23.0",
    "react": "~15.4.0",
    "react-native": "https://github.com/exponent/react-native/archive/sdk-15.0.0.tar.gz",
    "react-native-drawer": "^2.3.0",
    "react-native-router-flux": "^3.38.0",
    "react-navigation": "^1.0.0-beta.7",
    "react-redux": "^5.0.4",
    "reactotron-apisauce": "^1.9.1",
    "reactotron-react-native": "^1.9.1",
    "reactotron-redux": "^1.9.1",
    "reactotron-redux-saga": "^1.9.1",
    "redux": "^3.6.0",
    "redux-persist": "^4.6.0",
    "redux-saga": "^0.14.6",
    "reduxsauce": "^0.5.0",
    "seamless-immutable": "^7.1.2"
  },
  "devDependencies": {
    "babel-eslint": "^7.2.2",
    "ignite-dev-screens": "^2.0.0-beta.8",
    "ignite-ir-boilerplate-2016": "^0.2.1",
    "standard": "^10.0.2",
    "react-native-scripts": "0.0.29",
    "jest-expo": "^0.4.0",
    "react-test-renderer": "16.0.0-alpha.6"
  }

**Comment by brentvatne** [comment]
hello! we don't provide support for integrating with other libraries unfortunately, can you create this issue on the ignite repo? thanks!
