### ISSUE TITLE
npm test always fails

### ISSUE THREAD

**Issue by kay-is** [react-community/create-react-native-app#199]
## Description

I want to run tests.

## Expected Behavior

Tests succeed.

## Observed Behavior

Tests always fail. With a variety of syntax errors.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: 0.0.28 & 0.0.29
* `npm ls react-native`: 0.43.4
* `npm ls expo`: 16.0.0
* `node -v`: 6.10.3
* `npm -v`: 3.10.10

Also specify:

1. Operating system: Xubuntu 17.4
2. Phone/emulator/simulator & version: Jest 19.0.2

## Reproducible Demo

I got only one test, it's the default test CRNA creates.

I try to run it with `npm run test`

I get `SyntaxError: Unexpected token import` in my own source files when I use this config:

    "jest": {
      "preset": "jest-expo"
    },

I get `SyntaxError: Unexpected identifier` on `type ModuleConfig = [` in the `react-native` files when I use this config:

    "jest": {
      "preset": "jest-expo",
      "transformIgnorePatterns": [
        "/node_modules/",
        "/src/"
      ]
    },

I get `SyntaxError: Unexpected token import` on a react-native import in the expo package when I use this config:

    "jest": {
      "preset": "react-native"
    },

I get `SyntaxError: Unexpected token )` in the react-native packages jest setup when I use this config:

    "jest": {
      "preset": "react-native",
      "transformIgnorePatterns": [
        "/node_modules/",
        "/src/"
      ]
    },

**Comment by bang88** [comment]
try this:
```
"transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-navigation)"
 ]
```

**Comment by kay-is** [comment]
<code>
FAIL  ./App.test.js
  ● Test suite failed to run

    ..../mobile-app/node_modules/expo/src/Expo.js:6
    import { NativeModules } from 'react-native';
    ^^^^^^
    SyntaxError: Unexpected token import

      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:321:12)
      at Object.<anonymous> (src/components/shared/Screen.js:5:11)
      at Object.<anonymous> (src/components/Home/index.js:2:13)
</code>

Didn't work :/

**Comment by dikaiosune** [comment]
On a fresh project with this jest config:

```
  "scripts": {
...
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
```

I'm able to run tests without problems. Can you paste your full package.json?

**Comment by kay-is** [comment]
I just created a new project and ejected.

### package.json

<pre><code>
{
  "name": "mobile-app",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "jest-expo": "~1.0.1",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "^0.44.0"
  }
}
</code>
</pre>

## Error

     FAIL  ./App.test.js
      ● Test suite failed to run

        /Users/kay/Development/mobile-app/App.test.js: Unexpected token (7:35)
             5 |
             6 | it('renders without crashing', () => {
          >  7 |   const rendered = renderer.create(<App />).toJSON();
               |                                    ^
             8 |   expect(rendered).toBeTruthy();
             9 | });
            10 |

    Test Suites: 1 failed, 1 total
    Tests:       0 total
    Snapshots:   0 total 
    Time:        1.046s
    Ran all test suites.

**Comment by brentvatne** [comment]
@kay-is - can you post the output of `npm ls --depth=1`? I suspect there might be some global dependency that is messing with our mojo

**Comment by kay-is** [comment]
<code><pre>
mobile-app@0.1.0 /Users/kay/Development/mobile-app
├─┬ husky@0.13.4
│ ├── chalk@1.1.3
│ ├── find-parent-dir@0.3.0
│ ├── is-ci@1.0.10
│ └── normalize-path@1.0.0
├─┬ jest-expo@1.0.1
│ ├── babel-jest@19.0.0
│ └── jest@19.0.2
├─┬ lint-staged@3.6.0
│ ├── app-root-path@2.0.1
│ ├── cosmiconfig@1.1.0
│ ├── execa@0.6.3
│ ├── listr@0.12.0
│ ├── lodash.chunk@4.2.0
│ ├── minimatch@3.0.4
│ ├── npm-which@3.0.1
│ ├── p-map@1.1.1
│ └── staged-git-files@0.0.4
├─┬ prettier@1.3.1
│ ├── ast-types@0.9.8
│ ├── babel-code-frame@6.22.0
│ ├── babylon@7.0.0-beta.8
│ ├── esutils@2.0.2
│ ├── flow-parser@0.45.0
│ ├── get-stdin@5.0.1
│ ├── glob@7.1.1
│ ├── jest-validate@19.0.0
│ └── minimist@1.2.0
├─┬ react@16.0.0-alpha.6
│ ├── fbjs@0.8.12
│ ├── loose-envify@1.3.1
│ └── object-assign@4.1.1
├─┬ react-native@0.44.2
│ ├── absolute-path@0.0.0
│ ├── art@0.10.1
│ ├── async@2.4.1
│ ├── babel-core@6.24.1
│ ├── babel-generator@6.24.1
│ ├── babel-plugin-external-helpers@6.22.0
│ ├── babel-plugin-syntax-trailing-function-commas@6.22.0
│ ├── babel-plugin-transform-async-to-generator@6.16.0
│ ├── babel-plugin-transform-flow-strip-types@6.22.0
│ ├── babel-plugin-transform-object-rest-spread@6.23.0
│ ├── babel-polyfill@6.23.0
│ ├── babel-preset-es2015-node@6.1.1
│ ├── babel-preset-fbjs@2.1.2
│ ├── babel-preset-react-native@1.9.2
│ ├── babel-register@6.24.1
│ ├── babel-runtime@6.23.0
│ ├── babel-traverse@6.24.1
│ ├── babel-types@6.24.1
│ ├── babylon@6.17.1
│ ├── base64-js@1.2.0
│ ├── bser@1.0.3
│ ├── commander@2.9.0
│ ├── concat-stream@1.6.0
│ ├── connect@2.30.2
│ ├── core-js@2.4.1
│ ├── debug@2.6.8
│ ├── denodeify@1.2.1
│ ├── event-target-shim@1.1.1
│ ├── fbjs-scripts@0.7.1
│ ├── form-data@2.1.4
│ ├── fs-extra@1.0.0
│ ├── glob@7.1.2
│ ├── graceful-fs@4.1.11
│ ├── image-size@0.3.5
│ ├── immutable@3.7.6
│ ├── imurmurhash@0.1.4
│ ├── inquirer@0.12.0
│ ├── jest-haste-map@20.0.4
│ ├── joi@6.10.1
│ ├── json-stable-stringify@1.0.1
│ ├── json5@0.4.0
│ ├── left-pad@1.1.3
│ ├── lodash@4.17.4
│ ├── mime@1.3.6
│ ├── mime-types@2.1.11
│ ├── mkdirp@0.5.1
│ ├── node-fetch@1.7.0
│ ├── npmlog@2.0.4
│ ├── opn@3.0.3
│ ├── optimist@0.6.1
│ ├── plist@1.2.0
│ ├── pretty-format@4.3.1
│ ├── promise@7.1.1
│ ├── react-clone-referenced-element@1.0.1
│ ├── react-devtools-core@2.2.1
│ ├── react-timer-mixin@0.13.3
│ ├── react-transform-hmr@1.0.4
│ ├── rebound@0.0.13
│ ├── regenerator-runtime@0.9.6
│ ├── request@2.81.0
│ ├── rimraf@2.6.1
│ ├── sane@1.4.1
│ ├── semver@5.3.0
│ ├── shell-quote@1.6.1
│ ├── source-map@0.5.6
│ ├── stacktrace-parser@0.1.4
│ ├── temp@0.8.3
│ ├── throat@3.0.0
│ ├── uglify-js@2.7.5
│ ├── whatwg-fetch@1.1.1
│ ├── wordwrap@1.0.0
│ ├── worker-farm@1.3.1
│ ├── write-file-atomic@1.3.4
│ ├── ws@1.1.4
│ ├── xcode@0.9.3
│ ├── xmldoc@0.4.0
│ ├── xpipe@1.0.5
│ └── yargs@6.6.0
├─┬ react-navigation@1.0.0-beta.11
│ ├── clamp@1.0.1
│ ├── hoist-non-react-statics@1.2.0
│ ├── path-to-regexp@1.7.0
│ ├── prop-types@15.5.10
│ ├── react-native-drawer-layout-polyfill@1.3.1
│ └── react-native-tab-view@0.0.65
└── react-test-renderer@16.0.0-alpha.6
</pre></code>

**Comment by brentvatne** [comment]
Sorry I meant `npm ls --global --depth=1`

**Comment by kay-is** [comment]
<pre><code>
/Users/kay/.nvm/versions/node/v6.10.3/lib
├─┬ create-react-native-app@0.0.6
│ ├── babel-runtime@6.23.0
│ ├── chalk@1.1.3
│ ├── cross-spawn@4.0.2
│ ├── fs-promise@1.0.0
│ ├── minimist@1.2.0
│ ├── path-exists@2.1.0
│ ├── semver@5.3.0
│ └── source-map-support@0.4.15
├── flow-bin@0.47.0
├── flow-cli@0.0.0-pre
└─┬ npm@3.10.10
  ├── abbrev@1.0.9
  ├── ansi-regex@2.0.0
  ├── ansicolors@0.3.2
  ├── ansistyles@0.1.3
  ├── aproba@1.0.4
  ├── archy@1.0.0
  ├── asap@2.0.5
  ├── chownr@1.0.1
  ├── cmd-shim@2.0.2
  ├── columnify@1.5.4
  ├── config-chain@1.1.11
  ├── debuglog@1.0.1
  ├── dezalgo@1.0.3
  ├── editor@1.0.0
  ├── fs-vacuum@1.2.9
  ├── fs-write-stream-atomic@1.0.8
  ├── fstream@1.0.10
  ├── fstream-npm@1.2.0
  ├── glob@7.1.0
  ├── graceful-fs@4.1.9
  ├── has-unicode@2.0.1
  ├── hosted-git-info@2.1.5
  ├── iferr@0.1.5
  ├── imurmurhash@0.1.4
  ├── inflight@1.0.5
  ├── inherits@2.0.3
  ├── ini@1.3.4
  ├── init-package-json@1.9.4
  ├── lockfile@1.0.2
  ├── lodash._baseindexof@3.1.0
  ├── lodash._baseuniq@4.6.0
  ├── lodash._bindcallback@3.0.1
  ├── lodash._cacheindexof@3.0.2
  ├── lodash._createcache@3.1.2
  ├── lodash._getnative@3.9.1
  ├── lodash.clonedeep@4.5.0
  ├── lodash.restparam@3.6.1
  ├── lodash.union@4.6.0
  ├── lodash.uniq@4.5.0
  ├── lodash.without@4.4.0
  ├── mkdirp@0.5.1
  ├── node-gyp@3.4.0
  ├── nopt@3.0.6
  ├── normalize-git-url@3.0.2
  ├── normalize-package-data@2.3.5
  ├── npm-cache-filename@1.0.2
  ├── npm-install-checks@3.0.0
  ├── npm-package-arg@4.2.0
  ├── npm-registry-client@7.2.1
  ├── npm-user-validate@0.1.5
  ├── npmlog@4.0.0
  ├── once@1.4.0
  ├── opener@1.4.2
  ├── osenv@0.1.3
  ├── path-is-inside@1.0.2
  ├── read@1.0.7
  ├── read-cmd-shim@1.0.1
  ├── read-installed@4.0.3
  ├── read-package-json@2.0.4
  ├── read-package-tree@5.1.5
  ├── readable-stream@2.1.5
  ├── readdir-scoped-modules@1.0.2
  ├── realize-package-specifier@3.0.3
  ├── request@2.75.0
  ├── retry@0.10.0
  ├── rimraf@2.5.4
  ├── semver@5.3.0
  ├── sha@2.0.1
  ├── slide@1.1.6
  ├── sorted-object@2.0.1
  ├── strip-ansi@3.0.1
  ├── tar@2.2.1
  ├── text-table@0.2.0
  ├── uid-number@0.0.6
  ├── umask@1.1.0
  ├── unique-filename@1.1.0
  ├── unpipe@1.0.0
  ├── validate-npm-package-license@3.0.1
  ├── validate-npm-package-name@2.2.2
  ├── which@1.2.11
  ├── wrappy@1.0.2
  └── write-file-atomic@1.2.0
</code></pre>

**Comment by brentvatne** [comment]
Oh sorry I should have read the original post more carefully, I jumped in half way.

What you're seeing here is a quirk of how babel and jest work with react-native.

1) react-native has a culture of shipping raw source (in other words, not compiled with babel yet) and jest by default does not run all of the packages in node_modules through babel, in order to be faster. 
2) react-native defaults to react-native-stage-0 if no `.babelrc` is present, whereas jest just assumes no babel config. Currently create-react-native-app deletes the `.babelrc` when you eject because it was assumed that it wasn't needed due to the stage-0 default, but it should not do that because jest needs it.

So, you'll need to install `babel-preset-react-native` and re-create `.babelrc` on an ejected project like so:

```
{
  "presets": ["react-native"]
}
```

This is a bug that needs to be resolved, see #243

**Comment by erhathaway** [comment]
I'm also getting this error

my package.json is: 
```
{
  "name": "mobile-client",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "babel-eslint": "^7.2.3",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^15.0.1",
    "eslint-plugin-flowtype": "^2.34.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^5.0.3",
    "eslint-plugin-react": "^7.0.1",
    "eslint-plugin-react-native": "^2.3.2",
    "flow-bin": "^0.40.0",
    "jest-expo": "^0.4.0",
    "react-native-scripts": "0.0.29",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch",
    "flow": "flow",
    "lint": "node node_modules/eslint/bin/eslint.js -c ./.eslintrc.json --ignore-pattern '*/node_modules/*' --ignore-pattern '*/npm/*' .; exit 0"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "apollo-client": "^1.4.0",
    "expo": "^16.0.0",
    "prop-types": "^15.5.10",
    "react": "16.0.0-alpha.6",
    "react-apollo": "^1.4.0",
    "react-native": "^0.43.4",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.5",
    "redux": "^3.6.0",
    "redux-persist": "^4.8.0",
    "redux-saga": "^0.15.3",
    "redux-thunk": "^2.2.0"
  }
}
```

**Comment by brentvatne** [comment]
what's in your `.babelrc` @erhathaway?

**Comment by kay-is** [comment]
Okay, tried to install the preset and add a `.babelrc` didn't help.

I also tried to use the `jest-react-native` preset and install `babel-jest`.

Still getting ES2015 related errors :(

<pre><code>
 FAIL  ./App.test.js
  ● Test suite failed to run

    /Users/kay/Development/mobile-app/node_modules/glamorous-native/src/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import createGlamorous
 from './create-glamorous'
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import

      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:321:12)
      at Object.<anonymous> (modules/screens/Placeholder.js:2:22)
      at Object.<anonymous> (modules/Navigation.js:2:18)
</code></pre>

**Comment by brentvatne** [comment]
this is related to quirk 1. that i mentioned above -- glamorous-native needs to be transpiled. unfortunately this is more of a jest issue than anything that we deal with directly here, but i'll try to help anyhow.

you will need to add glamorous-native to the regex here: https://facebook.github.io/jest/docs/tutorial-react-native.html#transformignorepatterns-customization

**Comment by erhathaway** [comment]
@brentvatne my babelrc is:

```
{
  "presets": [
    "babel-preset-expo",
  ],
  "env": {
    "development": {
      "plugins": [
        "transform-react-jsx-source",
      ]
    }
  }
}
```

I was able to fix the problem using a variation of @bang88 approach:
```
  "jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "node_modules/(?!react|@expo|expo)"
    ]
  },
```

**Comment by brentvatne** [comment]
it should work if you just remove the following entirely:

```
    "transformIgnorePatterns": [
      "node_modules/(?!react|@expo|expo)"
    ]
```

unless you are including another package that needs to be transpiled (see https://github.com/react-community/create-react-native-app/issues/199#issuecomment-307890700). nonetheless, I'm glad you found something that works

**Comment by kay-is** [comment]
Thanks, now to the JSX/ES2015 errors are gone.

Can it be that native modules have to be excluded entirely somehow?

I have a welcome screen with `react-native-video` as background and the whole thing blows up because of an `undefined` access of `Constants `native module here https://github.com/react-native-community/react-native-video/blob/master/Video.js#L172

**Comment by brentvatne** [comment]
@kay-is - you need to provide mocks for those constants. one of the nice things about using jest with expo is that we know all of the native apis that are available, so we can mock all of these for you, eg in jest-expo we have:

https://github.com/expo/jest-expo/blob/1041845d0dd128143d00a239f39921b5265e802c/src/exponentModules.js#L154-L159

then we apply all of those mocks (along with a few special case ones):
https://github.com/expo/jest-expo/blob/1041845d0dd128143d00a239f39921b5265e802c/src/setup.js#L28-L73

Regardless, this issue doesn't seem to be related to create-react-native-app anymore, maybe it's a problem with the jest documentation. The issue that has spun off from this is that we should switch the babel preset when ejecting: https://github.com/react-community/create-react-native-app/issues/243

thank you so much for your patience in going through the issue with me and sticking with it!

**Comment by Palisand** [comment]
I was receiving a `Syntax Error: Unexpected token import` originating from *react-navigation* while attempting to run tests. After adding 
```
"transformIgnorePatterns": [
  "node_modules/(?!(jest-)?react-native|react-navigation|other-problem-modules...)"
]
```
to the jest config in "package.json", the *react-navigation* error was no longer reported. Instead, jest complained with an error similar to the one mentioned [here](https://github.com/react-community/create-react-native-app/issues/199#issuecomment-300753765) (involving `expo` modules).
**This leads me to believe configuration settings in "package.json" override those in "jest-expo/jest-preset.json". Is this what is happening?**

I ended up having to copy the setting from "jest-preset.json" and include `react-navigation`:
```
"transformIgnorePatterns": [
  "node_modules/(?!(jest-)?react-native|react-navigation|react-clone-referenced-element|expo|@expo/*|exponent|@exponent/*)"
]
```

**Comment by lazzlo** [comment]
I would love some help on this too.

Jest keeps failing and displays this:

`import type { NavigationAction } from './TypeDefinition';
    ^^^^^^
    
    SyntaxError: Unexpected token import
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)`

I've tried the various methods listed here, but nothing works.

My package.json file:

`"devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-flow": "^6.23.0",
    "babel-preset-react-native": "^4.0.0",
    "jest": "^21.2.1",
    "jest-expo": "^21.0.2",
    "react-native-scripts": "1.3.1",
    "react-test-renderer": "^16.0.0"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node_modules/.bin/jest"
  },
  "jest": {
    "preset": "react-native"
  },
  "dependencies": {
    "axios": "^0.16.2",
    "expo": "^21.0.2",
    "firebase": "^4.5.1",
    "lodash": "^4.17.4",
    "moment": "^2.19.1",
    "react": "16.0.0-beta.5",
    "react-native": "0.48.4",
    "react-native-router-flux": "^4.0.0-beta.21",
    "react-native-spinkit": "^1.1.1",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
  }`

And my .babelrc file:

`{
  "presets": ["babel-preset-expo", "react-native"],
  "env": {
    "development": {
      "plugins": ["transform-react-jsx-source"]
    }
  }
}
`

A funny thing that happens when I type `npm ls --depth=1`into the console is that I get a huge list of missing dependencies. But my project runs just fine. I'm not sure what's up with that.

**Comment by debugmaster** [comment]
Following discussion too :)

**Comment by ethanbrown3** [comment]
following. I'm having the same issue as lazzlo

**Comment by pintocarlos** [comment]
I was having the same issue. After trying a few different options of the posted above, the `    "transformIgnorePatterns"` targeting the correct package did the trick and now my tests pass normally.

**Comment by dikaiosune** [comment]
@debugmaster @ethanbrown3 GitHub has a follow/subscribe system for this that doesn't add noise to the thread. The button is on the right of issue pages (towards the top).

**Comment by dikaiosune** [comment]
@ide can you take a look at lazzlo's jest issue above here?

**Comment by ide** [comment]
I probably won’t look into this for awhile so if it’s important or urgent for you I recommend creating a new project and honing in on the specific issue (may need to read source under node_modules, I usually do that to debug JS things). If there’s something specific to jest-expo (vs the React Native Jest preset or Babel) you can open an issue on that repo.
