### ISSUE TITLE
Setup CI?

### ISSUE THREAD

**Issue by anp** [react-community/create-react-native-app#2]

**Comment by dikaiosune** [comment]
This also means setting up some tests. Might be worth looking to other `create-$FOO-app` projects for inspiration.

**Comment by dikaiosune** [comment]
It would also be nice to gate CI on whether prettier would write a diff if it were run on a PR (and fail if prettier has not been run).

**Comment by lucasbento** [comment]
Also setup AppVeyor to run tests on Windows, being seeing lots of Windows issues here.
