### ISSUE TITLE
Allow template project to work with vanilla react native dependency

### ISSUE THREAD

**Issue by dikaiosune** [react-community/create-react-native-app#20]
Currently the template project is init'd with the Exponent fork of react-native:

https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/src/scripts/init.js#L14

Ideally this would use the plain ol' react-native dependency from npm.

cc @ide

**Comment by ide** [comment]
There's an incompatibility between Electron and Node right now that requires the fork for RN to run from Electron. We could either patch RN upstream (one-line fix) or get the PR into Electron.

**Comment by dikaiosune** [comment]
After slack'ing, the context here is that once these two PRs are merged, we should be able to ditch the fork:

https://github.com/electron/node/pull/21
https://github.com/electron/electron/pull/8382

**Comment by dikaiosune** [comment]
This has been resolved in a pending release of XDE -- I've already moved the template project over to vanilla JS.
