### ISSUE TITLE
Explain how to update react-native-scripts

### ISSUE THREAD

**Issue by maximromanyuk** [react-community/create-react-native-app#200]
I have react-native-scripts 0.0.27 version installed. Current version is 0.0.29. How can I check some changelogs, upgrading guide, breaking changes, etc?

**Comment by rmkpatchaa** [comment]
Hi, I think this could help ... https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/template/README.md#updating-to-new-releases 

If you want to manually upgrade using git, I've written a gist a week ago when I had the same problem with a composer project.
Check it here : https://gist.github.com/rmkpatchaa/f5949c4564cd504f72f110e6cbbd015f

**Comment by dikaiosune** [comment]
oops, accidental close

@CandyOgre at the moment we aren't trying to aggregate things like React Native and Expo changes (those projects have their own release notes), but you're right that we should track things in CRNA that change/improve/break. I'll leave this open as a tracking issue to create a CHANGELOG.

**Comment by dawidk92** [comment]
Are there any updates to this issue?
