### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by CandyOgre** [react-community/create-react-native-app#201]
How can I localize my app? I can`t use this https://github.com/AlexanderZaytsev/react-native-i18n

I tried this https://github.com/JSxMachina/react-i18nify but I got errors about babel-preset-0

What shall I do?

**Comment by terribleben** [comment]
Hi, does [this](https://docs.expo.io/versions/v16.0.0/sdk/util.html#expoutilgetcurrentlocaleasync) do what you need?

**Comment by CandyOgre** [comment]
@terribleben no, I`m talking about localization inside app, not getting current locale

**Comment by terribleben** [comment]
That's funny, because the [implementation you linked to](https://github.com/AlexanderZaytsev/react-native-i18n/blob/master/RNI18n/RNI18n.m#L19-L20) does pretty much the same thing as the [implementation I linked to](https://github.com/expo/expo/blob/master/ios/Exponent/Versioned/Modules/Api/EXUtil.m#L31-L33).

**Comment by bang88** [comment]
@CandyOgre You can use React-Intl https://github.com/yahoo/react-intl/pull/739

**Comment by CandyOgre** [comment]
@terribleben I need functionality for translating my app with two languages. I can`t use `rlink`

**Comment by CandyOgre** [comment]
![s12creenshot from 2017-05-11 12-07-35](https://cloud.githubusercontent.com/assets/8741333/25941508/7773b86e-3642-11e7-97d5-6ba7010d19a6.png)

**Comment by CandyOgre** [comment]
@bang88 this is what I get

**Comment by CandyOgre** [comment]
Don`t know how to fix it

**Comment by bang88** [comment]
See https://github.com/yahoo/react-intl/wiki#i18n-in-javascript

**Comment by CandyOgre** [comment]
@bang88 I read it, but it doesn`t help

**Comment by bang88** [comment]
You need install this https://formatjs.io/guides/runtime-environments/#intl-polyfill

**Comment by CandyOgre** [comment]
@bang88 I have it installed. Still get errors

**Comment by CandyOgre** [comment]
Created own, simple package. https://github.com/CandyOgre/react-native-translate
