### ISSUE TITLE
Stuck in "Starting packager"

### ISSUE THREAD

**Issue by tleunen** [react-community/create-react-native-app#203]
I installed the project, got the latest version with React 16, but I'm trying to reuse some code from a project using React 15 so I downgraded all versions to what's specified [here](https://github.com/react-community/create-react-native-app/blob/master/VERSIONS.md). But now, it seems the process is stuck in "Starting packager...".

Any reason why I'm having this issue? And how can I fix/debug it?

* `npm ls react-native-scripts`: react-native-scripts@0.0.29 
* `npm ls react-native`: react-native@0.42.3 
* `npm ls expo`: expo@15.1.3 
* `node -v`: v7.10.0
* `npm -v`: 4.6.1
* `yarn --version`: 0.23.4
* `watchman version`: "version": "4.7.0"

Also specify:

1. Operating system: mac OS
2. Phone/emulator/simulator & version: npm start or npm run ios produces the same issue

**Comment by deepmehtait** [comment]
@tleunen : You can try to find current running node processes and kill them. Also try to clear watchman `watchman watch-del-all` (do it multiple times), close all open terminals and `react-native start --reset-cache`. Had similar issue and solved by killing all node processes, clearing watchman and reseting cache.

**Comment by tleunen** [comment]
I tried it, and killed all node processes. I even restarted the machine and it still stuck.
I can see that the script is spawning a couple of node processes, but I don't see anything but "Starting packager" in the console and the processes don't seem very active.

**Comment by deepmehtait** [comment]
@tleunen : try to clean up your `rm -rf node_modules` folder and `npm i` see if that helps?

**Comment by tleunen** [comment]
Nop :(

I tried to create a blank new app and it works fine there. So it seems there's something wrong in my other project but the system doesn't tell me what...

**Comment by brentvatne** [comment]
what sdkVersion is specified in app.json?

**Comment by tleunen** [comment]
15.0.0

**Comment by brentvatne** [comment]
can you share the repo with me privately?

**Comment by tleunen** [comment]
Could you try this one? https://github.com/tleunen/rn-myapp

It's a basic `create-react-native-app` install, then I updated the versions in the package.json and app.json, and fully rebuild/fetch the dependencies.

**Comment by brentvatne** [comment]
@tleunen - is that one broken for you too?

**Comment by tleunen** [comment]
Yep, as soon as I change the versions for react, expo and react-native, the packager doesn't start

**Comment by brentvatne** [comment]
@tleunen - I see! the problem is that react-native-scripts isn't guaranteed to be backwards compatible, and in this case it was not. It would have been better to have an error message to indicate that -- I didn't anticipate that anybody would want to create a new project and downgrade. If you install `react-native-scripts@0.0.26` this will be fixed (tried it on your example project)

**Comment by tleunen** [comment]
Oh I see. Thanks!

The reason why I wanted to downgrade is because I'm trying to integrate with another app which was built with react 15.4. And when I tried it at first, I got a few errors related to `react/lib/ReactTransitionGroup` not being found (probably because a few things used React 16 and some others React 15. So I wanted to downgrade and see if it resolved my issue.

Anyway, thanks for finding the root cause. Funny enough, I tried to change the version of the scripts but didn't go low enough to 0.0.26 :)

**Comment by RohanNg** [comment]
I am using Ubuntu 16.04. Now the problem happens to me even with fresh CNRA app.
https://github.com/react-community/create-react-native-app/issues/343

**Comment by ranfdev** [comment]
same problem here with ubuntu 17.04

**Comment by arnabrahman** [comment]
Happening in Ubuntu 16.04. I am new to react. What should i do?

**Comment by precocious** [comment]
This should resolve the "Starting packager" issue: [https://forums.expo.io/t/packager-not-loading-on-linux/2034/3](https://forums.expo.io/t/packager-not-loading-on-linux/2034/3)

**Comment by marco-fp** [comment]
Clean installation of Antergos with Gnome, npm 4.6.1, node 6.11.2. Already tried:
```
 sudo sysctl -w fs.inotify.max_user_instances=1024
  sudo sysctl -w fs.inotify.max_user_watches=12288
```

**Comment by precocious** [comment]
After dealing sometime with this problem, the only stable solution I found was to install [watchman](https://facebook.github.io/watchman/). Now everything is OK.

**Comment by praWeb** [comment]
I have tried all the above solutions. But none of them had worked. It was working fine till last week. Suddenly it stopped working. Any help ?

**Comment by brentvatne** [comment]
@praWeb - jump into https://slack.expo.io and dm brent

**Comment by nattanonm** [comment]
Try to install yarn, then run 'yarn start'

**Comment by Eldelshell** [comment]
Had the same problem just starting with _create-react-native-app_ today on Ubuntu 17.10 and finally got it working on Linux.

First of all:

```
Environment:
  OS: Linux 4.13
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: ^0.49.5 => 0.49.5
```

Install watchman as explained [here](https://facebook.github.io/watchman/docs/install.html)

For a fresh install you'll need the following to build Watchman:

```
$ sudo apt-get install python-dev libssl-dev autoconf automake libtool
```

Follow the instructions for *Build from Source*.

Next, this:

```
$ echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
$ echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
$ echo fs.inotify.max_queued_events=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

And finally, you can run `yarn start` and it should work.

**Comment by BWillis98** [comment]
For me, if I just press 'q' it displays the QR code, but it won't display the QR code automatically. If I don't press 'q', it will just say "running packager".

**Comment by kakkarott** [comment]
> For me, if I just press 'q' it displays the QR code, but it won't display the QR code automatically. If I don't press 'q', it will just say "running packager". However, then it leads to issue 81.

works for me

**Comment by harshalthakre** [comment]
AwesomeProject@0.1.0 start /home/harshal/react-Native/AwesomeProject
> react-native-scripts start

00:44:36: Starting packager...


its been five minutes its still have'nt started, I think it will wait for infinite time?
Whats the issue here?

**Comment by stopal** [comment]
Well... its almost a year since this is posted. Even the "Getting Started" skeleton wont work... and i cant figure out why. This cant be right :(

**Comment by marksilvis** [comment]
Removing the following from `app.json` worked for me:

```javascript
"packagerOpts": {
  "nonPersistent": true
}
```

**Comment by nickerlan** [comment]
For me the same issue was in accessing expo.io 
The solution worked for me is using proxy.

Thanks to @p0liper for setting up special proxy for that: https://github.com/react-community/create-react-native-app/issues/653

**Comment by pashute** [comment]
By me the issue was that the start command in package.json had changed from: 

    "start": "node node_modules/react-native/local-cli/cli.js start",

to 

        "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "jest"

**Comment by kenji-1996** [comment]
Really blows my mind that these sort of problems are in a starter seed that facebook themselves published.
If you want to get people into your platform then this is not the way to do it

**Comment by abayo-luc** [comment]
Just delete the yarn lock file, and run ``yarn start``

**Comment by pashute** [comment]
thanks abayo-luc  that solved it!

**Comment by kenji-1996** [comment]
Alot of people are using NPM; and these sorts of problems shouldnt need weird trouble shooting to fix

**Comment by brentvatne** [comment]
this is an old issue that conflates a bunch of different root causes with one message. locked conversation because it's off topic.

@kenji-1996 - this library is not published or maintained by facebook.
