### ISSUE TITLE
Injecting your own custom scripts

### ISSUE THREAD

**Issue by mobinni** [react-community/create-react-native-app#204]
Hi there, I had a couple of questions about the core philosophy of create-react-native-app. I was going to post this on stackoverflow, however I thought the discussion would be useful here.

I understand that when you want to divert from the current setup you must eject in order to make your own adjustments to native code and JS code. However I was wondering if there is a way to alter how to bootstrapping works.

Say for instance I want to use create-react-native-app and retain the structure to stay up-to-date but during the bootstrapping I want to inject my own custom files and structure. Say for instance I did not want to use the expo library. Is there a way to accomplish this without ejecting? Would it be better to just use the react-native init tool?

**Comment by dikaiosune** [comment]
Great question! I think you'd probably be better off using `react-native init` in that case, yeah. For one thing, the "don't build any native code" nature of CRNA relies heavily on Expo, so I don't think there'll be a good way to support going without it in the future. It'd be kind of like making a `create-react-app` without webpack -- might be cool, but kind of out of scope for the project.

We may explore using pluggable templates in the future, but for now it's definitely advantageous for QA and troubleshooting if users only have one option for initial project structure.

Thanks!
