### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by iRoachie** [react-community/create-react-native-app#205]
How can I enable RTL through crna/expo, the steps shown online are only for projects created with react-native standard cli. Would I have to eject to do this?

**Comment by brentvatne** [comment]
Hi @iRoachie! YMMV with this right now. You can try this out:

- https://snack.expo.io/SyNfcp7l-
- Open the app, tap the switch, then reload the app (using the notification drawer on Android or shake and press reload on iOS)

**Comment by iRoachie** [comment]
Thanks! This will do for now!

**Comment by eldadcaspi** [comment]
Hi there, any tricks to load the app with I18nManager.forceRTL() for a single (RTL) language app?
i can't get it to work with Expo. Maybe it's a matter of putting the forceRTL in the right lifecycle method? Thanks

**Comment by brentvatne** [comment]
@eldadcaspi - we haven't tested it a lot, like I mentioned above unfortunately it only seems to work when you reload the app after calling `forceRTL`

**Comment by nir-welldone** [comment]
Any new updtes?
