### ISSUE TITLE
Pass down `props` for getting extra field from expo.json

### ISSUE THREAD

**Issue by giautm** [react-community/create-react-native-app#206]
https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/src/bin/crna-entry.js#L16

I think this line should be fix to: 

```
// we don't want this to require transformation
class AwakeInDevApp extends React.Component {
  render() {
    return React.createElement(
      View,
      {
        style: {
          flex: 1,
        },
      },
      React.createElement(App, this.props),
      React.createElement(process.env.NODE_ENV === 'development' ? Expo.KeepAwake : View)
    );
  }
}
```

**Comment by dikaiosune** [comment]
This is tricky. We probably want to think about what this impacts a little bit more. For one thing, people using CRNA should generally be encouraged to write code that can eject to "raw" RN very cleanly, and adding more Expo-specific stuff here concerns me as a result. This is one reason why I exposed the `REACT_NATIVE_*` environment variables in `process.env` -- it allows you to pass configuration in an implementation-independent way that you can easily reproduce if you were to eject.

That said, this could be very nice to have, just want to think about it more.

**Comment by dikaiosune** [comment]
By the way, thanks so much for sending this PR and great catch!
