### ISSUE TITLE
Debugging with Nuclide doesn't seem to work.

### ISSUE THREAD

**Issue by scf4** [react-community/create-react-native-app#209]
It just hangs on "Starting Debugger..." and doesn't seem to do anything.

Is this a known issue?

**Comment by dikaiosune** [comment]
In order to debug with Nuclide, you'll need to specify the packager port, and I'm not sure if Nuclide supports that being configurable yet. If you (or someone reading) nails down good steps for doing so, please post here and we'll include it in the user guide.

**Comment by brentvatne** [comment]
cc @vjeux - we would love to make crna work with debugging out of the box with Nuclide

**Comment by vjeux** [comment]
Sooooo, it's a bit embarrassing but Nuclide debugger doesn't work with React Native. It went through waves of working, being broken and working again but due to the low usage, it has never been a high priority to fix it.

We're likely going to fix it again in the future but now it's not, sorry!

**Comment by wuno** [comment]
Is this still the case? or is it supposed to work now?

**Comment by brentvatne** [comment]
probably not? check the nuclide repo to see if they added support for react-native debugging again
