### ISSUE TITLE
'react-native-scripts' command not found on windows 7 os

### ISSUE THREAD

**Issue by axlider** [react-community/create-react-native-app#211]
Done installation as described in installation instructions:
> npm i -g create-react-native-app 
> create-react-native-app my-project 
> cd my-project 
> npm start

After 

> npm start

i get the error "create-react-native scripts" command not found.
I updated node.js cleared als the caches and so on...
I also installed with administration privileges

Propably it is only windows related. Is there a workaround so "react-native-scripts" can be found on windows?

**Comment by axlider** [comment]
I upgraded (uninstalled and installed) yarn to latest version.
Now it works!

**Comment by JefferyHus** [comment]
if anyone is willing to use npm only, then run this `npm i react-native-scripts --save`, then npm start or whatever the command you use
