### ISSUE TITLE
very slow bundle generation

### ISSUE THREAD

**Issue by thheller** [react-community/create-react-native-app#213]
## Description

I created a tool targeted at JS developers that want to use ClojureScript with existing JS tools like this one. However as soon as I use use some of the generated JS code the bundle generation gets extremely slow.

## Expected Behavior

```
2:39:28 PM: Finished building JavaScript bundle in <acceptable time>ms
```

Just `yarn start` after `shadow-cljs --once` completed.

## Observed Behavior

```
2:39:28 PM: Finished building JavaScript bundle in 108191ms
```

The startup eventually completed but took considerable amounts of time. No errors are generated and the code works just fine. Generating a new bundle after changing some code takes just as long.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: `react-native-scripts@0.0.29`
* `npm ls react-native`: `react-native@0.43.4`
* `npm ls expo`: `expo@16.0.0`
* `node -v`: `v7.10.0`
* `npm -v`: `4.2.0`
* `yarn --version`: `0.24.4`
* `watchman version`: `4.7.0`

## Reproducible Demo

https://github.com/thheller/npm-module-example/blob/master/examples/react-native-example/README.md

`shadow-cljs --once` generates code into the `./node_modules/shadow-cljs` directory (ie. `./node_modules/shadow-cljs/cljs.core.js`). 

It generates ES3 JS code. The file is `2.4MB` and contains an inline source-map with the original `sourcesContent`. I'm not sure why it would be so extremely slow. No other tools I have tested (`webpack`, `browserify`, `create-react-app`) showed noticeable slowdowns.

I'm not familiar with `react-native` at all and this is the first time I tried using it. If I'm supposed to exclude or configure something please let me know. I just used `yarn create react-native-app` generator and added one `.cljs` file.

Short overview for the `shadow-cljs` tool:
https://github.com/thheller/shadow-devtools/wiki/ClojureScript-for-JS-Devs

I uploaded all the generated CLJS -> JS code here:
http://thheller.com/files/create-react-native-app/
http://thheller.com/files/create-react-native-app/cljs.core.js
http://thheller.com/files/create-react-native-app/demo.foo.js

**Comment by thheller** [comment]
Ok, I figured it out. The babel `:presets` are responsible, doesn't seem to be possible to disable `:presets` for one directory.

Tried using a `.babelrc` with just `{ "presets": [] }` in the directory but that doesn't seem to have an effect.

Nevermind.

**Comment by cogwheel** [comment]
@thheller Can you elaborate? What did you change to make it work correctly? We are having the same problem.

**Comment by thheller** [comment]
Since `0.45.0` the `.babelrc` works again.

I have this `.babelrc` in the folder that has all the generated `.js` code. In the case of ClojureScript the generated code is ES3 already so it does not need any babel transforms.

```javascript
{
    "ignore": ["*.js"]
}
```

I do not know if it is possible to run custom babel transforms. I only tried not running any.

**Comment by newzhongdan** [comment]
try with this commands: 

sudo chown -R $USER ~/.npm
sudo chown -R $USER /usr/local/lib/node_modules


work for me, before time 5-8min, after this commands 1-2 min

source: https://facebook.github.io/react-native/docs/troubleshooting.html#content
