### ISSUE TITLE
Issues with Symlinks

### ISSUE THREAD

**Issue by ishortman** [react-community/create-react-native-app#214]
## Description

Having issues with app project running inside a lerna project.  The issue is a particular node module is replaced by a symlink and when adding the import statement the output returns a missing module inside node_modules.  That module is a symlink within the lerna project and doesn't seem include the module during export.  But when I run add the package such as `yarn add` the exported node_modules work. Is there settings or configuration to resolve symlinks?

## Expected Behavior

Expected the symlinks to get resolved properly.

## Observed Behavior

On the error I cleared out the cache and followed the recommended clearing of node cache.

```
Unable to resolve module `@test/test-redux` from `/projects/app/packages/app/App.js`: Module does not exist in the module map or in these directories: /projects/app/node_modules/@test
```

## Environment

Ran this command to clear cache
```
watchman watch-del-all
rm -rf ./node_modules
npm cache clean
yarn cache clean
rm -rf $TMPDIR/react-*
yarn install
npm cache clean
yarn cache clean
```

Also specify:

1. Mac OS
2. iPhone Simulator & version: 10.2

**Comment by agrcrobles** [comment]
I am getting the following when using lerna `Failed building JavaScript bundle` any help is welcome

**Comment by dikaiosune** [comment]
Related: https://github.com/facebook/react-native/issues/637

**Comment by dikaiosune** [comment]
I believe some work is happening upstream to improve symlink support for the RN packager, going to close this as this will be fixed once it is there. Thanks!
