### ISSUE TITLE
development with ngrok

### ISSUE THREAD

**Issue by lmittmann** [react-community/create-react-native-app#215]
Is there a way to use **ngrok** for development?

Since `npm start` exposes the packager on port 19001 and the expo server (logs and some metadata if I'm not mistaken) on port 19000 it would be necessary to manually set both host and port for the `bundleUrl` filed in the response for `curl localhost:19000`. While I can set the host using the environment variable `REACT_NATIVE_PACKAGER_HOSTNAME` I found no way to specify a custom port.

So is there a way to change the port, or to use ngrok for development?

**Comment by ccheever** [comment]
The easiest way to do this is just to use XDE or exp, the Expo development tools. ngrok and some other convenient services are just built in.

https://expo.io/tools
