### ISSUE TITLE
Undefined exception when ejecting.

### ISSUE THREAD

**Issue by Papipo** [react-community/create-react-native-app#219]
## Description

I get an undescriptive en error when ejecting.

## Expected Behavior

Either eject properly or at least get a meaningful error.

## Observed Behavior

I get this output (Chose ExpoKit ejecting method):

```
Validating project manifest...
Downloading iOS code...
Moving iOS project files...
Error running eject: undefined
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@0.0.29
* `npm ls react-native`: react-native@0.43.4
* `npm ls expo`:  expo@17.0.0
* `node -v`: v6.10.1
* `npm -v`: 3.10.10
* `yarn --version`:0.24.4
* `watchman version`: "4.7.0"

Operating system: OSX Sierra

**Comment by dikaiosune** [comment]
Can you paste your package.json and app.json and I'll reopen?

**Comment by Papipo** [comment]
I ended up ejecting with `exp detach`.
