### ISSUE TITLE
CRNA should add .eslintrc file in project

### ISSUE THREAD

**Issue by nsisodiya** [react-community/create-react-native-app#221]
I generated project using 
```
create-react-native-app test
cd test
```
There is no `.eslintrc` file present. It will be great if we provide a default eslintrc file.

**Comment by dikaiosune** [comment]
Hi! That's a very interesting idea. However, lint rules are pretty contentious! And we want to make sure that the project can be used by anyone without enforcing any particular code style. I think it may make sense at some point to have a `eslint-config-react-native-app` that beginners can use if they want an easy preset, but I'm not excited about taking on extra maintenance for that, nor for the inevitable bikesheds over what to include or not in the configuration.

In my ideal world, there would be no configuration in the template project beyond the package.json, but that will take a lot of work to achieve.

**Comment by nsisodiya** [comment]
May be you can keep it for future. Having a minimal eslist is sufficient
 Idea is not to give user a contrain bit kickstart over which he can add his rules by modifying .eslintrc file. You are also giving package.json which is minimal , who not one other file. Eslintrc is must for any js project. I do not think it requires a lot of maintenance efforts. All you need to keep all most empty . eslintrc file and 2-3 more entries in package.json. why not.
