### ISSUE TITLE
can't eject: "Error running eject: undefined"

### ISSUE THREAD

**Issue by kinergy** [react-community/create-react-native-app#223]
## Description

Brand new project, then run `npm run eject`

## Expected Behavior

I expected the to be able to eject (in order to add a native linked library) and keep the Expo libs included.

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Helios:k10 kimon$ npm run eject

> k10@0.1.0 eject /Users/kimon/Development/k10
> react-native-scripts eject


We didn't find any uses of the Expo SDK in your project, so you should be fine to eject to
"Plain" React Native. (This check isn't very sophisticated, though.)

We strongly recommend that you read this document before you proceed:
  https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md

Ejecting is permanent! Please be careful with your selection.

? How would you like to eject from create-react-native-app? ExpoKit: I'll create or log in with an Expo account to use React Native and the Expo SDK.

An Expo account is required to proceed.

? It appears you're already logged in to Expo as kinergy, would you like to continue with this account? Yes, continue as kinergy.
Validating project manifest...
Downloading iOS code...
Moving iOS project files...
Error running eject: undefined
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
```
k10@0.1.0 /Users/kimon/Development/k10
└── react-native-scripts@0.0.29
```
* `npm ls react-native`:
```
k10@0.1.0 /Users/kimon/Development/k10
└── react-native@0.44.0
```
* `npm ls expo`:
```
k10@0.1.0 /Users/kimon/Development/k10
└─┬ expo@17.0.0
  └── UNMET PEER DEPENDENCY react@>=15.3.1

npm ERR! peer dep missing: react@>=15.3.1, required by lottie-react-native@1.1.1
npm ERR! peer dep missing: react@>=15.4.0, required by react-native-branch@2.0.0-beta.3
npm ERR! peer dep missing: react@>=15.4.0, required by react-native-maps@0.14.0
```
* `node -v`:
```
v7.10.0
```
* `npm -v`:
```
4.2.0
```
* `yarn --version`:
```
0.24.5
```
* `watchman version`:
```
{
    "version": "4.7.0"
}
```

Also specify:

1. Operating system: Mac OS X 10.12.5
2. Phone/emulator/simulator & version: N/A

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by brentvatne** [comment]
Thanks for pointing this out @kinergy! I tried the exact repro steps and had the same error

**Comment by kinergy** [comment]
Same result in Node 6...

**Comment by brentvatne** [comment]
@kinergy - indeed, this has nothing to do with the node version -- we changed the format of the iOS template that is downloaded and it wasn't accounted for yet because we are slightly delayed on a new create-react-native-app release due to @dikaiosune and I being tied up with React Europe.

We'll have a fix for this today. Also cc @terribleben

**Comment by erhathaway** [comment]
@kinergy now that the fix is out, updating your `react-native-scripts` to a newer version (ex `0.0.40`) should fix the problem
