### ISSUE TITLE
Update fs-promise

### ISSUE THREAD

**Issue by dikaiosune** [react-community/create-react-native-app#225]
`warning react-native-scripts > fs-promise@1.0.0: Use mz or fs-extra^3.0 with Promise Support`

**Comment by shashkovdanil** [comment]
https://github.com/react-community/create-react-native-app/pull/227

**Comment by shashkovdanil** [comment]
Hi, how to upgrade dependencies compiled app? I have long tried to find this place in the code, but I could not. Help please

**Comment by brentvatne** [comment]
> Hi, how to upgrade dependencies compiled app? I have long tried to find this place in the code, but I could not. Help please

could you explain this another way? sorry I don't understand :(

closing this issue thanks to your PR @shashkovdanil!
