### ISSUE TITLE
Use With Native Base

### ISSUE THREAD

**Issue by stolinski** [react-community/create-react-native-app#230]
## Description

`Getting undefined is not an object ( evaluating '_reactNative.ViewPropTypes.style').` 
When attempting to import a component from native-base.  Tried following this example, https://github.com/expo/nativebase-example but app doesn't have an exp.json file. Adding one cause errors but adding the relevant lines from the exp file do nothing.

## Expected Behavior

The library to work as it would normally or at the very least, work as it does with Expo.

## Observed Behavior

`Getting undefined is not an object ( evaluating '_reactNative.ViewPropTypes.style').` 

## Environment

Mac OS, latest everything. Fresh CRNA project, nothing fancy. On iOS simulator.

**Comment by brentvatne** [comment]
hello! the expo example uses sdk13: https://github.com/expo/nativebase-example/blob/master/exp.json#L6

any issues with third party library integration should be created on the third party library repos unless it's demonstrated that there is something that create-react-native-app is doing incorrectly that is breaking integration. can you re-create this issue on the "NativeBase" repository?

**Comment by brentvatne** [comment]
it's also worth noting that they have some Expo/CRNA specific instructions in their documentation now: https://github.com/GeekyAnts/NativeBase#setup-with-crna

**Comment by stolinski** [comment]
This is not an issue with the native-base library as it works fine in just about any other context.

This is an issue with expo. The way to get this working with expo, was in the listed example, regardless of what sdk it uses, it's also on Expo's own blog. 

Expo requires you to use 

```
  "packagerOpts": {
    "assetExts": ["ttf", "mp4"]
  },
```

but this doesn't seem possible with CRNA. What is the work around here. This is not a Native Base issue, this is an expo issue.

**Comment by brentvatne** [comment]
@stolinski - I answered you on Twitter re: app.json vs exp.json which explains why it is not an Expo issue

**Comment by stolinski** [comment]
This is definitely a confusing experience. Why have both app.json and exp.json exist. If all the docs for expo say to use exp.json.

**Comment by stolinski** [comment]
The link above just shows the formatting difference in the .json files.

Either way, the point is just that you have a branded easy solution to get up and running, you have a major library and the standard install process breaks. If this works correctly and normally without Expo, I fail to see how this isn't an issue with CRNA & Expo.  Not trying to point fingers or anything, just putting out there that it's not a good experience.

**Comment by brentvatne** [comment]
I agree that's a little confusing! I would love some help in coming up with a better way to explain it. Here's some historical context:

- Expo was created a couple of years ago and we kept configuration in package.json at first.
- We realized that package.json was getting really large and difficult to manage with Expo config inside of it, so we moved it to its own file called exp.json about a year and a half ago.
- Several months ago we started working with folks at Facebook to make Create React Native App (CRNA). One of their goals was to make it possible for other tools like Expo to arise as alternatives and interop with CRNA. So, we made app.json namespace configurations for various clients such that in the future if, eg, @stolinski decides to create one, you can create a `"solinski"` namespace in app.json and your client can read from that and work with CRNA.
- Today you ran into this issue. It has been observed by others before, but we haven't been satisfied by any solution. Perhaps the right approach is to remove exp.json now and use app.json everywhere. That would be potentially annoying to existing users of Expo, but make things clearer for people who use CRNA and want to use Expo APIs. We are very open to suggestions for how we can improve messaging around this or fix the problem entirely.

**Comment by brentvatne** [comment]
> If this works correctly and normally without Expo, I fail to see how this isn't an issue with CRNA & Expo

I'm not sure that it does -- what I was responding to specifically with that comment was the error message that you shared, which is unrelated to exp.json/app.json, Expo, or CRNA:  `Getting undefined is not an object ( evaluating '_reactNative.ViewPropTypes.style')`

**Comment by stolinski** [comment]
Ah, my apologies, I incorrectly thought I was facing this issue.

https://github.com/expo/expo/issues/32

**Comment by brentvatne** [comment]
@stolinski - I initialized a new project and got NativeBase running on it here: https://github.com/brentvatne/crna-demo-issue-230

**Comment by stolinski** [comment]
Apparently it's an issue of what me being on RN 0.43.4 and not 44. https://github.com/GeekyAnts/NativeBase/issues/851

Like you said, it was a RN / Native Base issue, not an CRNA or Expo one.  I appreciate the time even though you were correct from the start and I wasn't listening well.

**Comment by brentvatne** [comment]
That makes sense!

Not a problem @stolinski -- I'm glad you sparked the app.json and exp.json discussion again, @dikaiosune and I spoke a bit about it as a result and we're leaning heavily towards getting rid of exp.json entirely and standardizing on app.json.
