### ISSUE TITLE
Cannot open the test app in web browser

### ISSUE THREAD

**Issue by yuren1978** [react-community/create-react-native-app#237]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

I am trying to open the app at http://192.168.0.1:19000/, it just hangs.

## Expected Behavior

I should be able to see the application and debug in console.

## Observed Behavior

The site cannot be reached.

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
The site cannot be reached.
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
* `npm ls react-native`:
* `npm ls expo`:
* `node -v`:
* `npm -v`:
* `yarn --version`:
* `watchman version`:

Also specify:

1. Operating system:
2. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by brentvatne** [comment]
I don't understand what you're trying to do :(

Apps that you build with Create React Native App will run on iOS and Android. They will not run in a web browser.
