### ISSUE TITLE
Eject leads to wrong bundle identifiers

### ISSUE THREAD

**Issue by kay-is** [react-community/create-react-native-app#238]
## Description

I ejected and my bundle identifiers were wrong.

## Expected Behavior

Would be nice if the whole project had the right bundle identifier after an eject.

## Observed Behavior

I got the wrong bundle identifiers.

I still built, but when I added the Facebook SDK for iOS, the builds started failing.

I had to set the bundle identifier manually in xCode. In some places in the `Info.plist` there was still a `com.facebook.REACT.example` (I made an example project) instead of the one I set in xCode.

**Comment by brentvatne** [comment]
Eject with ExpoKit or normal eject?

**Comment by brentvatne** [comment]
cc @terribleben

**Comment by kay-is** [comment]
Normal, without ExpoKit.

**Comment by brentvatne** [comment]
OK it looks like that is a problem with react-native-cli's `eject` command: https://github.com/facebook/react-native/blob/bc74dd1e14372ce2ff7c6d21401e67c946eb7595/local-cli/eject/eject.js

I'll look into that when I get a chance, or if you have the time that would be helpful as well!

**Comment by tomcrusader** [comment]
Is it preferable to use Expo's eject, or would you miss out on something else then?

**Comment by brentvatne** [comment]
@tomcrusader - more about this in the readme: https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md
