### ISSUE TITLE
npm start throws error

### ISSUE THREAD

**Issue by kenmasters** [react-community/create-react-native-app#239]
im using node v6.9.5 and npm 5.0.2

im getting this error when running npm start,

> react-native-scripts start                                                                            
                                                                                                        
9:55:03 PM: Starting packager...                                                                        
9:55:09 PM: Error starting packager: Error: Couldn't start project. Please fix the errors and restart th
    at E:\xdl\src\Project.js:1039:11                                                                    
    at next (native)                                                                                    
    at step (E:\Projects\RN\CurrencyConverter\node_modules\xdl\build\Project.js:1461:191)               
    at E:\Projects\RN\CurrencyConverter\node_modules\xdl\build\Project.js:1461:361                      
npm ERR! code ELIFECYCLE                                                                                
npm ERR! errno 1                                                                                        
npm ERR! CurrencyConverter@0.1.0 start: `react-native-scripts start`                                    
npm ERR! Exit status 1                                                                                  
npm ERR!                                                                                                
npm ERR! Failed at the CurrencyConverter@0.1.0 start script.                                            
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.      
                                                                                                        
npm ERR! A complete log of this run can be found in:                                                    
npm ERR!     C:\Users\kjsiosan\AppData\Roaming\npm-cache\_logs\2017-06-04T13_55_09_980Z-debug.log

**Comment by brentvatne** [comment]
Hello! npm5 is not stable. There is already an open issue for this (https://github.com/react-community/create-react-native-app/issues/233) *and* a note in the README :)

**Comment by kenmasters** [comment]
Thanks @brentvatne.
