### ISSUE TITLE
Can't make requests to local API server

### ISSUE THREAD

**Issue by mzdunek93** [react-community/create-react-native-app#241]
## Description

Can't connect to an API server ran on my local machine from my android phone running my Expo app. The IP address of my machine on my local network is `192.168.1.14`, so my app is served on the URL `http://192.168.1.14:19000`. My API server is on `http://192.168.1.14:3000`, and I can connect to it on my phone browser. 

## Expected Behavior

The fetch request to `http://192.168.1.14:3000` should return the same data as the request through my browser.

## Observed Behavior

I have to wait around 30 seconds of awaiting for a response, then I get this:

```
Possible Unhandled Promise Rejection (id: 0):
TypeError: Network request failed
onerror@http://192.168.1.14:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:13802:29
dispatchEvent@http://192.168.1.14:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:14702:39
setReadyState@http://192.168.1.14:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:16809:31
__didCompleteResponse@http://192.168.1.14:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:16665:27
http://192.168.1.14:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:16760:50
emit@http://192.168.1.14:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:5278:40
__callFunction@http://192.168.1.14:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:3517:47
http://192.168.1.14:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:3375:29
__guard@http://192.168.1.14:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:3489:11
callFunctionReturnFlushedQueue@http://192.168.1.14:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&hot=false&minify=false:3374:19
callFunctionReturnFlushedQueue@[native code]
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@0.0.30
* `npm ls react-native`: react-native@0.44.2
* `npm ls expo`: expo@17.0.0
* `node -v`: v7.4.0
* `npm -v`: 4.0.5
* `yarn --version`: 0.24.5
* `watchman version`: 4.7.0

Also specify:

1. Operating system: Ubuntu 16.04
2. Phone/emulator/simulator & version: Android 6.0.1

**Comment by brentvatne** [comment]
hello! I think you may be mistaken and have made some error somewhere in your code. see https://github.com/brentvatne/crna-issue-241-example for a minimal example of what you describe in this issue, and notice that it works as expected. if that example doesn't work for you then let me know!

**Comment by ericdfanning** [comment]
@brentvatne other solutions were not helping or working by using the local IP, but your code in your link helped a lot. Thanks!

**Comment by Nermin-K** [comment]
I have the same problem and I have tried to replace "localhost" with my machine IPv4 address but nothing has changed! I got the same error "Network request failed". 
I also followed the link provided by @brentvatne  but still get the same error. 
I don't use express as my local server, I got my API from ASP.NET Web API application. and it works fine on Postman.

**Comment by brentvatne** [comment]
you need to be able to access the server from your phone. if you can't access it from a web browser you also can't access it from an app

**Comment by Nermin-K** [comment]
@brentvatne but I can access it from my web browser and it also works fine with Postman. The problem is just with the react native, it keeps returning "Network request failed" error.

**Comment by brentvatne** [comment]
your web browser on your phone?

**Comment by Nermin-K** [comment]
@brentvatne  no, on my pc

**Comment by brentvatne** [comment]
right, the problem here is that you need to be able to connect to the server from your phone

**Comment by Nermin-K** [comment]
@brentvatne  could you help me with that?! how can I connect to the server? Is it okay to use express with ASP.NET Web back-end?
I'm sorry if it is a stupid question, it's my first time ever to deal with react native or ASP.NET Web API or even APIs in general.

**Comment by brentvatne** [comment]
hi @Nermin-K - this isn't really a thing specific to react-native or ASP.NET or anything like that. you need to make your server somehow reachable from your phone. you could use ngrok for that if your router doesn't allow you to access other computers on the network - https://ngrok.com/

**Comment by Nermin-K** [comment]
@brentvatne that was very helpful. thanks a lot.

**Comment by ezranbtmr** [comment]
@Nermin-K did you solve that issue? i have a problem with exactly as you had.

**Comment by Nermin-K** [comment]
@ezranbtmr using ngrok, yes. use this command by ngrok cmd `ngrok http 64599 --host-header="localhost:64599"` you should replace 64599 with your port number. ngrok will give you a 7 hours session after it finishes, you have to run the command again and edit your code with the new URL.

**Comment by dlaugh14** [comment]
Well, for some of you PHP developers out there....

If you're not bound to using Apache or nginx for some special reason and this is for development purposes only, you could serve the application using the PHP built-in server and artisan. It's by far the easiest thing to setup, and will only require you to run one command in the Laravel application directory:

php artisan serve --host 0.0.0.0
The default port it will be listening to will be 8000 to avoid any conflicts, so you can now access the application from your phone via the IP address of your computer:

http://192.168.1.101:8000
If you want to listen to another port (for example the default HTTP port of 80) you can pass that as a parameter, just make sure no other server is running on that port. So if you run this instead:

php artisan serve --host 0.0.0.0 --port 80
You can now access your application with just the IP address:

http://192.168.1.101

I ran php artisan serve --host (computer IP) and I'm not golden to test my local dev calls from the Expo app!

**Comment by at-hoangnguyen** [comment]
@dlaugh14 you saved my day

**Comment by Carles11** [comment]
You could try this:
Open "Node.js command prompt" and type `ipconfig`. From there, copy your IPv4-IP-address.
Then, in your code, change the request URL from `http://localhost:8000` to` http://YOUR-IP-ADDRESS:8000`
That worked for me.

**Comment by sh3p4rd83** [comment]
> Hi. I had the same problem and i can connect the mobile app with react native to the asp.net server web app. I have to turn off the firewall of windows, that was blocked my ports and i wasnt able to connect to the server api. This work for me.

After more than 5 hours of debugging, that was my issue. Opened the firewall for this specific port on my domain, and it worked. Thanks

**Comment by sunilswain** [comment]
Hey what could be my problem? 
let's say I'm running my local API server on 192.168.0.99 and when I tested the app through Expo Go, it was successfully making requests. Once my collegue converted into an actual independent, it stopped making any requests. I tried accessing the server through browser and it faces no issue accessing it. 

I don't know much it's my collegue who's making the app and he uses an app called Expo before bundling it.

**Comment by 0wulf** [comment]
I am facing the exact same problem that @sunilswain 
My API server is an HTTP and not HTTPS, but it is working with the development build.
The ports from the API server's host machine are open and accessible from the browser.

**Comment by zaibi7262** [comment]
My problem is when I run my expo app on my lap top it work fine. But after creating apk when i install it in my phone then login api do not hit. I changed the BaseUrl from public host to my laptop's ipv4 address but still it do not working.

One more thing when i test the public api on post man it worked fine but when i test the same api with my laptop's ip address then it fails.
@sunilswain  @dlaugh14 @brentvatne 
please give me some suggestions

**Comment by 0wulf** [comment]
The funny part for me was that I had the firewall blocking all ports. I use firewalld so with firewall-ctl I was able to open the port and have a working comunication

**Comment by dlaugh14** [comment]
@zaibi7262 - make sure it's running on the port you expect it to - and if not use - ngrok for now.

Like I have an llm bot on my website in prod (so I can test on my tablet) - then point my UI to grok url

so you install ngrok-cli tool - create an account - I think the command line prompt will open up a browser to authenticate - then run "ngrok http 9000" - this will generate you a url and show in terminal - you can also login to ngrok on line and see the url and use that - in prod for testing - or local on another pc or whatever if needed. It will connect to the app on your computer if it's running on http 9000 like in my ngrok command above. Its simple for just a quick fix - also free. Unless you're setting up for a team it might be work just smarter to do that for now. Also use LLM's and put full output and ask for suggestions. that can help too.

**Comment by zaibi7262** [comment]
Okay thanks I'll surely test your solution
