### ISSUE TITLE
Switch to babel-preset-react-native and remove jest-preset-expo when ejecting to plain React Native project

### ISSUE THREAD

**Issue by brentvatne** [react-community/create-react-native-app#243]
Related to:
- https://github.com/react-community/create-react-native-app/issues/47
- https://github.com/react-community/create-react-native-app/issues/199

When you eject to a plain React Native project, we install `"babel-preset-react-native"` and change the preset used in `.babelrc` to `"react-native"`.

**Comment by fson** [comment]
The template `.babelrc` file uses `babel-preset-expo`, which extends `babel-preset-react-native` by adding decorator support. I think this makes it possible to use decorators in CRNA apps. If we replace the `"expo"` preset to `"react-native"`, wouldn't it break any app that relies on the decorator support?

**Comment by brentvatne** [comment]
@fson - good point, we should use `babel-preset-react-native-stage-0/decorator-support` (this is the same preset that `babel-preset-expo` extends)

**Comment by fson** [comment]
This was added in #328.
