### ISSUE TITLE
Crash after upgrade from 15 to 16

### ISSUE THREAD

**Issue by silasrm** [react-community/create-react-native-app#244]
Hi,

I'm following this article to update https://blog.expo.io/expo-sdk-v16-0-0-is-now-available-2151d555a580 but after run, on startup of app, this error occurs:

![screenshot_1496751658](https://cloud.githubusercontent.com/assets/197187/26828980/13c2e80a-4a9a-11e7-8657-37164cfc6e4d.png)

In package log has only a simple error message:

```
Logs from serving your app will appear here. Press Ctrl+C at any time to stop.

09:13:06: Failed building JavaScript bundle
```

My package.json diff:

```
-    "react-native-scripts": "0.0.26",
-    "jest-expo": "^0.3.0",
-    "react-test-renderer": "~15.4.1",
+    "react-native-scripts": "0.0.28",
+    "jest-expo": "^0.4.0",
+    "react-test-renderer": "16.0.0-alpha.6",
-    "expo": "^15.1.0",
+    "expo": "^16.0.0",
-    "react": "~15.4.0",
-    "react-native": "0.42.3",
+    "react": "16.0.0-alpha.6",
+    "react-native": "0.43.4",
```

* `npm ls react-native-scripts`: 0.0.28
* `npm ls react-native`: 0.43.4
* `npm ls expo`: ^16.0.0
* `node -v`: v7.10.0
* `npm -v`: 4.2.0
* `yarn --version`: 0.24.4
* `watchman version`: 4.7.0

Operating system: Ubuntu 17.04
Phone/emulator/simulator & version: Android SDK Emulator with rom Nexus 5 API 23

I'm using this theme from base to my app: https://market.nativebase.io/view/react-native-flat-app-theme
No demo. I don't send to Expo with error.

**Comment by brentvatne** [comment]
Hello! Please ask for support from the react-native-flat-app-theme project, we do not provide support for these things. If this turns out to be a problem with CRNA or Expo then please narrow the error down to a reproducible minimal example then we can investigate.

**Comment by silasrm** [comment]
@brentvatne I'm desire to upgrade Expo, not the theme. I'm following yours tutorial to upgrade yours packages and break occurs with CRNA. 

Why others is responsible for this problem?

Expo ou CRNA has a full log with the CRNA errors? The terminal/packager log don't returns nothing beyond this generic message.

**Comment by brentvatne** [comment]
@silasrm - the error comes from the project, not Expo, so they are responsible for it.

The full log shows up on the device in the screenshot that you sent. Not sure why it isn't showing up in the terminal logs in this case though, can you create an issue for that?

**Comment by dikaiosune** [comment]
@silasrm from the package section of that UI theme, it looks like they currently only support Expo 15 and its version of RN: https://www.dropbox.com/s/21akqntjo80oyye/Screenshot%202017-06-06%2011.02.40.png?dl=0.

My guess is that the version of NativeBase (and maybe other packages) that they're using is making use of an RN API which was removed between 0.42 and 0.43.

**Comment by silasrm** [comment]
@brentvatne in terminal just show this: 
09:13:06: Failed building JavaScript bundle

@dikaiosune Before I'm trying to upgrade native-base but show others errors. After that, I'm trying to following strict the article, but this error appeared.

NativeBase 2.1.4 (new) requires:
```
"react-native": "^0.43.0",
"react": "^16.0.0-alpha.3",
```

I'll trying  to upgrade NativeBase again.

Sorry for discomfort. Thank's!
