### ISSUE TITLE
npm ERR! code EINTEGRITY

### ISSUE THREAD

**Issue by VimalRaj571** [react-community/create-react-native-app#245]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request
```
When i try to create new APP using Command __create-react-native-app Some-name__ 
I face some error.I am a windows user!

```
## Expected Behavior

What action did you perform, and what did you expect to happen?

```                      
The application and the folder must be created with Some-name
```
## Observed Behavior

What actually happened when you performed the above actions?

The error is
```
npm ERR! code EINTEGRITY
npm ERR! sha1-N/5m+SKxAD2ip4xmt9TTvJMT5CM= integrity checksum failed when using sha1: wanted sha1-N/5m+SKxAD2ip4xmt9TTvJMT5CM= but got sha1-gMmRd/yXvyF1QzhD6cPmudRLrNA=. (12254838 bytes)

```

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!

5181 verbose stack     at emitNone (events.js:91:20)
5181 verbose stack     at Transform.emit (events.js:185:7)
5181 verbose stack     at endReadableNT (_stream_readable.js:974:12)
5181 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
5181 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
5182 verbose cwd C:\Users\VR\Desktop\EXPO_STUFFS\APP
5183 verbose Windows_NT 10.0.14393
5184 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "--save-exact" "react-native-scripts"
5185 verbose node v6.10.0
5186 verbose npm  v5.0.0
5187 error code EINTEGRITY
5188 error sha1-N/5m+SKxAD2ip4xmt9TTvJMT5CM= integrity checksum failed when using sha1: wanted sha1-N/5m+SKxAD2ip4xmt9TTvJMT5CM= but got sha1-gMmRd/yXvyF1QzhD6cPmudRLrNA=. (12254838 bytes)
5189 verbose exit [ 1, true ]


```
##Screen Shot

![error](https://user-images.githubusercontent.com/8166149/26842278-e4307f9c-4b09-11e7-98c2-eaea61c92e61.JPG)

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
* `npm ls react-native`:
* `npm ls expo`:
* `node -v`: v6.10.0
* `npm -v`:5.0.0
* `yarn --version`:
* `watchman version`:

Also specify:

1. Operating system:Microsoft Windows 10 Enterprise   Version	10.0.14393 Build 14393
2. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by brentvatne** [comment]
Hello! You are using npm5, that is not supported as it is currently buggy. Please pay attention to the installation instructions in the README:

```
You'll need to have Node v6 or later on your machine. We strongly recommend using npm v3, v4, or a recent version of Yarn. Create React Native App does not currently work with npm v5 due to bugs in npm
```

**Comment by VimalRaj571** [comment]
Thank so Much!!! @brentvatne Really!
