### ISSUE TITLE
The development server returns response error code: 500

### ISSUE THREAD

**Issue by mahbubmukul** [react-community/create-react-native-app#247]
I am trying to implement react native into my existing native android app. I added a ReactActivity in to my app. It was running perfectly.

Suddenly it giving the error "The development server returns response error code: 500" 

![device-2017-06-06-143906](https://user-images.githubusercontent.com/13809555/26863304-aaa1a868-4b73-11e7-8f1a-9a6ec32bff1e.png)
<img width="576" alt="screen shot 2017-06-06 at 2 48 02 pm" src="https://user-images.githubusercontent.com/13809555/26863306-acc6df82-4b73-11e7-96c5-994ac1d82b6f.png">

**Comment by brentvatne** [comment]
I'm sorry I believe you have the wrong repository, create-react-native-app handles helping you get up and running quickly and then ejecting to React Native or Expo (and perhaps more targets in the future) if you need native code. Check out this site for options on getting help: https://facebook.github.io/react-native/support.html
