### ISSUE TITLE
create-react-native-app fails (yarn related??)

### ISSUE THREAD

**Issue by Lars-m** [react-community/create-react-native-app#248]
## Description

When I run `create-react-native-app appName` it fails as demonstrated below.

## Expected Behavior

When I run create-react-native-app appName I expect to get an application which I can start via npm start

## Observed Behavior
See outputs below:

**After: `create-react-native-app demo`**
...
Installing dependencies using yarnpkg
yarn install v0.17.8
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning Incorrect peer dependency "react@>=15.4.0".
warning Incorrect peer dependency "react@>=15.3.1".
warning Incorrect peer dependency "react@>=15.4.0".
error An unexpected error occurred: "ENOENT: no such file or directory, open 'c:\\data\\react-native-demoes\\demo\\node_modules\\@ccheever\\crayon\\node
info If you think this is a bug, please open a bug report with the information provided in "c:\\data\\react-native-demoes\\demo\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
`yarn ` failed

**When I do `npm start`**

> react-native-scripts start

'react-native-scripts' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\plaul1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.0
npm ERR! npm  v4.1.2

**If I do `npm install`again**

... A HOLE BUNCH OOF WARNS LIKE BELOW
npm WARN enoent ENOENT: no such file or directory, open 'c:\data\react-native-demoes\demo\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\fstream-ignore\node_modules\minimatch\node_modules\brace-expansion\node_modules\concat-map\package.json'
npm WARN react-native-branch@2.0.0-beta.3 requires a peer of react@>=15.4.0 but none was installed.
npm WARN lottie-react-native@1.1.1 requires a peer of react@>=15.3.1 but none was installed.
npm WARN react-native-maps@0.14.0 requires a peer of react@>=15.4.0 but none was installed.

## Environment

Please run these commands in the project folder and fill in their results:

 **`npm ls react-native-scripts`:**
demo@0.1.0 c:\data\react-native-demoes\demo
`-- react-native-scripts@0.0.31

* `npm ls react-native`:
demo@0.1.0 c:\data\react-native-demoes\demo
`-- react-native@0.44.3

* `npm ls expo`:
demo@0.1.0 c:\data\react-native-demoes\demo
`-- expo@17.0.0
  `-- UNMET PEER DEPENDENCY react@>=15.3.1

* `node -v`:  v6.11.0
* `npm -v`:  4.1.2
* `yarn --version`:
* `watchman version`:

Also specify:

1. Operating system: Windows 8
2. Phone/emulator/simulator & version: NA

## Reproducible Demo
For me, it happens when ever I do `create-react-native-app`

## Hack to solve the problem
If I (right after the create-react-native-app command) delete **node_modules** and then do a npm install it gives me this output, but NOW I CAN START THE APP:
....
   `-- yesno@0.0.1
-- react-test-renderer@16.0.0-alpha.6
pm WARN react-native-branch@2.0.0-beta.3 requires a peer of react@>=15.4.0 but none was installed.
pm WARN lottie-react-native@1.1.1 requires a peer of react@>=15.3.1 but none was installed.
pm WARN react-native-maps@0.14.0 requires a peer of react@>=15.4.0 but none was installed.

#### So this hack seems to work everytime (but is cumbesome):

do create-react-native-app
do delete the node_modules folder
do npm install
do npm start

**Comment by dikaiosune** [comment]
Hi! Sorry you're running into problems here. I think you need to upgrade your yarn version -- 0.17 is quite old. If you update your yarn version and are still running into problems please report back and we'll reopen the issue!

**Comment by Lars-m** [comment]
Upgrading "partly" solved the problem, but coursed some other errors. I ended up with, completely uninstalling yarn, and now everything works as expected.
Thanks for the help :-)
