### ISSUE TITLE
Cannot run create-react-native-app

### ISSUE THREAD

**Issue by rishikahpowany** [react-community/create-react-native-app#249]
I installed this  and after that, I am getting this error: 

F:\RHP_backup\Project\expo\apps created via terminal\my-app>npm start

> my-app@0.1.0 start F:\RHP_backup\Project\expo\apps created via terminal\my-app

> react-native-scripts start

11:21:48 AM: Starting packager...
11:21:48 AM: Error starting packager: TypeError: gen is not a function
    at step (F:\RHP_backup\Project\expo\apps created via terminal\my-app\node_mo
dules\xdl\build\Project.js:1461:183)
    at F:\RHP_backup\Project\expo\apps created via terminal\my-app\node_modules\
xdl\build\Project.js:1461:432
    at Object.<anonymous> (F:\RHP_backup\Project\expo\apps created via terminal\
my-app\node_modules\xdl\build\Project.js:1461:99)
    at Object.startAsync (F:\RHP_backup\Project\expo\apps created via terminal\m
y-app\node_modules\xdl\build\Project.js:1208:19)
    at Object.run (F:\RHP_backup\Project\expo\apps created via terminal\my-app\n
ode_modules\react-native-scripts\build\util\packager.js:173:11)
    at Object.<anonymous> (F:\RHP_backup\Project\expo\apps created via terminal\
my-app\node_modules\react-native-scripts\build\scripts\start.js:24:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@0.1.0 start: `react-native-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2017-06-09T05_51_48_
582Z-debug.log

when i run `npm ls react-native` i get this error: 
my-app@0.1.0 F:\RHP_backup\Project\expo\apps created via terminal\my-app
`--  (react-native) invalid error: ENOENT: no such file or directory, open 'F:\R
HP_backup\Project\expo\apps created via terminal\my-app\node_modules\react-nativ
e\package.json

npm ERR! error in F:\RHP_backup\Project\expo\apps created via terminal\my-app\no
de_modules\react-native: ENOENT: no such file or directory, open 'F:\RHP_backup\
Project\expo\apps created via terminal\my-app\node_modules\react-native\package.
json'
npm ERR! invalid: react-native F:\RHP_backup\Project\expo\apps created via termi
nal\my-app\node_modules\react-native

When I run `npm ls expo` I get this error:

my-app@0.1.0 F:\RHP_backup\Project\expo\apps created via terminal\my-app
`-- UNMET DEPENDENCY expo@^17.0.0

npm ERR! missing: expo@^17.0.0, required by my-app@0.1.0

Whereas, when I try to update, I get it is up to date.

`npm ls react-native-scripts`: -- react-native-scripts@0.0.30
`npm ls react-native`: error 
`npm ls expo' : error 
`node -v`: v7.10.0
`npm -v`: 5.0.3

1. Operating system: Windows 8
2. Phone/emulator/simulator & version: Asus Zenfone 2 Laser

**Comment by brentvatne** [comment]
This is due to a bug in npm 5, see the README: https://github.com/react-community/create-react-native-app/blob/89f8b780a1739b3d13f8c95ec36c56fa590b4d13/README.md#installation
