### ISSUE TITLE
Hot Reloading Unavailable

### ISSUE THREAD

**Issue by Rafaell416** [react-community/create-react-native-app#250]
## Description

Hey guys, your product expo is awesome! thanks a lot.
but i'm writing this for asking help with something.
I'm rendering the same app in the Expo IOS and Android client. in Android I can use hot reloading  but in IOS I can't.

## Expected Behavior

I shake my Iphone and the config screen appear but when I try to click the Hot reloading button to enable it. It is Disabled with te text: Hot Reloading Unavailable. I want to be able to use hot reloading in both platforms. Android and IOS
![screen](https://user-images.githubusercontent.com/18080929/26969274-cc660522-4cca-11e7-9500-7e8ae1a8b8a0.jpg)

I would be grateful if you would help me. Thanks a lot.

**Comment by brentvatne** [comment]
Hello! For posterity, you need to disable live reload to use hot reloading
