### ISSUE TITLE
App times out in the ios simulator

### ISSUE THREAD

**Issue by QuantumInformation** [react-community/create-react-native-app#251]
I made a new app today following the read me, and ran `yarn start ios`

![image](https://user-images.githubusercontent.com/216566/27002663-2dbf9b20-4ddf-11e7-89f9-7882587f383c.png)
![image](https://user-images.githubusercontent.com/216566/27002671-4d89e76c-4ddf-11e7-8b65-c1a6b3156e3f.png)

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
npm ls react-native-scripts
        time-tracker@0.1.0 /Users/nikos/WebstormProjects/test/time-tracker
├── UNMET PEER DEPENDENCY react@16.0.0-alpha.6
└── react-native-scripts@0.0.31 

npm ERR! peer dep missing: react@>=15.4.0, required by react-native-maps@0.14.0

* `npm ls react-native`:
* `npm ls expo`:
* `node -v`: v7.8.0

* `npm -v`: 4.2.0

* `yarn --version`:0.19.1

* `watchman version`:"version": "4.7.0"

Also specify:

1. Operating system: MAC OS
2. Phone/emulator/simulator & version: Version 10.0 (SimulatorApp-726.7

**Comment by HappyZombies** [comment]
I'd like to report that I am also having this issue. All I did was follow the React Native getting started lab https://facebook.github.io/react-native/docs/getting-started.html and I get this same exact error.

**Comment by brentvatne** [comment]
try opening your ios simulator and choosing doing [reset content & settings](https://stackoverflow.com/a/9088416/659988) -- that may fix it. if not, then can you go to the url that times out in your browser on and tell me if it times out and if not, what the output is? in the screenshots provided, the url would be http://localhost:19000 (exp becomes http, the port may change).

**Comment by HappyZombies** [comment]
Ah, I didn't realize that this was for the iOS simulator, I am using my actual iPhone 6 for this. And my OS is Windows (could that be it).

I tested out the QR code and URL on my android phone and I got the same 'time out' error on the Android as I did on my iPhone. The URL does not time out on my localhost and I get the outputted json data as expected. See screenshot for what I got.
![image](https://user-images.githubusercontent.com/11294700/27006637-138f8c88-4e07-11e7-9b6a-e80ed806ecdd.png)

**Comment by brentvatne** [comment]
@HappyZombies - this could be an issue with your wifi network -- your phone and computer need to be on the same wifi and the wifi network should allow connections between devices on the network over network ips. this often doesn't work in restaurants, cafes, hotels, and the like.

**Comment by HappyZombies** [comment]
I'm on my home network, and it seems like I didn't have my network setup right as you suggested. 

I was able to get it to work with my 192.168.xx.xx address, not with the one that the terminal suggest (it was 169.254.xx.xxx) ...must be because I have VirtualBox installed or something. Thanks for the tip on that.
