### ISSUE TITLE
Always stuck in fetching packages step

### ISSUE THREAD

**Issue by dev-ahmed** [react-community/create-react-native-app#257]
1. Operating system:Linux ElementaryOS Loki
2. Phone/emulator/simulator & version:
![screenshot 2017-06-14 22 47 58](https://user-images.githubusercontent.com/15056155/27154063-feadf034-5153-11e7-9eca-f01540a97f1e.png)

**Comment by brentvatne** [comment]
how long does it get stuck for? can you try cloning this repo, going into the `frontend` directory and running `yarn` and let me know what happens? https://github.com/brentvatne/crna-issue-241-example

**Comment by dev-ahmed** [comment]
after long time trying i got this error
![screenshot 2017-06-14 23 42 01](https://user-images.githubusercontent.com/15056155/27155946-35c829fc-515b-11e7-9d71-7b3a899fcbf9.png)

**Comment by brentvatne** [comment]
it sounds like there is a problem with your internet connection :)

**Comment by brentvatne** [comment]
followup -- ngrok-2.2.7.tgz is about 42mb (unfortunately), so you'll need to make sure that you're on an internet connection that is fast enough and stable enough to download a file of that size

**Comment by brentvatne** [comment]
created this issue to discuss removing ngrok dependency, which would speed up CRNA installation significantly: https://github.com/react-community/create-react-native-app/issues/258

**Comment by youngwind** [comment]
The same issue. But after waiting a long time, perhaps 5 minutes, it works!
![2017-06-19 10 22 56](https://user-images.githubusercontent.com/8401872/27267282-d36ee7b4-54d9-11e7-8348-cfef4d8a684a.png)

**Comment by brentvatne** [comment]
hello! this should be much better now when you create a new project. we removed a couple of dependencies that were both heavy and required native build steps
