### ISSUE TITLE
Can I publish to expo after eject

### ISSUE THREAD

**Issue by lslvxy** [react-community/create-react-native-app#259]
use crna to creat an app

then run `eject`

after this operation, can it publish?

i have tried `exp publish` and XDE to publish but all give me an error

```

Failed to publish package: Packager url http://localhost:19001/index.bundle?dev=false&minify=true&hot=false&assetPlugin=exponent/tools/hashAssetFiles&platform=ios returned unexpected code 404. Please open your project in the Expo app and see if there are any errors. Also scroll up and make sure there were no errors or warnings when opening your project.

```

**Comment by brentvatne** [comment]
hello! yes you can if you eject to expokit. otherwise you can't. if you ejected to expokit then make sure you run the packager first.

**Comment by lslvxy** [comment]
how  to ` eject to expokit`, i just run `npm run eject`

**Comment by brentvatne** [comment]
if you run `npm run eject` it gives you two options, ejecting to regular react native or ejecting to expokit. see here: https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md#starting-the-ejection-process

**Comment by weizeng** [comment]
after I eject on ios, may i need to  'react-native bundle'  then drag final js to xcode???

**Comment by brentvatne** [comment]
depends if you eject to expokit or not. if expokit, you don't have to do that, just publish with `exp publish`
