### ISSUE TITLE
Expo app is not installing on Android emulator

### ISSUE THREAD

**Issue by rizwanahmed19** [react-community/create-react-native-app#261]
## Description
After creating a new project, I ran 'yarn run android' but instead of getting the expo app on the emulator I'm getting an error.

## Expected Behavior
Expo app should be installed on my emulator and my app should be up and running.

## Observed Behavior
I'm getting an error in the terminal while running the packager. Although I'm getting the QR code.

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error running adb: Failed to install C:\Users\Rizwan\.expo\android-apk-cache\Exponent-1.16.1.apk: Failure [INSTALL_PARSE
_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl1193990351.tmp/base.apk: AndroidManifest.xml]
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: +-- UNMET PEER DEPENDENCY react@16.0.0-alpha.6
`-- react-native-scripts@0.0.31

npm ERR! peer dep missing: react@>=15.4.0, required by react-native-maps@0.14.0
* `npm ls react-native`: react-native@0.44.3
* `npm ls expo`: expo@17.0.0
* `node -v`: v7.9.0
* `npm -v`: 3.10.9
* `yarn --version`: 0.23.2
* `watchman version`:

Also specify:

1. Operating system: Windows 8.1 64bit
2. Phone/emulator/simulator & version: Nexus 5X API 25

**Comment by brentvatne** [comment]
hello! try deleting the directory `C:\Users\Rizwan\.expo\android-apk-cache` and opening the project on android again

**Comment by mg** [comment]
I had the same problem, can confirm that deleting the .expo/android-apk-cache directory and re-running yarn start android fixed it for me

**Comment by aep** [comment]
deleting that dir helped me resolve my issue where nothing at all happens after "11:35:50 AM: Starting Android..."

**Comment by marcelosantos** [comment]
I had the same problem (on Ubuntu 16.04), after deleting the .expo/android-apk-cache directory and re-running yarn start or npm start fixed it for me too! great help! thanks guys!

**Comment by hemantnagori11** [comment]
I had the same problem, I am using windows 10, after creating a new project when I clicked on device then it was giving me some errors

**Comment by brentvatne** [comment]
please create a new issue with more information, original issue was resolved above

**Comment by ArsooCh** [comment]
Thanks!  fixed for me as well.

**Comment by anarkrypto** [comment]
I solved after restart adb:

```sudo adb kill-server```
```sudo adb start-server```

**Comment by moodizone** [comment]
> hello! try deleting the directory `C:\Users\Rizwan\.expo\android-apk-cache` and opening the project on android again

worked !!! Thank You.

**Comment by Dekin0Linux** [comment]
I had to change my emulator and it worked
