### ISSUE TITLE
eject as regular React Native project

### ISSUE THREAD

**Issue by alihaydar2462** [react-community/create-react-native-app#262]
Hi,

I have a expo app and i want to eject the app.

When i run the "npm run eject" command and choose "React Native: I'd like a regular React Native project." I got the "Error running eject: TypeError: Cannot read property 'name' of undefined" error.

Can anyone help me please

```
Error running eject: TypeError: Cannot read property 'name' of undefined
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: empty
* `npm ls react-native`: empty
* `npm ls expo`: empty
* `node -v`: v7.10.0
* `npm -v`: 4.2.0
* `watchman version`: version": "4.7.0

1. Operating system: mac os sierra
2. Phone/emulator/simulator & version: xCode iPhone 6 emilator (iOS 10.3)

**Comment by brentvatne** [comment]
hello! i just tried this on a new project and it worked as expected. can you share the contents of your app.json and tell me what your responses were to the prompts?

```
─ ~/coding/HelloTestEjecting yarn eject
yarn eject v0.23.0-3-exp
$ react-native-scripts eject

We didn't find any uses of the Expo SDK in your project, so you should be fine to eject to
"Plain" React Native. (This check isn't very sophisticated, though.)

We strongly recommend that you read this document before you proceed:
  https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md

Ejecting is permanent! Please be careful with your selection.

? How would you like to eject from create-react-native-app? React Native: I'd like a regular React Native project.
We have a couple of questions to ask you about how you'd like to name your app:
? What should your app appear as on a user's home screen? HelloThere
? What should your Android Studio and Xcode projects be called? HelloTestEjecting
Writing your selections to app.json...
Wrote to app.json, please update it manually in the future.
Scanning 761 folders for symlinks in /Users/brent/coding/HelloTestEjecting/node_modules (9ms)
Generating the iOS folder.
Generating the Android folder.
Successfully copied template native code.
The template .babelrc is no longer necessary after ejecting.
It has been successfully deleted.
Updating your yarnpkg scripts in package.json...
Your package.json is up to date!
Adding platform-specific entry points...
Added new entry points!

Note that using `yarnpkg start` will now require you to run Xcode and/or
Android Studio to build the native code for your project.

It's recommended to delete your node_modules directory and rerun yarnpkg
to ensure that the changes we made to package.json persist correctly.

Ejected successfully!
Please consider letting us know why you ejected in this survey:
  https://goo.gl/forms/iD6pl218r7fn9N0d2
✨  Done in 14.26s.
```

**Comment by alihaydar2462** [comment]
Hi Brent,

Thank you for response,

**Firstly my app.json is like that;**

{
  "expo": {
    "sdkVersion": "15.0.0",
    "icon": "./images/icon.png",
     "slug": "appName",
    "loading": {
      "hideExponentText": true,
      "icon": "./images/loading.png",
      "backgroundImage": "./images/launchImages/splashscreen.png"
    },
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "packagerOpts": {
      "assetExts": [
        "ttf"
      ]
    },
   "ios": {
    "bundleIdentifier": "io.market.nativebase.geekyants.flatappui",
  },
  "android": {
     "package": "io.market.nativebase.geekyants.flatappui",
   },
   "androidStatusBarColor": "#01cca1",
     "androidStatusBar": {
     "barStyle": "dark-content",
     "backgroundColor": "#01cca1",
    },
  }
}

**But when i try to run eject, the command returns json error and because of that i changed it. Now my app.json is like that;**

{
    "sdkVersion": "15.0.0",
    "icon": "./images/icon.png",
     "slug": "appName",
    "loading": {
      "hideExponentText": true,
      "icon": "./images/loading.png",
      "backgroundImage": "./images/launchImages/splashscreen.png"
    },
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "packagerOpts": {
      "assetExts": [
        "ttf"
      ]
    },
   "ios": {
    "bundleIdentifier": "io.market.nativebase.geekyants.flatappui"
  },
  "android": {
     "package": "io.market.nativebase.geekyants.flatappui"
   },
   "androidStatusBarColor": "#01cca1",
     "androidStatusBar": {
     "barStyle": "dark-content",
     "backgroundColor": "#01cca1"
    
  }
}


**And here is my console out;**

LinuxPluss-Mac:mobile-app linuxplus$ npm run eject

> Mobile@7.0.0 eject /Users/linuxplus/git/mobile/mobile-app
> react-native-scripts eject


Warning! We found at least one file where your project imports the Expo SDK:
  /Users/linuxplus/git/mobile/mobile-app/js/setup.js

If you choose the "plain" React Native option below, these imports will stop working.

We strongly recommend that you read this document before you proceed:
  https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md

Ejecting is permanent! Please be careful with your selection.

? How would you like to eject from create-react-native-app? React Native: I'd li
ke a regular React Native project.
Error running eject: TypeError: Cannot read property 'name' of undefined
LinuxPluss-Mac:mobile-app linuxplus$

**Comment by usehotkey** [comment]
I have the similar problem with following config:
```
{
  "name": "Tap, Tap!",
  "displayName": "Tap, Tap!",
  "icon": "./distribution/_assets/iconTapTap.png",
  "version": "1.1.4",
  "slug": "tap-tap",
  "sdkVersion": "17.0.0",
  "ios": {
    "bundleIdentifier": "com.impale.usehotkey"
  },
  "android": {
    "package": "com.impale.usehotkey"
  }
}
```
But my error is:

> ? How would you like to eject from create-react-native-app? ExpoKit: I'll create or log in with
> an Expo account to use React Native and the Expo SDK.
> 
> An Expo account is required to proceed.
> 
> ? It appears you're already logged in to Expo as impale, would you like to continue with this ac count? Yes, continue as impale.
> Error running eject: TypeError: Cannot read property 'ios' of undefined

**Comment by brentvatne** [comment]
@alihaydar2462 - can you share the project privately with me on Github?

**Comment by brentvatne** [comment]
oh, actually -- @alihaydar2462 - your project needs to have a `name` field in app.json:

```
{
  "name": "your app name here",
  "expo": {
    "sdkVersion": "15.0.0",
    "icon": "./images/icon.png",
     "slug": "appName",
    "loading": {
      "hideExponentText": true,
      "icon": "./images/loading.png",
      "backgroundImage": "./images/launchImages/splashscreen.png"
    },
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "packagerOpts": {
      "assetExts": [
        "ttf"
      ]
    },
   "ios": {
    "bundleIdentifier": "io.market.nativebase.geekyants.flatappui",
  },
  "android": {
     "package": "io.market.nativebase.geekyants.flatappui",
   },
   "androidStatusBarColor": "#01cca1",
     "androidStatusBar": {
     "barStyle": "dark-content",
     "backgroundColor": "#01cca1",
    },
  }
}
```

**Comment by alihaydar2462** [comment]
Hi Brent,

Thank you soo much, it works.

Here is the final state (I remove some comma);
{
  "name": "oyakmobile",
  "expo": {
    "sdkVersion": "15.0.0",
    "icon": "./images/icon.png",
     "slug": "oyakmobile",
    "loading": {
      "hideExponentText": true,
      "icon": "./images/loading.png",
      "backgroundImage": "./images/launchImages/splashscreen.png"
    },
    "orientation": "portrait",
    "primaryColor": "#cccccc",
    "packagerOpts": {
      "assetExts": [
        "ttf"
      ]
    },
   "ios": {
    "bundleIdentifier": "io.market.nativebase.geekyants.flatappui"
  },
  "android": {
     "package": "io.market.nativebase.geekyants.flatappui"
   },
   "androidStatusBarColor": "#01cca1",
     "androidStatusBar": {
     "barStyle": "dark-content",
     "backgroundColor": "#01cca1"
    }
  }
}
