### ISSUE TITLE
Expo stuck on loading my app

### ISSUE THREAD

**Issue by youngwind** [react-community/create-react-native-app#263]
## Description
After scanning the qrcode, Expo stuck on loading my app.

## Expected Behavior
Expo should load my app.

## Observed Behavior
Expo stuck in showing it's loading icon, as shown below. Attention, the icon blinks all the time.
![image](https://user-images.githubusercontent.com/8401872/27272288-080ee7a4-54fc-11e7-9ad1-e6c0c9034dea.png)

1. **At the beginning, the problem does not exist.** But later it comes, and I don't know why.
2. The phone and mac is in the same network, and the phone can visit the address : http://myId:19000, which is shown on the terminal. The phone also can visit the JS bundle File, such as : http://myIp:19001/node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles
3. I have tried reinstall the Expo APP and restart the `npm start`, it doesn't work.

## Environment

* `npm ls react-native-scripts`: @0.0.31
* `npm ls react-native`: @0.44.3
* `npm ls expo`: @17.0.0
* `node -v`: v7.7.4
* `npm -v`: v4.1.2
* `yarn --version`: 0.20.3
* `watchman version`:  command not found

Also specify:

1. Operating system: macOS Sierra 10.12.1
2. Phone/emulator/simulator & version:  Redmi Note 2, Android 5.0.2LRX22G

## Reproducible Demo
The demo is here : https://github.com/youngwind/react-native-demo 
Any suggestion may help, thanks!

**Comment by youngwind** [comment]
Sorry, I make a stupid mistake. 
```jsx
// my code missing return in the render function!!
render() {
    <Text>sdfhh</Text>
}
```
When I solve this bug, it works.

However, I want to put forward a suggestion:"Why it doesn't show any error log in this case?"
For example:
```jsx
// the return keyword has a spelling mistake
render() {
    retun(
        <Text>sdfhh</Text>
    );
}
```
In this case, it neither show any error log in the terminal.

**Comment by brentvatne** [comment]
we definitely should provide some information when this happens -- I'm not able to reproduce this though, I get an error message like expected:

![screenshot_20170619-092635](https://user-images.githubusercontent.com/90494/27295369-82a104a0-54d1-11e7-8131-92f44a415ead.png)

this happens on a brand new project with

```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default class App extends React.Component {
  render() {
    retun (
      <View style={styles.container}>
        <Text>Hello</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

how can I reproduce your case of not seeing any error?

**Comment by youngwind** [comment]
I'm not able to steadily reproduce this case now.
When I meet this issue again, I would provide more information.
Thanks for your Help!

**Comment by pckhoi** [comment]
For me the way to reliably reproduce this is to start `react-native-scripts android` with phone plugged-in. Then the Expo app will be automatically started and it will load forever. The way to fix it is to close the app then open it again, or never let Expo app be started automatically.

**Comment by Zerocchi** [comment]
Had the same problem, and completely closing the expo app and reopening it again works for me.

**Comment by atish23** [comment]
Have the same problem, application does not any error logs .

**Comment by hoeselm** [comment]
I was also running in this problem on a virtual android device. Running yarn start and then at the prompt pressing R to restart the packager and clear the cache solved the issue for me.

**Comment by sambragge** [comment]
Im having the same problem, I've cleared the cache, reinstalled the app...nothing. loads to 100% then just hangs there for about 5 minutes before crashing with no errors. Even stranger, my app was working fine with expo yesterday, and i haven't changed any code.

**Comment by TomKarachristos** [comment]
I have exacly the same problem with @sambragge.

**Comment by browncj** [comment]
I am having the same issue here. It was all working fine yesterday, but now for whatever reason the app just hangs on the expo logo, both on my actual Android device and on the virtual one.

**Comment by Danjavia** [comment]
use `return` instead `retun` at line 7 @brentvatne

**Comment by renielDev** [comment]
How did you resolve this issue? Mine is also stuck in the loading.

**Comment by finnfiddle** [comment]
for me I was testing the app on both the simulator and my phone at the same time and I had to close expo, the expo app on my phone as well as the simulator. then after opening expo again and the app on my phone it loaded fine

**Comment by Nermin-K** [comment]
I have the same issue and I checked my code is not missing "return". It was working just an hour ago and since then it stuck in `Building Javascript bundle [                                                                          ] 0%` I tried to reload it sooo many times, I restarted my pc and mobile but nothing work! and I got no message just white page with expo logo in the center.

**Comment by krish512** [comment]
Same for me as @Nermin-K 
How did you solve this?

**Comment by Nermin-K** [comment]
@krish512 I cleared my mobile cashed data and it did work for a while but later it struck again, so I tried to uninstall some apps and it worked!!🤷 It is a little confusing because I had a very enough space for Expo to work! anyway, this is what worked for me

**Comment by MangalamPalod** [comment]
I cleared cache and all the data used by expo. It worked.
A simple way is to just reinstall expo application.
