### ISSUE TITLE
SyntaxError when attempting to eject

### ISSUE THREAD

**Issue by ljesparis** [react-community/create-react-native-app#265]
## Description

I'm trying to eject my project, but a SyntaxError occurred.

## Expected Behavior

What action did you perform, and what did you expect to happen?
i did type yarn eject in the command line and i did expect to
eject my project =P.

## Observed Behavior

What actually happened when you performed the above actions?

A SyntaxError ocurred.

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
yarn eject v0.24.5
$ react-native-scripts eject 

Warning! We found at least one file where your project imports the Expo SDK:
  /home/joker/Escritorio/projects/nodejs/trabajo/ofertazo/App.js

If you choose the "plain" React Native option below, these imports will stop working.

We strongly recommend that you read this document before you proceed:
  https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md

Ejecting is permanent! Please be careful with your selection.

? How would you like to eject from create-react-native-app? ExpoKit: I'll create or log in with an Expo account to use React Native and the Expo SDK.

An Expo account is required to proceed.

? It appears you're already logged in to Expo as leoxnidas, would you like to continue with this account? Yes, continue as leoxnidas.
Error running eject: SyntaxError: Unexpected token } in JSON at position 237
Done in 21.92s.
```

Also specify:

1. Operating system: Ubuntu 16.04
2. Phone/emulator/simulator & version: iPhone 4 => iOS 10(i think).

**Comment by brentvatne** [comment]
hello! are you using npm5?

**Comment by brentvatne** [comment]
@leoxnidas - I just ran `yarn eject` on a new project and chose the same options as you, it worked as expected. I think that there is a syntax error in your app.json

**Comment by jaymzcd** [comment]
I had the same problem and @brentvatne's comment sorted me out. Examining my `app.json` I had an extra comma after the last item in my list which was causing the JSON to be invalid. After fixing it up `eject` ran successfully.
