### ISSUE TITLE
Unable to export a function

### ISSUE THREAD

**Issue by morenoh149** [react-community/create-react-native-app#266]
## Description

I'm trying to add a bare-bones implementation of redux. Specifically the file [actions.js](http://redux.js.org/docs/basics/ExampleTodoList.html#actionsindexjs)

## Expected Behavior

I expect
```js
//src/actions/index.js
export const logIn = () => {
  return { type: types.LOG_IN }
}
export const logOut = () => {
  return { type: types.LOG_OUT }
}
console.log(logIn, logOut)
```
to print `function() { ... }, function() { ... }`
## Observed Behavior

Instead I get `null, null`

## Environment

* `npm ls react-native-scripts`:
foo@0.1.0 /Users/harrymoreno/programming/foo
└── react-native-scripts@0.0.31 

* `npm ls react-native`:
foo@0.1.0 /Users/harrymoreno/programming/foo
└── react-native@0.44.3 

* `npm ls expo`:
foo@0.1.0 /Users/harrymoreno/programming/foo
└── expo@17.0.0

* `node -v`: v8.1.0

* `npm -v`:5.0.3

* `yarn --version`:0.24.6

* `watchman version`: {
    "version": "4.7.0"
}

1. Operating system: OSX sierra (10.12)
2. Phone/emulator/simulator & version: running on phone LG volt

## Reproducible Demo

https://github.com/morenoh149/crna-redux
https://github.com/morenoh149/crna-redux/blob/master/src/actions/index.js#L7

**Comment by brentvatne** [comment]
hi @morenoh149! this is an issue with logging: https://github.com/expo/expo/issues/168 -- currently we don't handle logging functions.

an improvement for this will be released in the next few days! :)

**Comment by morenoh149** [comment]
omg you're right. Hope it get's fixed soon!

**Comment by brentvatne** [comment]
it is fixed :)
