### ISSUE TITLE
Where to find Android Manifest?

### ISSUE THREAD

**Issue by matwii** [react-community/create-react-native-app#267]
Where can I find the Android Manifest file to activate this setting:
android:windowSoftInputMode="adjustResize"?

**Comment by brentvatne** [comment]
hello @matwii! this configuration is already set on default create-react-native-app apps, so you don't need to do anything for this! [this is the AndroidManifest.xml](https://github.com/expo/expo/blob/5a9d8698a8767c21bb87232e66858e2eb3f0d227/template-files/android/AndroidManifest.xml) that is used on apps.

If you need to edit the AndroidManifest.xml directly, you will [need to eject](https://github.com/react-community/create-react-native-app/blob/e37f1a7a6863d528fe57a6c6e73632e8c8ce8cb0/EJECTING.md).
