### ISSUE TITLE
`npm run android` acts like `npm start`

### ISSUE THREAD

**Issue by ps-aux** [react-community/create-react-native-app#269]
I would like to use connected Android device as using local network is not possible for me.

## Description
So I tried `npm run android` but there is no difference in behaviour from `npm start`

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@0.0.31 
* `npm ls react-native`: react-native@0.44.3 
* `npm ls expo`: expo@17.0.0 \
* `node -v`: v7.8.0
* `npm -v`: 4.2.0

1. Operating system: Linux (Arch Linux)
2. Phone Nexus 5x

1. run `npm run android`
2. See output:

```
8:08:40 PM: Starting packager...
8:08:55 PM: Starting Android...
8:08:57 PM: Packager started!

To view your app with live reloading, point the Expo app to this QR code.
You'll find the QR scanner on the Projects tab of the app.
...
```

**Comment by tamj0rd2** [comment]
As far as I can see you shouldn't need to run `npm run android`. You use `npm run android` when you want to start your app in an Android Virtual Device or in Genymotion.

When you run `npm start` it should give you a QR code and an IP address that you need to type into the expo app. Did that happen?

**Comment by gonzoramos** [comment]
Same issue here. I expect `npm run android` to launch the react native app on my connected Android device to my host computer. What happens is instead identical to npm start.

**Comment by brentvatne** [comment]
do you get an adb error?

```
...
For links to install the Expo app, please visit https://expo.io.

Logs from serving your app will appear here. Press Ctrl+C at any time to stop.

Error running adb: No Android device found. Please connect a device and follow the instructions here to enable USB debugging:
https://developer.android.com/studio/run/device.html#developer-device-options. If you are using Genymotion go to Settings -> ADB, select "Use custom Android SDK tools", and point it at your Android SDK directory.
```

**Comment by theGABS** [comment]
The same. 
And I dont see any ADB error. 
How I cat run without expo?

**Comment by brentvatne** [comment]
If I understand correct, what you want is to be able to tell the packager's canonical url to be localhost, so you can use adb reverse to access it from a connected device, correct?

**Comment by and3rson** [comment]
Same here.

Is there any way to run & debug the app directly on a physical device without the crappy Expo?

**Comment by jdaviderb** [comment]
@and3rson react-native-cli

**Comment by jacek213** [comment]
@jdaviderb WORD, been playin with this sh***t for 12 hours today

**Comment by j16180339887** [comment]
I understand that Expo is trying to do something like hot-reloading,

and I understand that some of you are also developers of Expo,

but can you provide a simple way to run the app on physical device without Expo?

Also, the command `npm run android` is a very confusing command name.
