### ISSUE TITLE
Can't run/complete eject

### ISSUE THREAD

**Issue by joeyfigaro** [react-community/create-react-native-app#271]
## Description

Every time I run eject, the process freezes after the first prompt.

## Expected Behavior

`yarn run eject` - I expected to be able to eject.

## Observed Behavior

I answer the first question (choosing either option for ejecting produces the same result - freezing) and then the session becomes unresponsive.

## Environment

* react-native-scripts@0.0.31
* react-native@0.44.3
* expo@17.0.0
* node 8.1.0
* npm 5.0.3
* yarn 0.24.6
* `watchman version -> Please specify a target and action`

1. Operating system:
OS X 10.12.5

2. Phone/emulator/simulator & version:
10.0

## Reproducible Demo

**N/A**

**Comment by brentvatne** [comment]
hello! it looks like you are using npm5, we do not support that as it is currently very buggy. this is likely the problem.

see:
- https://github.com/react-community/create-react-native-app/issues/233
- https://github.com/npm/npm/issues/16991

i suspect if you `npm i -g npm@4.6.1` and then reinstall your node_modules, that will resolve the problem. we warn when you create a new project now, but unfortunately don't have error handling sprinkled everywhere, if you'd like to submit a PR to warn in more situations that would be helpful!

**Comment by joeyfigaro** [comment]
@brentvatne Thanks! I'll give that a shot this evening.

**Comment by joeyfigaro** [comment]
@brentvatne No go, unfortunately. Created a new project after installing / using `npm@4.6.1` and it is still freezing. The plot thickens.

**Comment by brentvatne** [comment]
did you ever resolve this @joeyfigaro?

**Comment by eveningkid** [comment]
I'm running into the exact same issue even when using `npm@4.6.1`, on macOS. 

It would be nice to hear from you @joeyfigaro if you managed to solve this on your side! 😄

**Comment by nbucciarelli** [comment]
I was having eject freezes on Node 8.1.0/NPM 4.6.1 + 5.5. I jumped up to Node 8.6.0/NPM 5.3.0 and it worked.

**Comment by juanlet** [comment]
Same issue...windows 10
