### ISSUE TITLE
How to use camera

### ISSUE THREAD

**Issue by danielantelo** [react-community/create-react-native-app#274]
Sorry to bring this question here, could not find info googling around this morning and have given up!

I'm new to react native, I've created a fresh app with create-react-native-app , and got it working on my iPhone expo app by scanning the QR Code. 

Now I am trying to get the [react-native-camera](https://github.com/lwansbrough/react-native-camera)  component to work with it, but getting some errors. Their readme says to add things to Info.plist (for iOS) and to settings.gradle (for android) and other stuff... but I can't see these files in my freshly created project.

Is create-react-native-app compatible with such components? or do I need to eject? What would you recommend for using the camera to record video that I can upload to a server?

Thanks!

**Comment by cambaughn** [comment]
[It looks like there's a built-in SDK for working with the camera](https://docs.expo.io/versions/v18.0.0/sdk/imagepicker.html) (for still photos only, not video yet) via Expo. 

I need to record video, so if anyone knows if we can do that without ejecting, let me know!

**Comment by terribleben** [comment]
Hi, Expo doesn't include a built-in camera component, but is [tracking this request](https://expo.canny.io/feature-requests/p/camera-component) and somebody is working on it currently.

You would need to eject (with ExpoKit or without would both work) in order to integrate with `react-native-camera` right now.

**Comment by Stophface** [comment]
@terribleben there is a Module now: https://docs.expo.io/versions/latest/sdk/camera.html
And we are having the same problems @danielantelo is having. I opened an issue here: https://github.com/expo/camerja/issues/1

**Comment by MbF-Ebin** [comment]
Hi..I am using the **camera** component...but one issue here..onec i click the snap button the image will be save the gallery..next time click the snap button the image is not save...what is the reason..and solve the correct the answer

**Comment by johanna** [comment]
I have the same problem, first time a photo is snapped (and I use it for stuff), but the second time the first picture is still there.
