### ISSUE TITLE
Convert Expo project to Original RN App

### ISSUE THREAD

**Issue by deadcoder0904** [react-community/create-react-native-app#276]
I did `yarn run eject` to eject but it gave me this warning

```
Warning! We found at least one file where your project imports the Expo SDK
```

I know I have some modules which use Expo API like this -

```
await Expo.Font.loadAsync({
      Roboto: require('native-base/Fonts/Roboto.ttf'),
      Roboto_medium: require('native-base/Fonts/Roboto_medium.ttf'),
    });
```

Now I want to convert this to React Native Components so that I can eject without any errors so that I get 
`index.android.js` & `index.ios.js` in the root folder like we do while using `react-native init example`

**Comment by deadcoder0904** [comment]
After 4 hours, I got the answer..
Had to install `exp` using `npm i -g exp` & then used `exp detach` to detach the project
Also I added some fields in `app.json` for it to work as follows

```
{
  "expo": {
    "name": "Project",
    "slug": "project",
    "sdkVersion": "18.0.0",
    "privacy": "public",
    "android": {
      "package": "com.example.project"
    }
 }
}
```

Docs are given [here](https://docs.expo.io/versions/v15.0.0/guides/detach.html)

**Comment by Buddikazz** [comment]
IS your detach sucess how you able build apk after detach?
Can we run it using react-native run-android?

**Comment by deadcoder0904** [comment]
> IS your detach sucess how you able build apk after detach?

Yep detach was successful. Follow [this](https://docs.expo.io/versions/latest/guides/detach.html) for building apk after detach.

> Can we run it using react-native run-android?

Not sure what you're saying. But if I remember, `npm start` will do the job.

**Comment by manishkumarv2** [comment]
Docs link is not working ...
404
This page could not be found.

**Comment by deadcoder0904** [comment]
Try again
