### ISSUE TITLE
unable to install react native on Mac

### ISSUE THREAD

**Issue by naboneles** [react-community/create-react-native-app#279]
I'm the admin, the only user. And I can't even install, I've tried to run:
iMac:~ Luis$ npm install -g create-react-native-app
and voilla 
![captura de tela 2017-06-27 as 00 26 41](https://user-images.githubusercontent.com/29721815/27569903-97775bf4-5ad0-11e7-8c10-991120463793.png)

And I'm getting back to codes from a while

**Comment by brentvatne** [comment]
Hello! You'll need to fix your npm permissions, npm has a good guide for how to do this: https://docs.npmjs.com/getting-started/fixing-npm-permissions
