### ISSUE TITLE
Use camera to record video using Expo SDK?

### ISSUE THREAD

**Issue by cambaughn** [react-community/create-react-native-app#280]
Is there a way to record video without ejecting and using a native component? I was checking out the [Expo SDK docs](https://docs.expo.io/versions/v18.0.0/sdk/index.html) and it looks like the [camera](https://docs.expo.io/versions/v18.0.0/sdk/imagepicker.html) is only used to take photos right now. 

Am I missing something, or is this the case?

**Comment by brentvatne** [comment]
Hi there! You are right, this isn't currently available. We're working on a camera component with video recording capabilities right now -- see https://expo.canny.io/feature-requests/p/camera-component for more information. For now, you'll need to eject and use something like react-native-camera if you'd like to record video, sorry for the hassle, we'll get there ;)

**Comment by cambaughn** [comment]
Thanks Brent! Looking forward to switching back when it's available.
