### ISSUE TITLE
node[6612] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)

### ISSUE THREAD

**Issue by hengsoheak** [react-community/create-react-native-app#281]
## Description

Fresh install react native on MAC (MacBook Pro (Retina, 15-inch, Mid 2015) Version 10.12.5 (16F73)

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
* `npm ls react-native`:
* `npm ls expo`:
* `node -v`:
* `npm -v`:
* `yarn --version`:
* `watchman version`:

Also specify:

1. Operating system:
        (MacBook Pro (Retina, 15-inch, Mid 2015)
2. Phone/emulator/simulator & version:
        Iphone 6 plush

## Reproducible Demo

`npm WARN react-native-branch@2.0.0-beta.3 requires a peer of react@>=15.4.0 but none was installed.
npm WARN lottie-react-native@1.1.1 requires a peer of react@>=15.3.1 but none was installed.
npm WARN react-native-maps@0.15.2 requires a peer of react@>=15.4.0 but none was installed.

Success! Created AwesomeProject at /Users/sopheak/Documents/cam/react/AwesomeProject
Inside that directory, you can run several commands:

  npm start
    Starts the development server so you can open your app in the Expo
    app on your phone.

  npm run ios
    (Mac only, requires Xcode)
    Starts the development server and loads your app in an iOS simulator.

  npm run android
    (Requires Android build tools)
    Starts the development server and loads your app on a connected Android
    device or emulator.

  npm test
    Starts the test runner.

  npm run eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd AwesomeProject
  npm start

Happy hacking!
SOPHEAKs-MacBook-Pro:react sopheak$ cd AwesomeProject/
SOPHEAKs-MacBook-Pro:AwesomeProject sopheak$ npm test

> AwesomeProject@0.1.0 test /Users/sopheak/Documents/cam/react/AwesomeProject
> node node_modules/jest/bin/jest.js --watch

2017-06-28 14:14 node[6612] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-06-28 14:14 node[6612] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-06-28 14:14 node[6612] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1018:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1420:11)
npm ERR! Test failed.  See above for more details.
SOPHEAKs-MacBook-Pro:AwesomeProject sopheak$ 
`

**Comment by terribleben** [comment]
Hi, can you fill out the `Environment` part of the issue template so we know more about your system?

**Comment by andrewdelprete** [comment]
I'm also having this same issue. I received it after shelving a CRNA project for a few weeks and coming back to it and running `yarn` I believe. I've since deleted node_modules and tried again with the existing app but kept receiving the error @hengsoheak commented on. I tried starting a new CRNA app and got the same error.

**Comment by andrewdelprete** [comment]
```

**Comment by andrewdelprete** [comment]
Hey @hengsoheak, I was able to solve this issue. It had to do with the version of `watchman` I was running. 

The steps I took:
1. `npm uninstall watchman -g`
2. `brew install watchman`
3. `npm start` from project directory

I had `watchman` installed globally with npm (wrong version maybe?). I uninstalled it and re-installed via `brew` and now it's working again. I hope this helps.

**Comment by hengsoheak** [comment]
Yes that it

**Comment by Luckvery** [comment]
I got this error, but then it went away when I bumped from jest version   "jest": "20.0.4" to "jest": "23.2.0"
