### ISSUE TITLE
Error: Process exited with non-zero code: 60

### ISSUE THREAD

**Issue by gsklee** [react-community/create-react-native-app#282]
```
$ yarn ios
yarn ios v0.24.6
$ react-native-scripts ios 
22:17:35: Starting packager...
22:17:49: Starting simulator...
22:18:08: Failed to start simulator:

Error: Process exited with non-zero code: 60

Exiting...
✨  Done in 32.91s.
```

Sometimes I got random error like this... rerun `yarn ios` again usually works, but still.

**Comment by terribleben** [comment]
Doing some google searching, it seems like this is a more widespread iOS simulator issue, specific to some machines but not others, and Apple hasn't offered any particular solution yet. I'm not sure there's much we can do other than wait for the underlying Xcode tooling bug to get fixed.

**Comment by nikbelikov** [comment]
https://github.com/react-community/create-react-native-app/issues/62

**Comment by wangwenjun12** [comment]
me too
