### ISSUE TITLE
Error while installing react native project on ubuntu 16.04

### ISSUE THREAD

**Issue by naveen84123** [react-community/create-react-native-app#283]
When I am trying to install react native project, on ubuntu 16.04, I getting error with npm. No idea why this is happning. 

`naveen@naveen-HP-Pavilion-g6-Notebook-PC:/var/www$ sudo create-react-native-app AwesomeProject
Creating a new React Native app in /var/www/AwesomeProject.

Installing packages. This might take a couple minutes.
Installing react-native-scripts...

npm WARN deprecated @exponent/spawn-async@1.2.8: Please switch to @expo/spawn-async, the new name of this package. It's the same code with our new name.
npm ERR! Linux 4.8.0-56-generic                                                                                                              
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save-dev" "--save-exact" "react-native-scripts"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0

npm ERR! shasum check failed for /tmp/npm-3396-bb3fdd34/registry.npmjs.org/_40exponent/ngrok/-/ngrok-2.2.7.tgz
npm ERR! Expected: 37fe66f922b1003da2a78c66b7d4d3bc9313e423
npm ERR! Actual:   cd32c3d658b96974cc79b4ec248618cde6fb82ed
npm ERR! From:     https://registry.npmjs.org/@exponent/ngrok/-/ngrok-2.2.7.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/naveen/.npm/_logs/2017-06-28T14_35_02_362Z-debug.log
`npm install --save-dev --save-exact react-native-scripts` failed
`

**Comment by deadcoder0904** [comment]
Me too getting the same issue on same OS

**Comment by grigio** [comment]
it works with
```
~/C/AwesomeProject ❯❯❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
~/C/AwesomeProject ❯❯❯ node --version
v7.10.0
```

**Comment by naveen84123** [comment]
So do I have to install 17.04 to use react native?

**Comment by grigio** [comment]
@naveen84123 No, it isn't enough because then I'm stuck with another bug.. i don't get the QRCode, but also on MacOS.. I think create-react-native-app isn't stable yet and the old way with Android SDK is the way to go :(

**Comment by AbdelRahmanSalah** [comment]
getting the same issue on archlinux

**Comment by grigio** [comment]
With the current version of crna on Ubuntu 17.04 I'm able to see the qrcode.. so, sad to say, but now it works for me :)

**Comment by DavidWallJ** [comment]
I got the QRCode after a restart

**Comment by brentvatne** [comment]
seems to be resolved? if someone can provide a repro case that would be helpful. going to close but please reopen if you still have this issue on the latest version

**Comment by syamjayaraj** [comment]
I think this link will help you.
http://www.techomoro.com/how-to-install-and-setup-react-native-on-ubuntu-17-10/
