### ISSUE TITLE
How to follow along with books for React Native?

### ISSUE THREAD

**Issue by theclipse** [react-community/create-react-native-app#286]
Hi I noticed most books for react native are for ios and you need a mac for that. I have a windows computer and am interested in using CRNA. 

My question is, how can I follow along with these books when I notice that the file structure/directories are completely different?

Any Suggestions or help would be greatly appreciated.

**Comment by brentvatne** [comment]
Hello! It really depends what the books are explaining. I imagine most books would be out of date as well, given the rate of change. But here's a rough guide:

- If it mentions index.ios.js or index.android.js, you should use App.js
- If it mentions the ios or android directories, you can't change things there without doing `npm run eject` and generating those, however you would need to build your project with Xcode/Android Studio. You might be able to [find a comparable configuration option for app.json](https://docs.expo.io/versions/latest/guides/configuration.html).
- Feel free to ask specific questions here if you aren't sure what the analog is for something with CRNA.

Good luck! You might also want to check out [this playlist of videos on YouTube](https://www.youtube.com/playlist?list=PLCC436JpVnK2RFms3NG9ubPToWCNbMLbT) which is recorded from a two-day workshop that I did with a couple other folks at React Europe this year. It's up to date, easy to follow (I think) and free :)
