### ISSUE TITLE
navigator.geolocation.getCurrentPosition not showing error on Android

### ISSUE THREAD

**Issue by matwii** [react-community/create-react-native-app#287]
In my CRNA project I'm using navigator.geolocation.getCurrentPosition to get the geolocation. When my GPS is turned off, the error message isn't showing, but it does on iOs. I tested this on a classic project with react-native init and it worked perfectly there. Anyone know any fix for this?

**Comment by brentvatne** [comment]
hi there! what do you mean by "the error message isn't showing" -- the error callback doesn't fire?
 also, by GPS turned off you mean completely disabled on the device, or you don't give the app permission? additionally, it would be very helpful if you can reproduce it using https://snack.expo.io and share the example with us, then we can investigate the issue further.

in the meantime, check out [Expo.Location.getProviderStatusAsync](https://docs.expo.io/versions/v18.0.0/sdk/location.html#expolocationgetproviderstatusasync) which enables you to determine if the user has gps enabled or disabled

**Comment by matwii** [comment]
To me it looks like the method dosn't get fired at all when I dissable the GPS on the android device. I'm not getting the console log in success and error callback. The app has permission to use gps, but I want to show something if the gps is turned off. I tried the Expo.Location.getProviderStatusAsync and I'm just getting undefined if it is dissabled and null if it is on..

**Comment by nikki93** [comment]
What's `sdkVersion` in `exp.json` ior `app.json`?

**Comment by matwii** [comment]
Version 17.0.0

**Comment by matwii** [comment]
Got it to work with updating to 18 and react-native 0.45 :)

**Comment by dabbott** [comment]
I just ran into this. The success and error callbacks of `navigator.geolocation.getCurrentPosition` never fired. When I opened the Maps app for the first time, it asked if I wanted to enable location services. Now, the success callback returns my location as expected.
