### ISSUE TITLE
Find way to disable warning about not using the Exponent fork of RN

### ISSUE THREAD

**Issue by dikaiosune** [react-community/create-react-native-app#29]
`2/9/2017, 9:24:18 PM: Warning: Not using the Exponent fork of react-native. See https://docs.getexponent.com/.`

Needs a branch or some other change here:

https://github.com/exponent/xdl/blob/master/src/project/Doctor.js#L176

**Comment by luferogo** [comment]
Hello, I am receiving the warning @0.0.6 version...
Could you give me some advice?

**Comment by dikaiosune** [comment]
@luferogo what version of `react-native-scripts` is in your package.json?

**Comment by luferogo** [comment]
Nevermind @dikaiosune , This message is appearing when using the expo for running the project. If I run the project directly with npm start , the message is not shown. 
That makes sense, right?
(The version is 0.0.26)

**Comment by dikaiosune** [comment]
Yeah, using Expo tools we'll warn you if you're not using the Expo fork of RN b/c it has a few things to work nicely with our stuff, but it's intended that CRNA won't display that error.
