### ISSUE TITLE
How to make dtrace install using yarn

### ISSUE THREAD

**Issue by shashkovdanil** [react-community/create-react-native-app#290]
If you use yarn, then an error occurs https://github.com/react-community/create-react-native-app/issues/135 , but when using npm, there is no such error, since this module is installed during npm install

**Comment by brentvatne** [comment]
We are removing the dtrace dependency soon, so the problem will go away. I haven't had issues with dtrace and yarn personally, you can go to either the dtrace or yarn repos to ask for more information on those.
