### ISSUE TITLE
Unable to connect to the application using the QR Code

### ISSUE THREAD

**Issue by Hareesh007** [react-community/create-react-native-app#291]
React native app create and run the npm start,but 
 Unable to load my app by scanning the QR code in expo,I was checked the Troubleshooting Network section and test in the phone browser and script is loading fine , but after scanning,  i am getting message like Something  Went Wrong with description sorry about that you can go back to home or try to reload the experience.    

**Both Desktop browser and phone browser script is loading.** 
  {"sdkVersion":"18.0.0","name":"AwesomeProject","slug":"awesomeproject","version":"0.1.0","xde":true,"developer":{"tool":"crna"},"packagerOpts":{"hostType":"tunnel","lanType":"ip","dev":true,"strict":false,"minify":false,"urlType":"exp","urlRandomness":null},"env":{},"bundleUrl":"http://ip/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles","debuggerHost":"ip","mainModuleName":"./node_modules/react-native-scripts/build/bin/crna-entry","logUrl":"http://ip/logs","id":"@anonymous/awesomeproject-9efa045c-e943-458c-b36c-f0205aa2a9b6"}

## Environment

* `npm ls react-native-scripts`: react-native-scripts@0.0.40
* `npm ls react-native`: react-native@0.45.1
* `npm ls expo`: expo@18.0.7 
* `node -v`: v8.1.3
* `npm -v`:4.0.0
* `yarn --version`: uninstalled to check this error 
* `watchman version`:  not installed.

Also specify:

1. Operating system: Ubuntu 14 
2. Phone/emulator/simulator & version: redmi 3s prime latest version.

**Comment by brentvatne** [comment]
were you ever able to resolve this?

**Comment by a-eid** [comment]
+1

**Comment by inoutw** [comment]
+1, expo in Android emulator

**Comment by shindexro** [comment]
+1, using expo in actual Android phone
