### ISSUE TITLE
Orientation does not work

### ISSUE THREAD

**Issue by Lars-m** [react-community/create-react-native-app#292]
## Description
This is the content of my app.json
```
{
  "expo": {
    "sdkVersion": "18.0.0",
    "orientation" : "portrait",
    "description" : "..."
  }
}
```

## Expected Behavior
According to the Expo documentation the orientation property should act as:
"Lock your app to a specific orientation with portrait or landscape" 

## Observed Behavior

It DOES NOT lock the orientation to portrait as expected.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
   _npm ERR! peer dep missing: react@>=15.4.0, required by react-native-maps@0.15.2_
* `npm ls react-native`:
    _npm ERR! peer dep missing: react@>=15.4.0, required by react-native-maps@0.15.2_
* `npm ls expo`:
    _npm ERR! peer dep missing: react@>=15.4.0, required by react-native-maps@0.15.2
    npm ERR! peer dep missing: react@>=15.4.0, required by react-native-maps@0.15.2
    npm ERR! peer dep missing: react@>=15.3.1, required by lottie-react-native@1.1.1
    npm ERR! peer dep missing: react@>=15.4.0, required by react-native-branch@2.0.0-beta.3_
* `node -v`:  _6.11.0_
* `npm -v`:  _4.1.2_
* `yarn --version`: _0.24.6_
* `watchman version`:  NA

## Reproducible Demo

Tried on both a real Android device and  a real ios device (Iphone 5)

**Comment by Lars-m** [comment]
I found that a way to get arround this is to use Expo's: ScreenOrientation component, like:

`Expo.ScreenOrientation.allow(Expo.ScreenOrientation.Orientation.PORTRAIT_UP );`

This solves my problem, but does not change the fact that the orientation property in app.json, does not seem to be read

**Comment by satya164** [comment]
Hello. I just created a new project and tried this, but was unable to reproduce this bug. I tested on both iOS, Android real devices and simulators.

Can you DM me the code on slack @satya164 so I can take a look?

**Comment by terribleben** [comment]
Is this a duplicate of https://github.com/expo/expo/issues/323 ?

**Comment by satya164** [comment]
Seems so. Weird how @ccheever could repro this, but I couldn't. Could it have something to do with some library version?

**Comment by Lars-m** [comment]
Yes, a mentioned by terribleben, this seems to be a duplicate of https://github.com/expo/expo/issues/323

**Comment by NoelAnnParisi** [comment]
I am having the same issue: but before I begin typing out all of my versions and so on: is the syntax `{
  "expo": {
    "sdkVersion": "18.0.0",
    "orientation" : "portrait",
    "description" : "..."
  }
}`

or `{
  "expo": {
    "sdkVersion": "17.0.0",
    "name": "Compass",
  },
  "orientation": "portrait"
}`

Because I've seen both online. Thanks so much!

**Comment by satya164** [comment]
The first one

**Comment by NoelAnnParisi** [comment]
Thank you!

**Comment by nightCapLounge** [comment]
I found that upon restarting my expo dev server, the property took effect.

**Comment by staroflead** [comment]
Someone please edit this with above code so beginner like me have better time using react native. When react native doc promote the use of `CRNA`, the ios and android folders have not been generate thus there was no way to change orientation.
https://facebook.github.io/react-native/docs/improvingux.html#screen-orientation-lock
BTW, how could I change orientation of a single screen in app? E.g Video player.

**Comment by whathejoe** [comment]
@staroflead See https://docs.expo.io/versions/latest/sdk/screen-orientation

**Comment by whathejoe** [comment]
@staroflead See: https://docs.expo.io/versions/latest/sdk/screen-orientation
