### ISSUE TITLE
Make react-native run-[android/ios] and react-native start and react-native link work as expected in CRNA

### ISSUE THREAD

**Issue by brentvatne** [react-community/create-react-native-app#294]
## Description

It's kind of silly that we have two approaches for doing the same thing depending on whether you're using an app bootstrapped with react-native-cli or Create React Native App.

## Expected Behavior

react-native-cli commands should delegate to the CRNA equivalent when they are used in the CRNA context

## Observed Behavior

They start the react-native packager without using Create React Native App: https://github.com/facebook/react-native/issues/14828

**Comment by Hum4n01d** [comment]
+1

**Comment by brentvatne** [comment]
Also, react-native-cli should throw an informative error when you try to `react-native link` on a CRNA project

**Comment by fson** [comment]
I've created a pull request in the react-native repository with this improvement: https://github.com/facebook/react-native/pull/15139.
