### ISSUE TITLE
Getting error while starting the npm in my mac

### ISSUE THREAD

**Issue by zakirsajib** [react-community/create-react-native-app#296]
Tried to run react native app, followed the official guidelines - Quick Guide.

After I run the following command:

`npm start`

Then I received error, seems its regarding the 'Watchman'

## Observed Behavior

 *full terminal output and error message* in this code block:

```
Zakir:AwesomeProject sajib$ npm start -- --reset-cache

> AwesomeProject@0.1.0 start /Users/sajib/Downloads/AwesomeProject
> react-native-scripts start "--reset-cache"

Asking packager to reset its cache...
12:48:51 PM: Starting packager...
***ERROR STARTING PACKAGER***
Starting React Native packager...
Scanning 756 folders for symlinks in /Users/sajib/Downloads/AwesomeProject/node_modules (83ms)
Loading dependency graph.
Running packager on port 19001.


jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman error: unable to resolve root /Users/Sajib/Downloads/AwesomeProject: failed to opendir(/Users/Sajib/Downloads/AwesomeProject): No such file or directory. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.html.

```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: 
AwesomeProject@0.1.0 /Users/sajib/Downloads/AwesomeProject
└── react-native-scripts@0.0.40 
* `npm ls react-native`:
AwesomeProject@0.1.0 /Users/sajib/Downloads/AwesomeProject
└── react-native@0.45.1
* `npm ls expo`:
AwesomeProject@0.1.0 /Users/sajib/Downloads/AwesomeProject
└─┬ expo@18.0.6 
  └── UNMET PEER DEPENDENCY react@>=15.3.1

npm ERR! peer dep missing: react@>=15.3.1, required by lottie-react-native@1.1.1
npm ERR! peer dep missing: react@>=15.4.0, required by react-native-branch@2.0.0-beta.3
npm ERR! peer dep missing: react@>=15.4.0, required by react-native-maps@0.15.2

* `node -v`: v6.11.0
* `npm -v`: 3.10.10
* `yarn --version`: command not found
* `watchman version`: command not found

Also specify:

1. Mac OSX Yosemite 10.10.5:

**Comment by zakirsajib** [comment]
![screen shot 11 2](https://user-images.githubusercontent.com/996796/27985178-6e1543fe-63de-11e7-9c69-9f9e3273a8d0.jpg)

**Comment by brentvatne** [comment]
hello! this looks like a watchman issue. try following the instructions it suggests -- create an empty `.watchmanconfig` or initialize a git repo in the directory.

if you run into further watchman issues then I'd suggest checking out the repo: https://github.com/facebook/watchman

**Comment by pdwjun** [comment]
this may help

https://github.com/react-community/create-react-native-app/issues/51#issuecomment-286320333
