### ISSUE TITLE
can not find entry file crna-entry.js in any of the roots after initial install when using expo and node 6.11.0 LTS

### ISSUE THREAD

**Issue by johansyd** [react-community/create-react-native-app#299]
I am having issues with setting up new projects on Windows 10.

This is how I set things up:

    ## Deleted C:\Users\johan.sydseter\AppData\Local\Yarn\cache\v1\.tmp\*
    ## Deleted C:\Users\johan.sydseter\AppData\Local\Yarn\cache\v1\npm-*
    ## Deleted C:\Users\johan.sydseter\AppData\Roaming\npm-cache\*
    ## Deleted C:\Users\JOHAN~1.SYD\AppData\Local\Temp\npm-*
    ## Deleted C:\Users\JOHAN~1.SYD\AppData\Local\Temp\react-native*
    ## Deleted C:\Users\JOHAN~1.SYD\AppData\Local\Temp\jest*
    ## Deleted C:\Users\johan.sydseter\AppData\Roaming\nvm\v6.11.0
    ## Deleted C:\Program Files (x86)\yarn
    nvm install 6.11.0
    nvm use 6.11.0
    npm install -g create-react-native-app
    cd C:\Users\johan.sydseter\.babun\cygwin\home\Johan.Sydseter\sydseter
    create-react-native-app codewars
    cd codewars
    npm start

1. I then installed ANDROID SDK, Genymotion and expo and Downloaded Google Nexus 5 with Android 4.4.4
2. setup adb tool connection with a custom  Android SDK in genymotion to point to: C:\Program Files (x86)\Android\android-sdk
3. Started Google Nexus 5 emulator and installed the expo client on the device.
4. Opned expo in the emulator and pasted in the expo url

The emulator then complained with the following:

    The development server returned response error code: 404
    URL: http://192.168.56.1:19001/node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=android&dev=true&strict=false&minify=false&hot=false&assetPlugin=expo/tools/hashAssetFiles
    Body:
    {"message":"Cannot find entry file node_modules/react-native-scripts/build/bin/crna-entry.js in any of the roots:[\"C:\\\\Users\\\\johan.sydseter\\\\.babun\\\\cygwin\\\\home\\\\Johan.Sydseter\\\\sydseter\\\\codewars\"]","name":"NotFoundError","type":"NotFoundError","status":404,"errors":[{}]}
    processBundleResult
        DevServerHelper.java:484
    access$000
        DevServerHelper.java:76
    execute
        DevServerHelper.java:434
    emitChunk
        MultipartStreamReader.java:69
    readAllParts
        MultipartStreamReader.java:116
    onResponse
        DevServerHelper.java:423
    execute
        RealCall.java:126
    run
        NamedRunnable.java:32
    runWorker
        ThreadPoolExecutor.java:1112
    run
        ThreadPoolExecutor.java:587
    run
        Thread.java:841

The command line returned this:

    12:05:53: Failed building JavaScript bundle

Here is my package.js after the initial install:

```
{
  "name": "codewars",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "0.0.40",
    "jest-expo": "~18.0.0",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^18.0.3",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.45.1"
  }
}
```
## Environment

```
{ codewars }  » npm ls react-native-scripts
codewars@0.1.0 C:\Users\johan.sydseter\.babun\cygwin\home\Johan.Sydseter\sydseter\codewars
`-- react-native-scripts@0.0.40

{ codewars }  » npm ls react-native
codewars@0.1.0 C:\Users\johan.sydseter\.babun\cygwin\home\Johan.Sydseter\sydseter\codewars
`-- react-native@0.45.1

{ codewars }  » npm ls expo
codewars@0.1.0 C:\Users\johan.sydseter\.babun\cygwin\home\Johan.Sydseter\sydseter\codewars
`-- expo@18.0.6
  `-- UNMET PEER DEPENDENCY react@>=15.3.1

npm ERR! peer dep missing: react@>=15.3.1, required by lottie-react-native@1.1.1
npm ERR! peer dep missing: react@>=15.4.0, required by react-native-branch@2.0.0-beta.3
npm ERR! peer dep missing: react@>=15.4.0, required by react-native-maps@0.15.2
{ codewars }  » node -v
v6.11.0
{ codewars }  » npm -v
3.10.10
{ codewars }  » yarn --version
0.27.5
{ codewars }  » watchman version 4.9.0
{
    "version": "4.9.0",
    "buildinfo": "981452aff98ee5064c06a3a8cd39ff2394846114 2017-07-03T21:52:36.0000000Z",
    "capabilities": {}
}

```
OS: Windows 10 Pro
Emulator Genymotion: Google Nexus 5 - 4.4.4

I got some issues with the package manager complaining that 16.0.0-alpha.12 was an unmet dependency so I downgraded to react 15.4 ,but that didn't help since react-native-scripts 0.40 depends on react@16.0.0-alpha.12

I am not sure how to proceed. I will try to downgrade to another version of react-native-scripts

**Comment by johansyd** [comment]
What is the last version of react-native-scripts  that uses react@15.x.x ? react@16.0.0-alpha.12 gets dragged in with xdl@42 I am sort of hoping that I can downgrade my way out of this.

**Comment by johansyd** [comment]
Forgot to add the log.

[log.txt](https://github.com/react-community/create-react-native-app/files/1133782/log.txt)

**Comment by johansyd** [comment]
Confirmed working on create-react-native-app@0.0.5

**Comment by johansyd** [comment]
Downgrading to create-react-native-app@0.0.5 fixes the issue for me.

**Comment by johansyd** [comment]
Looks like I was too quick. I am still getting the same error after the downgrade. For a short moment I was able to get the project up an running, but then I tried to do it once more from the top. Result: The same thing happens. Can't understand what I did different. The same thing happens regardless whether I use yarn or npm.

    ## Deleted C:\Users\JOHAN~1.SYD\AppData\Local\Temp\npm-*
    ## Deleted C:\Users\JOHAN~1.SYD\AppData\Local\Temp\react-native*
    ## Deleted C:\Users\JOHAN~1.SYD\AppData\Local\Temp\jest*
    ## Deleted C:\Users\johan.sydseter\AppData\Roaming\nvm\v6.11.0
    npm cache clean
    yarn cache clean
    nvm install 6.11.0
    nvm use 6.11.0
    npm install -g create-react-native-app@0.0.5
    ## I also tried: npm install -g yarn
    cd C:\Users\johan.sydseter\.babun\cygwin\home\Johan.Sydseter\sydseter
    create-react-native-app codewars
    cd codewars
    npm start ## or yarn start

**Comment by johansyd** [comment]
After some searching I believe my issue might be related to: https://github.com/facebook/react-native/issues/14736

**Comment by brentvatne** [comment]
interesting. I think the new release should fix it. try creating a new project if it is not resolved then feel free to re-create the issue

**Comment by braianj** [comment]
you ask and answer your own question, this community really works!
