### ISSUE TITLE
Have an error on Xcode8.3.3:C++ requires a type specifier for all declarations

### ISSUE THREAD

**Issue by 1049017200** [react-community/create-react-native-app#300]
## Description

I have an error on Xcode8.3.3:C++ requires a type specifier for all declarations when I run the React Native project on Xcode.

## Expected Behavior

I ask my leader about the project how created, he tell me,he use the command to created the project ,the command is 'create-react-native-app ProjectName',then,I use command 'npm run eject' to get native project ,then ,use Xcode open the ios/XXX.xcodeproj file, click the 'run' button ,finally,I have the error.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
extraneous: react-native-scripts@0.0.40 /Users/apple/Documents/reactNative/cws-logistics/node_modules/react-native-scripts
* `npm ls react-native`:
cws-logistics@0.1.0 /Users/apple/Documents/reactNative/cws-logistics
└── react-native@0.45.1 
* `npm ls expo`:
extraneous: expo@18.0.4 /Users/apple/Documents/reactNative/cws-logistics/node_modules/expo
* `node -v`:v8.0.0
* `npm -v`:4.6.1
* `yarn --version`:0.21.3
* `watchman version`:
{
    "version": "4.7.0"
}

Also specify:

1. Operating system: Mac OS Sierra 10.12.3
2. Phone/emulator/simulator & version: iPhone 6s plus 10.3.2
![wx20170710-111702](https://user-images.githubusercontent.com/17327793/28001714-5972052a-6561-11e7-8525-f9f62e10b3e4.png)

**Comment by brentvatne** [comment]
can you share the ejected project? this works fine for me
