### ISSUE TITLE
missing script: start

### ISSUE THREAD

**Issue by Opty1712** [react-community/create-react-native-app#301]
## Description
After completing these 4 steps
```
$ npm install -g create-react-native-app
$ create-react-native-app my-app
$ cd my-app/
$ npm start
```
I got this error:
```
npm start
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3

npm ERR! missing script: start
```

When I open package.json I see only
```
{
  "name": "my-project",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "0.0.40"
  }
}
```

**Comment by brentvatne** [comment]
what version of windows is "Windows_NT 6.1.7601"?

**Comment by Opty1712** [comment]
Windows 7
--
С уважением, 
Андрей понедельник, 17 июля 2017г., 22:28 +03:00 от Brent Vatne  notifications@github.com :

**Comment by webdevbrian** [comment]
Same issue here

**Comment by brentvatne** [comment]
Something must be wrong with that version of npm, I'd recommend 4.6.1 or yarn. Notice that the only dependency that is installed is react-native-scripts, it should be installing react-native, expo, and a few more.

**Comment by Opty1712** [comment]
with these versions it works fine!
```
$ node -v
v7.3.0
$ npm -v
3.10.10
```

**Comment by bob-zs** [comment]
Can confirm @brentvatne.
Was using node version `8.2.1` and npm version `5.3.0` and got the same error.
Downgrading everything to node `6.11.1` and npm `4.6.1`, which did fixed it.

**Comment by webdevbrian** [comment]
Used yarn here, that worked for me.

**Comment by sarancruzer** [comment]
After completing these steps

$ npm install -g create-react-native-app
$ create-react-native-app AwesomeProject
$ cd AwesomeProject
$ npm start

I got this error:

npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/saravanan/.npm/_logs/2017-09-22T13_47_56_942Z-debug.log

npm ERR! missing script: start

this versions i have used
$ node -v
v8.4.0
$ npm -v
5.3.0

**Comment by SDJLee** [comment]
use npm 4.6.1

**Comment by BenCook28** [comment]
How do I either downgrade to npm 4.6.1 or use Yarn to start?  I read the top four or five Google results about this thread's issue, looked up the Yarn documentation and didn't find "start", and I tried npm install -g npm@4.  I'm getting an error which says "package.json must be actual JSON, not just JavaScript.

My package.json looks like this after I added a start script:

{
  "name": "AwesomeProject",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "start": "node server.js",
  "devDependencies": {
    "react-native-scripts": "1.5.0"
  }
}

**Comment by johnlaine1** [comment]
Using npm 4.6.1, got the same error

**Comment by stoufa06** [comment]
@johnlaine1 you need to have nodejs version >=6 and npm version 4
After that you need to reinstall create-react-native-app and delete my-app folder and create project again
that's it

**Comment by johnlaine1** [comment]
Yup, re-installing creacte-react-native-app did the trick!

John Laine
602.741.0261

**Comment by hieuleevizi** [comment]
Currently I have the same issue:
C:\Users\PC\AwesomeProject>npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PC\AppData\Roaming\npm-cache\_logs\2017-10-09T09_30_43_954Z-debug.log

And below as these version I had installed:
C:\Users\PC\AwesomeProject>node --version
v8.6.0

C:\Users\PC\AwesomeProject>npm --version
5.4.2

Could you please advise how to fix them?

**Comment by vantuan02t1** [comment]
I have the same issue:
C:\Users\PC\AwesomeProject>npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PC\AppData\Roaming\npm-cache\_logs\2017-10-09T09_30_43_954Z-debug.log

Below as my version:
C:\Users\PC\AwesomeProject>node --version
v8.6.0

C:\Users\PC\AwesomeProject>npm --version
5.4.2

**Comment by vantuan02t1** [comment]
I have the same issue:
C:\Users\PC\AwesomeProject>npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\PC\AppData\Roaming\npm-cache_logs\2017-10-09T09_30_43_954Z-debug.log

Below as my version:
C:\Users\PC\AwesomeProject>node --version
v8.6.0

C:\Users\PC\AwesomeProject>npm --version
5.4.2

**Comment by stoufa06** [comment]
@vantuan02t1 use npm version 4.6.1 and reinstall creacte-react-native-app and remove AwesomeProject and create again
npm install npm@4.6.1

**Comment by stoufa06** [comment]
If you are using firewall in linux try open port 19001

**Comment by vantuan02t1** [comment]
Thank you stoufa06, It works fine now

**Comment by nizar2yas** [comment]
same issue :
npm version: 5.4.2
node version :6.11.3

**Comment by vantuan02t1** [comment]
@nizar2yas , please use npm version 4.6.1 and reinstall creacte-react-native-app and remove AwesomeProject and create again
npm install npm@4.6.1

**Comment by eniniz** [comment]
Yes you were right 
here is the command to be executed for those who face the same issue : 
npm i -g npm@4.6.1

**Comment by wilsonsk** [comment]
why is downgrading to 4.6.1 the correct solution?

**Comment by RenatoBello** [comment]
I have this same issue and I don't know how to downgrade the NPM version. 

`npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rb/.npm/_logs/2017-11-07T16_06_56_332Z-debug.log`

I am using the last versions of node and npm

I am a Mac user and did not find the 4.6.1 version. By the way, I also would like to know why I need to downgrade to fix it. Thanks in advance.

**Comment by RenatoBello** [comment]
Thanks for the fast reply.

I tried to install it and I got a lot of "npm WARN checkPermissions" messages and some error messages:

```
npm ERR! path /usr/local/lib/node_modules/npm/node_modules/abbrev
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/npm/node_modules/abbrev'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules/npm/node_modules/abbrev'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules/npm/node_modules/abbrev\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/npm/node_modules/abbrev' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/renatobello/.npm/_logs/2017-11-07T16_52_59_581Z-debug.log
```

**Comment by stoufa06** [comment]
sudo npm install -g npm@4.6.1

**Comment by RenatoBello** [comment]
Thanks you @stoufa06 

I installed the 4.6.1 version but I am still getting the same error:

```
 npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rb/.npm/_logs/2017-11-07T21_00_17_458Z-debug.log
```

**Comment by jponc** [comment]
Encountered this as well using MacOS Sierra

Instructions
```sh
# Install npm version 4
npm install -g npm@4

# This should now be @ 4.6 something
npm --version 

# Reinstall  create-react-native-app
npm install -g create-react-native-app

# Recreate project
create-react-native-app AwesomeProject
cd AwesomeProject
npm start

```

**Comment by cscan** [comment]
I love react-native because it always need to do some tricks to do normal things

**Comment by montao** [comment]
These solutions are not working with Ubuntu 16.04
```

sudo ./npm install npm@4.6.1
developer@1604:~/node-v8.9.4-linux-x64/bin$ npm -v
ERROR: npm is known not to run on Node.js v4.2.6
Node.js 4 is supported but the specific version you're running has
a bug known to break npm. Please update to at least 4.7.0 to use this
version of npm. You can find the latest release of Node.js at https://nodejs.org/

```

**Comment by nambitable** [comment]
node -v
8.9.4
npm -v 
5.6.0 

same issue. My "issue" is that it doesn't work with the latest version of npm. 

Downgrading npm is not an option.

**Comment by dann1609** [comment]
please check package.json file. Inside you need to check script key:



"scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node ./node_modules/jest/bin/jest.js --watch"
  },

if you don't see the previous code and only see "test" key. Then copy these lines and add 

"devDependencies": {
    "react-native-scripts": "1.11.1",
    "jest-expo": "XXX",
    "react-test-renderer": "16.2.0"
  },

**Comment by Andrei199541** [comment]
Help Me!

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bootstrap-magic@4.0.0 dev: `./node_modules/serve/bin/serve.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bootstrap-magic@4.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2018-08-22T20_57_09_522Z-debug.log

How can I do?
what else i can?
