### ISSUE TITLE
Deprecated fs-extra and gitClone error

### ISSUE THREAD

**Issue by mdblis6121** [react-community/create-react-native-app#308]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

First, I'm new to React Native so I am probably just doing something wrong, but...
I ran:

`npm install -g create-react-native-app`
`create-react-native-app Auth`

I received no QR code to launch Expo simulator. Instead I received this. I had completed a project that worked fine and when I started a new one, everything went wrong. I uninstalled everything and started over. Here is where I am.

## Expected Behavior

A project name Auth should be built and a QR code displayed for Expo app.

What action did you perform, and what did you expect to happen?

## Observed Behavior

What actually happened when you performed the above actions?

There is a folder named Auth now in my directory but I can not seem to get the project launched so I can begin. The first code block came after running:

`npm install -g create-react-native-app`

and the second came after running:

`create-react-native-app Auth`

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
C:\Users\Blisstopher\ReactNative>npm install -g create-react-native-app
npm WARN deprecated fs-promise@1.0.0: Use mz or fs-extra^3.0 with Promise Support
C:\Users\Blisstopher\AppData\Roaming\npm\create-react-native-app -> C:\Users\Blisstopher\AppData\Roaming\npm\node_modules\create-react-native-app\build\index.js
C:\Users\Blisstopher\AppData\Roaming\npm
`-- create-react-native-app@0.0.6
```
```
npm WARN react-redux@5.0.5 requires a peer of react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0 but none was installed.
Installing dependencies using npm...

npm ERR! git clone --template=C:\Users\Blisstopher\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:expo/node-websql.git C:\Users\Blisstopher\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expo-node-websql-git-18-0-0-8213877d: undefined
npm ERR! git clone --template=C:\Users\Blisstopher\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:expo/node-websql.git C:\Users\Blisstopher\AppData\Roaming\npm-cache\_git-remotes\git-github-com-expo-node-websql-git-18-0-0-8213877d: undefined
npm ERR! code ENOGIT
npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Blisstopher\AppData\Roaming\npm-cache\_logs\2017-07-13T14_54_25_262Z-debug.log
`npm install --save` failed
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:   react-native-scripts@0.0.50
* `npm ls react-native`:    UNMET DEPENDENCY react-native@^0.45.1
        npm ERR! missing: react-native@^0.45.1, required by Auth@0.1.0
* `npm ls expo`:   UNMET DEPENDENCY expo@^18.0.3
        npm ERR! missing: expo@^18.0.3, required by Auth@0.1.0
* `node -v`:   v6.11.0
* `npm -v`:   4.6.1
* `yarn --version`:   'yarn' is not recognized as an internal or external command,
operable program or batch file.
* `watchman version`:   'watchman' is not recognized as an internal or external command,
operable program or batch file.

Also specify:

1. Operating system:   Windows 10
2. Phone/emulator/simulator & version:  lg g4/ Expo app

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by smitthakkar1** [comment]
I was getting this error and it was a silly mistake. I'm sure most of you don't do this:

I was importing the file like this : import file from 'file';
But actual way was : import file from './file';

That works.
P.S. I also run the command "yarn" before doing above change.

**Comment by amdani786** [comment]
**UNMET DEPENDENCY react-native@^0.45.1
npm ERR! missing: react-native@^0.45.1, required by Auth@0.1.0**
 can anyone tell me how to overcome this error

**Comment by brentvatne** [comment]
no idea what the "Auth" package is, maybe ask them

**Comment by amdani786** [comment]
who can give the solution
