### ISSUE TITLE
No iOS or Android folder after creating a app with create-react-native-app

### ISSUE THREAD

**Issue by eschao** [react-community/create-react-native-app#311]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description
Using **create-react-native-app** to create application, but I can't find **iOS** or **Android** related folders in created application folder. 

## Expected Behavior
In my memory, they should be created since this is a react native app not a web app. 

What action did you perform, and what did you expect to happen?
```shell
sudo npm install -g create-react-native-app
create-react-native-app my-app
```

## Observed Behavior
In my-app folder, I only can see the below folders:
>App.js       App.test.js  README.md    app.json     node_modules package.json

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@0.0.50
* `npm ls react-native`: react-native@0.45.1
* `npm ls expo`: expo@18.0.9
* `node -v`: v6.9.2
* `npm -v`: 4.6.1
* `yarn --version`: Not installed
* `watchman version`: "version": "4.7.0"

Also specify:

1. Operating system: MacOS 10.12
2. Phone/emulator/simulator & version: IPhone 6 simulator

## Reproducible Demo

Is it normal? I can't make sure since I remember the **iOS** and **android** folder will be generated together. If I'm wrong, please correct! Thanks a lot!

**Comment by eschao** [comment]
Its' my fault. I know how to create them now. Close it

**Comment by bdibenedetto** [comment]
whats the problem? I have the same issue

**Comment by brentvatne** [comment]
@bdibenedetto - there is no problem. this is intentional. read the readme

**Comment by nicoceledon** [comment]
The whole situation is not so clear to me from the readme. I know they won't be there but a library i need, requires some modifications in those folders. I could guess that those folders would appear with `yarnpkg eject` but as it says it's **permanent**, i don't feel sure about doing it now.

**Comment by TonyFrancis** [comment]
I did not understand. Can you give me step to `create ios/ android` folder

**Comment by lasuax** [comment]
@TonyFrancis read here: https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md

**Comment by mohamedebrahim96** [comment]
One of the points of Expo on top of React Native is that you don't go down to android or ios code. Expo deals with those folders for you, you don't need to interact with them. Is there a reason you need those folders? if so, you will have to detach. Here's the documentation to do so: [Detaching with expo](https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md)

**Comment by Vijaysuryawanshi1993** [comment]
create your app using - 
react-native init (AppName) 
It'll create both android and ios folders
or you can go to the directory 
node_modules->react-native

**Comment by Astarta0** [comment]
Can you help me please? I can't find how to organize the React Native Project, if i created it using "create-react-native-app", and I need to have two "entry point"-files: for IOS and Android
as I understood, I can't rename App.js and it is the only one in project

**Comment by Vijaysuryawanshi1993** [comment]
Create your project using:- react-native init (appname)

**Comment by rudra0713** [comment]
Hi @Vijaysuryawanshi1993, I have created my react native app with react native init command three weeks ago and I have been working on it since then. Recently, to do some analytics work like showing some line or bar chart, I found the package react-chartjs. However, this package heavily uses canvas and if I decide to add this package in my app, "". It seemed to me the error is occurring because react native does not support div or html in general. But, then I went to youtube to see some tutorial on chart-js, https://www.youtube.com/watch?v=Ly-9VTXJlnA. In this tutorial, the youtuber created his project with create-react-native-app command and he could easily use <div> like components in his project. So this might be a stupid question, but does create-react-native has something to do with supporting html components ??

**Comment by nosisky** [comment]
Read on **Detaching to ExpoKit**

**Comment by nicoceledon** [comment]
It seems that the flow changed a little bit. As far as i remember, i just ejected the project with 'react-native eject'. Then android and iOS folders where created. Nevertheless, checkout the README.md ;)

**Comment by Fed0t** [comment]
https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/template/README.md#ejecting-from-create-react-native-app

**Comment by MichaelHuy** [comment]
@eschao . How to generate ios and android folder? Please show me the link? Thanks.

**Comment by Nyconing** [comment]
Those will be created by **'Eject'**? This name is a confusing.

**Comment by asif11996** [comment]
I am also facing the same issue. I create the project by react-native init App name but android and ios folder is missing

**Comment by JatinBhuva** [comment]
If you previously installed a global react-native-cli package, please remove it as it may cause unexpected issues:

`npm uninstall -g react-native-cli @react-native-community/cli`

then create a new project again:
`
npx react-native init DemoApp`

**Comment by microgold** [comment]
This fixed it for me:
    npm uninstall -g react-native-cli @react-native-community/cli
, previously it was showing no ios or android folders, and completely ignoring the template.
