### ISSUE TITLE
App crashes when touching screen with 3 fingers

### ISSUE THREAD

**Issue by tusharkhatiwada** [react-community/create-react-native-app#312]
## Description

As mentioned on the title, the app crashes after touching the screen with three fingers both in development and production version. 
I have a **One Plus 2** device and I needed to take a screenshot of my app. It has **Three-finger screenshot** gesture control. The app simply restarts on the production version but displays the following error on development version.

![screenshot_20170715-204307](https://user-images.githubusercontent.com/5126590/28240306-084b0452-699f-11e7-9c31-51e3661f653d.png)

**Error Message**

```
Cannot record touch end without a touch start.
Touch End: %s
 Touch Bank: %s {"identifier":2,"pageX":97,"pageY":320,"timestamp":78140617} [{"touchActive":false,"startPageX":198.3333282470703,"startPageY":270.3333435058594,"startTimeStamp":78140609,"currentPageX":198.3333282470703,"currentPageY":270.3333435058594,"currentTimeStamp":78140617,"previousPageX":198.3333282470703,"previousPageY":270.3333435058594,"previousTimeStamp":78140609},{"touchActive":false,"startPageX":293,"startPageY":306.6666564941406,"startTimeStamp":78140615,"currentPageX":293,"currentPageY":306.6666564941406,"currentTimeStamp":78140617,"previousPageX":293,"previousPageY":306.6666564941406,"previousTimeStamp":78140615}]
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: **react-native-scripts@0.0.40**
* `npm ls react-native`: **react-native@0.45.1**
* `npm ls expo`: **expo@18.0.6**
* `node -v`: **v7.4.0**
* `npm -v`: **4.6.1**
* `yarn --version`: **0.27.5**
* `watchman version`: **"version": "4.7.0"**

Also specify:

1. Operating system: **MacOS Sierra 10.12.6 beta** 
2. Phone/emulator/simulator & version: **One Plus 2**

**Comment by brentvatne** [comment]
Hello! This appears to be an upstream React Native issue. I created an issue on the react-native repository for you: https://github.com/facebook/react-native/issues/15059

If possible please provide a link to an example application on Github where this happens for you. If it happens just on any new project, let us know in that thread. Thank you so much for the report!

**Comment by tusharkhatiwada** [comment]
@brentvatne This issue isn't on the app created with `react-native init`. Here's the app on the play store created with **CRNA** .
https://play.google.com/store/apps/details?id=com.ictechmedia.ictaward

**Comment by tusharkhatiwada** [comment]
The issue is device specific. It's only on **One Plus 2**. I've tested with some other devices, but they didn't crash.

**Comment by brentvatne** [comment]
@tusharkhatiwada - so it happens on a brand new app created with CRNA but not on a brand new app created with `react-native init`?

**Comment by tusharkhatiwada** [comment]
@brentvatne Sorry. I just tested with `react-native init` and it's showing the same error too. I had an App built few months back and wasn't showing the error. So that means the error is with the latest version of `react-native`. 
Sorry, I opened the issue on wrong repo.

**Comment by csgsky** [comment]
i find this problem too, do you have any solution?

**Comment by brentvatne** [comment]
@csgsky - sorry to hear that. I see you commented on https://github.com/facebook/react-native/issues/15059 -- that's your best bet for a resolution. feel free to investigate a solution on your own as well and submit a PR!

**Comment by amitkumarsingh1991** [comment]
@brentvatne , i am also same issue in MI , try to figure out root cause ,please provide solution, Thanks in advance

**Comment by mojotti** [comment]
Same issue on OnePlus 5

**Comment by gregoriohc** [comment]
I also have this problem and I have proposed some workarounds and possible solution on the react-native issue: https://github.com/facebook/react-native/issues/15059#issuecomment-366948308

**Comment by hassaanmirza** [comment]
Same issue on Oppo A57

**Comment by raglopa** [comment]
Same issue on OnePlus 5T

**Comment by anp** [comment]
Hi everyone, the upstream react native issue is where to track/report this. Thanks!
