### ISSUE TITLE
How to have browser debugger with app on device

### ISSUE THREAD

**Issue by richkeenan** [react-community/create-react-native-app#314]
This is a question, not a bug report.

Is it possible to run the app through the Expo client app on device, but to have debugging output through the browser on my dev machine?

By default my terminal shows console output but the formatting is all screwed up for debug modules that write with colors/tables etc

**Comment by brentvatne** [comment]
Hi @richkeenan! It is possible, on iOS for example you can shake the device to show the dev menu (when your app is open) and then choose "Debug Remote JS". [React Native Debugger](https://github.com/jhen0409/react-native-debugger) also works quite well. Check out the [usage section](https://github.com/jhen0409/react-native-debugger/blob/6d33909ac0587fe3d8db58fa9a2f0bd2ecd66547/npm-package/README.md#usage) to see how to integrate with Expo.

**Comment by richkeenan** [comment]
Thanks @brentvatne that's cool. Given that this solution isn't mentioned in the CRNA docs I think I'll make a PR to include this - I'm sure it's useful for people like me, who only have experience of CRNA and not react-native-debugger

**Comment by richkeenan** [comment]
@brentvatne does this also work for Android? Your answer only mentions iOS and I don't have an Androis device to test on

**Comment by brentvatne** [comment]
Yup. Nice! A PR would be very welcome for that. Sorry I just assumed iOS for some reason, you can do it on Android with the same gesture -- shake the device and choose 'Debug JS Remotely'

**Comment by dkulichkin** [comment]
@brentvatne Current Android version (Nexus 5) does not invoke any Developer Menu when shaking

**Comment by dmongit** [comment]
Is the shake gesture supposed to work on a detached app? I have the Expo app on my phone, and scanned the QR code from my expo project. Shaking does not pull up a debugger menu.

**Comment by hnanh** [comment]
Step 1: Ensure device and server on the same network.
Step 2: Deploy the application to the device with debug mode.
Step 3: Shake device -> Select Remote JS Debugging.

**Comment by darthmolen** [comment]
I have the same question as @dmongit. we are having considerably different performance on a handset vs a simulator and need to debug the handset but the shake does not bring up a debug menu.

**Comment by ChirantanPatel** [comment]
Hi @brentvatne ,
 Please give me full step by step suggestion for how to debug application on chrome.
