### ISSUE TITLE
AppDelegate.m:12:9: 'React/RCTBundleURLProvider.h' file not found

### ISSUE THREAD

**Issue by Pyrolistical** [react-community/create-react-native-app#316]
## Description
Vanilla ejected app without expo iOS build has compilation error and failed to build.

## Expected Behavior
It should build out of the box.

## Observed Behavior
`AppDelegate.m:12:9: 'React/RCTBundleURLProvider.h' file not found`

## Environment
* `npm ls react-native-scripts`: `N/A`
* `npm ls react-native`: `0.45.1`
* `npm ls expo`: `N/A`
* `node -v`: `v6.11.0`
* `npm -v`: `3.10.10`
* `yarn --version`: `0.20.3` (this is the one installed by create-react-native-app!)
* `watchman version`: `4.7.0`
* Operating system: Sierra 10.12.5
* Phone/emulator/simulator & version: 10.0

## Reproducible Demo

1. create a new app using create-react-native-app@0.0.6
2. eject without expo
3. Open Xcode project
4. Build

## Workaround

Update to latest yarn `0.27.5` makes it run, however the compilation error is still there??

**Comment by Pyrolistical** [comment]
create-react-native-app needs to be updated to use latest yarn

**Comment by Pyrolistical** [comment]
Hmm, I have a dot in my project name, I wonder if that is the issue

**Comment by brentvatne** [comment]
@Pyrolistical --  possibly! if you try without that does it work on your machine? works as expected for me

**Comment by Pyrolistical** [comment]
@brentvatne nope, still a problem
<img width="560" alt="screen shot 2017-07-18 at 12 14 46 am" src="https://user-images.githubusercontent.com/463642/28304813-2976fcb6-6b4e-11e7-9338-ad2c096c0f55.png">

**Comment by b3bakyt** [comment]
Having the same issue

**Comment by brentvatne** [comment]
I just did this again and it worked fine. If you can provide a project that has this issue, please re-open the issue. Without a repro there's not much we can do :\

**Comment by kappe** [comment]
I have the same problem! using react-native 0.47, node 8.2.1, xcode 8.3.3
_react-native init projName
cd projName
react-native run-ios_

**AppDelegate.m #import <React/RCTBundleURLProvider.h> . 'file not found'**

File exists in:
./ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTBundleURLProvider.h
./node_modules/react-native/React/Base/RCTBundleURLProvider.h
but was not found by xcode?

**Comment by kappe** [comment]
don't know if it is important, but IMO it's strange:
when I comment RTCURLProvider 
//#import <React/RCTBundleURLProvider.h>
**#import <React/RCTRootView.h> ist set to 'file not found'**

**Comment by chiragpurohit71085** [comment]
I am facing the same issue.

DemoProject/ios/DemoProject/AppDelegate.m:12:9: 'React/RCTBundleURLProvider.h' file not found
is there any solution? 

I am following instructions from 

https://facebook.github.io/react-native/docs/getting-started.html (Building Projects with Native Code)

I have tried to create project again and again, but no luck.

**Comment by shukerullah** [comment]
Same issue
"react": "16.0.0-alpha.12",
"react-native": "0.47.0",

**Comment by Pyrolistical** [comment]
@brentvatne seems like a lot of people are having this issue. What additional information can people provide in order to reproduce this?

**Comment by greenteamer** [comment]
same issue

**Comment by Pyrolistical** [comment]
I am not blocked by this, since I am using an earlier version now. Somebody who is blocked by this, please repo this with a new project and link the created project here.

**Comment by drpiou** [comment]
same issue, RN 0.47...

**Comment by chiragpurohit71085** [comment]
Hi @Pyrolistical

I have created repo for the same

https://github.com/chiragpurohit71085/RNTutorialProject

I have mentioned command I have issued and output.

Just for information 



RNTutorialProject/ios/RNTutorialProject/AppDelegate.m:12:9: 'React/RCTBundleURLProvider.h' file not found

I am following instructions from

https://facebook.github.io/react-native/docs/getting-started.html (Building Projects with Native Code)

**Comment by chiragpurohit71085** [comment]
Hi

Same issue on another machine with yarn installed...

Here is the logs while creating the project...

sudo react-native init RNTutorialProject
Password:
This will walk you through creating a new React Native project in /Applications/XAMPP/xamppfiles/htdocs/github/ReactNative/demo/RNTutorialProject
Using yarn v0.24.6
Installing react-native...
yarn add v0.24.6
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning react-native > connect@2.30.2: connect 2.x series is deprecated
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-native@0.47.1" has unmet peer dependency "react@16.0.0-alpha.12".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "0.27.5" while you're on "0.24.6".
success Saved 490 new dependencies.
├─ abbrev@1.1.0
├─ absolute-path@0.0.0
├─ accepts@1.2.13
├─ ajv@4.11.8
├─ align-text@0.1.4
├─ ansi-escapes@2.0.0
├─ ansi-regex@2.1.1
├─ ansi-styles@2.2.1
├─ ansi@0.3.1
├─ anymatch@1.3.2
├─ aproba@1.1.2
├─ are-we-there-yet@1.1.4
├─ arr-diff@2.0.0
├─ arr-flatten@1.1.0
├─ array-differ@1.0.0
├─ array-filter@0.0.1
├─ array-map@0.0.0
├─ array-reduce@0.0.0
├─ array-uniq@1.0.3
├─ array-unique@0.2.1
├─ art@0.10.1
├─ asap@2.0.6
├─ asn1@0.2.3
├─ assert-plus@1.0.0
├─ async@2.5.0
├─ asynckit@0.4.0
├─ aws-sign2@0.6.0
├─ aws4@1.6.0
├─ babel-code-frame@6.26.0
├─ babel-core@6.26.0
├─ babel-generator@6.26.0
├─ babel-helper-builder-react-jsx@6.26.0
├─ babel-helper-call-delegate@6.24.1
├─ babel-helper-define-map@6.26.0
├─ babel-helper-function-name@6.24.1
├─ babel-helper-get-function-arity@6.24.1
├─ babel-helper-hoist-variables@6.24.1
├─ babel-helper-optimise-call-expression@6.24.1
├─ babel-helper-regex@6.26.0
├─ babel-helper-remap-async-to-generator@6.24.1
├─ babel-helper-replace-supers@6.24.1
├─ babel-helpers@6.24.1
├─ babel-messages@6.23.0
├─ babel-plugin-check-es2015-constants@6.22.0
├─ babel-plugin-external-helpers@6.22.0
├─ babel-plugin-react-transform@2.0.2
├─ babel-plugin-syntax-async-functions@6.13.0
├─ babel-plugin-syntax-class-properties@6.13.0
├─ babel-plugin-syntax-flow@6.18.0
├─ babel-plugin-syntax-jsx@6.18.0
├─ babel-plugin-syntax-object-rest-spread@6.13.0
├─ babel-plugin-syntax-trailing-function-commas@6.22.0
├─ babel-plugin-transform-async-to-generator@6.16.0
├─ babel-plugin-transform-class-properties@6.24.1
├─ babel-plugin-transform-es2015-arrow-functions@6.22.0
├─ babel-plugin-transform-es2015-block-scoped-functions@6.22.0
├─ babel-plugin-transform-es2015-block-scoping@6.26.0
├─ babel-plugin-transform-es2015-classes@6.24.1
├─ babel-plugin-transform-es2015-computed-properties@6.24.1
├─ babel-plugin-transform-es2015-destructuring@6.23.0
├─ babel-plugin-transform-es2015-for-of@6.23.0
├─ babel-plugin-transform-es2015-function-name@6.24.1
├─ babel-plugin-transform-es2015-literals@6.22.0
├─ babel-plugin-transform-es2015-modules-commonjs@6.26.0
├─ babel-plugin-transform-es2015-object-super@6.24.1
├─ babel-plugin-transform-es2015-parameters@6.24.1
├─ babel-plugin-transform-es2015-shorthand-properties@6.24.1
├─ babel-plugin-transform-es2015-spread@6.22.0
├─ babel-plugin-transform-es2015-sticky-regex@6.24.1
├─ babel-plugin-transform-es2015-template-literals@6.22.0
├─ babel-plugin-transform-es2015-unicode-regex@6.24.1
├─ babel-plugin-transform-es3-member-expression-literals@6.22.0
├─ babel-plugin-transform-es3-property-literals@6.22.0
├─ babel-plugin-transform-flow-strip-types@6.22.0
├─ babel-plugin-transform-object-assign@6.22.0
├─ babel-plugin-transform-object-rest-spread@6.26.0
├─ babel-plugin-transform-react-display-name@6.25.0
├─ babel-plugin-transform-react-jsx-source@6.22.0
├─ babel-plugin-transform-react-jsx@6.24.1
├─ babel-plugin-transform-regenerator@6.26.0
├─ babel-plugin-transform-strict-mode@6.24.1
├─ babel-polyfill@6.26.0
├─ babel-preset-es2015-node@6.1.1
├─ babel-preset-fbjs@2.1.4
├─ babel-preset-react-native@2.1.0
├─ babel-register@6.26.0
├─ babel-runtime@6.26.0
├─ babel-template@6.26.0
├─ babel-traverse@6.26.0
├─ babel-types@6.26.0
├─ babylon@6.18.0
├─ balanced-match@1.0.0
├─ base64-js@1.2.1
├─ base64-url@1.2.1
├─ basic-auth-connect@1.0.0
├─ basic-auth@1.0.4
├─ batch@0.5.3
├─ bcrypt-pbkdf@1.0.1
├─ beeper@1.1.1
├─ big-integer@1.6.23
├─ block-stream@0.0.9
├─ body-parser@1.13.3
├─ boom@2.10.1
├─ bplist-creator@0.0.7
├─ bplist-parser@0.1.1
├─ brace-expansion@1.1.8
├─ braces@1.8.5
├─ bser@1.0.3
├─ builtin-modules@1.1.1
├─ bytes@2.1.0
├─ camelcase@3.0.0
├─ caseless@0.12.0
├─ center-align@0.1.3
├─ chalk@1.1.3
├─ cli-cursor@2.1.0
├─ cli-width@2.1.0
├─ cliui@3.2.0
├─ clone-stats@0.0.1
├─ clone@1.0.2
├─ co@4.6.0
├─ code-point-at@1.1.0
├─ color-convert@1.9.0
├─ color-name@1.1.3
├─ combined-stream@1.0.5
├─ commander@2.11.0
├─ compressible@2.0.11
├─ compression@1.5.2
├─ concat-map@0.0.1
├─ concat-stream@1.6.0
├─ connect-timeout@1.6.2
├─ connect@2.30.2
├─ console-control-strings@1.1.0
├─ content-type@1.0.2
├─ convert-source-map@1.5.0
├─ cookie-parser@1.3.5
├─ cookie-signature@1.0.6
├─ cookie@0.1.3
├─ core-js@2.5.0
├─ core-util-is@1.0.2
├─ crc@3.3.0
├─ create-react-class@15.6.0
├─ cross-spawn@3.0.1
├─ cryptiles@2.0.5
├─ csrf@3.0.6
├─ csurf@1.8.3
├─ dashdash@1.14.1
├─ dateformat@2.0.0
├─ debug@2.2.0
├─ decamelize@1.2.0
├─ deep-extend@0.4.2
├─ delayed-stream@1.0.0
├─ delegates@1.0.0
├─ denodeify@1.2.1
├─ depd@1.0.1
├─ destroy@1.0.4
├─ detect-indent@4.0.0
├─ dom-walk@0.1.1
├─ duplexer2@0.0.2
├─ ecc-jsbn@0.1.1
├─ ee-first@1.1.1
├─ encoding@0.1.12
├─ errno@0.1.4
├─ error-ex@1.3.1
├─ errorhandler@1.4.3
├─ escape-html@1.0.3
├─ escape-string-regexp@1.0.5
├─ esutils@2.0.2
├─ etag@1.7.0
├─ event-target-shim@1.1.1
├─ exec-sh@0.2.0
├─ expand-brackets@0.1.5
├─ expand-range@1.8.2
├─ express-session@1.11.3
├─ extend@3.0.1
├─ external-editor@2.0.4
├─ extglob@0.3.2
├─ extsprintf@1.3.0
├─ fancy-log@1.3.0
├─ fb-watchman@2.0.0
├─ fbjs-scripts@0.7.1
├─ fbjs@0.8.12
├─ figures@2.0.0
├─ filename-regex@2.0.1
├─ fill-range@2.2.3
├─ finalhandler@0.4.0
├─ find-up@1.1.2
├─ for-in@1.0.2
├─ for-own@0.1.5
├─ forever-agent@0.6.1
├─ form-data@2.2.0
├─ fresh@0.3.0
├─ fs-extra@1.0.0
├─ fs.realpath@1.0.0
├─ fsevents@1.1.2
├─ fstream-ignore@1.0.5
├─ fstream@1.0.11
├─ gauge@1.2.7
├─ get-caller-file@1.0.2
├─ getpass@0.1.7
├─ glob-base@0.3.0
├─ glob-parent@2.0.0
├─ glob@7.1.2
├─ global@4.3.2
├─ globals@9.18.0
├─ glogg@1.0.0
├─ graceful-fs@4.1.11
├─ gulp-util@3.0.8
├─ gulplog@1.0.0
├─ har-schema@1.0.5
├─ har-validator@4.2.1
├─ has-ansi@2.0.0
├─ has-flag@2.0.0
├─ has-gulplog@0.1.0
├─ has-unicode@2.0.1
├─ hawk@3.1.3
├─ hoek@2.16.3
├─ home-or-tmp@2.0.0
├─ hosted-git-info@2.5.0
├─ http-errors@1.3.1
├─ http-signature@1.1.1
├─ iconv-lite@0.4.18
├─ image-size@0.3.5
├─ imurmurhash@0.1.4
├─ inflight@1.0.6
├─ inherits@2.0.3
├─ ini@1.3.4
├─ inquirer@3.2.1
├─ invariant@2.2.2
├─ invert-kv@1.0.0
├─ is-arrayish@0.2.1
├─ is-buffer@1.1.5
├─ is-builtin-module@1.0.0
├─ is-dotfile@1.0.3
├─ is-equal-shallow@0.1.3
├─ is-extendable@0.1.1
├─ is-extglob@1.0.0
├─ is-finite@1.0.2
├─ is-fullwidth-code-point@1.0.0
├─ is-glob@2.0.1
├─ is-number@2.1.0
├─ is-posix-bracket@0.1.1
├─ is-primitive@2.0.0
├─ is-promise@2.1.0
├─ is-stream@1.1.0
├─ is-typedarray@1.0.0
├─ is-utf8@0.2.1
├─ isarray@1.0.0
├─ isexe@2.0.0
├─ isobject@2.1.0
├─ isomorphic-fetch@2.2.1
├─ isstream@0.1.2
├─ jest-docblock@20.1.0-echo.1
├─ jest-haste-map@20.1.0-alpha.3
├─ js-tokens@3.0.2
├─ jsbn@0.1.1
├─ jschardet@1.5.1
├─ jsesc@1.3.0
├─ json-schema@0.2.3
├─ json-stable-stringify@1.0.1
├─ json-stringify-safe@5.0.1
├─ json5@0.4.0
├─ jsonfile@2.4.0
├─ jsonify@0.0.0
├─ jsprim@1.4.1
├─ kind-of@3.2.2
├─ klaw@1.3.1
├─ lazy-cache@1.0.4
├─ lcid@1.0.0
├─ left-pad@1.1.3
├─ load-json-file@1.1.0
├─ lodash._basecopy@3.0.1
├─ lodash._basetostring@3.0.1
├─ lodash._basevalues@3.0.0
├─ lodash._getnative@3.9.1
├─ lodash._isiterateecall@3.0.9
├─ lodash._reescape@3.0.0
├─ lodash._reevaluate@3.0.0
├─ lodash._reinterpolate@3.0.0
├─ lodash._root@3.0.1
├─ lodash.escape@3.2.0
├─ lodash.isarguments@3.1.0
├─ lodash.isarray@3.0.4
├─ lodash.keys@3.1.2
├─ lodash.pad@4.5.1
├─ lodash.padend@4.6.1
├─ lodash.padstart@4.6.1
├─ lodash.restparam@3.6.1
├─ lodash.template@3.6.2
├─ lodash.templatesettings@3.1.1
├─ lodash@4.17.4
├─ longest@1.0.1
├─ loose-envify@1.3.1
├─ lru-cache@4.1.1
├─ makeerror@1.0.11
├─ media-typer@0.3.0
├─ merge-stream@1.0.1
├─ merge@1.2.0
├─ method-override@2.3.9
├─ methods@1.1.2
├─ metro-bundler@0.9.2
├─ micromatch@2.3.11
├─ mime-db@1.29.0
├─ mime-types@2.1.16
├─ mime@1.3.6
├─ mimic-fn@1.1.0
├─ min-document@2.19.0
├─ minimatch@3.0.4
├─ minimist@1.2.0
├─ mkdirp@0.5.1
├─ morgan@1.6.1
├─ ms@0.7.1
├─ multiparty@3.3.2
├─ multipipe@0.1.2
├─ mute-stream@0.0.7
├─ nan@2.6.2
├─ negotiator@0.5.3
├─ node-fetch@1.7.2
├─ node-int64@0.4.0
├─ node-pre-gyp@0.6.36
├─ nopt@4.0.1
├─ normalize-package-data@2.4.0
├─ normalize-path@2.1.1
├─ npmlog@2.0.4
├─ number-is-nan@1.0.1
├─ oauth-sign@0.8.2
├─ object-assign@4.1.1
├─ object.omit@2.0.1
├─ on-finished@2.3.0
├─ on-headers@1.0.1
├─ once@1.4.0
├─ onetime@2.0.1
├─ opn@3.0.3
├─ optimist@0.6.1
├─ options@0.0.6
├─ os-homedir@1.0.2
├─ os-locale@1.4.0
├─ os-tmpdir@1.0.2
├─ osenv@0.1.4
├─ parse-glob@3.0.4
├─ parse-json@2.2.0
├─ parseurl@1.3.1
├─ path-exists@2.1.0
├─ path-is-absolute@1.0.1
├─ path-type@1.1.0
├─ pause@0.1.0
├─ pegjs@0.10.0
├─ performance-now@0.2.0
├─ pify@2.3.0
├─ pinkie-promise@2.0.1
├─ pinkie@2.0.4
├─ plist@1.2.0
├─ preserve@0.2.0
├─ pretty-format@4.3.1
├─ private@0.1.7
├─ process-nextick-args@1.0.7
├─ process@0.5.2
├─ promise@7.3.1
├─ prop-types@15.5.10
├─ prr@0.0.0
├─ pseudomap@1.0.2
├─ punycode@1.4.1
├─ qs@4.0.0
├─ random-bytes@1.0.0
├─ randomatic@1.1.7
├─ range-parser@1.0.3
├─ raw-body@2.1.7
├─ rc@1.2.1
├─ react-clone-referenced-element@1.0.1
├─ react-deep-force-update@1.1.0
├─ react-devtools-core@2.3.1
├─ react-native@0.47.1
├─ react-proxy@1.1.8
├─ react-timer-mixin@0.13.3
├─ react-transform-hmr@1.0.4
├─ read-pkg-up@1.0.1
├─ read-pkg@1.1.0
├─ readable-stream@2.3.3
├─ rebound@0.0.13
├─ regenerate@1.3.2
├─ regenerator-runtime@0.9.6
├─ regenerator-transform@0.10.0
├─ regex-cache@0.4.3
├─ regexpu-core@2.0.0
├─ regjsgen@0.2.0
├─ regjsparser@0.1.5
├─ remove-trailing-separator@1.1.0
├─ repeat-element@1.1.2
├─ repeat-string@1.6.1
├─ repeating@2.0.1
├─ replace-ext@0.0.1
├─ request@2.81.0
├─ require-directory@2.1.1
├─ require-main-filename@1.0.1
├─ response-time@2.3.2
├─ restore-cursor@2.0.0
├─ right-align@0.1.3
├─ rimraf@2.6.1
├─ rndm@1.2.0
├─ run-async@2.3.0
├─ rx-lite-aggregates@4.0.8
├─ rx-lite@4.0.8
├─ safe-buffer@5.1.1
├─ sane@1.4.1
├─ sax@1.1.6
├─ semver@5.4.1
├─ send@0.13.2
├─ serve-favicon@2.3.2
├─ serve-index@1.7.3
├─ serve-static@1.10.3
├─ set-blocking@2.0.0
├─ setimmediate@1.0.5
├─ shell-quote@1.6.1
├─ signal-exit@3.0.2
├─ simple-plist@0.2.1
├─ slash@1.0.0
├─ slide@1.1.6
├─ sntp@1.0.9
├─ source-map-support@0.4.15
├─ source-map@0.5.6
├─ sparkles@1.0.0
├─ spdx-correct@1.0.2
├─ spdx-expression-parse@1.0.4
├─ spdx-license-ids@1.2.2
├─ sshpk@1.13.1
├─ stacktrace-parser@0.1.4
├─ statuses@1.3.1
├─ stream-buffers@2.2.0
├─ stream-counter@0.2.0
├─ string_decoder@1.0.3
├─ string-width@1.0.2
├─ stringstream@0.0.5
├─ strip-ansi@3.0.1
├─ strip-bom@2.0.0
├─ strip-json-comments@2.0.1
├─ supports-color@2.0.0
├─ tar-pack@3.4.0
├─ tar@2.2.1
├─ temp@0.8.3
├─ throat@3.2.0
├─ through@2.3.8
├─ through2@2.0.3
├─ time-stamp@1.1.0
├─ tmp@0.0.31
├─ tmpl@1.0.4
├─ to-fast-properties@1.0.3
├─ tough-cookie@2.3.2
├─ trim-right@1.0.1
├─ tsscmp@1.0.5
├─ tunnel-agent@0.6.0
├─ tweetnacl@0.14.5
├─ type-is@1.6.15
├─ typedarray@0.0.6
├─ ua-parser-js@0.7.14
├─ uglify-js@2.7.5
├─ uglify-to-browserify@1.0.2
├─ uid-number@0.0.6
├─ uid-safe@2.0.0
├─ ultron@1.0.2
├─ unpipe@1.0.0
├─ util-deprecate@1.0.2
├─ utils-merge@1.0.0
├─ uuid@3.0.1
├─ validate-npm-package-license@3.0.1
├─ vary@1.0.1
├─ verror@1.10.0
├─ vhost@3.0.2
├─ vinyl@0.5.3
├─ walker@1.0.7
├─ watch@0.10.0
├─ whatwg-fetch@1.1.1
├─ which-module@1.0.0
├─ which@1.3.0
├─ wide-align@1.1.2
├─ window-size@0.1.0
├─ wordwrap@1.0.0
├─ worker-farm@1.5.0
├─ wrap-ansi@2.1.0
├─ wrappy@1.0.2
├─ write-file-atomic@1.3.4
├─ ws@1.1.4
├─ xcode@0.9.3
├─ xmlbuilder@4.0.0
├─ xmldoc@0.4.0
├─ xmldom@0.1.27
├─ xpipe@1.0.5
├─ xtend@4.0.1
├─ y18n@3.2.1
├─ yallist@2.1.2
├─ yargs-parser@4.2.1
└─ yargs@6.6.0
✨  Done in 147.40s.
Setting up new React Native app in /Applications/XAMPP/xamppfiles/htdocs/github/ReactNative/demo/RNTutorialProject
Adding React...
yarn add v0.24.6
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 3 new dependencies.
├─ loose-envify@1.3.1
├─ prop-types@15.5.10
└─ react@16.0.0-alpha.12
✨  Done in 13.04s.
Adding Jest...
yarn add v0.24.6
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 109 new dependencies.
├─ abab@1.0.3
├─ acorn-globals@3.1.0
├─ acorn@4.0.13
├─ amdefine@1.0.1
├─ ansi-escapes@1.4.0
├─ ansi-regex@2.1.1
├─ ansi-styles@3.2.0
├─ append-transform@0.4.0
├─ argparse@1.0.9
├─ array-equal@1.0.0
├─ arrify@1.0.1
├─ async@2.5.0
├─ babel-core@6.26.0
├─ babel-generator@6.26.0
├─ babel-jest@20.0.3
├─ babel-plugin-istanbul@4.1.4
├─ babel-plugin-jest-hoist@20.0.3
├─ babel-plugin-syntax-dynamic-import@6.18.0
├─ babel-preset-jest@20.0.3
├─ babel-preset-react-native@3.0.0
├─ babel-template@6.26.0
├─ babel-traverse@6.26.0
├─ babel-types@6.26.0
├─ babylon@6.18.0
├─ browser-resolve@1.11.2
├─ callsites@2.0.0
├─ ci-info@1.0.0
├─ content-type-parser@1.0.1
├─ convert-source-map@1.5.0
├─ cssom@0.3.2
├─ cssstyle@0.2.37
├─ deep-is@0.1.3
├─ default-require-extensions@1.0.0
├─ diff@3.3.0
├─ escodegen@1.8.1
├─ esprima@4.0.0
├─ estraverse@1.9.3
├─ fast-levenshtein@2.0.6
├─ fileset@2.0.3
├─ glob@7.1.2
├─ growly@1.3.0
├─ handlebars@4.0.10
├─ html-encoding-sniffer@1.0.1
├─ is-ci@1.0.10
├─ istanbul-api@1.1.11
├─ istanbul-lib-coverage@1.1.1
├─ istanbul-lib-hook@1.0.7
├─ istanbul-lib-instrument@1.7.4
├─ istanbul-lib-report@1.1.1
├─ istanbul-lib-source-maps@1.2.1
├─ istanbul-reports@1.1.1
├─ jest-changed-files@20.0.3
├─ jest-cli@20.0.4
├─ jest-config@20.0.4
├─ jest-diff@20.0.3
├─ jest-environment-jsdom@20.0.3
├─ jest-environment-node@20.0.3
├─ jest-jasmine2@20.0.4
├─ jest-matcher-utils@20.0.3
├─ jest-matchers@20.0.3
├─ jest-message-util@20.0.3
├─ jest-mock@20.0.3
├─ jest-regex-util@20.0.3
├─ jest-resolve-dependencies@20.0.3
├─ jest-resolve@20.0.4
├─ jest-runtime@20.0.4
├─ jest-snapshot@20.0.3
├─ jest-util@20.0.3
├─ jest-validate@20.0.3
├─ jest@20.0.4
├─ js-yaml@3.9.1
├─ jsdom@9.12.0
├─ leven@2.1.0
├─ levn@0.3.0
├─ locate-path@2.0.0
├─ minimatch@3.0.4
├─ natural-compare@1.4.0
├─ node-notifier@5.1.2
├─ nwmatcher@1.4.1
├─ once@1.4.0
├─ optionator@0.8.2
├─ p-limit@1.1.0
├─ p-locate@2.0.0
├─ p-map@1.1.1
├─ parse5@1.5.1
├─ path-parse@1.0.5
├─ pify@2.3.0
├─ prelude-ls@1.1.2
├─ pretty-format@20.0.3
├─ react-test-renderer@16.0.0-alpha.12
├─ resolve@1.4.0
├─ shellwords@0.1.0
├─ source-map@0.5.6
├─ sprintf-js@1.0.3
├─ string-length@1.0.1
├─ symbol-tree@3.2.2
├─ test-exclude@4.1.1
├─ tough-cookie@2.3.2
├─ tr46@0.0.3
├─ type-check@0.3.2
├─ uglify-js@2.7.5
├─ webidl-conversions@4.0.2
├─ whatwg-encoding@1.0.1
├─ whatwg-url@4.8.0
├─ which@1.3.0
├─ wordwrap@1.0.0
├─ xml-name-validator@2.0.1
├─ yargs-parser@5.0.0
└─ yargs@7.1.0
✨  Done in 79.45s.
To run your app on iOS:
   cd /Applications/XAMPP/xamppfiles/htdocs/github/ReactNative/demo/RNTutorialProject
   react-native run-ios
   - or -
   Open ios/RNTutorialProject.xcodeproj in Xcode
   Hit the Run button
To run your app on Android:
   cd /Applications/XAMPP/xamppfiles/htdocs/github/ReactNative/demo/RNTutorialProject
   Have an Android emulator running (quickest way to get started), or a device connected
   react-native run-android

**Comment by chiragpurohit71085** [comment]
Hi

If anybody facing the same issue as I have mentioned, can pull working template project from

https://github.com/chiragpurohit71085/working_react_native_0.47

I was earlier also facing the issue of (both of these issues has been resolved in template project)

no such file or directory: 'folly-2016.09.26.00/folly/StringBase.cpp'
Fix Unexpected token ) in babel-preset-react-native

**Comment by Pyrolistical** [comment]
@brentvatne there's your project

**Comment by askarhu** [comment]
Did a "Clean Build Folders" on Xcode and ran into this error, that doesn't seem to go away no matter what I do. Anyone has a working solution to this issue? I was running RN 0.45.1.

**Comment by shaneosullivan** [comment]
I'm also running into this problem, and even reverting all changes in Git doesn't help, my project appears to be permanently borked now.

@brentvatne , any update on this?  It's pretty much a complete development blocker.

**Comment by shivam-ucreate** [comment]
Any workaround for this issue?

**Comment by lefoy** [comment]
Same here..

**Comment by ArvoGuo** [comment]
+1

**Comment by swarna-sathya** [comment]
+1

**Comment by Pyrolistical** [comment]
@brentvatne you should reopen this issue.

**Comment by kajm** [comment]
+1

**Comment by Pau1fitz** [comment]
+1 - any one find a solution for this?

I saw this separate thread, but none of the solutions worked for me

**Comment by Pyrolistical** [comment]
Awesome @Pau1fitz. Does this give you a hint on the root cause @brentvatne?

**Comment by lefoy** [comment]
I tried every suggestions and it's still not working for me..

**Comment by jellohouse** [comment]
Damn! same here nothing's working.
I just upgraded my react native using react-native-git-upgrade as suggested here:
https://facebook.github.io/react-native/docs/upgrading.html
I got a few errors when upgrading, but I don't know how to fix this one...

**Comment by aprilmintacpineda** [comment]
@Pau1fitz's solution worked.

**Comment by jfyles** [comment]
@Pau1fitz's solution worked for me too. How does the create-react-native-app eject tutorial gloss over that?

**Comment by ispadoto** [comment]
Just add '$(SRCROOT)/../node_modules/react-native-fcm/ios' in Header Search paths (recursive)

**Comment by garethiv** [comment]
Still receiving this error after trying all of the above.

RN v0.56.0

**Comment by rsortiz** [comment]
+1

**Comment by jamesone** [comment]
Any update for 0.56?

**Comment by ociata** [comment]
I've run `npm install` from the main directory and the issue is gone. It is very strange though, as my /node_module/react-native folder was empty before that. This is what version I use:

```

    "react": "16.4.1",
    "react-native": "0.56.0",
```

**Comment by deorukhkarchaitanya** [comment]
Same issue on 

```
"react": "16.4.1",
"react-native": "0.56.0"
```

None of the above mentioned solutions work.

**Comment by forster-thomas** [comment]
This is because the React scheme is missing from your project. You can verify this by opening the Product menu and the Scheme submenu.

To make the React scheme available to your project, run npm install -g react-native-git-upgrade followed by react-native-git-upgrade. Once this is done, you can click back to the menu in Xcode: Product -> Scheme -> Manage Schemes, then click '+' to add a new scheme. From the Target menu, select "React", and click the checkbox to make the scheme shared. This should make the error disappear.

**Comment by piotr-s-brainhub** [comment]
@ArvoGuo @swarna-sathya 
could you upvote this issue here instead of writing `+1` comments?
![screen shot 2018-10-03 at 17 39 27](https://user-images.githubusercontent.com/20856232/46421896-78475380-c733-11e8-8e1a-0fce4d68eb0b.png)
thanks to upvoting it's possible to sort issues by number of votes;
in the other hand writing a `+1` comment is a bad practice because it generates spam


btw. @Pyrolistical @Pau1fitz @kajm and all the other people who have problems with that - could you also upvote, maybe when we have more votes, somebody will fix it

**Comment by Pau1fitz** [comment]
@piotr-s-brainhub I already have upvoted this, I did so when I first came across this issue. I also provided a solution above that has helped people to resolve this issue.
