### ISSUE TITLE
Unable to create react-native-app

### ISSUE THREAD

**Issue by tigerbally** [react-community/create-react-native-app#320]
Hi,

D:\Bally\ReactNativeApp>node -v v6.11.1
D:\Bally\ReactNativeApp>npm -v 5.3.0
D:\Bally\ReactNativeApp>create-react-native-app AweApp 'create-react-native-app' is not recognized as an internal or external command, operable program or batch file.
D:\Bally\ReactNativeApp>

Everything configured properly but commands not recognized...don`t know why
unable to create react native app by Node Plz provide step by step app creation process...

**Comment by ccheever** [comment]
Did you `npm install -g create-react-native-app` ?

**Comment by therovermind** [comment]
I too got the similar problem...when i m installing terminal shows success and when i access the command "create-react-native-app" terminal says command not found
i hv node 8
npm 5.0.2
yarn 0.27

**Comment by brentvatne** [comment]
@therovermind - if you look in README you will see that npm 5 is buggy and not supported. we recommend using npm 4.6.1
