### ISSUE TITLE
[question] has anyone successfully integrated bucklescript/reason with CRNA?

### ISSUE THREAD

**Issue by awitherow** [react-community/create-react-native-app#322]
bucklescript.github.io/bucklescript/

https://github.com/reasonml-community/bs-react-native

**Comment by dikaiosune** [comment]
I think I saw tweets from @kenwheeler about doing this.

**Comment by kenwheeler** [comment]
Yup. Just create a `re` or `src` folder and run bsb against it to compile, then import and subsequently export the compiled root in `App.js`

**Comment by awitherow** [comment]
noice! 🎉  I will work on converting my application to bucklescript and maybe we could collab @kenwheeler on getting a section in the documentation about integrating bucklescript?

**Comment by brentvatne** [comment]
it would be amazing to add this to docs, very welcome

**Comment by kenwheeler** [comment]
Want me to write it up? Its easy peez.

**Comment by brentvatne** [comment]
yes pls @kenwheeler

**Comment by awitherow** [comment]
Yess pls @kenwheeler 🙇

**Comment by kenwheeler** [comment]
@brentvatne @dikaiosune under what heading/section would one add that?

**Comment by dikaiosune** [comment]
Seems like turning the [Adding Flow](https://github.com/react-community/create-react-native-app/tree/master/react-native-scripts/template#adding-flow) section into something like "Static Types" and having Flow, BuckleScript, TypeScript (to be written) sections would be reasonable. I'll defer to @brentvatne though as I'm just clearing out GitHub notifications.

**Comment by mathieudutour** [comment]
Wouldn't it be easier to create a `react-native-scripts` version for Reason? A bit like the [version for typescript](https://github.com/mathieudutour/create-react-native-app-typescript). 

Maybe we can just link to those alternative scripts in the README afterwards so that it doesn't grow out of hand ;)

**Comment by awitherow** [comment]
Would be awesome if something happened, anything would be nice at this point 👍

**Comment by kenwheeler** [comment]
Ill do it, give me til monday or so

**Comment by brentvatne** [comment]
@kenwheeler - this will be awesome, looking forward to playing with reason again to try out the syntax changes with reason3

**Comment by brentvatne** [comment]
here ya go: https://github.com/brentvatne/reason-react-native-scripts

let's move all reason / crna discussions there
