### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by dbnex14** [react-community/create-react-native-app#323]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description
Broken link 

1-2 sentences describing the problem you're having or the feature you'd like to request
Broken link in section talking about jest testing, the link is "the template project"

## Expected Behavior
Link should take you to the page

What action did you perform, and what did you expect to happen?
Clicked on "the template project" in section talking about testing and got 404 page.  Expecting to see correct page.

## Observed Behavior
404 page

What actually happened when you performed the above actions?
as explained above

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment
MacOS

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
* `npm ls react-native`:
* `npm ls expo`:
* `node -v`:
* `npm -v`:
* `yarn --version`:
* `watchman version`:

Also specify:

1. Operating system:
2. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by brentvatne** [comment]
fixed in https://github.com/react-community/create-react-native-app/commit/5322584644413c1ea4ac70bbf1629a71803b27d5
