### ISSUE TITLE
Icon android does not resize.

### ISSUE THREAD

**Issue by thiagonsilva** [react-community/create-react-native-app#330]
I'm trying to build an android application with expo, however the icon is getting a bad quality for mdpi screens, I tried using a png image 512x512 and 192x192. Apparently the expo does not resize the icon for Android, it simply places the image of the size icon provided in the mipmap_xxxx folders, different from the IOS that does the resize. I would not like to have to use detach because of the benefits it is compiling with exp. Is there a solution to this problem currently?

![appicon](https://user-images.githubusercontent.com/9751576/28634184-becf1a4a-720c-11e7-8331-0f58cb6b22b2.png)

Thank you
-------------------------------------------------------
react-native-scripts: 0.0.50
react-native: 0.45.1
expo:  18.0.3
node: 6.10.3
npm: 3.10.10
yarn: 0.27.5
watchman:  4.6.0
Operating system: MacOX 10.12.5
Phone version:  Positivo First S410
Display Type: TFT LCD
Size in inches: 4 "inches
Screen resolution: 480 x 800 pixels
Density: 233 PPI

**Comment by jesseruder** [comment]
Can you explain how you built this app? Did you click the pin button in the Expo notification to add it to your home screen?

**Comment by thiagonsilva** [comment]
I created using exp build: android. 

(Sorry. It's a standalone app. I was trying to say that it is not a detach app.)

**Comment by jesseruder** [comment]
Ok thanks for the information. We'll take a look at this.
