### ISSUE TITLE
xdl > auth0-js > xtend > object-keys and "react-redux@5.0.5" has unmet peer dependency

### ISSUE THREAD

**Issue by Pro-Ton** [react-community/create-react-native-app#332]
On a fresh installation of node v6.11.1 lts on Ubuntu 16.04 and yarn 0.27.5 I get two warnings when I create new project:

```
yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...
warning react-native-scripts > xdl > auth0-js > xtend > object-keys@0.4.0: 
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "react-redux@5.0.5" has unmet peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0".

```
But it continues the installation and after `npm start` it is stuck at `Starting packager...`

**Comment by brentvatne** [comment]
> warning "react-redux@5.0.5" has unmet peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0".


these warnings are a red herring. not having an error message here for when things do actually not work is unfortunate however. do you have watchman installed?  please follow issue template in the future ;)
