### ISSUE TITLE
Watch for EMFILE errors and provide a more useful message

### ISSUE THREAD

**Issue by fson** [react-community/create-react-native-app#334]
## Description

If the packager tries to open more files than the max number of file descriptors configured for the operating system, this cryptic error is thrown: `(FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)`.

## Expected Behavior

`react-native-scripts` should catch the error and print a more helpful error message that explains how to fix the problem (increase the number of file descriptors using `ulimit -n` or install watchman).

@brentvatne had this idea in https://github.com/react-community/create-react-native-app/issues/331#issuecomment-318275459.

## Observed Behavior

See: #331, https://github.com/facebook/react-native/issues/10028.

**Comment by brentvatne** [comment]
we do this now
