### ISSUE TITLE
No QR code is generated when doing npm start.....i m on ubuntu with npm3 and node6 

### ISSUE THREAD

**Issue by therovermind** [react-community/create-react-native-app#335]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description
i created a fresh project using the command create-react-native-app...
then after the execution i did npm start ,after this process got stop(with curson blinking on running packager) and QR code is generated

1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior
i expect a QR code so as  to run on my device

What action did you perform, and what did you expect to happen?

## Observed Behavior
no files related toandroid  generated(index.android.js)..nor for ios

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
* `npm ls react-native`:
* `npm ls expo`:
* `node -v`:6.11.1
* `npm -v`:3.10.10
* `yarn --version`:
* `watchman version`:

Also specify:

1. Operating system:ubuntu
2. Phone/emulator/simulator & version:

## Reproducible Demo
https://drive.google.com/open?id=0B0514LVH5u7lUDNRbzhWT0N5dUk
https://drive.google.com/open?id=0B0514LVH5u7lWEhsTlZMWWx0bzg

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by fson** [comment]
@therovermind Is this happening in a fresh project created with `create-react-native-app`? Could you fill in the information in the issue template (especially any error messages, if you're getting them, the environment and if possible, a reproducible demo). This would help the issue get resolved much more quickly. Thanks!

**Comment by therovermind** [comment]
@fson hey,any progress

**Comment by yacineblr** [comment]
Hello, i have same bug ... npm start has freeze at -> `Starting packager...`

**Comment by jonching** [comment]
same for me

**Comment by bganicky** [comment]
Hi, possibly related to https://github.com/react-community/create-react-native-app/issues/234. This comment was helpful for me: https://github.com/react-community/create-react-native-app/issues/234#issuecomment-313849888

**Comment by shivendrasoni** [comment]
@bganicky  Thanks a lot man. I was stuck at it for 3 days. Stupid me, should have seen this coming.

For changig file watcher limit:
https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers

**Comment by alexandre-thauvin** [comment]
Hi,

I have the same issue, no qr-code generated but the project was compiled.

![image](https://user-images.githubusercontent.com/27420929/30861888-6e99fe00-a2cc-11e7-866c-3098197b7fd5.png)

**Comment by brentvatne** [comment]
try this https://github.com/react-community/create-react-native-app/issues/234#issuecomment-313849888

**Comment by chitrajoshi** [comment]
I had the same problem, no qrcode generated while npm start command, 
The terminal itself mentioned to either install watchman or run the following commands:

 sudo sysctl -w fs.inotify.max_user_instances=1024
 sudo sysctl -w fs.inotify.max_user_watches=12288
