### ISSUE TITLE
React native error can not find entry modules error 404

### ISSUE THREAD

**Issue by MBehtemam** [react-community/create-react-native-app#337]
hi today i install `React native` and create an app with `create-react-native-app` with following instruction of [this page](https://facebook.github.io/react-native/docs/getting-started.html) and then run `npm start` but i get this error : 

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/xLWHQ.png

before it i develop android app and i think the problem is not from sdk but i cant face why this error happen , also i doesn't change source of app only create app and then run it.

**Comment by slaviczavik** [comment]
Same issue here.
![soubor_000](https://user-images.githubusercontent.com/6020945/28748024-619dae2e-74ad-11e7-8915-4f8d1654a08c.png)

**Comment by brentvatne** [comment]
can you try installing watchman? https://facebook.github.io/watchman/

**Comment by MBehtemam** [comment]
i installed watchman ? so what should i do ? which command should is use to know what happen or get out put and  paste here ?

**Comment by brentvatne** [comment]
please create an issue again if this happens and you care, nobody else seems to have encountered this issue and commented on it so it seems specific to your setup

**Comment by janajay** [comment]
Hi i am also getting the error same like the above error while running an existing app through expo
