### ISSUE TITLE
Difference between create-react-native-app and react-native-cli

### ISSUE THREAD

**Issue by liujb** [react-community/create-react-native-app#339]
`create-react-native-app` is quick and easy way to create react-native project. The `react-native-cli` have the same feature when use `react-native init Awesome`.  What's the difference.

**Comment by brentvatne** [comment]
https://facebook.github.io/react-native/docs/getting-started.html

> Create React Native App is the easiest way to start building a new React Native application. It allows you to start a project without installing or configuring any tools to build native code - no Xcode or Android Studio installation required (see Caveats).

**Comment by Airomad** [comment]
First uses Expo, second not

**Comment by Emyboy** [comment]
but i can't use any without internet connection... is there a way to do so offline ?

**Comment by captDaylight** [comment]
Ha, [this discussion](https://github.com/react-community/create-react-native-app/issues/516) had the same first response. Follow it down the thread to get a nuanced answer.
