### ISSUE TITLE
The eject code rewriting is fragile

### ISSUE THREAD

**Issue by dikaiosune** [react-community/create-react-native-app#34]
It breaks on this gist:

https://gist.github.com/anonymous/0e8ec441c797a03e5265c9fd1f53d1c6

Need to diagnose and do the AST traversal in a less fragile manner.

**Comment by dikaiosune** [comment]
I've also received feedback multiple times that the code rewriting is a less-than-ideal solution.

I think the alternative will involve doing some kind of monkey patching from a `crna-env`-like package to make sure that AppRegistry sets up the font component for us. Need to explore options here.

**Comment by ericvicenti** [comment]
Maybe we need to put the "font component" in core, or find an alternative for it? I'm using quotes because I know you do some tricky font stuff but I'm not quite sure what the component is.

**Comment by dikaiosune** [comment]
Our plan here is to stash the CRNA entry point in the `react-native-scripts` package, and then write new entry points when ejecting. I'm going to work on this today, probably.

**Comment by dikaiosune** [comment]
Resolved in 149fbd5f8152b0a8c6d99e2b5ce4866dda4974a1.
