### ISSUE TITLE
Bundle Generation Speed on Node 6 vs 7 / NPM 3 / 4

### ISSUE THREAD

**Issue by chmaltsp** [react-community/create-react-native-app#347]
## Description

After a few days of testing and building out a scaffold for an app it became painfully slow to generate the initial bundle with Node 7 and npm 4. The time to create the initial bundle was about 631000 ms, way too long and the ios simulator would actually end up timing out and give me the red screen. I downgraded to node 6.91 and npm 3 and the time went down to 13000ms which is a reasonable time. Has anyone else experienced this? Would love to use Node 8 and NPM 5 but there is an open issue about that already. 
## Expected Behavior

Expected reasonable bundle generation times. 

## Observed Behavior

Simulator timed out and crashed when using node 7.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:  1.10
* `npm ls react-native`: 0.46.4
* `npm ls expo`: 19.0.1
* `node -v`: 7.10.4
* `npm -v`: 4
* `yarn --version`: 27.5
* `watchman version`: 4.7.0

Also specify:

1. Operating system: Mac OS Sierra 10.12.5
2. Phone/emulator/simulator & version: ios iPhone 6, v 10

## Reproducible Demo

Run CRNA with Node v7 and then with v6 and npm 3 and 4.

**Comment by brentvatne** [comment]
please post this issue on https://github.com/facebook/metro-bundler -- this is the library used by react-native for packaging
