### ISSUE TITLE
Packager isn't working for my hello world

### ISSUE THREAD

**Issue by Mazuh** [react-community/create-react-native-app#349]
## Description

I'm trying to start a new app following the readme steps. But ```npm start``` is taking too long.

I never used npm before, just saying. My guess it's some dependence is missing, I even tried ```npm install -g react``` with no success (```npm start``` keeps taking too long). I'm lost here.

## Expected Behavior

Since it's the very first time I'm trying to run this, I don't really know what should be happening here.

## Observed Behavior

```sh
npm start
```

> InfoBusUFRN-App@0.1.0 start /home/mazuh/Projects/InfoBusUFRN-App
> react-native-scripts start
> 6:00:04 PM: Starting packager...
> 6:42:37 PM: Stopping packager...
> 6:42:37 PM: Packager stopped.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
InfoBusUFRN-App@0.1.0 /home/mazuh/Projects/InfoBusUFRN-App
└── react-native-scripts@1.1.0 

* `npm ls react-native`:
InfoBusUFRN-App@0.1.0 /home/mazuh/Projects/InfoBusUFRN-App
└── react-native@0.46.4 

* `npm ls expo`:
└─┬ expo@19.0.1 
  └── UNMET PEER DEPENDENCY react@>=15.3.1

npm ERR! peer dep missing: react@>=15.3.1, required by lottie-react-native@1.1.1
npm ERR! peer dep missing: react@>=15.4.0, required by react-native-branch@2.0.0-beta.3

* `node -v`:
v6.11.2

* `npm -v`:
3.10.10

* `yarn --version`:
Not installed.

* `watchman version`:
Not found.

1. Operating system: Ubuntu 17
2. Phone/emulator/simulator & version: Android 6

**Comment by brentvatne** [comment]
hello! can you try installing watchman? https://facebook.github.io/watchman/

basically just install it then try running `npm start` again

**Comment by Mazuh** [comment]
Tried ```npm install -g watchman``` and then ```npm start``` wasn't doing anything again. It keeps "starting packager".

Following Stackoverflow tips, I removed node_modules directory and tried ```npm install```. And here's what happened:

```$ npm install```
> npm WARN lottie-react-native@1.1.1 requires a peer of react@>=15.3.1 but none was installed.
> npm WARN react-native-branch@2.0.0-beta.3 requires a peer of react@>=15.4.0 but none was installed.
> up to date in 9.026s

```$ npm install react@>=15.4.0```
> npm WARN lottie-react-native@1.1.1 requires a peer of react@>=15.3.1 but none was installed.
> npm WARN react-native-branch@2.0.0-beta.3 requires a peer of react@>=15.4.0 but none was installed.

I'm really having no idea of what to do. I just want to create my "hello world".

**Comment by Mazuh** [comment]
Tried ```yarn``` too. No success either.

Since I have been the whole day trying this "quick method", I'll go for Visual Studio and/or pure react-native see if I can get better results.

**Comment by shivatalwar** [comment]
I have the exact same issue. Prop-types and createClass were deprecated on the newest version of react. I believe there are some libraries in react-native that still use these.

**Comment by Brejw15** [comment]
Hey I had the same problem and this helped me:
`echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`
`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`
`echo fs.inotify.max_queued_events=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

**Comment by Mazuh** [comment]
I indeed got better results trying the "react-native-cli" method. That said, I won't try @Brejw15 suggestion, but I still would like to know what these command lines are doing (and why).

Won't close the issue either, since it seems to be a bug.

**Comment by Mazuh** [comment]
I don't know if it's somehow related to this:

https://github.com/facebook/react-native/issues/3199

But just saying, I'm getting any errors at all. It just gets stuck at "starting packager" forever.

**Comment by limichange** [comment]
```shell
yarn run v0.18.1
$ react-native-scripts ios
06:28:44: Starting packager...
```
me too.

**Comment by baptistemanson** [comment]
I'm not an expert, but what do you see when you type:
```bash
$ DEBUG=* npm start
```
?

**Comment by limichange** [comment]
@baptistemanson 
<details>

```

$ DEBUG=* npm start

> rn-test2@0.1.0 start /Users/limichange/testCode/rn-test2
> react-native-scripts start

06:56:57: Starting packager...
  express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +5ms
  express:application set "etag fn" to [Function: wetag] +0ms
  express:application set "env" to 'development' +1ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +0ms
  express:application set "subdomain offset" to 2 +0ms
  express:application set "trust proxy" to false +1ms
  express:application set "trust proxy fn" to [Function: trustNone] +0ms
  express:application booting in development mode +0ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to '/Users/limi/testCode/rn-test2/views' +1ms
  express:application set "jsonp callback name" to 'callback' +0ms
  express:router use '/' query +17ms
  express:router:layer new '/' +0ms
  express:router use '/' expressInit +1ms
  express:router:layer new '/' +0ms
  express:router use '/' jsonParser +0ms
  express:router:layer new '/' +0ms
  express:router use '/' urlencodedParser +4ms
  express:router:layer new '/' +0ms
{ name: 'expo',
  hostname: 'limis-MacBook-Air-2.local',
  pid: 6677,
  type: 'project',
  project: '/Users/limichange/testCode/rn-test2',
  level: 40,
  tag: 'expo',
  msg: 'Warning: You are using npm version 5.3.0. There may be bugs in this version, use it at your own risk. We recommend version 4.6.1.',
  time: 2017-08-11T22:56:58.810Z,
  v: 0 }

```
</details>

**Comment by baptistemanson** [comment]
Have you tried a lower version of node (LTS version 6.x) and yarn instead of npm?
I personally use nvm to  switch the node version I use with ease, and have installed yarn with the curl command.

**Comment by limichange** [comment]
@baptistemanson Thank you so much. I have solved it. It's a network problem.
https://github.com/react-community/create-react-native-app/issues/343#issuecomment-321848066

**Comment by Mazuh** [comment]
I did tried two different networks and yarn With no success.

**Comment by baptistemanson** [comment]
Sorry! I want to cheer you up. Must be not fun.
Again I'm not an expert in Expo, just trying to help you. Hang on, there is still tons of hope for your project.
Do you see your express server starting when launching with:
```bash
$ DEBUG=* npm start
```
You can copy the trace and I'll dig in your logs.

**Comment by vs1682** [comment]
@Mazuh  you should try @Brejw15's solution. You can refer to https://github.com/react-community/create-react-native-app/issues/234.
Those command tells if the system is capable of tracking your files for any changes.
[Watchman](https://facebook.github.io/watchman/) need those commands. 
Also refer https://facebook.github.io/watchman/docs/install.html#system-specific-preparation

**Comment by limichange** [comment]
you can try this. turn off your wifi, and run it.

**Comment by dikaiosune** [comment]
@Mazuh I don't think you installed watchman correctly, `npm i -g watchman` won't get you an up to date version. Can you try installing from the https://facebook.github.io/watchman docs?
