### ISSUE TITLE
Warnings on create-react-native-app command and errors on fresh app creation

### ISSUE THREAD

**Issue by novito** [react-community/create-react-native-app#351]
## Description

I am getting warnings while running `create-react-native-app my-app` and after installation is done. 

I have installed create-react-native-app with yarn.

## Expected Behavior

I would expect on a fresh creation of an app to not get those warnings.

## Observed Behavior

What actually happened when you performed the above actions?

While creating the app `create-react-native-app Highlights` I get the following errors:

```
warning react-native-scripts > xdl > auth0-js > xtend > object-keys@0.4.0
warning "react-redux@5.0.5" has unmet peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0".
```

And after it succeeds the creation of the app, when I do `npm ls`, I get the following errors:

```
npm ERR! extraneous: websql@0.4.4 /Users/teespring10063/Code/Highlights/node_modules/websql
npm ERR! missing: websql@github:expo/node-websql#18.0.0, required by expo@19.0.1
npm ERR! peer dep missing: react@>=15.3.1, required by lottie-react-native@1.1.1
npm ERR! peer dep missing: react@>=15.4.0, required by react-native-branch@2.0.0-beta.3
```

If I run `yarn check`, I get the following errors:

```
error "qs" is wrong version: expected "6.4.0", got "6.5.0"
error "expo#lottie-react-native#react@>=15.3.1" doesn't satisfy found match of "react@16.0.0-alpha.12"
error "expo#react-native-branch#react@>=15.4.0" doesn't satisfy found match of "react@16.0.0-alpha.12"
error "express#qs" not installed
error "superagent#qs" not installed
error Found 5 errors.
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
```
react-native-scripts@1.1.0
```
* `npm ls react-native`:
```
react-native@0.46.4
```
* `npm ls expo`:
```
expo@19.0.1
```
* `node -v`:
```
v6.10.3
```
* `npm -v`:
```
5.3.0
```
* `yarn --version`:
```
0.24.5
```
* `watchman version`:
```
{
    "version": "4.7.0"
}
```
Also specify:

1. Operating system: Mac OS X Yosemite, 10.10.5
2. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Do the following:

`yarn global add create-react-native-app`
`create-react-native-app Highlights`

**Comment by brentvatne** [comment]
hello, the "errors" you see are problems with how semver works with npm. >= 15.0.0 is not satisfied by 16.0.0-alpha, and react-native depends on an alpha version of react.

the other warnings will be fixed in the next release. none of these warnings have any impact on your app.

**Comment by novito** [comment]
Thanks @brentvatne

**Comment by brentvatne** [comment]
@novito - this is a problem whether you're using react-native or create-react-native-app or any react app with an alpha or beta version of react, so it'd be good if there was some broader education rather than in this readme. or if npm would just change their behaviour around peerDependencie semver to be sane, that would be cool ;)
