### ISSUE TITLE
npm start stuck in Starting packager...

### ISSUE THREAD

**Issue by kinglywork** [react-community/create-react-native-app#352]
## Description

npm start stuck in Starting packager... without any error message.

I debugged the code of exp and xdl and I found the process hung at getting schema from https://exp.host/--/xdl-schema/19.0.0
and getting versions from 
https://exp.host/--/api/v2/versions
I send request with postman to these urls and they response very slow and fail to response mostly.

Any idea to avoid getting schema from server?
Or maybe the server should be fixed.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: 1.1.0
* `npm ls react-native`: 0.46.4
* `npm ls expo`: 19.0.1
* `node -v`: 3.11.0
* `npm -v`: 3.10.10
* `yarn --version`:  none
* `watchman version`: 4.7.0

Also specify:

1. Operating system: MacOs
2. Phone/emulator/simulator & version: IOS

**Comment by henrydf** [comment]
Also stuck in Win10.
npm ls react-native-scripts: 1.1.0
npm ls react-native: 0.46.4
npm ls expo: 19.0.1
node -v: 8.1.2
npm -v: 4.6.1
yarn --version: 0.27.5
watchman version: none

**Comment by dotamir** [comment]
And I have the same problem on Linux ! Any help?

**Comment by coderafei** [comment]
me too!

**Comment by dotamir** [comment]
I didn't have it anymore. I just reboot my system and then works.
BTW, If this way didn't work .. use [Expo](https://expo.io) tools.

**Comment by kinglywork** [comment]
maybe it has something to do with the network environment.
close
