### ISSUE TITLE
Support for AR, e.g. Apple ARKit

### ISSUE THREAD

**Issue by andythemoron** [react-community/create-react-native-app#353]
This feature request to support some form of AR utilties, cf. Apple’s ARKit, might fall outside of the current scope or be subject to the constraint that dependencies which rely on custom native code are restricted.

From my naive perspective, this seems like to be a very useful library to include, though I understand that choices have to be made, taking into considering technical issues/concerns, long-term sustainability, and how this fits in with the other existing allocations of time and effort by those doing the hard work in which AR support might be significantly less critical than other desired features.

Thank you Expo for doing all this hard work! I tried dabbling in React Native a few months ago, and found it to be a really exciting avenue for cross-platform development. I also experienced a lot of pain points around incompatibilities between different versions of different npm packages. At one point, I wanted to do a simple project using react-native-maps, and could not get it to work at all, unless I specifically downgraded both packages to versions which were demonstrated elsewhere as being in alignment.

Just a week ago or so I started playing around with create-react-native-app, and I've never had any of these difficulties. After playing around to understand flex box, and the ecosystem more generally, I jusy gave MapView a go in Expo, and it worked like a charm! Thank you for putting out this wonderful product!

**Comment by andythemoron** [comment]
Derp, of course this depends on custom native code. No more late night github requests for me.

**Comment by brentvatne** [comment]
heya! ARKit would definitely be awesome to add. you can upvote it here: https://expo.canny.io/feature-requests/p/arkit-support

we started investigating it a bit internally, it's not our highest priority right now but with enough interest it could move up

**Comment by andythemoron** [comment]
Hey Brent, thanks for sharing that link... upvoted! 👍
