### ISSUE TITLE
Missing license in main package.json

### ISSUE THREAD

**Issue by brentvatne** [react-community/create-react-native-app#354]
## Description

`yarn global add create-react-native-app` shows a warning

## Expected Behavior

Should not show a warning

## Observed Behavior

```
╭─~ yarn global add create-react-native-app
yarn global v0.27.5
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-react-native-app@1.0.0" with binaries:
      - create-react-native-app
warning No license field
Done in 2.63s.
```

## Environment

Please run these commands in the project folder and fill in their results:

* `node -v`: 8.2.1
* `npm -v`: 4.6.1
* `yarn --version`: 0.27.5

Also specify:

1. Operating system: macOS Sierra

## Reproducible Demo
Same as described above

**Comment by baptistemanson** [comment]
```bash
$ yarn global add leftpad
yarn global v0.27.5
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
```
This error seems to be related to yarn and not crna. What do you think?

Here is the related bug and bug fix in yarn: https://github.com/yarnpkg/yarn/issues/3821

**Comment by danvitoriano** [comment]
try to insert:

`{ "license" : "SEE LICENSE IN <filename>" }`

Then include a file named <filename> at the top level of the package, eg.: LICENSE 

from [here](https://stackoverflow.com/questions/31998202/all-rights-reserved-license-in-package-json) and [here](https://raw.githubusercontent.com/facebook/jest/master/LICENSE)

**Comment by dikaiosune** [comment]
I am confused -- https://github.com/react-community/create-react-native-app/blob/master/create-react-native-app/package.json#L5

Is there some subdependency that doesn't include a license? Does yarn show where the warning is generated in verbose mode?

**Comment by brentvatne** [comment]
yeah, sounds right @baptistemanson

**Comment by YasinYA** [comment]
At some point, you run `yarn add` command in your home directory, so check your home(`~/`) and remove the  `package.json` and `yarn.lock` files.
