### ISSUE TITLE
integrity checksum failed while creating AwesomeProject

### ISSUE THREAD

**Issue by daku** [react-community/create-react-native-app#356]
## Description

```
[daku@dakudell playground]$ create-react-native-app AwesomeProject
Creating a new React Native app in /home/daku/Development/playground/AwesomeProject.

Using package manager as npm with npm interface.
Installing packages. This might take a couple minutes.
Installing react-native-scripts...

npm WARN react-redux@5.0.6 requires a peer of react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0 but none was installed.

npm ERR! code EINTEGRITY
npm ERR! sha1-VpwFCRi+ZIazg3VSAorgRmtxcIY= integrity checksum failed when using sha1: wanted sha1-VpwFCRi+ZIazg3VSAorgRmtxcIY= but got sha1-kCrBab3IKS6lEN/qOtED1z4c+z4=. (48628 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daku/.npm/_logs/2017-08-09T22_43_27_438Z-debug.log
`npm install --save-dev --save-exact react-native-scripts` failed
[daku@dakudell playground]$ ^C
[daku@dakudell playground]$ 
```
## Expected Behavior

AwesomeProject is created without errors

## Observed Behavior

AwesomeProject folder created, but with failures

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
```
/home/daku/Development/playground
└── (empty)
```
* `npm ls react-native`:
same
* `npm ls expo`:
same
* `node -v`:
v8.2.1
* `npm -v`:
5.3.0
* `yarn --version`:
`bash: yarn: command not found`
* `watchman version`:
same (command not found)

Also specify:

1. Operating system:
Linux dakudell 4.12.4-1-ARCH #1 SMP PREEMPT Fri Jul 28 18:54:18 UTC 2017 x86_64 GNU/Linux

2. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by olucurious** [comment]
@daku I also encountered the same issue and noticed it only works with the current LTS version of nodejs, which is v6.11.2.

So, uninstall node and reinstall the LTS version before trying to the create-react-native-app command

**Comment by shine1594** [comment]
I have same problem.. plz help

**Comment by baptistemanson** [comment]
Can you share your npm logs?
/home/daku/.npm/_logs/2017-08-09T22_43_27_438Z-debug.log

**Comment by kpachar** [comment]
I'm seeing the same issue today. Attached logs:

[2017-08-15T09_14_05_603Z-debug.log.txt](https://github.com/react-community/create-react-native-app/files/1224616/2017-08-15T09_14_05_603Z-debug.log.txt)

**Comment by raghavgoel1994** [comment]
I am also facing we same problem while creating angular app using node

**Comment by kpachar** [comment]
I got around the problem by installing react, react-redux, and react-native-scripts manually and then running the same command (create-react-native-app)
`npm install -g react`
`npm install -g react-redux`
`npm install -g react-native-scripts`
After I did that, it errored out saying that I have npm 5 but it needs npm 4.
So I downgraded npm to the last of the version 4
`sudo npm install -g npm@4.6.1`

p.s. After all this, it took a really long time to run the create-react-native-app but running it with --verbose option helped speed it up and it succeeded.

**Comment by crazyabdul** [comment]
@kpachar Thanks so much for the steps. I had the same issue today after a whole year of react abstinence due to monumental challenges I faced with every step. Mine happened with the `create-react-app` command; and when I followed your steps I wasn't prompted to downgrade to npm v4

Frankly, If this hadn't worked, it would've been the last time I was trying react.

**Comment by baptistemanson** [comment]
I'm glad it helped you moving forward.
I would advice to give up on npm 5 altogether and downgrade to npm 4 or even switch to yarn. Installing react, react-redux globally will cause you other conflicts later when you will want to upgrade, or start another project.
If you are in a hurry, you can just try:
```bash
yarn create react-native-app test-rn
```

**Comment by onuar** [comment]
@kpachar How did you manage to downgrade npm using npm 5? The same bug occurred when I've tried it :) I mean, npm 5.3.0 is buggy one. So, I can't use it to install any package. Even, for itself.

**Comment by baptistemanson** [comment]
@onuar Just switch to yarn then! It is usually easy. Yarn is faster for me. https://yarnpkg.com/lang/en/docs/install/

**Comment by onuar** [comment]
@baptistemanson yesterday, I struggled to downgrade to npm 4 for about five hours and got nothing. And after this, I started to struggle to installing yarn because of the icu4c package. But I feel it, I'm about to achive it today.

**Comment by hongDevCode** [comment]
this fixed my issue of the exit code error #127:
https://stackoverflow.com/questions/40546231/sh-react-scripts-command-not-found-after-running-npm-start

**Comment by baptistemanson** [comment]
@onuar sorry to read you have difficulties. I never heard of the icu4c package, you may find more help on the yarn github. https://github.com/yarnpkg/yarn

**Comment by ShubhamKGupta** [comment]
I am facing the same issue. Please help me out and let me know the best possible solution.

**Comment by dikaiosune** [comment]
Hi everyone! Unfortunately this is almost always a problem with your network connection or with npm/yarn, and there's not a lot we can do. In the future we hope to reduce the size of the package download for CRNA, which will make it less likely to suffer failed downloads, but there's not a lot for us to do other than that.
