### ISSUE TITLE
Error running CLI, Error installing @expo%2fbunyan: User not found

### ISSUE THREAD

**Issue by ericmasiello** [react-community/create-react-native-app#359]
## Description

I am unable to run `create-react-native-app AppName`. Whenever I do so, I see the following output:

```
[ Sites ] ericmasiello 🐼  create-react-native-app AppName
Creating a new React Native app in /Users/ericmasiello/Sites/AppName.

Using package manager as yarnpkg with yarn interface.
Installing packages. This might take a couple minutes.
Installing react-native-scripts...

yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@expo%2fbunyan: User not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/ericmasiello/Sites/AppName/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
`yarnpkg add --dev --exact --ignore-optional react-native-scripts` failed
```

## Expected Behavior

1. First ran `npm install -g create-react-native-app` (installed without error or warning)
2. Then ran `create-react-native-app AppName`
3. Expected to be able to then continue with the instructions explained here https://facebook.github.io/react-native/docs/getting-started.html

## Observed Behavior

After running `Then ran `create-react-native-app AppName` I saw the following output:
```
yarn add v0.17.10
info No lockfile found.
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@expo%2fbunyan: User not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/ericmasiello/Sites/AppName/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
`yarnpkg add --dev --exact --ignore-optional react-native-scripts` failed
```

Also, by running `cat yarn-error.log` I see the following output:

```
Arguments:
  /Users/ericmasiello/.nvm/versions/node/v8.1.4/bin/node /usr/local/Cellar/yarn/0.27.5_1/libexec/bin/yarn.js add --dev --exact --ignore-optional react-native-scripts

PATH:
  /Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/ericmasiello/.nvm/versions/node/v8.1.4/bin:~/Library/Android/sdk/tools:~/Library/Android/sdk/platform-tools:~/Development/mongodb-osx-x86_64-3.2.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:~/Library/Python/3.6/bin

Yarn version:
  0.27.5

Node version:
  8.1.4

Platform:
  darwin x64

npm manifest:
  {
    "name": "AppName",
    "version": "0.1.0",
    "private": true
  }

yarn manifest:
  No manifest

Lockfile:
  No lockfile

Trace:
  Error: https://registry.yarnpkg.com/@expo%2fbunyan: User not found
      at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/0.27.5_1/libexec/lib/yarn-cli.js:58200:18)
      at Request.self.callback (/usr/local/Cellar/yarn/0.27.5_1/libexec/lib/yarn-cli.js:114242:22)
      at emitTwo (events.js:125:13)
      at Request.emit (events.js:213:7)
      at Request.<anonymous> (/usr/local/Cellar/yarn/0.27.5_1/libexec/lib/yarn-cli.js:115225:10)
      at emitOne (events.js:115:13)
      at Request.emit (events.js:210:7)
      at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/0.27.5_1/libexec/lib/yarn-cli.js:115145:12)
      at Object.onceWrapper (events.js:314:30)
      at emitNone (events.js:110:20)
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:

AppName@0.1.0 /Users/ericmasiello/Sites/AppName
└── (empty)

* `npm ls react-native`:

AppName@0.1.0 /Users/ericmasiello/Sites/AppName
└── (empty)

* `npm ls expo`:

AppName@0.1.0 /Users/ericmasiello/Sites/AppName
└── (empty)

* `node -v`: v8.1.4
* `npm -v`: 5.3.0
* `yarn --version`: 0.27.5
* `watchman version`:

{
    "version": "4.7.0"
}

Also specify:

1. Operating system: macOS Siera version 10.12.6
2. Phone/emulator/simulator & version: N/A

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by ericmasiello** [comment]
Anyone have any suggestions?

**Comment by brentvatne** [comment]
strange, this looks like a bug with yarn, perhaps transient. works on my machine:

```
╭─~/coding/testing/test-install-bunyan yarn add @expo/bunyan
yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 18 new dependencies.
├─ @expo/bunyan@1.8.10
├─ balanced-match@1.0.0
├─ brace-expansion@1.1.8
├─ concat-map@0.0.1
├─ glob@6.0.4
├─ inflight@1.0.6
├─ inherits@2.0.3
├─ minimatch@3.0.4
├─ minimist@0.0.8
├─ mkdirp@0.5.1
├─ moment@2.18.1
├─ mv@2.1.1
├─ ncp@2.0.0
├─ once@1.4.0
├─ path-is-absolute@1.0.1
├─ rimraf@2.4.5
├─ safe-json-stringify@1.0.4
└─ wrappy@1.0.2
Done in 2.36s.
```

can you try creating a new empty project and running `mkdir whatever && cd whatever && yarn init` then installing `@expo/bunyan`?

**Comment by ericmasiello** [comment]
@brentvatne thanks for the response. Same problem:

```
[ whatever ] ericmasiello 🐼  yarn add @expo/bunyan
yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@expo%2fbunyan: User not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/ericmasiello/Sites/__throw-away__/whatever/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
[ whatever ] ericmasiello 🐼
```

**Comment by btaller** [comment]
I am getting a similar error.  Cannot install @expo/bunyan at all.  npm update does nothing,

$/npm install @expo/bunyan

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@expo/bunyan"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2

npm ERR! Invalid name: "@expo/bunyan"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Code/node/npm-debug.log

npm-debug.log says @expo doesnt exist:

9 silly mapToRegistry name @expo/bunyan
10 silly mapToRegistry scope (from package name) @expo
11 verbose mapToRegistry no registry URL found in name for scope @expo
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry data Result {
14 silly mapToRegistry   raw: '@expo/bunyan',
14 silly mapToRegistry   scope: '@expo',
14 silly mapToRegistry   escapedName: '@expo%2fbunyan',
14 silly mapToRegistry   name: '@expo/bunyan',
14 silly mapToRegistry   rawSpec: '',
14 silly mapToRegistry   spec: 'latest',
14 silly mapToRegistry   type: 'tag' }
15 silly mapToRegistry uri https://registry.npmjs.org/@expo%2fbunyan
16 verbose request uri https://registry.npmjs.org/@expo%2fbunyan
17 verbose request no auth needed
18 info attempt registry request try #1 at 4:05:30 PM
19 verbose request id c1bf9e100b2ef665
20 verbose etag W/"599f7325-f04a"
21 verbose lastModified Fri, 25 Aug 2017 00:45:25 GMT

**Comment by ericmasiello** [comment]
Yeah the problem still exists on my end

**Comment by brentvatne** [comment]
maybe this is related? https://github.com/yarnpkg/yarn/issues/1394

**Comment by ericmasiello** [comment]
@brentvatne yup. Its a yarn issue. Thanks!
