### ISSUE TITLE
Build apk could not run it.

### ISSUE THREAD

**Issue by syssam** [react-community/create-react-native-app#360]
1. create-react-native-app testapp
2. npm run eject
3. follow https://facebook.github.io/react-native/docs/signed-apk-android.html build apk, but it say stopeed and closed when I run it.

I'm using react-native init, it is working.
What's wrong for me?

**Comment by tcdavis** [comment]
Can you send us log messages from when you attempted to run it?

**Comment by syssam** [comment]
Sorry.I could not send the log message to you.
You could no try this problem?
