### ISSUE TITLE
iOS Simulator won't open

### ISSUE THREAD

**Issue by corysimmons** [react-community/create-react-native-app#362]
iOS Simulator works in XCode, but doesn't work with create-react-native-app.

## Observed Behavior

```
Starting iOS...
Error: Command failed: osascript -e tell app "System Events" to count processes whose name is "Simulator"
28:69: execution error: System Events got an error: AppleEvent timed out. (-1712)


 › Press a to open Android device or emulator, or i to open iOS emulator.
 › Press q to display QR code.
 › Press r to restart packager, or R to restart packager and clear cache.
 › Press d to toggle development mode. (current mode: development)
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: 1.1.0
* `npm ls react-native`: 0.46.4
* `npm ls expo`: 19.0.1
* `node -v`: v8.2.1
* `npm -v`: 4.6.1
* `yarn --version`: 0.21.3
* `watchman version`: 4.7.0

Also specify:

1. Operating system: macOS 10.12.6
2. Phone/emulator/simulator & version: iOS Simulator

**Comment by tcdavis** [comment]
What happens if you run `osascript -e 'tell app "System Events" to count processes whose name is "Simulator"'` ?
