### ISSUE TITLE
How to import Icons from expo?

### ISSUE THREAD

**Issue by DaniyarJakupov** [react-community/create-react-native-app#365]
## Description

I'm trying to access a set of icons provided by [expo](https://docs.expo.io/versions/latest/guides/icons.html).
I looked into expo folder inside node_modules and as far as I can tell it is there:
`Icon.js`
```
import Icon from '@expo/vector-icons';
export default Icon;
```

So I tried to pull it out like this:
```
import Icon from 'expo';
const Sticker = () => {
  return (
    <View>
      <Icon name="md-checkmark-circle" size={32} color="green" />
    </View>
  );
};
```

Here is what I'm getting:

<img width="274" alt="screen shot 2017-08-15 at 14 32 40" src="https://user-images.githubusercontent.com/17025967/29316072-b6404722-81c6-11e7-91c7-49c5e08a7a6d.png">

## Environment

* `react-native-scripts@1.1.0`:
* `react-native@0.46.1`:
* `expo@19.0.0`:
* `node@8.1.3`:

By looking at the error, I know that I'm importing it incorrectly. But I don't know how to do it right

**Comment by danbydesign** [comment]
Try destructuring your import
```
import { Ionicons } from '@expo/vector-icons';
...
<Ionicons name="ios-search" ... />
```

**Comment by DaniyarJakupov** [comment]
This line here is incorrect:
`import { Ionicons } from '@expo/vector-icons';` 

We cannot import from `'@expo/vector-icons'` only from `expo`. With destructuring it looks like that:
`import { Icon } from 'expo';`
And it's not working

**Comment by ps06756** [comment]
Hi, were you able to find a solution to this problem?

**Comment by pashute** [comment]
My problem is ReferenceError: Can't find variable: FontAwsome.

My code was `<FontAwsome name='home' size={25} />`

and then I saw it was a spelling mistake. Should be **FontAwesome** with an e ...
