### ISSUE TITLE
Update flow/.flowconfig with version 0.53.0

### ISSUE THREAD

**Issue by Palisand** [react-community/create-react-native-app#366]
This isn't really an issue, it's more of a reminder to update to the latest version of flow (if possible) once expo SDK 20/21 is ready for release. Version 0.53.0 takes care of the [long-standing issue](https://github.com/facebook/flow/issues/1964) of typing react children.

**Comment by Palisand** [comment]
Closing since #109 suggests the _".flowconfig"_ template will be removed.

**Comment by wcandillon** [comment]
@Palisand I'm struggling to upgrade my project created with create-react-native-app to flow 0.53.0. I used `flow-upgrade` but I'm getting a lot of errors to the react-native-side (I'm using 0.50.1): https://gist.github.com/wcandillon/c12095d424817bc549d737f881af09e9.

Any tips would be appreciated.

**Comment by Palisand** [comment]
From the looks of your flow log, I would say the errors you are experiencing are to be expected.

For metro-bundler errors, I can't suggest much other than suppressing those errors. You shouldn't need to worry about flow issues coming from third-party modules (i.e. from `node_modules`). In fact, there has been a lengthy conversation on the matter in [this issue](https://github.com/facebook/flow/issues/869). It appears that updating to 0.57 is one solution. [One of my comments](https://github.com/facebook/flow/issues/869#issuecomment-336167413) on that issue includes 3 options for suppressing module errors.

The amount of flow errors originating from react-navigation depend on the version you are using. Please see [this issue comment](https://github.com/react-community/react-navigation/issues/2658#issuecomment-337311086). I have not updated past 1.0.0-beta13, so I have not yet confirmed if any flow >= 0.53 errors are reported with the latest version(s) of the library.

**Comment by wcandillon** [comment]
@Palisand Thank you so much for your answer. This is extremely helpful. I was really wondering about the status quo on that. Very informative. You've made my day 🤗. How could I find out where I won't need to use your package anymore for error suppressing? Is there a particular github issue I could track?

**Comment by Palisand** [comment]
@wcandillon I suggest subscribing to the ["add silence support" PR](https://github.com/facebook/flow/pull/4916).
