### ISSUE TITLE
No QR code shown with run "npm start"

### ISSUE THREAD

**Issue by bbirtle** [react-community/create-react-native-app#368]
## Description

No QR code is shown in the terminal when running "npm start"

```
npm install -g create-react-native-app
create-react-app driver
cd driver
npm start
```

This shows the following:

```
Compiled successfully!

You can now view driver in the browser.

  Local:            http://localhost:3000/
  On Your Network:  http://192.168.1.108:3000/

Note that the development build is not optimized.
To create a production build, use npm run build.
```

Notice there is no QR code...

## Environment

* `npm ls react-native-scripts`:
* `npm ls react-native`:
* `npm ls expo`:

All three return:

driver@0.1.0 /Users/...../driver
└── (empty)

npm ERR! code 1

* `node -v`:

v6.11.0

* `npm -v`:

3.10.10

* `yarn --version`:

-bash: yarn: command not found

* `watchman version`:

-bash: watchman: command not found

1. Operating system:

macOS Sierra
10.12.6

2. Phone/emulator/simulator & version:

Not got to that point yet without a QR code!

**Comment by maxisawesome** [comment]
I got this when my phone wasn't connected to the same wifi as mine. Ubunutu and android though

**Comment by denistsoi** [comment]
`npm run ios` - or press `i` after `npm start`

**Comment by brunoandradebr** [comment]
It's a vs code bug, if you start your project npm start with cmd or powershell it works.

**Comment by bbirtle** [comment]
I'm already running from the OSX Terminal prompt, not from VS Code.

*Brian Birtle . Alp Systems . support@alpsystems.com
<support@alpsystems.com>*
*France: 07 56 79 50 99 . USA: (347) 580-5835This message contains
confidential information and is intended only for the recipients
specifically included. Disclosing, copying, distributing or forwarding this
email without prior written consent from Alp Systems is a violation of your
Alp Systems terms and conditions, if one is in effect for your company.*

**Comment by thelaith** [comment]
I have this issue as well, mine just straight up doesn't display the code - no clue why, 

This is what my package.json looks like:

`{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "1.8.1",
    "jest-expo": "23.0.0",
    "react-test-renderer": "16.0.0"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^23.0.4",
    "react": "16.0.0",
    "react-native": "0.50.3"
  }
}`

Here's how it looks https://i.imgur.com/gdVnO6G.png

**Comment by bbirtle** [comment]
I ended up solving this issue. It involved working through a variety of dependancies - like installing watchman for macOS, upgrading node versions, etc. They have since added more helpful info to their Getting Started page.

Of course better output of helpful errors would be lovely but in my case it was really just carefully studying dependancies and Googling around common issues.

**Comment by znwhite** [comment]
I solved this for me by deleting `package-lock.json` and `node_modules` and running `npm install` again.

**Comment by ilikebuttons** [comment]
> What solved this for me was deleting `package-lock.json` and `node_modules`, closing out of all expo tabs, running `npm install` again, and then `npm start` again.

This worked for me as well. It seems to disappear on me when I do `npm install <package>`.

**Comment by 0o10** [comment]
Thank you this was very helpful. I have been struggling with this for a while now. 
It was working fine until I installed a new package as @ilikebuttons said. Deleting all modules and reinstalling works great. Thank you for saving me so much time. 👍

**Comment by Nangiro** [comment]
> What solved this for me was deleting `package-lock.json` and `node_modules`, closing out of all expo tabs, running `npm install` again, and then `npm start` again.

Just this way makes ir work again. Thx a lot
