### ISSUE TITLE
using yarn i got ' Warning: You are using npm version 5.3.0.. We recommend version 4.6.1.

### ISSUE THREAD

**Issue by webmobiles** [react-community/create-react-native-app#375]
I've just installed  last version node and npm on my new ubuntu machine, and i've installed yarn because i hear the are problems with npm new versions,

## Description
$ yarn global add create-react-native-app
$  create-react-native-app myapp
$ cd myapp
$ yarn start

## Expected Behavior

if i use yarn why tell me i'm using node, how to solve this? i must to install a node and npm old versions? or just new node with old npm version?

```
 Warning: You are using npm version 5.3.0. There may be bugs in this version, use it at your own risk. We recommend version 4.6.1.
```
Why the warning don't suggest me what version of node must to install in order to get npm version 4.6.1 ?  or i can use 4 ? or just 4.6  ? It would be clearer about the version?  create-react-native-app just work with 4.6.1 npm version? what about yarn ? i'm not using npm , but i know yarn use npm...

I'm have donwgraded to npm 4.6.1 and uninstalled globally yarn package create-react-native-app: 
` yarn global remove  create-react-native-app
npm -g install create-react-native-app
create-react-native-app pelemobil

`

i'm not using more yarn, but npm;

 why when i create the project i see yarn  and not npm messages:

```
create-react-native-app myapp
Creating a new React Native app in /...

Using package manager as yarnpkg with yarn interface.
Installing packages. This might take a couple minutes.
Installing react-native-scripts...

yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...

```
and finally yarn commands:  

very different from official page that works with npm:
https://facebook.github.io/react-native/docs/getting-started.html

```
Success! Created ...
Inside that directory, you can run several commands:

  yarn start
    Starts the development server so you can open your app in the Expo
    app on your phone.

  yarn run ios
    (Mac only, requires Xcode)
    Starts the development server and loads your app in an iOS simulator.

  yarn run android
    (Requires Android build tools)
    Starts the development server and loads your app on a connected Android
    device or emulator.

  yarn test
    Starts the test runner.

  yarn run eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd myapp
  yarn start
```

## Environment

$ node -v
v8.3.0
$ npm -v
5.3.0
$ yarn -v
yarn install v0.27.5

Also specify:

1. Operating system: Ubuntu 17

**Comment by dmnd** [comment]
I also get this error when using Yarn. There's some related discussion i #277 that you might be interested in.

**Comment by webmobiles** [comment]
there are a lot of bugs on npm5 that will take months complet:

the solution is do a dowgrade to last npm 4:

$ npm install -g npm@4.6.1
