### ISSUE TITLE
Connect via "usb"

### ISSUE THREAD

**Issue by doublex** [react-community/create-react-native-app#376]
Is there an option to use "create-react-native-app" via USB?

If I run "expo xde" the url looks like:
`exp://ha-vwz.doublex.testing.exp.direct:80`

If I start "create-react-native-app" the url is:
`exp://192.168.1.104:19000`

It would take a lot of work to re-configure our network.
Could I configure "create-react-native-app" via USB?

**Comment by jalal246** [comment]
@doublex  Did you find any solution to connect via USB?

**Comment by thesogafoi** [comment]
https://facebook.github.io/react-native/docs/running-on-device.html
