### ISSUE TITLE
[Question] How to include react-native-sqlite-storage to my project?

### ISSUE THREAD

**Issue by 6pm** [react-community/create-react-native-app#378]
I have installed a clean app by create-react-native-app and I want to attach SQLite database for Android. I want to use this plugin [react-native-sqlite-storage](https://github.com/andpor/react-native-sqlite-storage)
By instruction, I must add some code into file './android/settings.gradle'. But this file doesn't exist.
What can I do it?

**Comment by shu-90** [comment]
same problem for me (I am new in react-native) 
I think you can´t use create-react-native-app out of the box with this plugin. 
So use "react-native init" to create your programm 
or run "npm run eject" in your "Create-react-native-app" 
But you will need Xcode and/or Android Studio afterwards

For more information see the link below or at the getting startet page of react-native
https://facebook.github.io/react-native/blog/2017/03/13/introducing-create-react-native-app.html

**Comment by dikaiosune** [comment]
@6pm you can use the Expo [SQLite API](https://docs.expo.io/versions/latest/sdk/sqlite.html) without ejecting, and if you want `react-native-sqlite-storage` you'll have to eject or use `react-native init`, as @shu-90 said. Thanks!
