### ISSUE TITLE
Can't create app. Getting 500 error on yesno yarn pkg

### ISSUE THREAD

**Issue by lotekmedia** [react-community/create-react-native-app#379]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

Attempting to run create-react-native-app my-app and fails.

## Expected Behavior
Successfully creates new react-native app

## Observed Behavior
Installing dependencies using yarn...

yarn install v0.23.4
[1/4] Resolving packages...
warning react-native > connect@2.30.2: connect 2.x series is deprecated
[2/4] Fetching packages...
error An unexpected error occurred: "https://codeload.github.com/expo/node-websql/tar.gz/e364fa65146a9e2157a19e5c719e7702c2b6b87a: Request failed \"500 Internal Server Error\"".
info If you think this is a bug, please open a bug report with the information provided in "c:\\Users\\jmmann\\Projects\\my-app\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
`yarnpkg ` failed

Arguments: 
  C:\Program Files\nodejs\node.exe C:\Users\jmmann\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js

PATH: 
  C:\Program Files (x86)\MSBuild\14.0\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Docker\Docker\Resources\bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files\dotnet\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\nodejs\;C:\Program Files\PuTTY\;C:\Program Files (x86)\Microsoft VS Code\bin\;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\7-Zip;C:\Program Files\Git\cmd;C:\hugo;c:\Go\bin;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Ruby24-x64\bin;C:\Users\jmmann\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\jmmann\AppData\Local\Programs\Python\Python36-32\;C:\Users\jmmann\AppData\Local\Microsoft\WindowsApps;C:\Users\jmmann\AppData\Roaming\npm;C:\Program Files\Heroku\bin

Yarn version: 
  0.23.4

Node version: 
  6.10.2

Platform: 
  win32 x64

npm manifest: 
  {
    "name": "my-app",
    "version": "0.1.0",
    "private": true,
    "devDependencies": {
      "react-native-scripts": "1.2.1",
      "jest-expo": "~20.0.0",
      "react-test-renderer": "16.0.0-alpha.12"
    },
    "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
    "scripts": {
      "start": "react-native-scripts start",
      "eject": "react-native-scripts eject",
      "android": "react-native-scripts android",
      "ios": "react-native-scripts ios",
      "test": "node node_modules/jest/bin/jest.js --watch"
    },
    "jest": {
      "preset": "jest-expo"
    },
    "dependencies": {
      "expo": "^20.0.0",
      "react": "16.0.0-alpha.12",
      "react-native": "^0.47.0"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1
  

```
  yesno@^0.0.1:
    version "0.0.1"
    resolved "https://registry.yarnpkg.com/yesno/-/yesno-0.0.1.tgz#ffbc04ff3d6f99dad24f7463134e9b92ae41bef6"

Trace: 
  Error: https://codeload.github.com/expo/node-websql/tar.gz/e364fa65146a9e2157a19e5c719e7702c2b6b87a: Request failed "500 Internal Server Error"
      at Request.handleRequestError (C:\Users\jmmann\AppData\Roaming\npm\node_modules\yarn\lib\fetchers\tarball-fetcher.js:205:20)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at Request.onRequestResponse (C:\Users\jmmann\AppData\Roaming\npm\node_modules\yarn\node_modules\request\request.js:1074:10)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:188:7)
      at HTTPParser.parserOnIncomingClient (_http_client.js:473:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
      at TLSSocket.socketOnData (_http_client.js:362:20)
      at emitOne (events.js:96:13)
      at TLSSocket.emit (events.js:188:7)

```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: c:\Users\jmmann\Projects
`-- (empty)
* `npm ls react-native`:c:\Users\jmmann\Projects
`-- (empty)
* `npm ls expo`:c:\Users\jmmann\Projects
`-- (empty)
* `node -v`: v6.10.2
* `npm -v`: 5.3.0
* `yarn --version`:  0.23.4
* `watchman version`: Not installed

Also specify:

1. Operating system: Windows 10
2. Phone/emulator/simulator & version: N/A (can't even get app to get created)

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

From cmd (run as administrator)
create-react-native-app my-app 

attached log file.

[yarn-error.log.txt](https://github.com/react-community/create-react-native-app/files/1245568/yarn-error.log.txt)
error listed above occurred.

**Comment by denistsoi** [comment]
try `npm 5.2.0`

**Comment by dikaiosune** [comment]
Hi! It looks like this was a temporary issue due to downtime at GitHub -- can you try again? Report back if you're still having issues and I'll reopen. Sorry for the delay.
