### ISSUE TITLE
How to create splash screen ?

### ISSUE THREAD

**Issue by vivekebics** [react-community/create-react-native-app#380]
I have seen few samples they have added few lines in native code. Since I don't find any native code. How can I achieve it in create-react-native-app ?

**Comment by mathieudutour** [comment]
have a look here: https://docs.expo.io/versions/latest/guides/configuration.html#loading

**Comment by dikaiosune** [comment]
Hi! As indicated in the docs, adding native code is only possible if you eject from CRNA or use `react-native init`. Thanks!

**Comment by brentvatne** [comment]
also @mathieudutour is correct that you can use that loading api. we are also currently working on an improve api for splash screens, which will land in sdk22, so check out our release notes at blog.expo.io for that in the next couple of weeks
