### ISSUE TITLE
How to Specify the iOS Simulator, such as iPhone6, iPhone6 Plus

### ISSUE THREAD

**Issue by wenbobao** [react-community/create-react-native-app#383]
if there is a way to specify the iOS Simulator, but not the recent open simulator ? 
Thanks.

**Comment by brentvatne** [comment]
there is not, but you can select it once you're in the simulator like this:

![](http://url.brentvatne.ca/w6wuN4.png)

**Comment by wenbobao** [comment]
OK,Thanks
