### ISSUE TITLE
expo doesn't load app

### ISSUE THREAD

**Issue by ramusbucket** [react-community/create-react-native-app#386]
App does not load in expo (android - Xiomi MI Max phone)

## Description
Followed the process described in Readme. I can see QR code, scanned it in expo app. I just see a spinner and application does not load home screen

## Expected Behavior

It should load application home screen

## Observed Behavior

I see spinner but nothing else.

No errors in the terminal. I see "Finished building JavaScript bundle in 3085ms"

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:1.3.0
* `npm ls react-native`:0.47.2
* `npm ls expo`:
* `node -v`:v6.10.1
* `npm -v`:3.10.10
* `yarn --version`: not installed
* `watchman version`: not installed

Also specify:

1. Operating system: Windows 10 Pro
2. Phone/emulator/simulator & version: Android 7.0 - Xiomi MI Max

**Comment by aurelienbr** [comment]
I am currently facing the same problem, did you fixed it ?

**Comment by mposada** [comment]
Same situation here

**Comment by FrankCharlz** [comment]
Same here

**Comment by vvmann** [comment]
I'm having the same problem.

**Comment by kburton** [comment]
It may not help many people, but shutting down and restarting the Expo app fixed this for me.

**Comment by dikaiosune** [comment]
Hi! Can you try again on a newer version of CRNA & Expo? If it still hangs after the `Downloading JavaScript Bundle...` phase, then please report back and we'll reopen this issue.

**Comment by this-miguel** [comment]
I'm having this same issue but just in the phone, in the emulator the app works fine. Im devoloping in ubuntu 17.10, my phone is a moto e 2d generation. Do you have any news? Did you all solved the problem?

**Comment by ramusbucket** [comment]
Please try changing the [metrics (priority) of networks](https://www.ghacks.net/2016/12/02/change-network-adapter-priorities-in-windows-10/) and restarting PC.

**Comment by justingosan** [comment]
What worked for me was to go to `Apps -> Expo -> Storage -> Clear Data` then I reconnected after that.

**Comment by nft2** [comment]
Can confirm @justingosan's solution fixes the problem.

**Comment by zimozy** [comment]
Also confirming @justingosan's solution worked.
