### ISSUE TITLE
Suppress `yarnpkg is not a command` when only npm is installed

### ISSUE THREAD

**Issue by dikaiosune** [react-community/create-react-native-app#39]
Inheriting stdout is how CRNA shows init status to the developer, but maybe it should be buffered until we're sure that yarn is installed for the "attempt installing with yarn first" version. Or maybe it's OK to just show this -- there's a lot of other output users see immediately after.

**Comment by gaearon** [comment]
FWIW [this](https://github.com/facebookincubator/create-react-app/blob/b55a7d80f2b07220781b05b8e144d19e436ffea3/packages/create-react-app/createReactApp.js#L136-L143) is what we do in CRA.

**Comment by dikaiosune** [comment]
@gaearon thanks! Very useful.
