### ISSUE TITLE
Error after expo-sdk upgrade from 18 to 20 

### ISSUE THREAD

**Issue by vyemialyanchyk** [react-community/create-react-native-app#390]
per https://github.com/expo/new-project-template/issues/6 recommendation from @dikaiosune, I've create issue here:

after these changes:
app.json:
{ "expo": { "sdkVersion": "18.0.0", ...
==>
{ "expo": { "sdkVersion": "20.0.0", ...

package.json:
`
"devDependencies": {
"jest-expo": "18.0.0",
"jest-expo-ts": "18.0.1",
...
"dependencies": {
"expo": "18.0.0",
"react-native": "0.45.1",
...

==>
"devDependencies": {
"jest-expo": "20.0.0",
"jest-expo-ts": "20.0.0",
...
"dependencies": {
"expo": "20.0.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz",
...

`

gets error with

npm start
react-native-scripts start
4:27:29 PM: Starting packager...
ERROR STARTING PACKAGER
Starting React Native packager...
Scanning 779 folders for symlinks in .......\node_modules (17ms)

EISDIR: illegal operation on a directory, read
4:33:49 PM: Stopping packager...
4:33:49 PM: Packager stopped.

**Comment by malangaveuday** [comment]
same problem
