### ISSUE TITLE
Failed building JavaScript bundle - iOS

### ISSUE THREAD

**Issue by elarue53078** [react-community/create-react-native-app#393]
## Description

I am attempting to run an app from a react native tutorial which worked fine in the past, but now is failing to load in my Expo app.

## Expected Behavior

I did npm start in my terminal application, and following, I launched Expo and attempted to load the app in the Expo environment.  I expected to see the demo text from the app as I have on previous occasions.

## Observed Behavior

The Expo app on my iOS device displayed SyntaxError: Unterminated JSX contents (12:9).  The error displayed in my terminal is "Failed building JavaScript bundle"

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: tipcalc@0.1.0 /Users/safespace53078/Sites/React Native/tipcalc
└── react-native-scripts@1.1.0 
* `npm ls react-native`: tipcalc@0.1.0 /Users/safespace53078/Sites/React Native/tipcalc
└── react-native@0.46.4 
* `npm ls expo`: tipcalc@0.1.0 /Users/safespace53078/Sites/React Native/tipcalc
└─┬ expo@19.0.1 
  └── UNMET PEER DEPENDENCY react@>=15.3.1

npm ERR! peer dep missing: react@>=15.3.1, required by lottie-react-native@1.1.1
npm ERR! peer dep missing: react@>=15.4.0, required by react-native-branch@2.0.0-beta.3
* `node -v`: v6.11.2
* `npm -v`: 3.10.10
* `yarn --version`: yarn: command not found
* `watchman version`: watchman: command not found

Also specify:

1. Operating system: Mac OS 10.12
2. Phone/emulator/simulator & version: iPhone 7 iOS 10.2

## Reproducible Demo

from within the folder with the react native app:
npm start
Launch Expo on iPhone
access appropriate application within Expo

**Comment by fxfactorial** [comment]
```
The Expo app on my iOS device displayed SyntaxError: Unterminated JSX contents (12:9). The error displayed in my terminal is "Failed building JavaScript bundle"
```

Seems to imply that you have some syntax mistakes in your code somewhere, maybe you forgot to close some jsx?
