### ISSUE TITLE
CameraModule from NativeModules is returned as undefined when using create-react-native-app on Android

### ISSUE THREAD

**Issue by javaherian** [react-community/create-react-native-app#394]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

`CameraModule` from `NativeModules` is returned as undefined when using `create-react-native-app`. This is used in the de facto camera library for React Native, `react-native-camera` and breaks any camera functionality I could find.

## Expected Behavior

I used the `react-native-camera` and other camera libraries on Android, and expected it to work, but it didn't work at all and gave me an error as per: https://github.com/facebook/react-native/issues/15809

## Observed Behavior

https://github.com/facebook/react-native/issues/15809

Also specify:

1. Operating system: Ubuntu, but also the same on MacOS
2. Phone/emulator/simulator & version: Android all phones

## Reproducible Demo

https://snack.expo.io/BJJlfZhYZ - Scan with an Android phone.

**Comment by ferminmoli** [comment]
It's not working for me. I've started the App using react-native init so this solution does not solve the issue for me. Is there anothere alternative? I've been stuck since last week and my app is not working properly.

**Comment by dikaiosune** [comment]
Hi! Using libraries with native code (like `react-native-camera`) will require ejecting from CRNA or making use of `react-native init`. That said, the Expo SDK (which you can use with CRNApps) now includes a more complete camera option.
