### ISSUE TITLE
Using generator functions and import/export not working

### ISSUE THREAD

**Issue by mattisfrommars** [react-community/create-react-native-app#395]
## Description

Referencing generator functions returns an error message from Regenerator. Which as I understand is used downstream by babel. I'm aware that the issue is probably not in *this* codebase but it's very unclear which codebase the problem actually lies in, where to submit the issue to, or how to fix.

From what I've read, downgrading a babel preset `babel-preset-react-native` to version 2.0.0 is one correct solution. (A workaround is not referencing generator functions directly i.e. `const genFn = function* () {}` rather than `function* genFn() {}`.)

However, that preset is not referenced in either the package.json or the .babelrc so I'm unsure how to do this.

Repro steps
```
# get latest version
npm install -g create-react-native-app
create-react-native-app my-app
cd my-app
# create a file with a default export of generator function in
#
echo 'export default function* () { console.log("foo") }' > generator.js
#
# use the genrator in App.js
echo -e "import gnFN from './generator'\n$(cat App.js)\ngnFN()" > App.js
```
## Expected Behavior

Generator calls without problem

## Observed Behavior

![image](https://user-images.githubusercontent.com/1679485/30112450-c001eaa2-9311-11e7-9306-d4e82baf3bc9.png)

```
undefined is not an object (evaluating 'regeneratorRuntime.mark')
```

## Environment

```
➜  my-new-app npm ls react-native-scripts
my-new-app@0.1.0 /Users/mattisfrommars/Code/spike/my-new-app
└── react-native-scripts@1.3.1

➜  my-new-app npm ls react-native
my-new-app@0.1.0 /Users/mattisfrommars/Code/spike/my-new-app
└── react-native@0.47.2

➜  my-new-app npm ls expo
my-new-app@0.1.0 /Users/mattisfrommars/Code/spike/my-new-app
└─┬ expo@20.1.2
  └── UNMET PEER DEPENDENCY react@>=15.3.1

npm ERR! peer dep missing: react@>=15.3.1, required by lottie-react-native@1.1.1
npm ERR! peer dep missing: react@>=15.4.0, required by react-native-branch@2.0.0-beta.3
npm ERR! peer dep missing: react@>= 16.0.0, required by react-native-gesture-handler@1.0.0-alpha.18
➜  my-new-app npm ls react
my-new-app@0.1.0 /Users/mattisfrommars/Code/spike/my-new-app
└── react@16.0.0-alpha.12

➜  my-new-app node -v
v6.11.0
➜  my-new-app npm -v
3.10.10
➜  my-new-app yarn --version
0.27.5
➜  my-new-app watchman --version
4.9.0
```

Any help (even if it's just directing me to the correct place to direct this question) would be much appreciated

**Comment by fxfactorial** [comment]
Is your app up somewhere on github?

**Comment by chenkaiC4** [comment]
I get the same problem. and get `this._lazyLoadModules[e] is not a function`

**Comment by doublex** [comment]
Create a file `npm-shrinkwrap.json`
````
{
  "dependencies": {
    "babel-preset-expo": {
      "version": "3.0.0",
      "from": "babel-preset-expo@^3.0.0",
      "dependencies": {
        "babel-preset-react-native": {
          "version": "3.0.2",
          "from": "babel-preset-react-native@^2.1.0"
        }
      }
    }
  }
}
````

**Comment by nbaghiro** [comment]
Was this issue solved? I am having issues with importing generators in my app too.
