### ISSUE TITLE
Cannot specify scripts-version from github repository

### ISSUE THREAD

**Issue by el1t** [react-community/create-react-native-app#396]
## Description

`--scripts-version {github username}/{package name}` downloads the specified package but does not run it—due to parsing done [here?](https://github.com/react-community/create-react-native-app/blob/ed4f5f4d1e1464a782eb65ca1b7a5d26f3998c91/create-react-native-app/src/index.js#L199)

## Expected Behavior

`--scripts-version {github username}/{package name}` should successfully run using the specified package under the given github account.

## Observed Behavior

Installation successfully downloads custom `react-native-scripts` into `node_modules/react-native-scripts`, but can't find the `package.json` file because it looks in `node_modules/{username}/react-native-scripts`.

### Terminal output
```
❯ create-react-native-app --scripts-version el1t/react-native-scripts repo
Creating a new React Native app in /Users/El1t/Documents/repo.

Using package manager as npm with npm interface.
Installing packages. This might take a couple minutes.
Installing react-native-scripts...

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN react-redux@5.0.6 requires a peer of react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0 but none is installed. You must install peer dependencies yourself.

+ react-native-scripts@1.3.1
added 406 packages in 12.226s
(node:75548) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open '/Users/El1t/Documents/repo/node_modules/el1t/react-native-scripts/package.json'
(node:75548) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: 1.3.1
* `npm ls react-native`: 0.47.2
* `npm ls expo`: 20.1.2
* `node -v`: 8.4.0
* `npm -v`: 5.4.0
* `yarn --version`: n/a
* `watchman -v`: 4.9.0

Also specify:

1. Operating system: MacOS 10.12.6
2. Phone/emulator/simulator & version: n/a

## Reproducible Demo

Run the following:
```sh
npx create-react-native-app --scripts-version el1t/react-native-scripts my-repo
```
I've confirmed `el1t/react-native-scripts` works when the package name in `node_modules` is hardcoded to `react-native-scripts`.

**Comment by dikaiosune** [comment]
To be perfectly honest I'm surprised that this even works halfway. `--scripts-version` is intended for development purposes. PRs making this work in the general case would be welcome but today this isn't intended to be supported.
