### ISSUE TITLE
Can it run at Virtual phone ?

### ISSUE THREAD

**Issue by moxiaonai** [react-community/create-react-native-app#397]
## Expected Behavior

i just want it can be worked with the virtual machine
## Observed Behavior

```
Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'length' of null
```

## Environment

Please run these commands in the project folder and fill in their results:

* node -v: 8.3.0
* npm -v: 5.3.0
* yarn --version (if you use Yarn): 0.27.5
* npm ls react-scripts (if you haven’t ejected): 1.1.0

i'm am not installed exp,but i want it running at virtual machine.
i'm sure that the react-native init project  was worked ok by the virtual machine

**Comment by brentvatne** [comment]
hi there, sorry i don't understand the question -- what is virtual phone? are you running an emulator inside of a virtual machine or something?
