### ISSUE TITLE
Error running adb: Error running app. Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=exp://192.168.0.100:19000 flg=0x10000000 }

### ISSUE THREAD

**Issue by a-eid** [react-community/create-react-native-app#398]
## Description
trying to run genymotion simulator .. 

followed the instructions but getting the following error 

`Error running adb: Error running app. Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=exp://192.168.0.100:19000 flg=0x10000000 }`

## Expected Behavior
for the simulator to run 

## Observed Behavior

```
Error running adb: Error running app. Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=exp://192.168.0.100:19000 flg=0x10000000 }
```

## Environment

* `npm ls react-native-scripts`:

```
 react-native-scripts@1.2.1
```

* `npm ls react-native`:
```
 react-native@0.47.2
```

* `npm ls expo`:
```
expo@20.0.1
```

* `node -v`: 
`8.4.0` 

* `npm -v`:
`5.3.0` 

* `yarn --version`:
`1.0.1`

* `watchman version`:
`4.9.0.

Also specify:

1. Operating system: `macos sierra` 
2. Phone/emulator/simulator & version: `genymotion`

**Comment by WilliamAnputra** [comment]
+1

**Comment by rednull** [comment]
make sure you are using minimal **API 19** on your emulator, its work on me somehow.

**Comment by dikaiosune** [comment]
Can you try some of the steps that the Expo docs recommend at https://docs.expo.io/versions/latest/guides/genymotion.html ?

**Comment by this-miguel** [comment]
I'm having the same issue, do you have any pointers? 
![screenshot from 2017-10-24 19-10-48](https://user-images.githubusercontent.com/15721544/31972527-24ca9972-b8ef-11e7-9693-d01c02556033.png)
Just yesterday the emulator was running fine :/

**Comment by this-miguel** [comment]
this worked for me
![screenshot from 2017-10-24 19-37-47](https://user-images.githubusercontent.com/15721544/31973231-e8c1332e-b8f2-11e7-9e1c-28d70788b7b3.png)
source: https://www.bountysource.com/issues/43329081-error-staring-android-emulator

**Comment by brentvatne** [comment]
@this-miguel's solution should work!

**Comment by AndrewLosikhin** [comment]
@rednull solution helped. Don't toss that out.

**Comment by pinchez254** [comment]
I went over to play store in the emulator and viewed expo to see whether i could update it, and I found a message that  this version us not supported in your device. Try different emulators..for me i used android 7 emulator instead and That worked for me!

**Comment by parappathekappa** [comment]
@this-miguel thanks!

**Comment by parappathekappa** [comment]
@this-miguel solution fixed one problem, but then I kept getting 'Couldn't adb reverse' error messages and 'Couldn't start project on Android...'.  @rednull solution was the only one that actually fixed it.  I just wish Genymotion had a wider range of tablets with API 19.

**Comment by lualparedes** [comment]
My two cents for people that want to understand what's going on:

When you run `npm run android`, Expo gets installed on the emulator automatically, and since Expo requires Android 4.4+ (API 19), @rednull solution may do the trick (my case :raised_hands:).

On the other hand, if you're using Genymotion and it throws this error when you try to use an emulator that has Android 4.4+:

![genymotion_error](https://imgur.com/p0AvWy9.png)

you may still be able to use it by reducing the number of cores in the device settings.

**Comment by Aziel1234** [comment]
O meu erro  é recente tem como me ajudar??

Couldn't start project on Android: Error running adb: Error running app. Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=exp://192.168.44.236:19000 flg=0x10000000 }

**Comment by douglasffilho** [comment]
> O meu erro é recente tem como me ajudar??
> 
> Couldn't start project on Android: Error running adb: Error running app. Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=exp://192.168.44.236:19000 flg=0x10000000 }

Conseguiu resolver? estou com o mesmo erro.

**Comment by PiotrSzlagura** [comment]
I bumped into this exact issue when trying to run my Expo (42) app on android emulator (I was trying to use API 31 at first). Clearing `~/.expo/android-apk-cache` did not work.

My issue was resolved when I decided to switch to an emulator with API 30.

**Comment by douglasffilho** [comment]
> I bumped into this exact issue when trying to run my Expo (42) app on android emulator (I was trying to use API 31 at first). Clearing `~/.expo/android-apk-cache` did not work.
> 
> My issue was resolved when I decided to switch to an emulator with API 30.

Too bad, I tryed other API versions and got success, but not to API 22. Thanks by answering @PiotrSzlagura

**Comment by seb-glanum** [comment]
> I bumped into this exact issue when trying to run my Expo (42) app on android emulator (I was trying to use API 31 at first). Clearing `~/.expo/android-apk-cache` did not work.
> 
> My issue was resolved when I decided to switch to an emulator with API 30.

Same issue but I had my emulator already with API 30, so I've just created a new emulator and it's working now !

**Comment by learnersaurabh** [comment]
> Can you try some of the steps that the Expo docs recommend at https://docs.expo.io/versions/latest/guides/genymotion.html ?

Thanks @anp , it worked for me

**Comment by owivans** [comment]
In my case it was solved by running any device with API 30. It is worth mentioning that it was with the M1 chip.

**Comment by garrett-gottlieb** [comment]
This is happening to me with the newest Pixel 6 on API 33 and I've also tried on Pixel 4 API 30, Expo v44.

**Comment by boolfalse** [comment]
In case if anyone needs it։

Specifically in my case I've found that after running "expo start --dev-client" I had installed `expo-dev-client`.
So I just uninstalled that package, also for just in case removed `node_modules` and reinstalled npm packages again

```
npm uninstall expo-dev-client
rm -r node_modules
npm install
```

And after that it worked well as before.
My android physical device worked with v12, Expo v49, emulator was Pixel_7_API_34

I'm new to RN so don't have much knowledge, but clearing .apk caches didn't help me.
Actually I've had my app running well until working with EAS builds (for the Mapbox integration).

**Comment by ICardosoRamos** [comment]
GUYS, THIS PROBLEM IS THAT:
IN YOU EAS.JSON FILE, YOU HAVE ALL THE BUILD CATEGORIES, AND YOU CAN CREATE SOME CUSTOM CATEGORY, SO, IF YOU NEED SOME BUILD CATEGORY THAT RUNS WITH THE --DEV-CLIENT OPTION IN THE NPX EXPO START COMMAND, ALL YOU NEED TO GUARANTEE IS THE THE CATEGORY YOU CHOOSE HAS THE "developmentClient: true" FLAG INSIDE OG THE CATEGORY, LIKE:

		"development": {
			"developmentClient": true,
			"distribution": "internal"
		}
SO IF YOU DON'T HAVE THIS THE BUILD WILL NOT HAVE THE COMPATIBILITY TO RUN WITH --DEV-CLIENT OPTION.

**Comment by david-vendel** [comment]
For me I needed to **unlock the lock screen in my simulated Android**, then try again and app runs. Yes weird.

**Comment by hankwallace** [comment]
> For me I needed to **unlock the lock screen in my simulated Android**, then try again and app runs. Yes weird.

Omg! Hours of trying to diagnose this and then I saw this. I launched the simulator before trying to launch the app, unlocked the simulator, and then launched the app. Thank you!!

**Comment by tim-win** [comment]
Same issue. Had to unlock the damn phone, hahaha.

**Comment by manegame** [comment]
Also make sure airplane mode is off... happened to me too many times xD

**Comment by abena07** [comment]
> For me I needed to **unlock the lock screen in my simulated Android**, then try again and app runs. Yes weird.

same lol
