### ISSUE TITLE
 Error: React native is not installed. Please run `npm install` in your project directory...

### ISSUE THREAD

**Issue by Jawadgee** [react-community/create-react-native-app#399]
just followed the instructions on facebook.github for  create-react-native-app
first got: react-redux 5.0.6 requires a peer of react@^0.14.0 || react@^15.0.0-0 .... 
then I  uninstalled react-redux now getting this... 

***ERROR STARTING PACKAGER***

Error: React native is not installed. Please run `npm install` in your project directory.
1:23:51 AM: Error starting packager: Error: Couldn't start project. Please fix t
he errors and restart the project.
    at E:\xdl\src\Project.js:1126:11
    at next (native)
    at step (E:\react-native\hello-world\node_modules\xdl\build\Project.js:1504:
191)
    at E:\react-native\hello-world\node_modules\xdl\build\Project.js:1504:361
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hello-world@0.1.0 start: `react-native-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hello-world@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jawad Ul Hassan\AppData\Roaming\npm-cache\_logs\2017-09-08
T20_23_51_654Z-debug.log

here is package.json 
https://drive.google.com/file/d/0BwNXojt_xhBGYy1leUxnQ0lTWEE/view?usp=sharing

what could be my mistake or any suggestion about doing it right way ?

**Comment by brentvatne** [comment]
i imagine you are using npm 5. npm 5 is still very buggy, please either use yarn or npm 4.

```
npm i -g yarn
npm i -g npm@4
```

**Comment by brentvatne** [comment]
(fwiw this is documented here: https://github.com/react-community/create-react-native-app#getting-started)

**Comment by sanjay90chd** [comment]
Follow this link: https://www.microsoft.com/developerblog/2015/09/30/upgrading-to-npm3-on-windows/
