### ISSUE TITLE
where is the documentation for .expo/settings.json?

### ISSUE THREAD

**Issue by a3diti** [react-community/create-react-native-app#400]
I searched the web and nothing was found regarding the configuration for `settings.json`

My current `settings.json` file:
```
{
  "hostType": "tunnel",
  "lanType": "ip",
  "dev": true,
  "strict": false,
  "minify": false,
  "urlType": "exp",
  "urlRandomness": null
}
```

I'm using yarn start to test the app on ios emulator
If i change hostType to localhost it stills opens the port globally on the lan, i'm working on public wifi and i don't wanna expose the project to the network, neither to expo.

**Comment by brentvatne** [comment]
there is no documentation on this, it is a private configuration used internally by expo. this is why it is in .gitignore. if you want to use different options here, you'll need to install `exp` -- `npm i -g exp`, then you can refer to this documentation: https://docs.expo.io/versions/latest/guides/exp-cli.html
