### ISSUE TITLE
The development server returned response error code: 500

### ISSUE THREAD

**Issue by samassango** [react-community/create-react-native-app#401]
![whatsapp image 2017-09-11 at 08 39 24](https://user-images.githubusercontent.com/9332901/30262713-3e803884-96d2-11e7-9253-b20965fa9da9.jpeg)

## Description
I started experiencing this issue after change an expo version from 15.0.0 to 19.0.0

**Comment by aloifolia** [comment]
I just ran in the same or a similar issue. For me, the red screen appears when I create a completely fresh project with CRNA 1.0.0, then eject and finally try to start the app with `react-native run-android`

<img width="742" alt="screen shot 2017-09-13 at 17 10 46" src="https://user-images.githubusercontent.com/1295054/30385227-d7146f90-98a6-11e7-851c-4712a886685e.png">

**Comment by brentvatne** [comment]
I guess maybe you're using this lib: https://github.com/GeekyAnts/NativeBase/issues/24

anyhow the issue is related to react-native version changes and some code (either yours or a library) depending on some private code in react-native that changed

**Comment by samassango** [comment]
I managed to solve this error
The cause of this error is the changes of files location made in react-native dependency which other libraries like native-base point to.

To solve it you need to view the mentioned file and change the file location to the correct location.

**Comment by izzateesafia** [comment]
Sorry but @samassango could you please explain a little bit further.

**Comment by samassango** [comment]
@izzateesafia Okay this issue occurs in node_modules meaning it's not your code but its some of the dependence which had changed files location example:
If we have modules/components/js/btn.js in a certain library, and it happen that another library use that library as one of it's dependence, then the used library decide to move the change btn.js to button/btn.js. if another app use both dependence this issue will occur. What you need to do is find the correct file location and update the file which can't resolve the previous location with the correct file location. Then its gonna work. 
Or 
Just implement expo 20.0.0 sdkversion 20.0.0, react-native 0.47.0, and react^16.0.0-alpha.12 then you won't experience that issue.

**Comment by guarani** [comment]
For me this error was resolved running `yarn` in the project folder. The cause may have been due to the fact that I'd switched branches and some of the packages were not installed.

**Comment by bethwelt** [comment]
@guarani your  solution worked for me,thank you

**Comment by thakursaurabh1998** [comment]
One of the reasons why I was having this error was because I imported 'react-native' library twice.

`import { View, Text, ActivityIndicator } from "react-native";`
`import { View, Text, ActivityIndicator, TouchableOpacity, StyleSheet } from "react-native";`

I don't know If this can really cause this problem but removing the redundant line of import solved this issue for me.

**Comment by Navithahk** [comment]
restarting the metro bundler work!

**Comment by kishanmahor** [comment]
![screenshot_2018-07-13-17-57-14-241_com awesomeproject](https://user-images.githubusercontent.com/24253970/42691688-adfb3d00-86c6-11e8-9382-4219351449c8.png)
this is my first app and i got this error .i am using -g react-native-cli

**Comment by mazhardev** [comment]
I also have this issue :(

**Comment by rcsoares** [comment]
Try run `npm start` and  `react-native run-android`. Maybe your Metro Bundler isn't started.

**Comment by karmicdice** [comment]
Expected Output

Running App.


Sets followed:


```
npm -g install react-native
npm -g install socks
npm -g install react-native-cli

cd /project-directory
react-native init <projectname>
```

cd projectname

-- Start Android Studio - Run Emulator (API 23) --

`react-native run-android`

Output:
![native-error](https://user-images.githubusercontent.com/3824371/43119992-3ff0ce2e-8f36-11e8-8c42-c6cd74d7f5d2.png)

**Comment by kishanmahor** [comment]
first delete node_modules folder <http://folder.in/> and in package.json
change react-native version "react-native": "0.55.2", and
  babel "babel-preset-react-native": "4", after that run yarn install or
npm install and run its work fine for me.

**Comment by EugeneRaynerNZ** [comment]
Kish that's perfect mate. Thanks a bunch.

**Comment by MondeLionel** [comment]
The horror of Android on windows is real. Same issue, metro bundler seems to be fine  but issue persists. Time for some tea.

**Comment by psatler** [comment]
Thanks a lot @kishanmahor !

**Comment by edoantonioco** [comment]
React native on windows seems to be broken, and Kishanmahor workaround to return to an older vesion of react native seems to be the way to make it work.

As a temporary workaround works, but its not something that makes me feel comfortable with react native.

**Comment by prasad456** [comment]
@rcsoares Metro Builder was running, but having the same issue for the sample starting app in react
Please don't mind, I'm a newbie in react-native

**Comment by ravichandrasv** [comment]
Downgrade the following:
react-native init Project
cd Project
npm uninstall react-native
npm install --save react-native@0.55.4
npm uninstall --save babel-preset-react-native
npm install --save babel-preset-react-native@4.0.0
react-native run-android

**Comment by albertcjr** [comment]
Issue is due to react-native 0.56

**Comment by qweasdzxc23** [comment]
hello , fast solution is :
1 - delete node_modules folder
2 - edit package json : react-native version to "55.4" or "55.2" and babel-preset-react-native to "4.0.0"
3 - run npm install or yarn install command
4 - you're done 👍

**Comment by jerrychong25** [comment]
@kishanmahor methods works for me, thanks a lot!

**Comment by aditodkar** [comment]
@ravichandrasv  @ravichandrasv You just saved me today. It works fine for windows 10.

**Comment by cyb3rsalih** [comment]
Restarting Metro Bundler with  `npm start`  solved my problem

**Comment by md0092651** [comment]
I just started with learning react native and got the same error. [This link ](https://github.com/facebook/react-native/issues/21310)solved the issue. All the above solution did not work for me

**Comment by rizkisunaryo** [comment]
@md0092651 solution works for me.

**Comment by bsendras** [comment]
None off the solutions above worked for me. Finaly  I replaced the dependencies in package.json to match the one generated a couple of days ago with react-native init. This is the plane base package.json that works for me, even using react-native 0.57. Hope it helps!
```
{
  "name": "someProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.5.0",
    "react-native": "0.57.0"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.45.3",
    "react-test-renderer": "16.5.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by SulaRanawake** [comment]
I also had this issue. Found out I have misspelled when mentioning a component I have created. But needs them to run. The issue solved after correcting that.

**Comment by dushabella** [comment]
> One of the reasons why I was having this error was because I imported 'react-native' library twice.
> 
> `import { View, Text, ActivityIndicator } from "react-native";`
> `import { View, Text, ActivityIndicator, TouchableOpacity, StyleSheet } from "react-native";`
> 
> I don't know If this can really cause this problem but removing the redundant line of import solved this issue for me.

Same to me

**Comment by luisitocard** [comment]
The same thing happened to me and the import had doubled, validate that first

**Comment by WCH0820** [comment]
Thanks for your asking

**Comment by ndukachukz** [comment]
has anyone gotten this error its terrible kept me in for weeks now

**Comment by SamuelCvC** [comment]
I spent almost two days trying to fix this issue, I tried so many difficult alternatives and what helped me was a easy one.

I just dowload the node version and download a older one. Simple as that... That works for me, I hope works for ya'll! <3

**Comment by aashishpanthi** [comment]
Got the same problem.

I deleted `package-lock.json` and `node_modules` then install all packages using `yarn add`, my problem is now solved.

**Comment by iamnomadgg** [comment]
> hello , fast solution is : 1 - delete node_modules folder 2 - edit package json : react-native version to "55.4" or "55.2" and babel-preset-react-native to "4.0.0" 3 - run npm install or yarn install command 4 - you're done 👍

In my first case, as long as I imported the library which I have created (WelcomeScreen) in App.js, I had this problem. After I applied your 1st and 3rd steps, it was solved.
However, as long as I use it in the App.js as <WelcomeScreen>, the problem occurs again.

Since the used versions are "react-native": "0.71.3", "@babel/core": "^7.20.0", I couldn't apply your 2nd step. Do you have any idea which versions I should use?
