### ISSUE TITLE
New project with CRNA cannot find entry file

### ISSUE THREAD

**Issue by jd1388** [react-community/create-react-native-app#402]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request

After installing create-react-native-app globally, I try to run `create-react-native-app foo`. This creates a `foo` project. After running `cd foo` to enter the `foo` directory, I run `npm start`. The terminal outputs the following: 
<img width="1080" alt="terminal1" src="https://user-images.githubusercontent.com/14971968/30291214-c244ba30-96f7-11e7-90de-77b7f3f86d15.png">
<img width="1080" alt="terminal2" src="https://user-images.githubusercontent.com/14971968/30291220-c6fdef38-96f7-11e7-98d3-3b5952f56bfd.png">

When I try to use the Expo app to scan the barcode, the terminal outputs that there was an error compiling the JavaScript bundle.
<img width="1080" alt="terminal3" src="https://user-images.githubusercontent.com/14971968/30291232-cda0f3d0-96f7-11e7-805a-73d0bebe9d33.png">
![screenshot_20170911-131439](https://user-images.githubusercontent.com/14971968/30291265-f052550e-96f7-11e7-99d8-6c5ac8362fc6.png)

## Expected Behavior

What action did you perform, and what did you expect to happen?

I ran `npm start` inside of the project created by create-react-native-app. I expected that the terminal would output a qr code that I could scan with the Expo app so that I could see the project was set up successfully.

## Observed Behavior

What actually happened when you performed the above actions?

When I scan the qr code in the terminal, I am provided the terminal output above.

If there's an error message, please paste the *full terminal output and error message* in this code block:

See above

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: `-- react-native-scripts@1.3.1
* `npm ls react-native`: `-- react-native@0.47.2
* `npm ls expo`: `-- expo@20.1.3
  `-- UNMET PEER DEPENDENCY react@>=15.3.1
* `node -v`: v6.11.3
* `npm -v`: 3.10.10
* `yarn --version`: 'yarn' is not recognized as an internal or external command,
operable program or batch file.
* `watchman version`: {
    "version": "4.9.0",
    "buildinfo": "2e41dcec654687136a4bfc8fefd8911dbed367e3 2017-08-23T18:23:28.0000000Z"
}

Also specify:

1. Operating system: Windows 10
2. Phone/emulator/simulator & version: Android (Samsung Galaxy S6 running Android 7.0)

## Reproducible Demo

I've put this on github here: https://github.com/jd1388/create-react-native-app-issue
To reproduce, pull the repo, run `npm install` inside of the project, then run `npm start`. Make sure to be using the same versions of node and npm as above.

**Comment by dikaiosune** [comment]
Hi! Can you try using npm 4? It seems like fbemitter isn't being flattened properly between its various dependencies.

**Comment by jd1388** [comment]
I've updated npm to 4.6.1, but that did not fix it. However, I tried updating CRNA and using that to build a new app, and I got it to work. I updated my repo in case your curious as to what changed.

**Comment by brentvatne** [comment]
strange. well I'm glad that updating fixed it, if you run into it again feel free to make another issue
