### ISSUE TITLE
[Question] using react-native link dependent modules

### ISSUE THREAD

**Issue by fzymek** [react-community/create-react-native-app#403]
Hello,

I have a question related to using native modules with react-native apps. 

As described [here](https://github.com/react-community/create-react-native-app#what-are-the-limitations-of-create-react-native-app) it appears that application created with CRNA is not supposed to be used with native modules. Is it still true? 

Recently I was able to integrate `@shoutem/ui` module with my app created with CRNA (as far as I understand this is native module because it requires me to run `react-native link` command) and it was working just fine on my android and ios phones and ios simulator as well. 

As [this](https://github.com/facebook/react-native/pull/15139) PR explains, using `react-native link` should display error message but I cannot observe it at all. 

Has anything changed?  This is really confusing.

**Comment by fxfactorial** [comment]
CRNA is for apps that are gonna be pure JS. If you need to use native code, things that use `react-native link` then you'll need to follow this guide https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md

**Comment by fzymek** [comment]
@fxfactorial This is exactly the part I do not understand. 

As I said, I have successfully used native module `@shoutem/ui`(https://github.com/shoutem/ui) with CRNA code and it was working fine. I have not ejected from CRNA.  
But given your explanation this should not happen and should not work. But it is. How is this possible?

**Comment by kaueDM** [comment]
@fzymek check the Install steps:
```

$ npm install --save @shoutem/ui
$ react-native link # No need to run this with Exponent
```

Probably the shoutem/ui dependencies are already  packed in Expo. Its the same with libraries using SVG or ART library. Check the docs for more info.

**Comment by dikaiosune** [comment]
Shoutem relies on `react-native-vector-icons` which is already included in Expo. In their case the use of `react-native link` is to add some static assets to your app, not native code. Sorry this is confusing, it's a kinda weird edge case of how we talk about native code in RN.
