### ISSUE TITLE
[Question] Change loading screen with Expo logo

### ISSUE THREAD

**Issue by kaueDM** [react-community/create-react-native-app#409]
## Description

Can i change the loading screen from my project? I generated an standalone app with `exp` and installed in my phone, but when i open it, the expo logo appears before the app main screen.

I used `AppLoading` component while my app loads fonts, images, etc. Is this Expo logo the result?

**Comment by mathieudutour** [comment]
that's what you need to change: https://docs.expo.io/versions/latest/guides/configuration.html#loading

**Comment by kaueDM** [comment]
Great! Thanks @mathieudutour
