### ISSUE TITLE
[Question] Triggers Expo preview manually

### ISSUE THREAD

**Issue by shrotavre** [react-community/create-react-native-app#410]
## Description
Is it possible to disable automatic expo preview after save? And trigger it manually with a key press? 
Just like how we do it with packager restarting and QR displaying? Restarting app from the home screen sometimes get so annoying.

I think there should be a way to do this! 
I'm new, sorry if I'm doing this incorrectly :)

**Comment by mathieudutour** [comment]
if you press `cmd + crtl + z` in the emulator, you should be able to disable "live reload"
