### ISSUE TITLE
Expo Windows LAN Timeout

### ISSUE THREAD

**Issue by Mg-Yaya** [react-community/create-react-native-app#413]
Hi, each time I run on device over LAN network I get connection timeout on Expo App.
Here's what I did : 

- I added port and app exeption in firewall on windows and avast antivirus.
- Then I disabled all firewalls.
- I disabled all others virtual connections and I'm sure with the ip address of my wifi.
- Android Phone and pc same wifi.
- I this is what I got from netstat command:
![image](https://user-images.githubusercontent.com/14295330/30778364-76423464-a0d4-11e7-8985-f9294a8dc9a0.png)

Please tell me if I missed something, I searched a lot and I didn't find a solution.

**Comment by wjielim** [comment]
Why is this closed? Did you managed to solve the problem?
Because I'm also having the exact same problem right now.

**Comment by Mg-Yaya** [comment]
Add firewall exception (in and out) for ports 19000 and 19001
