### ISSUE TITLE
Getting undefined is not an object (evaluating RNFSManager.RNFSFileTypeRegular) when using create-react-native-app

### ISSUE THREAD

**Issue by sw-yx** [react-community/create-react-native-app#415]
quick question... is react-native-fs compatilble with create-react-native-app? i am getting an error and am not sure if its me or CRNA...

**Comment by dikaiosune** [comment]
Per `react-native-fs`'s docs, it requires linking native code: https://github.com/itinance/react-native-fs#adding-automatically-with-react-native-link

Which will require ejecting from CRNA :*(
