### ISSUE TITLE
Error message about npm 5 not being supported is out of date

### ISSUE THREAD

**Issue by joelpresence** [react-community/create-react-native-app#424]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request

If you try to `create-react-native-app` with npm 5 installed, you get a helpful message indicating that npm 5 doesn't work with react native right now.  That helpful message references https://github.com/npm/npm/issues/16991 .  However, the NPM team is no longer accepting comments on that issue and have locked it down.  Being sent to that issue is now frustrating to a newbie (like myself).  Could we update the "react native doesn't work with npm 5" message to reference that now-locked issue, but also mention that the issue is locked, and include a message like "you'd better downgrade to npm 4, and here's how: npm install -g npm@4".

See the final comments on the linked issue https://github.com/npm/npm/issues/16991
```
I'm gonna lock this 'cause I keep getting pinged and I can't imagine this conversation going anywhere good the way it's happening.

Again: we're working on the fixes. I'm just not using this issue to track it anymore because it is not an effective medium for it. We're collecting blockers in other ways and prioritizing what we'll be fixing in the next couple of weeks/months according to that.

We're also working on new stuff, which is needed in order to help stabilize stuff -- npm is in a bit of an interim state while we move to this new model, and we're rewriting and refactoring a lot of its core. This will help us make npm more maintainable/testable/patchable, and ultimately more stable. But while all that stuff lands, we're going to have all this very fresh code, and we're going to be finding a lot of corner cases our very large community had grown used to -- and we'll have solutions for those.

My suggestion for folks is that if you can't upgrade: wait for it. npm@5 is a massive shift from older version and introduces a ton of new things and workflows. The CLI team decided to release npm5 when we did because it worked for us and for a number of people -- and the positive changes with npm5 are huge enough that there's a lot of people willing to use the bleeding edge and who have had a great experience with it. The work now is to extend those benefits to the rest of y'all <3.
```
I can see @zkat's point about being pinged, but as a newbie, being led to that issue with no idea how to resolve things makes react native seem a bit flaky (if your first experience is that react native won't even create an app due to npm 5 issues) when in fact I find react native to be quite stable and awesome!  :-) I just want to help with the first time experience.

Would you accept a PR to update this message?

## Expected Behavior

What action did you perform, and what did you expect to happen?

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
* `npm ls react-native`:
* `npm ls expo`:
* `node -v`:
* `npm -v`:
* `yarn --version`:
* `watchman version`:

Also specify:

1. Operating system:
2. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by michaelBenin** [comment]
Why not put in the readme to use npm v4?

**Comment by dikaiosune** [comment]
@joelpresence I think ideally we could update the message to point to the specific issues which are causing problems. Unfortunately, it seems that without a single npm5 tracking issue, that might not be feasible since there are several issues that affect CRNA across the various npm5 releases. What would you suggest for the error message?

@michaelBenin from https://github.com/react-community/create-react-native-app#installation:

> You'll need to have Node v6 or later on your machine. We strongly recommend using npm v3, v4, or a recent version of Yarn. Create React Native App does not currently work with npm v5 due to bugs in npm (you can track the issue here).

**Comment by eflamm** [comment]
Is there a way to force CRNA to use yarn instead of NPM@5 if both are installed? The current LTS installer for Node (8.9.1) installs NPM@5 by default. You can downgrade is noted in the original post, but if there's a command line switch to invoke yarn instead, that could be a better workaround.

**Comment by fson** [comment]
@eflamm, when `yarn` is installed, CRNA already uses it by default to install packages.
