### ISSUE TITLE
i can't create an awesome project

### ISSUE THREAD

**Issue by NottherealIllest** [react-community/create-react-native-app#426]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

I'm trying to install react native for the first times I'm a new user, i just want to write code i hate that i have to go through so many installations and fix so many errors, i have created a react native project using 

## Expected Behavior

create-react-native-app AwesomeProject

cd AwesomeProject
npm start

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Last login: Sat Oct  7 08:00:53 on ttys001
Bombatas-MacBook-Pro:~ bombata$ cd AwesomeProject
Bombatas-MacBook-Pro:AwesomeProject bombata$ npm start

> AwesomeProject@0.1.0 start /Users/bombata/AwesomeProject
> react-native-scripts start

08:23:48: Unable to start server
See https://git.io/v5vcn for more information, either install watchman or run the following snippet:
  sudo sysctl -w kern.maxfiles=5242880
  sudo sysctl -w kern.maxfilesperproc=524288
        
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! AwesomeProject@0.1.0 start: `react-native-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the AwesomeProject@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bombata/.npm/_logs/2017-10-07T07_23_48_639Z-debug.log
Bombatas-MacBook-Pro:AwesomeProject bombata$ 
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: -bash: /Users/bombata: is a directory
* `npm ls react-native`:/Users/bombata
└── (empty)
* `npm ls expo`:/Users/bombata
└── (empty)
* `node -v`:v8.0.0
* `npm -v`:4.6.1
* `yarn --version`: command not found
* `watchman version`:command not found

Also specify:

1. Operating system: mac OS Sierra 10.12.5
2. Phone/emulator/simulator & version: iPhone 6 iOS 10.3.2

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by brentvatne** [comment]
hello!

notice the suggestion in the error message:

```
See https://git.io/v5vcn for more information, either install watchman or run the following snippet:
  sudo sysctl -w kern.maxfiles=5242880
  sudo sysctl -w kern.maxfilesperproc=524288
```

try that out and if it doesn't work let me know!
