### ISSUE TITLE
Imported file not working on react-navigation

### ISSUE THREAD

**Issue by mbbarry91** [react-community/create-react-native-app#427]
I am having a problem with importing these files.
I have this error shown every time I run the app 

```
Bundling index.android.js [development, non-minified, hmr enabled] 32.2% (452/797), failed.
error: bundling failed: "Unable to resolve module ./CustomerComponents/MapContainer from C:\\Users\\Barry\\Desktop\\T axiMoto\\Navigation\\Routes.js: could not resolve `C:\Users\Barry\Desktop\TaxiMoto\Navigation\CustomerComponents
\MapContainer' as a folder: it did not contain a package, nor an index file"
```

I have a snap provided and you can see all my directories on the left side of the snap 
I have also tried the solutions suggested but none of them seem to be working 
if I import the files into another file, it doesn't run into any error, but if I import them into the navigation file, then the error occurs 
![erro2](https://user-images.githubusercontent.com/25786816/31325346-a53986e8-acee-11e7-81ff-a6a0f414986c.PNG)

So please if you know how to fix this, help me asap   

![error1](https://user-images.githubusercontent.com/25786816/31325096-e1c9d110-aceb-11e7-8c90-d8e8a3c43272.PNG)

**Comment by brentvatne** [comment]
I guess your Routes.js file is in Navigation, in which case you need to import MapContainer from '../CustomerComponents/MapContainer`

either way, not an issue with CRNA

**Comment by mbbarry91** [comment]
yes the Routes.js file is in Navigation folder. Thanks
