### ISSUE TITLE
how can  i release binary to ios and apk to android

### ISSUE THREAD

**Issue by lavarajallu** [react-community/create-react-native-app#431]
In React-native order method based on Xcode and based on android released using geny motion .

now this ,
1.what is the Installation Process in Xcode and Genymotion and Android Studio.
2. How can we release the Binary.
3. How can we release the Apk to android.

**Comment by dikaiosune** [comment]
Hi! This is covered in the user guide under https://github.com/react-community/create-react-native-app/tree/master/react-native-scripts/template#sharing-and-deployment
