### ISSUE TITLE
When will CRNA use react-native 0.49.0 by default?

### ISSUE THREAD

**Issue by joelpresence** [react-community/create-react-native-app#432]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request

I've updated create-react-native-app, but still it creates a new app that uses react-native 0.48.4, not the latest version, 0.49.0.  Also, the docs at https://github.com/react-community/create-react-native-app/blob/master/VERSIONS.md don't mention react-native 0.49.0.  Is there something we need to do to bump CRNA to use the latest react-native, or do I just need to be patient.  :-) . Thanks for all of your hard work on CRNA, it is really useful, especially for a newbie like me.  Best.

## Expected Behavior

What action did you perform, and what did you expect to happen?

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
* `npm ls react-native`:
* `npm ls expo`:
* `node -v`:
* `npm -v`:
* `yarn --version`:
* `watchman version`:

Also specify:

1. Operating system:
2. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by brentvatne** [comment]
we update CRNA when we update Expo. we do a release of Expo every month. we wait for a couple weeks for it to stabilize, to make any of our APIs up to date with the new release, and to give third party libraries time to catch up to any breaking changes.
