### ISSUE TITLE
React-native-socket.io

### ISSUE THREAD

**Issue by mbbarry91** [react-community/create-react-native-app#434]
I'm trying to use socket.io in my rn app, I install using this npm doc, here is the link https://www.npmjs.com/package/react-native-socket.io, so after I finished the installation then ran the app, this error appears 
```
:SocketIo:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execut
C:\Users\Barry\Desktop\TaxiMoto\node_modules\react-native-socketio\android\src\main\java\com\gcrabtree\rc
    @Override
    ^
C:\Users\Barry\Desktop\TaxiMoto\node_modules\react-native-socketio\android\src\main\java\com\gcrabtree\rc
ap cannot be applied to given types;
public class SocketIoReadableNativeMap extends ReadableNativeMap {
       ^
  required: HybridData
  found: no arguments
  reason: actual and formal argument lists differ in length
2 errors
:SocketIo:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':SocketIo:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```
so please help if you seem to know what is wrong!

![app build gradle](https://user-images.githubusercontent.com/25786816/31506196-5afb08fa-afa9-11e7-9dba-8059c1c88cd1.PNG)
![mainapplication](https://user-images.githubusercontent.com/25786816/31506197-5b2f881e-afa9-11e7-9124-b10235cb5dd2.PNG)
![settings gradlew](https://user-images.githubusercontent.com/25786816/31506198-5b6848ca-afa9-11e7-90b4-890b8f367a92.PNG)

**Comment by dikaiosune** [comment]
Hi! If you're editing Java code then it seems like you're probably not working on a CRNA app anymore. Can you open this issue on the socket.io repository? Thanks!
