### ISSUE TITLE
Icon is removed from app.json when ejecting

### ISSUE THREAD

**Issue by valk** [react-community/create-react-native-app#437]
Hi, the problem:
I need to build an apk from CRNA. But when I add the launcher icons and then ejecting with:`yarn run eject` the file app.json doesn't contain the "icon":... lines anymore. And these files remain the default icons: 
 `android/app/src/main/res/mipmap-*/ic_launcher.png`.

Expected: So the icons are the default icons, but I need the app.png that I've provided.

Also, Is it possible to just build apk without ejecting (it's not clear from the RN docs).

Thanks!

## Environment

* `npm ls react-native-scripts`:
myApp@0.1.0 ~/myApp
└── (empty)

* `npm ls react-native`:
myApp@0.1.0 ~/myApp
└── react-native@0.47.2 

* `npm ls expo`:
myApp@0.1.0 ~/myApp
└── UNMET DEPENDENCY expo@^20.0.0

npm ERR! missing: expo@^20.0.0, required by myApp@0.1.0

* `node -v`:
v8.4.0

* `npm -v`:
4.6.1

* `yarn --version`:
1.2.0

1. Operating system: Linux Mint
2. Phone/emulator/simulator & version: genymotion

**Comment by dikaiosune** [comment]
Hi! Expo provides a [build service](https://docs.expo.io/versions/latest/guides/building-standalone-apps.html) for generating APKs from CRNA projects, but if you want to compile it locally, you'll need to eject. I'm not sure why the eject script isn't honoring your icon file, can you upload a minimal repro of this issue somewhere so I can take a look? I suspect that something changed with how react-native-cli is parsing this file.

**Comment by valk** [comment]
Hi @dikaiosune ,

[Here's the code](https://ufile.io/gffob) I wrote generally from the tutorials, and I use the recommended by React procedure for building the apk (tell me if I should post it here).

I've just added the icon again to the app.json since it was removed once again.

Thank you!

**Comment by dikaiosune** [comment]
@valk can you maybe upload it as a repository or something? That site is not cooperating with me. Thanks!

**Comment by valk** [comment]
Hi @dikaiosune ,

I put it here: https://github.com/valk/react-native-play

**Comment by dikaiosune** [comment]
Hi! Sorry for the extreme delay here. I tried reproducing this report:

```
 ~/code  git clone git@github.com:valk/react-native-play.git                                 Thu Nov  9 12:11:27 2017
...
 ~/c/react-native-play   master  yarn                                                      Thu Nov  9 12:11:31 2017
...
 ~/c/react-native-play   master  cat app.json                                      322ms  Thu Nov  9 12:11:52 2017
{
  "expo": {
    "sdkVersion": "20.0.0",
    "icon": "./app.png"
  }
}
 ~/c/react-native-play   master  yarn run eject                                            Thu Nov  9 12:12:02 2017
yarn run v1.0.2
$ react-native-scripts eject

We didn't find any uses of the Expo SDK in your project, so you should be fine to eject to
"Plain" React Native. (This check isn't very sophisticated, though.)

We strongly recommend that you read this document before you proceed:
  https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md

Ejecting is permanent! Please be careful with your selection.

? How would you like to eject from create-react-native-app? React Native: I'd like a regular React Native project.
We have a couple of questions to ask you about how you'd like to name your app:
? What should your app appear as on a user's home screen? lol2
? What should your Android Studio and Xcode projects be called? phonya
Writing your selections to app.json...
Wrote to app.json, please update it manually in the future.
Scanning 786 folders for symlinks in /Users/adam/code/react-native-play/node_modules (22ms)
Generating the iOS folder.
Generating the Android folder.
Successfully copied template native code.
Babel preset changed to `babel-preset-react-native-stage-0/decorator-support`.
Updating your yarn scripts in package.json...
Your package.json is up to date!
Adding platform-specific entry points...
Added new entry points!

├─ babel-plugin-syntax-class-constructor-call@6.18.0
├─ babel-plugin-syntax-do-expressions@6.13.0
├─ babel-plugin-syntax-function-bind@6.13.0
├─ babel-plugin-transform-class-constructor-call@6.24.1
├─ babel-plugin-transform-do-expressions@6.22.0
├─ babel-plugin-transform-exponentiation-operator@6.24.1
├─ babel-plugin-transform-export-extensions@6.22.0
├─ babel-plugin-transform-function-bind@6.22.0
└─ babel-preset-react-native-stage-0@1.0.1
Ejected successfully!
Please consider letting us know why you ejected in this survey:
  https://goo.gl/forms/iD6pl218r7fn9N0d2
✨  Done in 42.69s.
 ~/c/react-native-play   master *…  cat app.json                                     43s  Thu Nov  9 12:12:53 2017
{
  "expo": {
    "sdkVersion": "20.0.0",
    "icon": "./app.png"
  },
  "name": "phonya",
  "displayName": "lol2"
}⏎                                                                                                                     ~/c/react-native-play 
```

Did you try ejecting with ExpoKit? Can you provide any other information that'll help me reproduce this issue? Thanks!
