### ISSUE TITLE
npm test is not working in the create react native App

### ISSUE THREAD

**Issue by MbF-Sedhu** [react-community/create-react-native-app#438]
I am trying to run the `npm test` in my react native project I am getting following error

```
`     TypeError: Path must be a string. Received undefined

      at assertPath (path.js:28:11)
      at Object.relative (path.js:559:5)`
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:1.5.0"
* `npm ls react-native`:0.48.4
* `npm ls expo`:21.0.0
* `node -v`:8.2.1
* `npm -v`:5.3.0
* `yarn --version`:1.1.0
* `watchman version`:

Also specify:

1. Operating system:windows 8 Pro

## Reproducible Demo
My package.json file

`{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "babel-jest": "^21.2.0",
    "babel-preset-env": "*",
    "babel-preset-react-native": "*",
    "enzyme": "^3.1.0",
    "jest": "*",
    "jest-expo": "^21.0.2",
    "react-native-scripts": "1.5.0",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "node_modules/(?!react|@expo|expo)"
    ]
  },
  "dependencies": {
    "base-64": "^0.1.0",
    "expo": "^21.0.0",
    "jest-react-native": "^18.0.0",
    "lodash": "^4.17.4",
    "react": "16.0.0-alpha.12",
    "react-addons-test-utils": "^15.6.2",
    "react-native": "^0.48.4",
    "react-native-extended-stylesheet": "^0.6.0",
    "react-native-keyboard-aware-scroll-view": "^0.3.0",
    "react-native-router-flux": "^4.0.0-beta.21",
    "react-native-video": "^2.0.0",
    "react-redux": "^5.0.6",
    "redux-thunk": "^2.2.0",
    "validator": "^9.0.0",
    "watchman": "^0.1.8"
  }
}`

anyone can solve this problem @gaving @ccheever @skevy

**Comment by dikaiosune** [comment]
Hi! Unfortunately this isn't enough information for us to reproduce your error. Can you upload your project to GitHub somewhere so we can try it?

**Comment by MbF-Sedhu** [comment]
@dikaiosune can u give me some basic example for running the test cases using jest

**Comment by yernandus** [comment]
same thing here. I just created new app with crna, and executed yarn test

**Comment by brentvatne** [comment]
@MbF-Sedhu - this sounds like an issue with jest as we're not doing anything special here. if you can't share the project, unfortunately we can't help much :( feel free to re-create issue if you can create a minimal example that reproduces the problem for us to investigate
