### ISSUE TITLE
Install "create-react-native-app" failed on OSX  using NPM 3.10.10

### ISSUE THREAD

**Issue by gmdove** [react-community/create-react-native-app#440]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description
Installation of create-react-native-app failed

1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior
Successful install 

What action did you perform, and what did you expect to happen?

## Observed Behavior
$ npm install -g create-react-native-app

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
m ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "create-react-native-app"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! path ../lib/node_modules/create-react-native-app/build/index.js
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall symlink

npm ERR! Error: EACCES: permission denied, symlink '../lib/node_modules/create-react-native-app/build/index.js' -> '/usr/local/bin/create-react-native-app'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, symlink '../lib/node_modules/create-react-native-app/build/index.js' -> '/usr/local/bin/create-react-native-app'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../lib/node_modules/create-react-native-app/build/index.js',
npm ERR!   dest: '/usr/local/bin/create-react-native-app' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
* `npm ls react-native`:
* `npm ls expo`:
* `node -v`:
* `npm -v`:
* `yarn --version`:
* `watchman version`:

Also specify:

1. Operating system:
2. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by crastyle** [comment]
Please try running this command again as root/Administrator.

`sudo npm install create-react-native-app -g`

**Comment by gmdove** [comment]
Apologies. All playing happily today
