### ISSUE TITLE
Image not working

### ISSUE THREAD

**Issue by dhruvdutt** [react-community/create-react-native-app#443]
## Description

`<Image />` not getting displayed.

## Expected Behavior

Using a simple parent `<View ... />` component and an `<Image />` inside it.

## Observed Behavior

Image not getting rendered.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: 1.5.0
* `npm ls react-native`: 0.48.4
* `npm ls expo`: 21.0.2
* `node -v`: 6.11.0
* `npm -v`: 4.6.1
* `yarn --version`: 1.1.0
* `watchman version`: 4.9.0

Also specify:

1. Operating system: Kubuntu 17.04
2. Phone/emulator/simulator & version: Zuk Z2 Plus 

## Reproducible Demo

Just 17 lines of code

```jsx
import React from 'react';
import { Text, View, Image } from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <View>
       <Text>Demo Text</Text>
       <Image
         style={{width: 50, height: 50}}
         source={{uri: 'https://facebook.github.io/react/img/logo_og.png'}}
       />
       <Image source={{uri: "https://i.imgur.com/2onYRdN.png"}} />
     </View>
    );
  }
}
```

**Comment by dikaiosune** [comment]
The first image URL returns a 404, and the second one needs to have height/width set somehow: https://snack.expo.io/HJID70X6Z

**Comment by dhruvdutt** [comment]
Ah! Gotcha. The 404 link was from react-native official docs actually. :grin: 
Anyways, thanks.
