### ISSUE TITLE
Babel Preset Env by default

### ISSUE THREAD

**Issue by deadcoder0904** [react-community/create-react-native-app#444]
From http://babeljs.io/env

> We’re super 😸 excited that you’re trying to use ES2015 syntax, but instead of continuing yearly presets, the team recommends using babel-preset-env. By default, it has the same behavior as previous presets to compile ES2015+ to ES5.

**Comment by brentvatne** [comment]
feel free to submit a pr to react-native to handle this. we just inherit the preset from there. https://github.com/facebook/react-native
