### ISSUE TITLE
Component gets mounted twice

### ISSUE THREAD

**Issue by DaniyarJakupov** [react-community/create-react-native-app#445]
## Description
I have a class based react component. When I call `setState` inside `componentDidMount` I'm getting this message:
```
Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.
```
The function that I'm trying to execute inside `componentDidMount` is a combination of `setState`, `setInterval` and `setTimeout`. All of it I need to gradually increase a certain number.
The actual component is rendered separately inside storybook. The warning shows up after I switch between this component and any other one. 

There is a similar [issue](https://github.com/gaearon/react-hot-loader/issues/457) in react-hot-loader repo, but the solution involves changing Babel config. With CRNA I wasn't be able to solve it.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@1.3.1
* `npm ls react-native`: react-native@0.48.4
* `npm ls expo`: expo@21.0.2
* `node -v`: v8.1.3
* `npm -v`: 5.4.1
* `yarn --version`: 1.1.0
* `watchman version`: "4.7.0"

Also specify:

1. Operating system: macOS Sierra

**Comment by brentvatne** [comment]
hello! this is best suited for stackoverflow. it is not related to CRNA itself. also, i recommend posting code to reproduce it :)
