### ISSUE TITLE
npm install --save react-navigation - peer react@>=15.4.0 not installed

### ISSUE THREAD

**Issue by generhim** [react-community/create-react-native-app#450]
## Description

When attempting to install react-navigation I run into npm warnings about peer, react@>=15.4.0 not being installed. 

## Expected Behavior

What action did you perform, and what did you expect to happen?
Actions were as follows:
1.) create-react-native-app myAppName
2.) cd myAppName/
3.) npm install --save react-navigation
4.) Expecting successful installation of react-navigation...

## Observed Behavior

```npm install --save react-navigation```

I get the following errors: 
```
npm install --save react-navigation
navigation2@0.1.0 /Users/myaccount/react_native/tests/navigation
└── react-navigation@1.0.0-beta.15 

npm WARN react-native-branch@2.0.0-beta.3 requires a peer of react@>=15.4.0 but none was installed.
npm WARN react-native-gesture-handler@1.0.0-alpha.22 requires a peer of react@> 15.0.0 but none was installed.
USBUR60WB147306:navigation $ 
```

## Environment

* `npm ls react-native-scripts`: react-native-scripts@1.5.0
* `npm ls react-native`: react-native@0.48.4 
* `npm ls expo`: expo@21.0.2
* `node -v`: v8.2.1
* `npm -v`: 4.6.1
* `yarn --version`: 1.2.1
* `watchman version`: command not found

Also specify:

1. Operating system: Mac OS X - 10.11.6
2. Phone/emulator/simulator & version: Android

**Comment by brentvatne** [comment]
peer dependency warnings are essentially meaningless given the strange semver policy that npm has chosen. you can ignore them. if you're curious, see more info at: https://github.com/npm/npm/issues/8854
