### ISSUE TITLE
No Androidmanifest with CRNA?

### ISSUE THREAD

**Issue by meurling** [react-community/create-react-native-app#452]
Hello!
I am currently working on a project where I use CRNA. However, some plugins, for example this one: https://www.npmjs.com/package/react-native-photo-upload, require me to edit the Androidmanifest manually, but I can't seem to find the manifest as easily as when I use react-native init to create a project. Is there a workaround for this?
Thanks,

**Comment by uxman-sherwani** [comment]
You cannot use plugins which require native code with a CRNA project. You can use JS-Only plugins or the components which are provided by Expo and in this case you don't need and native andorid/ios configurations. You can try out https://docs.expo.io/versions/latest/sdk/imagepicker.html

**Comment by brentvatne** [comment]
see http://native.directory/ which allows you to see which projects are compatible
