### ISSUE TITLE
Running on Expo not showing developer menu

### ISSUE THREAD

**Issue by KeevanDance** [react-community/create-react-native-app#454]
Starting the application using `yarn start` takes me to my application, however, when shaking the device after the app loading does not bring up the developer menu. I have restarted my phone, the development server, and more with still no luck. I can provide more information if need be

I am running my app on a Samsung Galaxy S7Edge

**Comment by KeevanDance** [comment]
Update, trying to open it on a coworkers device (iOS) worked perfectly fine. No idea what could be causing this.

**Comment by tcdavis** [comment]
Only thing I could thing of is if maybe you were running a published version of the experience?  Shaking the device should display the developer menu on Android as well as iOS.  Are you still encountering this issue?

**Comment by KeevanDance** [comment]
I started another create-react-native-app, and it worked fine! I am thinking there was some bug in my code and instead of throwing an error or warning, it would just silently fail or something? Not entirely sure...

**Comment by tcdavis** [comment]
I'm not entirely sure either.  Glad you're unblocked!
