### ISSUE TITLE
Build failed with an exception: Could not list contents of /node_modules/fbjs-scripts/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/.bin/defs

### ISSUE THREAD

**Issue by blazevignesh** [react-community/create-react-native-app#456]
**Exception occurred in fbjs-scripts node module**

FAILURE: Build failed with an exception.
* What went wrong:
Could not list contents of '/home/xxx/Documents/JBv2-master-49f125383eec0193f22aa71282abcdfc848f5788/node_modules/fbjs-scripts/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/.bin/defs'.

## Expected Behavior

i want deploy React Native Android app of Release version to device.

## Observed Behavior
Exception occurred while i am running  **cd android && ./gradlew assembleRelease** command.
I tried something to fix it
**rm /home/xxxx/Documents/JBv2-master-49f125383eec0193f22aa71282abcdfc848f5
788/node_modules/regenerator/node_modules/.bin/defs**
But it didn't work out...

*:~/Documents/JBv2-master-49f125383eec0193f22aa71282abcdfc848f5788$ cd android && ./gradlew assembleRelease
:AirMaps:compileLint
:AirMaps:copyReleaseLint UP-TO-DATE
:AirMaps:preBuild UP-TO-DATE
:AirMaps:preReleaseBuild UP-TO-DATE
:AirMaps:checkReleaseManifest
:AirMaps:preDebugAndroidTestBuild UP-TO-DATE
:AirMaps:preDebugBuild UP-TO-DATE
:AirMaps:preDebugUnitTestBuild UP-TO-DATE
:AirMaps:preReleaseUnitTestBuild UP-TO-DATE
:AirMaps:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:AirMaps:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:AirMaps:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
:AirMaps:prepareComFacebookFrescoDrawee081Library UP-TO-DATE
:AirMaps:prepareComFacebookFrescoFbcore081Library UP-TO-DATE
:AirMaps:prepareComFacebookFrescoFresco081Library UP-TO-DATE
:AirMaps:prepareComFacebookFrescoImagepipeline081Library UP-TO-DATE
:AirMaps:prepareComFacebookFrescoImagepipelineOkhttp081Library UP-TO-DATE
:AirMaps:prepareComFacebookReactReactNative0201Library UP-TO-DATE
:AirMaps:prepareComGoogleAndroidGmsPlayServicesBase840Library UP-TO-DATE
:AirMaps:prepareComGoogleAndroidGmsPlayServicesBasement840Library UP-TO-DATE
:AirMaps:prepareComGoogleAndroidGmsPlayServicesMaps840Library UP-TO-DATE
:AirMaps:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:AirMaps:prepareReleaseDependencies
:AirMaps:compileReleaseAidl UP-TO-DATE
:AirMaps:compileReleaseRenderscript UP-TO-DATE
:AirMaps:generateReleaseBuildConfig UP-TO-DATE
:AirMaps:generateReleaseAssets UP-TO-DATE
:AirMaps:mergeReleaseAssets UP-TO-DATE
:AirMaps:generateReleaseResValues UP-TO-DATE
:AirMaps:generateReleaseResources UP-TO-DATE
:AirMaps:mergeReleaseResources UP-TO-DATE
:AirMaps:processReleaseManifest UP-TO-DATE
:AirMaps:processReleaseResources UP-TO-DATE
:AirMaps:generateReleaseSources UP-TO-DATE
:AirMaps:processReleaseJavaRes UP-TO-DATE
:AirMaps:compileReleaseJavaWithJavac UP-TO-DATE
:AirMaps:extractReleaseAnnotations UP-TO-DATE
:AirMaps:mergeReleaseProguardFiles UP-TO-DATE
:AirMaps:packageReleaseJar UP-TO-DATE
:AirMaps:compileReleaseNdk UP-TO-DATE
:AirMaps:packageReleaseJniLibs UP-TO-DATE
:AirMaps:packageReleaseLocalJar UP-TO-DATE
:AirMaps:packageReleaseRenderscript UP-TO-DATE
:AirMaps:packageReleaseResources UP-TO-DATE
:AirMaps:bundleRelease UP-TO-DATE
:AirMaps:compileReleaseSources UP-TO-DATE
:AirMaps:assembleRelease UP-TO-DATE
:app:preBuild UP-TO-DATE
:app:preReleaseBuild UP-TO-DATE
:app:checkReleaseManifest
:app:preDebugBuild UP-TO-DATE
:react-native-adjust:compileLint
:react-native-adjust:copyReleaseLint UP-TO-DATE
:react-native-adjust:preBuild UP-TO-DATE
:react-native-adjust:preReleaseBuild UP-TO-DATE
:react-native-adjust:checkReleaseManifest
:react-native-adjust:preDebugAndroidTestBuild UP-TO-DATE
:react-native-adjust:preDebugBuild UP-TO-DATE
:react-native-adjust:preDebugUnitTestBuild UP-TO-DATE
:react-native-adjust:preReleaseUnitTestBuild UP-TO-DATE
:react-native-adjust:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-adjust:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:react-native-adjust:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
:react-native-adjust:prepareComFacebookFrescoDrawee081Library UP-TO-DATE
:react-native-adjust:prepareComFacebookFrescoFbcore081Library UP-TO-DATE
:react-native-adjust:prepareComFacebookFrescoFresco081Library UP-TO-DATE
:react-native-adjust:prepareComFacebookFrescoImagepipeline081Library UP-TO-DATE
:react-native-adjust:prepareComFacebookFrescoImagepipelineOkhttp081Library UP-TO-DATE
:react-native-adjust:prepareComFacebookReactReactNative0201Library UP-TO-DATE
:react-native-adjust:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-adjust:prepareReleaseDependencies
:react-native-adjust:compileReleaseAidl UP-TO-DATE
:react-native-adjust:compileReleaseRenderscript UP-TO-DATE
:react-native-adjust:generateReleaseBuildConfig UP-TO-DATE
:react-native-adjust:generateReleaseAssets UP-TO-DATE
:react-native-adjust:mergeReleaseAssets UP-TO-DATE
:react-native-adjust:generateReleaseResValues UP-TO-DATE
:react-native-adjust:generateReleaseResources UP-TO-DATE
:react-native-adjust:mergeReleaseResources UP-TO-DATE
:react-native-adjust:processReleaseManifest UP-TO-DATE
:react-native-adjust:processReleaseResources UP-TO-DATE
:react-native-adjust:generateReleaseSources UP-TO-DATE
:react-native-adjust:processReleaseJavaRes UP-TO-DATE
:react-native-adjust:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-adjust:extractReleaseAnnotations UP-TO-DATE
:react-native-adjust:mergeReleaseProguardFiles UP-TO-DATE
:react-native-adjust:packageReleaseJar UP-TO-DATE
:react-native-adjust:compileReleaseNdk UP-TO-DATE
:react-native-adjust:packageReleaseJniLibs UP-TO-DATE
:react-native-adjust:packageReleaseLocalJar UP-TO-DATE
:react-native-adjust:packageReleaseRenderscript UP-TO-DATE
:react-native-adjust:packageReleaseResources UP-TO-DATE
:react-native-adjust:bundleRelease UP-TO-DATE
:react-native-camera:compileLint
:react-native-camera:copyReleaseLint UP-TO-DATE
:react-native-camera:preBuild UP-TO-DATE
:react-native-camera:preReleaseBuild UP-TO-DATE
:react-native-camera:checkReleaseManifest
:react-native-camera:preDebugAndroidTestBuild UP-TO-DATE
:react-native-camera:preDebugBuild UP-TO-DATE
:react-native-camera:preDebugUnitTestBuild UP-TO-DATE
:react-native-camera:preReleaseUnitTestBuild UP-TO-DATE
:react-native-camera:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-camera:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:react-native-camera:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
:react-native-camera:prepareComFacebookFrescoDrawee081Library UP-TO-DATE
:react-native-camera:prepareComFacebookFrescoFbcore081Library UP-TO-DATE
:react-native-camera:prepareComFacebookFrescoFresco081Library UP-TO-DATE
:react-native-camera:prepareComFacebookFrescoImagepipeline081Library UP-TO-DATE
:react-native-camera:prepareComFacebookFrescoImagepipelineOkhttp081Library UP-TO-DATE
:react-native-camera:prepareComFacebookReactReactNative0201Library UP-TO-DATE
:react-native-camera:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-camera:prepareReleaseDependencies
:react-native-camera:compileReleaseAidl UP-TO-DATE
:react-native-camera:compileReleaseRenderscript UP-TO-DATE
:react-native-camera:generateReleaseBuildConfig UP-TO-DATE
:react-native-camera:generateReleaseAssets UP-TO-DATE
:react-native-camera:mergeReleaseAssets UP-TO-DATE
:react-native-camera:generateReleaseResValues UP-TO-DATE
:react-native-camera:generateReleaseResources UP-TO-DATE
:react-native-camera:mergeReleaseResources UP-TO-DATE
:react-native-camera:processReleaseManifest UP-TO-DATE
:react-native-camera:processReleaseResources UP-TO-DATE
:react-native-camera:generateReleaseSources UP-TO-DATE
:react-native-camera:processReleaseJavaRes UP-TO-DATE
:react-native-camera:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-camera:extractReleaseAnnotations UP-TO-DATE
:react-native-camera:mergeReleaseProguardFiles UP-TO-DATE
:react-native-camera:packageReleaseJar UP-TO-DATE
:react-native-camera:compileReleaseNdk UP-TO-DATE
:react-native-camera:packageReleaseJniLibs UP-TO-DATE
:react-native-camera:packageReleaseLocalJar UP-TO-DATE
:react-native-camera:packageReleaseRenderscript UP-TO-DATE
:react-native-camera:packageReleaseResources UP-TO-DATE
:react-native-camera:bundleRelease UP-TO-DATE
:react-native-datetime-picker:compileLint
:react-native-datetime-picker:copyReleaseLint UP-TO-DATE
:react-native-datetime-picker:preBuild UP-TO-DATE
:react-native-datetime-picker:preReleaseBuild UP-TO-DATE
:react-native-datetime-picker:checkReleaseManifest
:react-native-datetime-picker:preDebugAndroidTestBuild UP-TO-DATE
:react-native-datetime-picker:preDebugBuild UP-TO-DATE
:react-native-datetime-picker:preDebugUnitTestBuild UP-TO-DATE
:react-native-datetime-picker:preReleaseUnitTestBuild UP-TO-DATE
:react-native-datetime-picker:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-datetime-picker:prepareComAndroidSupportRecyclerviewV72301LibraryUP-TO-DATE
:react-native-datetime-picker:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
:react-native-datetime-picker:prepareComFacebookFrescoDrawee081Library UP-TO-DATE
:react-native-datetime-picker:prepareComFacebookFrescoFbcore081Library UP-TO-DATE
:react-native-datetime-picker:prepareComFacebookFrescoFresco081Library UP-TO-DATE
:react-native-datetime-picker:prepareComFacebookFrescoImagepipeline081Library UP-TO-DATE
:react-native-datetime-picker:prepareComFacebookFrescoImagepipelineOkhttp081Library                                                                            UP-TO-DATE
:react-native-datetime-picker:prepareComFacebookReactReactNative0201Library UP-TO-DATE
:react-native-datetime-picker:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-datetime-picker:prepareReleaseDependencies
:react-native-datetime-picker:compileReleaseAidl UP-TO-DATE
:react-native-datetime-picker:compileReleaseRenderscript UP-TO-DATE
:react-native-datetime-picker:generateReleaseBuildConfig UP-TO-DATE
:react-native-datetime-picker:generateReleaseAssets UP-TO-DATE
:react-native-datetime-picker:mergeReleaseAssets UP-TO-DATE
:react-native-datetime-picker:generateReleaseResValues UP-TO-DATE
:react-native-datetime-picker:generateReleaseResources UP-TO-DATE
:react-native-datetime-picker:mergeReleaseResources UP-TO-DATE
:react-native-datetime-picker:processReleaseManifest UP-TO-DATE
:react-native-datetime-picker:processReleaseResources UP-TO-DATE
:react-native-datetime-picker:generateReleaseSources UP-TO-DATE
:react-native-datetime-picker:processReleaseJavaRes UP-TO-DATE
:react-native-datetime-picker:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-datetime-picker:extractReleaseAnnotations UP-TO-DATE
:react-native-datetime-picker:mergeReleaseProguardFiles UP-TO-DATE
:react-native-datetime-picker:packageReleaseJar UP-TO-DATE
:react-native-datetime-picker:compileReleaseNdk UP-TO-DATE
:react-native-datetime-picker:packageReleaseJniLibs UP-TO-DATE
:react-native-datetime-picker:packageReleaseLocalJar UP-TO-DATE
:react-native-datetime-picker:packageReleaseRenderscript UP-TO-DATE
:react-native-datetime-picker:packageReleaseResources UP-TO-DATE
:react-native-datetime-picker:bundleRelease UP-TO-DATE
:react-native-device-info:compileLint
:react-native-device-info:copyReleaseLint UP-TO-DATE
:react-native-device-info:preBuild UP-TO-DATE
:react-native-device-info:preReleaseBuild UP-TO-DATE
:react-native-device-info:checkReleaseManifest
:react-native-device-info:preDebugAndroidTestBuild UP-TO-DATE
:react-native-device-info:preDebugBuild UP-TO-DATE
:react-native-device-info:preDebugUnitTestBuild UP-TO-DATE
:react-native-device-info:preReleaseUnitTestBuild UP-TO-DATE
:react-native-device-info:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-device-info:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:react-native-device-info:prepareComAndroidSupportSupportCompat2520Library UP-TO-DATE
:react-native-device-info:prepareComAndroidSupportSupportCoreUi2520Library UP-TO-DATE
:react-native-device-info:prepareComAndroidSupportSupportCoreUtils2520Library UP-TO-DATE
:react-native-device-info:prepareComAndroidSupportSupportFragment2520Library UP-TO-DATE
:react-native-device-info:prepareComAndroidSupportSupportMediaCompat2520LibraryUP-TO-DATE
:react-native-device-info:prepareComAndroidSupportSupportV42520Library UP-TO-DATE
:react-native-device-info:prepareComFacebookFrescoDrawee081Library UP-TO-DATE
:react-native-device-info:prepareComFacebookFrescoFbcore081Library UP-TO-DATE
:react-native-device-info:prepareComFacebookFrescoFresco081Library UP-TO-DATE
:react-native-device-info:prepareComFacebookFrescoImagepipeline081Library UP-TO-DATE
:react-native-device-info:prepareComFacebookFrescoImagepipelineOkhttp081LibraryUP-TO-DATE
:react-native-device-info:prepareComFacebookReactReactNative0201Library UP-TO-DATE
:react-native-device-info:prepareComGoogleAndroidGmsPlayServicesBase1104LibraryUP-TO-DATE
:react-native-device-info:prepareComGoogleAndroidGmsPlayServicesBasement1104Library                                                                            UP-TO-DATE
:react-native-device-info:prepareComGoogleAndroidGmsPlayServicesGcm1104Library UP-TO-DATE
:react-native-device-info:prepareComGoogleAndroidGmsPlayServicesIid1104Library UP-TO-DATE
:react-native-device-info:prepareComGoogleAndroidGmsPlayServicesTasks1104Library                                                                               UP-TO-DATE
:react-native-device-info:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-device-info:prepareReleaseDependencies
:react-native-device-info:compileReleaseAidl UP-TO-DATE
:react-native-device-info:compileReleaseRenderscript UP-TO-DATE
:react-native-device-info:generateReleaseBuildConfig UP-TO-DATE
:react-native-device-info:generateReleaseAssets UP-TO-DATE
:react-native-device-info:mergeReleaseAssets UP-TO-DATE
:react-native-device-info:generateReleaseResValues UP-TO-DATE
:react-native-device-info:generateReleaseResources UP-TO-DATE
:react-native-device-info:mergeReleaseResources UP-TO-DATE
:react-native-device-info:processReleaseManifest UP-TO-DATE
:react-native-device-info:processReleaseResources UP-TO-DATE
:react-native-device-info:generateReleaseSources UP-TO-DATE
:react-native-device-info:processReleaseJavaRes UP-TO-DATE
:react-native-device-info:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-device-info:extractReleaseAnnotations UP-TO-DATE
:react-native-device-info:mergeReleaseProguardFiles UP-TO-DATE
:react-native-device-info:packageReleaseJar UP-TO-DATE
:react-native-device-info:compileReleaseNdk UP-TO-DATE
:react-native-device-info:packageReleaseJniLibs UP-TO-DATE
:react-native-device-info:packageReleaseLocalJar UP-TO-DATE
:react-native-device-info:packageReleaseRenderscript UP-TO-DATE
:react-native-device-info:packageReleaseResources UP-TO-DATE
:react-native-device-info:bundleRelease UP-TO-DATE
:react-native-paypal:compileLint
:react-native-paypal:copyReleaseLint UP-TO-DATE
:react-native-paypal:preBuild UP-TO-DATE
:react-native-paypal:preReleaseBuild UP-TO-DATE
:react-native-paypal:checkReleaseManifest
:react-native-paypal:preDebugAndroidTestBuild UP-TO-DATE
:react-native-paypal:preDebugBuild UP-TO-DATE
:react-native-paypal:preDebugUnitTestBuild UP-TO-DATE
:react-native-paypal:preReleaseUnitTestBuild UP-TO-DATE
:react-native-paypal:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-paypal:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:react-native-paypal:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
:react-native-paypal:prepareComFacebookFrescoDrawee081Library UP-TO-DATE
:react-native-paypal:prepareComFacebookFrescoFbcore081Library UP-TO-DATE
:react-native-paypal:prepareComFacebookFrescoFresco081Library UP-TO-DATE
:react-native-paypal:prepareComFacebookFrescoImagepipeline081Library UP-TO-DATE
:react-native-paypal:prepareComFacebookFrescoImagepipelineOkhttp081Library UP-TO-DATE
:react-native-paypal:prepareComFacebookReactReactNative0201Library UP-TO-DATE
:react-native-paypal:prepareComPaypalSdkPaypalAndroidSdk2130Library UP-TO-DATE
:react-native-paypal:prepareIoCardAndroidSdk530Library UP-TO-DATE
:react-native-paypal:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-paypal:prepareReleaseDependencies
:react-native-paypal:compileReleaseAidl UP-TO-DATE
:react-native-paypal:compileReleaseRenderscript UP-TO-DATE
:react-native-paypal:generateReleaseBuildConfig UP-TO-DATE
:react-native-paypal:generateReleaseAssets UP-TO-DATE
:react-native-paypal:mergeReleaseAssets UP-TO-DATE
:react-native-paypal:generateReleaseResValues UP-TO-DATE
:react-native-paypal:generateReleaseResources UP-TO-DATE
:react-native-paypal:mergeReleaseResources UP-TO-DATE
:react-native-paypal:processReleaseManifest UP-TO-DATE
:react-native-paypal:processReleaseResources UP-TO-DATE
:react-native-paypal:generateReleaseSources UP-TO-DATE
:react-native-paypal:processReleaseJavaRes UP-TO-DATE
:react-native-paypal:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-paypal:extractReleaseAnnotations UP-TO-DATE
:react-native-paypal:mergeReleaseProguardFiles UP-TO-DATE
:react-native-paypal:packageReleaseJar UP-TO-DATE
:react-native-paypal:compileReleaseNdk UP-TO-DATE
:react-native-paypal:packageReleaseJniLibs UP-TO-DATE
:react-native-paypal:packageReleaseLocalJar UP-TO-DATE
:react-native-paypal:packageReleaseRenderscript UP-TO-DATE
:react-native-paypal:packageReleaseResources UP-TO-DATE
:react-native-paypal:bundleRelease UP-TO-DATE
:react-native-push-notification:compileLint
:react-native-push-notification:copyReleaseLint UP-TO-DATE
:react-native-push-notification:preBuild UP-TO-DATE
:react-native-push-notification:preReleaseBuild UP-TO-DATE
:react-native-push-notification:checkReleaseManifest
:react-native-push-notification:preDebugAndroidTestBuild UP-TO-DATE
:react-native-push-notification:preDebugBuild UP-TO-DATE
:react-native-push-notification:preDebugUnitTestBuild UP-TO-DATE
:react-native-push-notification:preReleaseUnitTestBuild UP-TO-DATE
:react-native-push-notification:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:react-native-push-notification:prepareComAndroidSupportRecyclerviewV72301Library                                                                              UP-TO-DATE
:react-native-push-notification:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:react-native-push-notification:prepareComFacebookFrescoDrawee081Library UP-TO-DATE
:react-native-push-notification:prepareComFacebookFrescoFbcore081Library UP-TO-DATE
:react-native-push-notification:prepareComFacebookFrescoFresco081Library UP-TO-DATE
:react-native-push-notification:prepareComFacebookFrescoImagepipeline081LibraryUP-TO-DATE
:react-native-push-notification:prepareComFacebookFrescoImagepipelineOkhttp081Library                                                                          UP-TO-DATE
:react-native-push-notification:prepareComFacebookReactReactNative0201Library UP-TO-DATE
:react-native-push-notification:prepareComGoogleAndroidGmsPlayServicesBase830Library                                                                           UP-TO-DATE
:react-native-push-notification:prepareComGoogleAndroidGmsPlayServicesBasement830Library                                                                       UP-TO-DATE
:react-native-push-notification:prepareComGoogleAndroidGmsPlayServicesGcm830Library                                                                            UP-TO-DATE
:react-native-push-notification:prepareComGoogleAndroidGmsPlayServicesMeasurement830Library                                                                    UP-TO-DATE
:react-native-push-notification:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-push-notification:prepareReleaseDependencies
:react-native-push-notification:compileReleaseAidl UP-TO-DATE
:react-native-push-notification:compileReleaseRenderscript UP-TO-DATE
:react-native-push-notification:generateReleaseBuildConfig UP-TO-DATE
:react-native-push-notification:generateReleaseAssets UP-TO-DATE
:react-native-push-notification:mergeReleaseAssets UP-TO-DATE
:react-native-push-notification:generateReleaseResValues UP-TO-DATE
:react-native-push-notification:generateReleaseResources UP-TO-DATE
:react-native-push-notification:mergeReleaseResources UP-TO-DATE
:react-native-push-notification:processReleaseManifest UP-TO-DATE
:react-native-push-notification:processReleaseResources UP-TO-DATE
:react-native-push-notification:generateReleaseSources UP-TO-DATE
:react-native-push-notification:processReleaseJavaRes UP-TO-DATE
:react-native-push-notification:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-push-notification:extractReleaseAnnotations UP-TO-DATE
:react-native-push-notification:mergeReleaseProguardFiles UP-TO-DATE
:react-native-push-notification:packageReleaseJar UP-TO-DATE
:react-native-push-notification:compileReleaseNdk UP-TO-DATE
:react-native-push-notification:packageReleaseJniLibs UP-TO-DATE
:react-native-push-notification:packageReleaseLocalJar UP-TO-DATE
:react-native-push-notification:packageReleaseRenderscript UP-TO-DATE
:react-native-push-notification:packageReleaseResources UP-TO-DATE
:react-native-push-notification:bundleRelease UP-TO-DATE
:react-native-share:compileLint
:react-native-share:copyReleaseLint UP-TO-DATE
:react-native-share:preBuild UP-TO-DATE
:react-native-share:preReleaseBuild UP-TO-DATE
:react-native-share:checkReleaseManifest
:react-native-share:preDebugAndroidTestBuild UP-TO-DATE
:react-native-share:preDebugBuild UP-TO-DATE
:react-native-share:preDebugUnitTestBuild UP-TO-DATE
:react-native-share:preReleaseUnitTestBuild UP-TO-DATE
:react-native-share:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-share:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:react-native-share:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
:react-native-share:prepareComFacebookFrescoDrawee081Library UP-TO-DATE
:react-native-share:prepareComFacebookFrescoFbcore081Library UP-TO-DATE
:react-native-share:prepareComFacebookFrescoFresco081Library UP-TO-DATE
:react-native-share:prepareComFacebookFrescoImagepipeline081Library UP-TO-DATE
:react-native-share:prepareComFacebookFrescoImagepipelineOkhttp081Library UP-TO-DATE
:react-native-share:prepareComFacebookReactReactNative0201Library UP-TO-DATE
:react-native-share:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-share:prepareReleaseDependencies
:react-native-share:compileReleaseAidl UP-TO-DATE
:react-native-share:compileReleaseRenderscript UP-TO-DATE
:react-native-share:generateReleaseBuildConfig UP-TO-DATE
:react-native-share:generateReleaseAssets UP-TO-DATE
:react-native-share:mergeReleaseAssets UP-TO-DATE
:react-native-share:generateReleaseResValues UP-TO-DATE
:react-native-share:generateReleaseResources UP-TO-DATE
:react-native-share:mergeReleaseResources UP-TO-DATE
:react-native-share:processReleaseManifest UP-TO-DATE
:react-native-share:processReleaseResources UP-TO-DATE
:react-native-share:generateReleaseSources UP-TO-DATE
:react-native-share:processReleaseJavaRes UP-TO-DATE
:react-native-share:compileReleaseJavaWithJavac UP-TO-DATE
:react-native-share:extractReleaseAnnotations UP-TO-DATE
:react-native-share:mergeReleaseProguardFiles UP-TO-DATE
:react-native-share:packageReleaseJar UP-TO-DATE
:react-native-share:compileReleaseNdk UP-TO-DATE
:react-native-share:packageReleaseJniLibs UP-TO-DATE
:react-native-share:packageReleaseLocalJar UP-TO-DATE
:react-native-share:packageReleaseRenderscript UP-TO-DATE
:react-native-share:packageReleaseResources UP-TO-DATE
:react-native-share:bundleRelease UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:app:prepareComFacebookAndroidFacebookAndroidSdk470Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee081Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore081Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco081Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline081Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp081Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0201Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBase840Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBasement840Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesGcm810Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesMaps840Library UP-TO-DATE
:app:prepareComPaypalSdkPaypalAndroidSdk2130Library UP-TO-DATE
:app:prepareIoCardAndroidSdk530Library UP-TO-DATE
:app:prepareJimmyBringsAirMapsUnspecifiedLibrary UP-TO-DATE
:app:prepareJimmyBringsReactNativeAdjustUnspecifiedLibrary UP-TO-DATE
:app:prepareJimmyBringsReactNativeCameraUnspecifiedLibrary UP-TO-DATE
:app:prepareJimmyBringsReactNativeDatetimePickerUnspecifiedLibrary UP-TO-DATE
:app:prepareJimmyBringsReactNativeDeviceInfoUnspecifiedLibrary UP-TO-DATE
:app:prepareJimmyBringsReactNativePaypalUnspecifiedLibrary UP-TO-DATE
:app:prepareJimmyBringsReactNativePushNotificationUnspecifiedLibrary UP-TO-DATE
:app:prepareJimmyBringsReactNativeShareUnspecifiedLibrary UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareReleaseDependencies
:app:compileReleaseAidl
:app:compileReleaseRenderscript
:app:generateReleaseBuildConfig
:app:generateReleaseAssets UP-TO-DATE
:app:mergeReleaseAssets
:app:generateReleaseResValues
:app:generateReleaseResources
:app:mergeReleaseResources
AAPT: /home/xxxx/Documents/JBv2-master-49f125383eec0193f22aa71282abcdfc848f5788/android/app/src/main/res/drawable-mdpi/images_map.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
:app:bundleReleaseJsAndAssets

FAILURE: Build failed with an exception.

* What went wrong:
Could not list contents of '/home/xxxx/Documents/JBv2-master-49f125383eec0193f22aa71282abcdfc848f5788/node_modules/fbjs-scripts/node_modules/babel/node_modules/babel-core/node_modules/regenerator/node_modules/.bin/defs'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
*

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: JBv2-master-49f125383eec0193f22aa71282abcdfc848f5788
`-- (empty)

* `npm ls react-native`:
* `npm ls expo`: /JBv2-master-49f125383eec0193f22aa71282abcdfc848f5788
`-- (empty)

* `node -v`: v8.6.0
* `npm -v`: 5.3.0
* `yarn --version`:
* `watchman version`:  watchman version
{
    "version": "4.4.0"
}

Also specify:

1. Operating system: ubuntu 16.04 LTS
2. Phone/emulator/simulator & version:

**Comment by brentvatne** [comment]
hi there! sorry, when you eject you're kind of on your own with these sorts of issues -- we can no longer help to debug at this point as there are too many unknowns. stackoverflow could be a good place to get help!
