### ISSUE TITLE
Minification breaks a 3rd party lib -- possible to configure UglifyJS?

### ISSUE THREAD

**Issue by smoll** [react-community/create-react-native-app#457]
## Description

I reported this issue to the library maintainers and the leading theory is that it's caused by the minifier is mangling class names that are subsequently [identified by their representative string](https://github.com/stems/join-monster/issues/250#issuecomment-339173181).

A possible fix is to pass the `mangle.except` option to `UglifyJS`. Does CRNA expose this anywhere, and if ejection is required, how would I configure the minifier in this manner?

I tried looking for hints in the upstream project https://github.com/facebook/metro-bundler but it's not obvious that there's any way to override [this flag](https://github.com/facebook/metro-bundler/blob/afb91bccd31a5a1ffd8e5d6b735ff789765655ba/packages/metro-bundler/src/JSTransformer/worker/minify.js#L41).

## Expected Behavior

N/A

## Observed Behavior

N/A

## Environment

N/A

## Reproducible Demo

N/A. I wrote a minimal repro of the original issue [here](https://github.com/smoll/monster) but it's not entirely relevant to this inquiry/feature request.

**Comment by smoll** [comment]
CRNA probably doesn't and won't support this, so I'm switching to https://github.com/callstack/haul

**Comment by brentvatne** [comment]
Probably the easiest way to make this work is to just add a npm postinstall script to modify that config for you in node_modules. The best way would be to submit a patch to metro to make it configurable
