### ISSUE TITLE
Best approach to use my own build of react-native-scripts

### ISSUE THREAD

**Issue by chochihim** [react-community/create-react-native-app#459]
Currently, the js-bundle of a newly created project consists of only one js file - App.js under https://github.com/react-community/create-react-native-app/tree/master/react-native-scripts/template.

I want a little more complex app structure and to add extra dependencies so that 
1) my team can use a standard set of libraries.
2) newbies can pick up things more quickly by following standard project structure.

For example, in my company, we use [react-navigation](https://github.com/react-community/react-navigation) for navigation. I would like to add it as a dependency and also add a few more js files to demonstrate its usage.

So I want to use my own copy of react-native-scripts. The only way I can figure out at this moment is to keep a .tgz of my own build and ask my team to create project by `$ create-react-native-app my-app --scripts-version path-to-my-own-tgz`. But I think there should be better ways. Can anyone suggest?

**Comment by brentvatne** [comment]
heya! you could make your own cli tool that wraps create-react-native-app and uses your scripts version by default :) `create-my-company-app app-name`. alternatively, you can create a repo that people just clone to get started!

hopefully that helps!

**Comment by chochihim** [comment]
@brentvatne There is one problem I don't know how to solve. 

If I create a own repo for `create-react-native-app`, `react-native-scripts` would be a sub-directory of this git repo. How can I point to it? 

If I create a repo for `react-native-scripts`, how can I sync it with the official one?
