### ISSUE TITLE
invalid characters error using create-react-native-app

### ISSUE THREAD

**Issue by bear-bibeault** [react-community/create-react-native-app#463]
# Description

When running create-react-native-app an error is displayed: An unexpected error occurred: "https://registry.yarnpkg.com/@expo%2fbunyan: The header content contains invalid characters".

## Expected Behavior

Expected successful creation of new application.

## Observed Behavior

Here is the transcript:

```
$ create-react-native-app AwesomeProject
Creating a new React Native app in /Users/bbibeault/Dropbox/Development/projects/native/AwesomeProject.

Using package manager as yarnpkg with yarn interface.
Installing packages. This might take a couple minutes.
Installing react-native-scripts...

yarn add v0.18.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@expo%2fbunyan: The header content contains invalid characters".
info If you think this is a bug, please open a bug report with the information provided in "/Users/bbibeault/Dropbox/Development/projects/native/AwesomeProject/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
`yarnpkg add --dev --exact --ignore-optional react-native-scripts` failed```
```
## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
AwesomeProject@0.1.0 /Users/bbibeault/Dropbox/Development/projects/native/AwesomeProject
└── (empty)

npm ERR! code 1

* `npm ls react-native`:
AwesomeProject@0.1.0 /Users/bbibeault/Dropbox/Development/projects/native/AwesomeProject
└── (empty)

npm ERR! code 1

* `npm ls expo`:
AwesomeProject@0.1.0 /Users/bbibeault/Dropbox/Development/projects/native/AwesomeProject
└── (empty)

npm ERR! code 1* `node -v`:

* `npm -v`:
3.10.8

* `yarn --version`:
0.18.1

* `watchman version`:
0.1.8

Also specify:

1. Operating system:
Mac OS X Sierra

2. Phone/emulator/simulator & version:
none

## Reproducible Demo

Obviously nothing to post here yet.

**Comment by brentvatne** [comment]
I think yarn 0.18.1 is like a year old, when it was still a wee baby of an OSS project. If you update to latest yarn (1.3.2) that will fix the problem. Sorry this is not a CRNA bug, it is a bug in the package manager, so I am closing the issue
