### ISSUE TITLE
Specify dependency versions in package.json

### ISSUE THREAD

**Issue by Floppy** [react-community/create-react-native-app#464]
## Description

`package.json` doesn't specify versions of dependencies (react, etc). Instead we have to refer to https://github.com/react-community/create-react-native-app/blob/master/VERSIONS.md when upgrading.

I assume there must be a good reason for not specifying these dependencies in `package.json`, but as I couldn't find a discussion on it in the issue list, I thought I'd open one. Forgive me if my search skills failed and this is a duplicate!

## Expected Behavior

I expect package.json to define the correct dependencies so npm/yarn can work them all out itself.

## Observed Behavior

I have to manually manage a set of interrelated dependencies.

**Comment by Floppy** [comment]
I *assume* that this is because create-react-native-app will work with any of those combinations. However, I'd suggest that for ease of development and upgrade, having CRNA locked to the latest valid combination would be sensible.

**Comment by brentvatne** [comment]
I don't understand the question. package.json does specify the correct versions, but when you want to update then you need to change those versions. If the versions are not in your package.json you are probably using npm 5.x, which is extremely buggy still, so as the README suggests, use npm 3, 4 or yarn.

package.json on a brand new project:

```
{
  "name": "Issue464Example",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "1.7.0",
    "jest-expo": "^22.0.0",
    "react-test-renderer": "16.0.0-beta.5"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^22.0.2",
    "react": "16.0.0-beta.5",
    "react-native": "^0.49.5"
  }
}
```

**Comment by Floppy** [comment]
Ah, no, sorry, I meant in the `package.json` of create-react-native-app itself, so that when installing or upgrading it, it can sensibly install a set of working versions of its dependencies.

**Comment by brentvatne** [comment]
oh, those are in react-native-scripts: https://github.com/react-community/create-react-native-app/blob/7402574e8be1474453e568ab467abc4501c9b3e2/react-native-scripts/src/scripts/init.js

**Comment by Floppy** [comment]
Aha, OK, thanks. :)
