### ISSUE TITLE
Couldn't find package "@expo/bunyan" on the "npm" registry

### ISSUE THREAD

**Issue by eduardoinnorway** [react-community/create-react-native-app#465]
Have added with NPM and Yarn, still same result

yarn add v0.24.5
info No lockfile found.
[1/4] 🔍  Resolving packages...
error Couldn't find package "@expo/bunyan" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
`yarnpkg add --dev --exact --ignore-optional react-native-scripts` failed

**Comment by eduardoinnorway** [comment]
Come on, you wan't people to use your framework and you can't even make sure that the simplest get started example works?

**Comment by brentvatne** [comment]
use the normal npm registry. if it's still a problem, this is a npm bug, so open the issue there.

**Comment by nmonti** [comment]
Realized I had the company's registry, setting it to default worked. I've never had a problem installing other packages so I didn't bother to check that out. Thanks!

**Comment by michaelkantor** [comment]
As far as I can tell, I am using the default npm registry. I have tried this with various versions of nodejs (7.x, 6.x and now 9.x) and various versions of `npm` as well.  I've done:

```
sudo npm uninstall -g create-react-native-app
sudo npm install -g create-react-native-app
```
to reinstall with the latest versions of everything.  I'm running on the latest version of High Sierra. And I continue to see the above errors when running `create-react-native-app my-app`.

I'm rather baffled by this.

Logs:
```
verbose 0.805 Request "https://registry.yarnpkg.com/lru-cache" finished with status code 200.
verbose 0.807 Performing "GET" request to "https://registry.yarnpkg.com/external-editor".
verbose 0.863 Request "https://registry.yarnpkg.com/@expo%2fbunyan" finished with status code 404.
verbose 0.863 Performing "GET" request to "https://registry.yarnpkg.com/figures".
verbose 0.864 Error: Couldn't find package "@expo/bunyan@1.8.10" required by "react-native-scripts" on the "npm" registry.
    at new MessageError (/usr/local/Cellar/yarn/1.5.1_1/libexec/lib/cli.js:186:110)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.5.1_1/libexec/lib/cli.js:36274:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.5.1_1/libexec/lib/cli.js:98:30)
    at /usr/local/Cellar/yarn/1.5.1_1/libexec/lib/cli.js:111:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)

```

**Comment by nessalauren5** [comment]
Fixed a similar issue by install a missing prereq react-native-cli 

> Make sure you have a React Native CLI installed on your machine. To install it, run the following command in the Terminal: npm install -g react-native-cli.

**Comment by luizfilipe** [comment]
I have the same problem with npm registry configured for https://registry.npmjs.org/
it's giving 404 for all packages named like `@expo/bunyan` or `@expo/osascript`.

I've also installed react-native-cli... that does not work. It seems to be an npm problem.
