### ISSUE TITLE
npm ERR! missing script: start

### ISSUE THREAD

**Issue by GitHubMurt** [react-community/create-react-native-app#467]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

I native android developer and have no expirience with node.
I followed instructions on [official documentation](https://facebook.github.io/react-native/docs/getting-started.html) how ever i can fire up node using `npm start`

## Observed Behavior

>npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\...\npm-cache\_logs\2017-11-05T16_45_01_380Z-debug.log

E:\...\ReactNative\hello_world>npm info

{ name: 'hello_world',
  description: 'Try',
  'dist-tags': { latest: '0.0.3' },
  versions: [ '0.0.1', '0.0.2', '0.0.3' ],
  maintainers: [ '42thcoder <42thcoder@gmail.com>' ],
  time:
   { modified: '2015-01-23T03:42:13.291Z',
     created: '2015-01-22T11:49:34.817Z',
     '0.0.1': '2015-01-22T11:49:34.817Z',
     '0.0.2': '2015-01-22T11:52:17.447Z',
     '0.0.3': '2015-01-23T03:42:13.291Z' },
  keywords: [ 'hello' ],
  author: '42thcoder',
  license: 'MIT',
  readmeFilename: '',
  version: '0.0.3',
  main: 'index.js',
  scripts: { test: 'echo "Error: no test specified" && exit 1' },
  dist:
   { shasum: 'db190a02cdcbfed9775a3ceab7b1e0b43617318b',
     tarball: 'https://registry.npmjs.org/hello_world/-/hello_world-0.0.3.tgz' },
  directories: {} }

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:  react-native-scripts@1.7.0
* `npm ls react-native`: -- (empty)
* `npm ls expo`:
* `node -v`: v8.9.0
* `npm -v`: 5.5.1
* `yarn --version`:
* `watchman version`:

Windows 10

[2017-11-05T17_04_19_844Z-debug.log](https://github.com/react-community/create-react-native-app/files/1444245/2017-11-05T17_04_19_844Z-debug.log)

![package json](https://user-images.githubusercontent.com/12357195/32417110-8016d35e-c254-11e7-82db-9c79392608c9.png)

**Comment by brentvatne** [comment]
please use `yarn` instead of npm. npm 5 is very buggy. [from the README:](https://github.com/react-community/create-react-native-app#installation)

> You'll need to have Node v6 or later on your machine. We strongly recommend using npm v3, v4, or a recent version of Yarn. Create React Native App does not currently work with npm v5 due to bugs in npm (you can track the issue [here](https://github.com/react-community/create-react-native-app/issues/233#issuecomment-305638103)).

to install yarn and use it instead, run `npm i -g yarn` and then `yarn global add create-react-native-app` and `create-react-native-app your-project`

**Comment by GitHubMurt** [comment]
Hmm 

```
yarn install v1.3.2
[1/4] Resolving packages...
warning react-native > connect@2.30.2: connect 2.x series is deprecated
[2/4] Fetching packages...
[#############################################################################################################] 947/948
```

and it stopped, you might know why?
