### ISSUE TITLE
Generated app has issues with dev-dependency jest-expo 22.0.0

### ISSUE THREAD

**Issue by nbkhope** [react-community/create-react-native-app#468]
## Description

Using `create-react-native-app@1.0.0` to generate an app, `npm install` fails because dev-dependency `jest-expo@22.0.0` can't find the directory `~/.npm/jest-expo/22.0.0`, but there is actually a `22.0.1` directory, which npm does not seem to use to the installation.

## Expected Behavior

There would be no problems creating the app. Npm would know to know jest-expo @ 22.0.1 directory.

## Observed Behavior

Got the following error, some parts omitted.

```
...
UNMET PEER DEPENDENCY react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0
...
npm WARN react-redux@5.0.6 requires a peer of react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0 but none was installed.
Installing dependencies using npm...

npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/someuser/.nvm/versions/node/v6.11.1/bin/node" "/Users/someuser/.nvm/versions/node/v6.11.1/bin/npm" "install" "--save"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code EREADFILE

npm ERR! Error extracting /Users/someuser/.npm/jest-expo/22.0.0/package.tgz archive: ENOENT: no such file or directory, open '/Users/someuser/.npm/jest-expo/22.0.0/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/someuser/.../SampleApp/npm-debug.log
Failed to install
```
## Environment

* `npm ls react-native-scripts`: 1.1.0
* `npm ls react-native`: 0.46.4
* `npm ls expo`: 19.0.1 `(UNMET PEER DEPENDENCY react@>=15.3.1)`
* `node -v`: v6.11.1
* `npm -v`: 3.10.10
* `yarn --version`: ---
* `watchman version`: "4.7.0"

1. Operating system: macOS Sierra 10.12.6
2. Phone/emulator/simulator & version: `iPhone 6 - iOS 10.2`, Xcode Simulator v10.0

## Comments

Changing the dev-dependency of jest-expo from `^22.0.0` to `^22.0.1` and doing `npm install` again seems to fix the problem. However, I am not sure if that version has a stable release, since using `npm install jest-expo` in a blank npm project yields the following dependency: `^22.0.1-SNAPSHOT.2017.11.1`

**Comment by ht512512** [comment]
Seeing the same issue on Ubuntu. After changing the dev-dependency and doing `npm install` it still fails in `npm start`. 

> npm ERR! Linux 4.4.0-97-generic
> npm ERR! argv "/home/hemant/HT/Downloads/Apps/node-v6.9.2-linux-x64/bin/node" "/usr/local/bin/npm" "start"
> npm ERR! node v6.9.2
> npm ERR! npm  v3.10.9
> npm ERR! code ELIFECYCLE
> npm ERR! my-app@0.1.0 start: `react-native-scripts start`
> npm ERR! Exit status 1
 
Any workaround or update? Thanks.

**Comment by brentvatne** [comment]
seems like some npm cache bug. `npm cache clean` might help
