### ISSUE TITLE
Can't run eject

### ISSUE THREAD

**Issue by pstanton** [react-community/create-react-native-app#469]
## Description

Can't run eject. I've followed the "getting started guide" and am trying to get to the point where I can publish an apk to transfer to my  #devices.

## Expected Behavior

npm run eject

## Observed Behavior

error

```
c:\cet\nodejs\AwesomeProject>npm run eject
npm ERR! missing script: eject

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[user]\AppData\Roaming\npm-cache\_logs\2017-11-06T02_36_57_026Z-debug.log
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: 1.7.0
* `npm ls react-native`:0.49.5
* `npm ls expo`: empty 
* `node -v`: v9.0.0
* `npm -v`: 5.5.1
* `yarn --version`: 1.2.1
* `watchman version`: not installed

Also specify:

1. Operating system: windows 10
2. Phone/emulator/simulator & version: Nexus_5X_API_27_x86

## Reproducible Demo
see output above

**Comment by brentvatne** [comment]
hello! can you show the contents of your package.json? I imagine you deleted the "eject' script from it

**Comment by pstanton** [comment]
my mistake, i actually created app with react-native init ... so no need to eject. sorry!

**Comment by brentvatne** [comment]
😆

**Comment by itachi97** [comment]
Hello I'm encountering the same problem. I can't run eject.


c:\Users\Kweku\AwesomeProject>npm run eject
npm ERR! missing script: eject

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[user]\AppData\Roaming\npm-cache\_logs\2017-11-06T02_36_57_026Z-debug.log

I create a react native app and this is what I'm getting.

**Comment by itachi97** [comment]
I just tried again this is what I'm getting...

Ejected successfully!
Please consider letting us know why you ejected in this survey:
  https://goo.gl/forms/iD6pl218r7fn9N0d2
The batch file cannot be found.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! App1@0.1.0 eject: `react-native-scripts eject`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the App1@0.1.0 eject script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kweku\AppData\Roaming\npm-cache\_logs\2018-07-15T08_28_34_142Z-debug.log

Please help

**Comment by itamarzil123** [comment]
itachi97, did you find the solution? i've got the same bug

**Comment by itachi97** [comment]
Yeah I did,  sometimes the eject script gets lost somehow in the package.json . Add the eject script yourself and try again. Delete the iOS and Android folder before trying again. Also, if npm is not working for install yarn and run 'yarn install --verbose' to keep a check on your node modules in the app folder. Let me know if it works for you.
