### ISSUE TITLE
tar.gz module has been deprecated warning

### ISSUE THREAD

**Issue by prog1dev** [react-community/create-react-native-app#470]
## Description

Getting warnings on `create-react-native-app AwesomeProject` command. This one `tar.gz module has been deprecated and your application is vulnerable` is especially concerning

## Observed Behavior
Here is command output

```
yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...
warning react-native-scripts > xdl > tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
warning react-native-scripts > xdl > auth0-js > xtend > object-keys@0.4.0:
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "react-redux@5.0.6" has unmet peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0".
[4/4] Building fresh packages...
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@1.7.0
* `npm ls react-native`: react-native@0.49.5
* `npm ls expo`: expo@22.0.2
* `node -v`: v7.10.1
* `npm -v`: 4.2.0
* `yarn --version`: 0.27.5

Also specify:

1. Operating system: macOs Sierra 10.12.6

**Comment by JoeyTawadrous** [comment]
Update your node version!

Cleared up the issue for me right away :)

**Comment by brentvatne** [comment]
fix coming in next release
