### ISSUE TITLE
Error when launching Dev Tools

### ISSUE THREAD

**Issue by baeckerman83** [react-community/create-react-native-app#471]
I installed crna and all went fine. I can open the app with expo on my android phone. But after some reloads I get an error when Launching the Dev Tools. 

In the packager log is:
22:34:35: Launching Dev Tools...
22:34:35: Google Chrome exited with error: { Error: spawn chromium ENOENT
22:34:35:     at exports._errnoException (util.js:1020:11)
22:34:35:     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
22:34:35:     at onErrorNT (internal/child_process.js:376:16)
22:34:35:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
22:34:35:     at process._tickCallback (internal/process/next_tick.js:104:9)
22:34:35:   code: 'ENOENT',
22:34:35:   errno: 'ENOENT',
22:34:35:   syscall: 'spawn chromium',
22:34:35:   path: 'chromium',
22:34:35:   spawnargs: [ 'http://localhost:19001/debugger-ui' ] }

What can I do to solve the error?

**Comment by fxfactorial** [comment]
Can you check if you have chrome/chormium installed on your system?

**Comment by bastieneti** [comment]
Hi,
I ve the same problem, do you find any solutions ?
Ty

**Comment by bastieneti** [comment]
Problem solved ! I just reinstall Expo on my phone....
1 day lost..

**Comment by fawaz-ahmed** [comment]
Possible duplicate of https://github.com/facebook/react-native/issues/9901

**Comment by mide42** [comment]
I could solve this issue by clearing the expo app's data & cache in the "app info".
