### ISSUE TITLE
Error starting packager: TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by travellerwjoe** [react-community/create-react-native-app#472]
## Description

When I try to use `yarn start` , I got this error. 
`Error starting packager: TypeError: Cannot read property 'version' of undefined`

## Expected Behavior

All commands I  used:
`create-react-native-app rn-awe`
`yarn start`

## Observed Behavior

Error details

```
E:\Web\Joe.Wu\rn-awe>yarn start
yarn run v1.3.2
$ react-native-scripts start
17:16:47: Starting packager...
17:17:43: Error starting packager: TypeError: Cannot read property 'version' of undef
    at E:\xdl\src\project\Doctor.js:641:44
    at E:\Web\Joe.Wu\rn-awe\node_modules\lodash\lodash.js:4944:15
    at baseForOwn (E:\Web\Joe.Wu\rn-awe\node_modules\lodash\lodash.js:3001:24)
    at E:\Web\Joe.Wu\rn-awe\node_modules\lodash\lodash.js:4913:18
    at Function.forEach (E:\Web\Joe.Wu\rn-awe\node_modules\lodash\lodash.js:9359:14)
    at E:\xdl\src\project\Doctor.js:631:9
    at Generator.next (<anonymous>)
    at step (E:\Web\Joe.Wu\rn-awe\node_modules\react-native-scripts\node_modules\xdl\
    at E:\Web\Joe.Wu\rn-awe\node_modules\react-native-scripts\node_modules\xdl\build\
    at <anonymous>
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Environment

* `npm ls react-native-scripts`: -- react-native-scripts@1.6.0
* `npm ls react-native`: -- (empty)  (Actually react-native is installed inside node_modules. I don't know why there is empty.)
* `npm ls expo`: -- (empty)
* `node -v`: v8.7.0
* `npm -v`: 5.4.2
* `yarn --version`: 1.3.2
* `watchman version`: Not installed

Also specify:

1. Operating system: Windows 7
2. Phone/emulator/simulator & version: Nubia NX549J

**Comment by fxfactorial** [comment]
It might be the case that not everything installed correctly.

Try being in `rn-awe`, `rm -rf node_modules` and then type `yarn` to install the dependencies again.

**Comment by travellerwjoe** [comment]
I try to reinstall several times, but it still does not work.

**Comment by kajm** [comment]
I installed react-native yesterday without problem. I run react-native-scripts version 1.7. Have you tried that version ?
Also i run the app with npm instead of yarn and I have read numerous problems regarding npm version 5 won't work with react-native.

**Comment by travellerwjoe** [comment]
The react-native-scripts version 1.7.0 is not in versions list.
```
E:\Web\Joe.Wu\rn-awe>yarn add react-native-scripts@1.7.0
yarn add v1.3.2
[1/4] Resolving packages...
Couldn't find any versions for "react-native-scripts" that matches "1.7.0"
? Please choose a version of "react-native-scripts" from this list: (Use arrow keys)
> 0.0.26
  0.0.1
  0.0.2
  0.0.3
  0.0.4
  0.0.5
  0.0.6
  0.0.7
  0.0.8
  0.0.9
  0.0.10
  0.0.11
  0.0.12
  0.0.13
  0.0.14
  0.0.15
  0.0.16
  0.0.17
  0.0.18
  0.0.19
  0.0.20
  0.0.21
  0.0.22
  0.0.23
  0.0.24
  0.0.25
  0.0.27
  0.0.28
  0.0.29
  0.0.30
  0.0.31
  0.0.40
  0.0.50
  1.0.0-rc.0
  1.0.0
  1.1.0
  1.2.0
  1.2.1
  1.3.0
  1.3.1
  1.5.0
  1.6.0
```
Is my yarn config registry problem?
```
E:\Web\Joe.Wu\rn-awe>yarn config list
yarn config v1.3.2
info yarn config
{ 'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'https://registry.yarnpkg.com',
  'strict-ssl': true,
  'user-agent': 'yarn/1.3.2 npm/? node/v8.7.0 win32 x64',
  lastUpdateCheck: 1511143910558 }
info npm config
{ config: 'registry=https://registry.npm.taobao.org',
  registry: 'http://r.cnpmjs.org/',
  dev: true,
  arg: '123', }
```

**Comment by brendonco** [comment]
@travellerwjoe have the same problem with you when using create-react-native-app. You might want to try  Building Projects with Native Code instead.

**Comment by travellerwjoe** [comment]
I finally find an alternative solution, which set up environments in the virtual machine based on OS win10 and install, then it works without any errors.

**Comment by brentvatne** [comment]
this is a xdl issue and @fson is investigating

**Comment by fson** [comment]
The error should be fixed in XDL and latest `react-native-scripts` (v1.11.0). You may still see a warning if `npm list` fails, but it won't crash `react-native-scripts` anymore.

**Comment by travellerwjoe** [comment]
@fson Thank you for your support. I have tried again. It works now.
