### ISSUE TITLE
Permissions error in packager-info.json

### ISSUE THREAD

**Issue by pkkalive** [react-community/create-react-native-app#475]
Guys I am Stuck here I have downgrade both my node and npm in order to run the application

currently my node version is 8.4.0 and npm is 4.6.1 Steps I did are

create-react-native-app SampleApp
cd SampleApp
npm run ios
And the result app is not working

Purushothams-MacBook-Pro:SampleApp Purushotham$ npm run ios

SampleApp@0.1.0 ios /Users/Purushotham/Desktop/Demo/SampleApp
react-native-scripts ios
21:59:37: Starting packager...
21:59:39: Error starting packager: Error: EACCES: permission denied, open '/Users/Purushotham/Desktop/Demo/SampleApp/.expo/packager-info.json'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! SampleApp@0.1.0 ios: react-native-scripts ios
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the SampleApp@0.1.0 ios script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/Purushotham/.npm/_logs/2017-11-12T16_29_39_085Z-debug.log

After executing sudo chmod -R 777 ~/.expo/ and installing expo.io application in my macbook it gets stuck like this you can see the below picture

<img width="1214" alt="screen shot 2017-11-12 at 11 00 02 pm" src="https://user-images.githubusercontent.com/4536902/32701619-1ce476fa-c7ff-11e7-87b6-70f988f84c3e.png">

**Comment by fxfactorial** [comment]
Check your permissions. 

Perhaps one thing can do is recursively change ownership of that project to your username. 

1. Double check permissions, see with `ls -halt`
2. use `chown` and the `-R` flag for recursive changes

**Comment by KendalMahy** [comment]
same issue here

**Comment by zim-lee** [comment]
same problem 
I am still facing the same issue after running
```sh 
sudo chown -R my_username ~/.expo
sudo chown -R my_username ~/.babel.json
```

**Comment by KendalMahy** [comment]
I did the "ls - halt" 
and the use "chown -R username .expo" it end up that the simulator is starting.

 But the app package is not loading on the simulator.

Some one may know where this issue could come from ?

Thanks in advance

**Comment by zjx** [comment]
same error.

**Comment by brentvatne** [comment]
not sure what's going on here. some help would be appreciated
