### ISSUE TITLE
Unable to load any app after changes are made

### ISSUE THREAD

**Issue by lrvlr** [react-community/create-react-native-app#476]
Description
Hi. I’m new to all this and getting awfully frustrated for I can’t load any app on my iphone. 

Observed Behavior
On my console I run:
> create-react-native-app myApp
> cd myApp
> npm start

I scan the code using Expo on my iphone… one in a trillion times (often the first time I follow these steps with a new project, but sometimes not even then),  it shows what it is supposed to:

Open up App.js to start working on your app!
Changes you make will automatically reload.
Shake your phone to open the developer menu.

But as soon as I try to change anything… even if it’s only the text between the tags, like:

<View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
        <Text>CHANGE SOMETHING HERE.</Text>
        <Text>Shake your phone to open the developer menu.</Text>
      </View>

if I press refresh the screen goes completely white, nothing shows anymore. If I put reload, then I get this message:

Could not connect to development server.

Ensure the following:
- Node server is running and available on the same network - run 'npm start' from react-native root
- Node server URL is correctly set in AppDelegate
- WiFi is enabled and connected to the same network as the Node Server

URL: http://192.168.0.X:19001/node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=/.../myApp/node_modules/expo/tools/hashAssetFiles

ABI21_0_0RCTFBQuickPerformanceLoggerConfigureHooks
ABI22_0_0RCTFBQuickPerformanceLoggerConfigureHooks
<redacted>
<redacted>
_dispatch_main_queue_callback_4CF
<redacted>
<redacted>
CFRunLoopRunSpecific
GSEventRunModal
<redacted>
UIApplicationMain
Exponent
<redacted>

I’ve been having like a thousand issues before that, and tried a thousand suggestions found over the web but in the end it all comes down to the same result: white screen, unable to load.
I also found this suggestions:
Try opening Safari or Chrome on your phone and loading
http://192.168.0.X:19000
and
http://192.168.0.X:19001

I tried to do so. 
http://192.168.0.X:19000 Shows this:
{"sdkVersion":"22.0.0","name":"myApp","slug":"myapp","version":"0.1.0","xde":true,"developer":{"tool":"crna","projectRoot":"/.../myApp"},"packagerOpts":{"hostType":"tunnel","lanType":"ip","dev":true,"strict":false,"minify":false,"urlType":"exp","urlRandomness":null},"env":{},"bundleUrl":"http://192.168.0.X:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=ios&dev=true&strict=false&minify=false&hot=false&assetPlugin=/.../myApp/node_modules/expo/tools/hashAssetFiles","debuggerHost":"192.168.0.194:19001","mainModuleName":"./node_modules/react-native-scripts/build/bin/crna-entry","logUrl":"http://192.168.0.X:19000/logs","id":"@anonymous/myapp-c198800e-5bde-4d29-8a44-2e1945412d25"}

http://192.168.0.X:19001  Says cant connect to the server

I would rather not follow this suggestion:
“try using the tethering/mobile hotspot feature on your phone (beware of data usage, though), connecting your computer to that WiFi network”
Can’t share my wifi connection and data connection is pretty expensive.

Finally, if I use Expo XDE and scan that code, I get this:

Failed to complete tunnel connection

The connection to http://packager.9u-9jc.lrvlr.myapp.exp.direct was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:19001.
Make sure that a web service is running on localhost:19001 and that it is a valid address.
The error encountered was: dial tcp 127.0.0.X:19001: getsockopt: connection refused

Just wish I could use this normally so I can keep up with this course I’m taking on react-native. 

Environment
Please run these commands in the project folder and fill in their results:
npm ls react-native-scripts: react-native-scripts@1.7.0
npm ls react-native: react-native@0.49.5
npm ls expo: expo@22.0.4
node -v: v6.12.0
npm -v: 4.6.1
yarn --version: 1.3.2
watchman version: Please specify a target and action
Also specify:
Operating system: Ubuntu 17.04
Phone/emulator/simulator & version: iphone

**Comment by sanjib-dev** [comment]
> The error encountered was: dial tcp 127.0.0.X:19001: getsockopt: connection refused

it may be some antivirus issue or if you are using linux may be the port is not white-listed.
just a guess though :)
