### ISSUE TITLE
Failed to notify project evaluation listener

### ISSUE THREAD

**Issue by TiagoGouvea** [react-community/create-react-native-app#478]
## Description

I trying to first run an react-native app with ```react-native run-android```.

## Expected Behavior

I expect it to work, like it does when I call ```react-native run-ios```

## Observed Behavior

```
react-native run-android
Scanning folders for symlinks in /Users/tiagogouvea/www/go-along/mobile/node_modules (12ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.gradle.internal.reflect.JavaMethod (file:/Users/tiagogouvea/.gradle/wrapper/dists/gradle-4.0-milestone-1-all/2rnr7rhi2zsmkxo9re7615fy6/gradle-4.0-milestone-1/lib/gradle-base-services-4.0.jar) to method java.lang.ClassLoader.getPackages()
WARNING: Please consider reporting this to the maintainers of org.gradle.internal.reflect.JavaMethod
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /Users/tiagogouvea/Library/Android/sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > javax/xml/bind/annotation/XmlSchema

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 4s
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: empty
* `npm ls react-native`: react-native@0.50.3 
* `npm ls expo`: empty
* `node -v`: v8.0.0
* `npm -v`: 5.5.1
* `yarn --version`: 1.2.1
* `watchman version`: 4.9.0

1. Operating system: macOs 10.12.6
2. Phone/emulator/simulator & version: Genymotion image

## Reproducible Demo

To validate it I started a clean project with ```react-native init goalong ``` and try to run it with ```react-native run-android```.

**Comment by shan-du** [comment]
Running into the exact same issue, same version everything as above except:
```
node -v: 7.10.1
npm -v: 4.2.0
```

**Comment by RizwanZaheer** [comment]
how can i move from JDK v9 to v8

**Comment by jphennessey** [comment]
See https://community.phantombot.tv/t/can-not-seem-to-downgrade-java-9-to-8-help-please-macbook-user/2498

**Comment by anp** [comment]
Hi! It looks like this is an issue with a "plain" React Native repository, and such issues belong on https://github.com/facebook/react-native. Thanks!

**Comment by krzysztofp** [comment]
Why JDK doesn't work? Java 10 is ahead of us, shouldn't we use the newest possible version all the time and this ticket should be closed when it's done?

**Comment by DoubleHub** [comment]
Confirmed it still doesn't work either with 9 or 10. This is not good at all! In other projects I'm using Java 10 features extensively so I can't just uninstall 10 and reinstall 8 >:(
Please add Java 10 support

**Comment by vashisthbhushan99** [comment]
It is still not working but I guess
Code below should work
```
brew cask uninstall java
brew tap caskroom/versions
brew cask install java8
```

**Comment by Hypothesis-github** [comment]
Bump

**Comment by szaske** [comment]
second bump, wish it worked with newer Java versions
