### ISSUE TITLE
Unsupported SDK Version 14.0

### ISSUE THREAD

**Issue by skyride99** [react-community/create-react-native-app#479]
Running Expo on a project that was completed back in May getting this error when deploy to ios simulator. How to get 14 supported.
## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
└── UNMET PEER DEPENDENCY react-native-vector-icons@~4.1.1

npm ERR! peer dep missing: react-native-vector-icons@~4.1.1, required by react-native-elements@0.13.0
npm ERR! code 1

* `npm ls react-native`:
├── react-native@0.41.2
└── UNMET PEER DEPENDENCY react-native-vector-icons@~4.1.1
* `npm ls expo`:
expo@14.0.2
* `node -v`:
v6.11.2
* `npm -v`:
3.10.10
* `yarn --version`:
v0.24.6
* `watchman version`:
"version": "4.7.0"
Also specify:

1. Operating system:
Mac OS Sierra 10.12.6
2. Phone/emulator/simulator & version:
Xcode 9.1
Xcode simulator

![simulator screen shot - iphone 7 plus - 2017-11-17 at 14 21 23](https://user-images.githubusercontent.com/3801142/32933401-07c384f6-cba5-11e7-93e7-156ef7ccafbd.png)

**Comment by tcdavis** [comment]
The clients no longer support SDK 14.  Fortunately, upgrading is usually a relatively pain-free process.  Release notes can be found at https://docs.expo.io/versions/latest/guides/upgrading-expo.html
