### ISSUE TITLE
How to use Headless JS Backgroundtask in Android

### ISSUE THREAD

**Issue by piu130** [react-community/create-react-native-app#481]
## Description

In the [react-native doc](https://facebook.github.io/react-native/docs/headless-js-android.html) they say you must add a `HeadlessJsTaskService` Java class and then a line to `AndroidManifest.xml` to use background tasks. How can I use it in this project?

## Expected Behavior

This single line should log `test`.

```js
AppRegistry.registerHeadlessTask('SomeTaskName', async () => console.log('test'))
```

## Observed Behavior

Nothing happens (Because I don't have the Java config?)

## Environment

react-native-scripts 1.7 on Android with expo 22 and react-native 0.49

**Comment by brentvatne** [comment]
the only way you can do this is to eject
