### ISSUE TITLE
Keeping Ejected App up to Snuff

### ISSUE THREAD

**Issue by parthradia** [react-community/create-react-native-app#482]
## Description

Hey all, I want to spin up an app that uses a combination of AR & OpenCV. The Expo team is magnificent, and is already tackling the former.

Unfortunately, I think OpenCV is a bit more of an obscure requirement, and I don't think they'll be tackling it any time soon. I'm fairly confident I could contribute a cross-platform native module ... but see here:

https://forums.expo.io/t/how-to-contribute-to-the-expo-sdk-add-native-code/4458

Understandable. So my question now becomes: once I eject and add custom native modules, how hard is it to keep up to date with this repo? I will be ejecting to ExpoKit, if that makes any difference.

**Comment by tcdavis** [comment]
You might get a better response on forums.expo.io, but fwiw I think the pain of keeping a detached project up to date more or less scales with the number & complexity of the native modules you bring in.

**Comment by brentvatne** [comment]
we have instructions on every sdk update how you can update to the latest version :)
