### ISSUE TITLE
expo hangs on xiomi device. shows no route to host on motorola.

### ISSUE THREAD

**Issue by xerosanyam** [react-community/create-react-native-app#483]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description
I do npm start. The qr shows up, I fire up expo on my phone. scan the qr code, expo shows a loader but doesn't move forward.
## Expected Behavior
show Hello world demo
What action did you perform, and what did you expect to happen?
perfomed exactly as mentioned in README of this repo
## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:
No err message

## Environment
Ubuntu 17.10 / 17.04 (facing on both)
Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
react-native-scripts@1.7.0

* `npm ls react-native`:

* `npm ls expo`:
* `node -v`:
v7.0.0
* `npm -v`:
4.6.1
* `yarn --version`:
The program 'yarn' is currently not installed. You can install it by typing:
sudo apt install cmdtest
* `watchman version`:

Also specify:

1. Operating system:
2. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by brentvatne** [comment]
-> github.com/expo/expo/issues
