### ISSUE TITLE
Better .gitignore after ejecting

### ISSUE THREAD

**Issue by slorber** [react-community/create-react-native-app#487]
## Description

After ejecting, the .gitignore remains the same.
I think it's safe to assume we should rather merge the current .gitignore with the default .gitignore of ReactNative projects

## Expected Behavior

The final .gitignore should rather look like this one after ejecting: https://github.com/facebook/react-native/blob/master/local-cli/templates/HelloWorld/_gitignore

## Observed Behavior

Gitignore after ejection is not really suited to RN projects

```
node_modules/
.expo/
npm-debug.*
```

**Comment by brentvatne** [comment]
pr would be accepted, issues are for bugs

**Comment by DavidNorena** [comment]
@slorber check this out https://www.gitignore.io/api/reactnative
