### ISSUE TITLE
QR code won't scan

### ISSUE THREAD

**Issue by timurtu** [react-community/create-react-native-app#49]
After creating an app and running `yarn start` the QR code gives no feedback when scanning on my iPhone.

**Comment by jesseruder** [comment]
Did you install the Expo app?

**Comment by timurtu** [comment]
Yeah I don't get any feedback when I scan the QR code with the Expo app

**Comment by jesseruder** [comment]
Hm not sure why that's happening. Can you upload a screenshot of the QR code? If you can't get it working you can type the url in manually - just go to the Explore tab in Expo and then type the url in the search bar.

**Comment by timurtu** [comment]
Yeah I just tried that it loaded here's the screenshot.

<img width="1280" alt="screen shot 2017-03-13 at 10 24 50 pm" src="https://cloud.githubusercontent.com/assets/4442012/23883214/ed919730-083b-11e7-9370-47cfbdd78257.png">

**Comment by jesseruder** [comment]
It looks like it might be a little squished horizontally. @dikaiosune do you think we can do anything about that?

**Comment by dikaiosune** [comment]
Interesting! I suspect that the horizontal scaling isn't the actual problem (I've seen it work well on much more squished consoles), but rather the contrast between the dark and light elements is. IntelliJ/Webstorm's terminal appears to have interesting ideas about how to render bash color codes!

I'm not sure what we can do about this. It might be possible by changing the Webstorm color theme, the font, or by trying in a different terminal.

**Comment by timurtu** [comment]
Using a terminal worked great

**Comment by dikaiosune** [comment]
Glad to hear it!

**Comment by dikaiosune** [comment]
Sorry, I'm going to leave this open as we need to at the very least document this issue.

**Comment by tmhn** [comment]
Is there a way that the QR code can be generated into a PNG (or something similar)? So that it could be pasted into a GitHub repo or Gist so users can quickly open it within Expo.

**Comment by dikaiosune** [comment]
While it's definitely possible from an implementation perspective, I'm not sure we want to add any more complexity to the startup scripts.

Generally if you want to share the app with someone they'll need to be on the same LAN and I'm mostly thinking that it's not unreasonable to expect them to be able to physically scan the phone.

**Comment by bhaskarzemoso** [comment]
Increased screen's brightness, disabled redshift and maximised terminal worked for me!!

**Comment by freemant2000** [comment]
Nothing worked. Had to tap the search icon in Expo and enter the url to open my own react native app.

**Comment by brentoboy** [comment]
I had this issue, and it ended up being the slightly transparent terminal window I was using was distorted by the content behind it

**Comment by SirPhemmiey** [comment]
Had the same issue. Re-installing the Expo app on my device, and restarting (clear cache) the packager did it. Relieved!

**Comment by samnet** [comment]
same as @hayanisaid here.

**Comment by crobinson42** [comment]
I experience this issue only when running in my IDE's terminal. If I switch and use iterm2 or OSX default terminal it works fine. It appears to be an issue with "squishing" the QR image's width.

**Comment by Just01** [comment]
It is really funny, but all you need to do just switch your ide theme on light :D

**Comment by SmelayaPanda** [comment]
True, the dark theme in IDE makes the reverse of colors =)

**Comment by avin** [comment]
![image](https://user-images.githubusercontent.com/36100/43701838-5b858e98-9960-11e8-8291-4661442b3f0a.png)
yet another example of qr image that does not recognizable.

Another qr-scanner apps read code well

Of course it should be an expo problem, but any way, posted here. Solution for me to start app in simple windows cmd

**Comment by stiwdiosddraig** [comment]
In WebStorm, Open `Settings > Editor > Color Scheme Font`, check `Use color scheme font instead of the default` and change `Line height` to `1.0`.

Previous comment was right that WebStorm (and other JetBrains products) have strange interpretations on how to view this using their Run Tool.

**Comment by aliwaqar981** [comment]
Hi guys, I'm getting this same issue. As above mentioned I tried changing themes to light and dark but still nothing.  I have tried testing both on android and ios.

## Behaviour 
### Android:
Nothing showing up after scanning the QR code
### IOS:
Getting message "no usable data found" and then nothing showing up. 

## Environment
Expo ( ~48.0.21 )
react native (0.71.14)

## Screenshot
<img width="912" alt="Screenshot 2024-07-12 at 8 54 07 PM" src="https://github.com/user-attachments/assets/25c98d79-781c-4f3e-be1d-682114c66863">
