### ISSUE TITLE
cant make react native run android

### ISSUE THREAD

**Issue by OdaiTu** [react-community/create-react-native-app#491]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description
i have followed the steps to setup the android and installed sdk with sdk build tools for android 23
and install jdk 8 and set the ANDROID_HOME

but i get this error when run the command 

![image](https://user-images.githubusercontent.com/12837840/33263948-5b17101a-d374-11e7-8ecf-6e7c6e18cb97.png)

![image](https://user-images.githubusercontent.com/12837840/33263956-6476e068-d374-11e7-8653-9fe2cffeedea.png)

1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior

What action did you perform, and what did you expect to happen?

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: empty
* `npm ls react-native`: react-native@0.50.4
* `npm ls expo`: empty
* `node -v`: v 8.7.0
* `npm -v`: 5.4.2
* `yarn --version`:
* `watchman version`:

Also specify:

1. Operating system: windows
2. Phone/emulator/simulator & version:  emulator android 23

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by dikaiosune** [comment]
Hi! It looks like this is an issue with a "regular" React Native project, not a CRNA project. If you created this with CRNA, can you please provide more details about what steps you took and I'll reopen? Thanks!

**Comment by OdaiTu** [comment]
@dikaiosune  thank you for your reply
i think using expo is the best so im now working with expo on my mobile and no problem at all :)
