### ISSUE TITLE
Any way to use react-native-vector-icons without ejecting?

### ISSUE THREAD

**Issue by FezVrasta** [react-community/create-react-native-app#492]
I'd just like to understand if is it possible to use `react-native-vector-icons` without ejecting, I can't find any information and I hardly believe I'm the only one with the necessity to use icons in my app...

Thanks!

**Comment by mgscreativa** [comment]
Have you tried?
> npm install --save @expo/vector-icons
That way you have vector icons in your CRNA/Expo project https://expo.github.io/vector-icons/

**Comment by FezVrasta** [comment]
Thanks, that works!

I think it would be useful to mention somewhere this, because most of the icon sets out there require a native link and people (like me) may get confused..

**Comment by dikaiosune** [comment]
I believe this is mentioned in the docs, but I could be wrong. PRs welcome!

**Comment by joshhaaronn** [comment]
This didn't seem to work for me. Here's the error log:

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.6.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'ios' ]
2 info using npm@5.6.0
3 info using node@v9.6.1
4 verbose run-script [ 'preios', 'ios', 'postios' ]
5 info lifecycle IHopeThisWorks@0.1.0~preios: IHopeThisWorks@0.1.0
6 info lifecycle IHopeThisWorks@0.1.0~ios: IHopeThisWorks@0.1.0
7 verbose lifecycle IHopeThisWorks@0.1.0~ios: unsafe-perm in lifecycle true
8 verbose lifecycle IHopeThisWorks@0.1.0~ios: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/joshuamartinez/Documents/IHopeThisWorks/node_modules/.bin:/Users/joshuamartinez/anaconda3/bin:/Users/joshuamartinez/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle IHopeThisWorks@0.1.0~ios: CWD: /Users/joshuamartinez/Documents/IHopeThisWorks
10 silly lifecycle IHopeThisWorks@0.1.0~ios: Args: [ '-c', 'react-native-scripts ios' ]
11 info lifecycle IHopeThisWorks@0.1.0~ios: Failed to exec ios script
12 verbose stack Error: IHopeThisWorks@0.1.0 ios: `react-native-scripts ios`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:127:13)
12 verbose stack     at maybeClose (internal/child_process.js:933:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
13 verbose pkgid IHopeThisWorks@0.1.0
14 verbose cwd /Users/joshuamartinez/Documents/IHopeThisWorks
15 verbose Darwin 17.4.0
16 verbose argv "/usr/local/Cellar/node/9.6.1/bin/node" "/usr/local/bin/npm" "run" "ios"
17 verbose node v9.6.1
18 verbose npm  v5.6.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error IHopeThisWorks@0.1.0 ios: `react-native-scripts ios`
23 error spawn ENOENT
24 error Failed at the IHopeThisWorks@0.1.0 ios script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
`
