### ISSUE TITLE
unable to resolve host "exp" No address.. react-native expo

### ISSUE THREAD

**Issue by hamidb14** [react-community/create-react-native-app#494]
hello.

i tried to run my react native project on my android device.

but expo (android app) give me this error:

> something went wrong.

> could not load exp://exp://192.168......

and in expo error log:

> ubcaught Error: java.net.UnknownHostExcep...

> unable ro resolve host "exp" No address associated with hostname

windows: 10 64bit

**Comment by Grimmjowjack** [comment]
Is the device in the same network? 

I faced some issues with network, and [this thread](https://github.com/react-community/create-react-native-app/issues/81) helped me.
