### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by thaneesan** [react-community/create-react-native-app#496]
thaneesan@thaneesan-PC:~/Desktop/AwesomeProject$ npm run android

> AwesomeProject@0.1.0 android /home/thaneesan/Desktop/AwesomeProject
> react-native-scripts android

10:20:35: Unable to start server
  See https://git.io/v5vcn for more information, either install watchman or run the following snippet:
    sudo sysctl -w fs.inotify.max_user_instances=1024
    sudo sysctl -w fs.inotify.max_user_watches=12288
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! AwesomeProject@0.1.0 android: `react-native-scripts android`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the AwesomeProject@0.1.0 android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/thaneesan/.npm/_logs/2017-12-01T04_50_35_736Z-debug.log

**Comment by brentvatne** [comment]
read the error message, do as it says, try again ;) create an issue if it doesn't work
