### ISSUE TITLE
No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

### ISSUE THREAD

**Issue by trustfall** [react-community/create-react-native-app#499]
## Description

Just trying to run a build in Android Studio out of the box after ejecting to ExpoKit, and it errors out on me, with the following error: `Error:(13, 5) No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.`

## Expected Behavior

Expected it to build without errors, similar to iOS

## Observed Behavior

`/Users/kyle/Documents/Development/app-mobile/android/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/27.0.1/res/values-v26/values-v26.xml`
`Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/kyle/Library/Android/sdk/build-tools/25.0.2/aapt'' finished with non-zero exit value 1`
## Environment
expo - v21.0.0
react native - expo sdk 21 fork
android studio v3.0.1
gradle 2.10

**Comment by patilrevansidh** [comment]
I also faced this issue you just need to make 2 chnages:
in android/build.gradle metion this below code 
`subprojects {
        afterEvaluate { project ->
            if (project.hasProperty("android")) {
                android {
                    compileSdkVersion 26
                    buildToolsVersion '26.0.2'
                }
            }
        }
}`


and in  android/app/build.gradle change your compliesdk version and buildToolVersion like this:
`
    compileSdkVersion 26
    buildToolsVersion "26.0.2"`

**Comment by wmonecke** [comment]
@patilrevansidh  Could you be more explicit, to where exactly goes 
`subprojects { afterEvaluate { project -> if (project.hasProperty("android")) { android { compileSdkVersion 26 buildToolsVersion '26.0.2' } } } }` ??

**Comment by varun07j** [comment]
It worked for me by changing to "26.0.2" version in android>app>build.gradle
def computeBuildToolsVersion = { -> project.hasProperty("buildToolsVersion") ? buildToolsVersion : "26.0.2" }

**Comment by RayVaniya** [comment]
thax..It worked for me by changing to "26.0.2" version in android>app>build.gradle you saved my day...

**Comment by Baburaomannepalli** [comment]
compileSdkVersion 26
    buildToolsVersion "26.0.1"

**Comment by jh3141** [comment]
I found changing the sdk/build tools versions in my own project didn't help, but following the instructions at https://github.com/oblador/react-native-keychain/issues/68#issuecomment-304836725 allowed me to force the versions used by all dependencies of my project, and that fixed the issue.

**Comment by TheBlackHacker** [comment]
Change compileSdkVersion and buildToolsVersion in android/app/build.gradle is worse, fixed it just by add this to android/build.gradle:
`subprojects { 
    afterEvaluate { 
        project -> if (project.hasProperty("android")) { 
            android { 
                compileSdkVersion 26 
                buildToolsVersion '26.0.2' 
            } 
        } 
    } 
}`
