### ISSUE TITLE
Infinite error loop when trying to open a non-existing app from clipboard

### ISSUE THREAD

**Issue by timurtu** [react-community/create-react-native-app#50]
Not sure if this should go here or somewhere else but on the iOS mobile app when I try to open an app from clipboard that doesn't exist I get an error which is expected because it doesn't exist, but my only option is to Try Again. The only way to exit this screen is to close the app.

**Comment by dikaiosune** [comment]
Hi! Thanks so much for the report! I copied this issue to the appropriate repo: https://github.com/exponent/exponent/issues/82

**Comment by timurtu** [comment]
No problem hoping to use this myself
