### ISSUE TITLE
Add script to clear RN packager

### ISSUE THREAD

**Issue by slorber** [react-community/create-react-native-app#500]
## Description

I think it is useful to provide a script by default to clear the RN packager, because you might want to clear it without actually starting it with --reset-cache

For example I need to clear it because I have a file in my app whose transform output does depend on environment variables:

![image](https://user-images.githubusercontent.com/749374/33667010-f0094a98-da9b-11e7-8e19-394c66b33368.png)

When I toggle the environment variable: it never taken into account and cache is never refreshed unless I clear the packager cache.

Here is a command that seems to work for my usecase:

`    "clear": "rm -rf $TMPDIR/react-native-packager-cache-* && rm -rf $TMPDIR/metro-bundler-cache-*",`

**Comment by fson** [comment]
You can also press Shift+r in the console with the CRNA server running to quickly clear the cache and restart the bundler. (It’s part of the “interactive mode” we added a while ago).

Does this help in your use case?

**Comment by slorber** [comment]
@fson unfortunately I have a quite specific setup:
- I use Expo detached
- I still run inside Expo client for local dev ([see](https://expo.canny.io/feature-requests/p/ability-to-work-in-expo-client-after-detaching))

So basically, according to an env variable, I have a module that will be in native app:

```javascript
    export { default as Intercom } from 'react-native-intercom';
    export { default as OneSignal } from 'react-native-onesignal';
```
and when run inside Expo client:

```javascript
    export const Intercom = undefined;
    export const OneSignal = undefined;
```

So I develop my native integrations are disabled, and when I publish to real native apps in production (detached expo) these native integrations are enabled.

The problem I encounter is that when I switch the environment variable, I must be sure to clear the cache otherwise this switch is not taken into account.

Here are my deployment scripts

```
    "expo:publish:all": "npm run expo:publish:android && npm run expo:publish:ios && npm run expo:publish:client",
    "expo:publish:android": "npm run icomoon && npm run clear && EXPO_DETACHED=true exp publish --release-channel prod-expo23-android-v1",
    "expo:publish:ios": "npm run icomoon && npm run clear && EXPO_DETACHED=true exp publish --release-channel prod-expo23-ios-v1",
    "expo:publish:client": "npm run icomoon && npm run clear && exp publish --release-channel prod-expo23-client-v1",
```

It is absolutely mandatory for me to clear the packager cache before each publish, because as you can see, the 3 publish (ios, android with native integrations, client with integrations disabled) use a different environment variable.

Here if I run `npm expo:publish:all` without clearing the cache, all 3 bundles will be equal due to caching, while the client bundle (which can work into Expo client thanks to disabled native dependencies) should be different from ios and android package.

BTW I have [another PR](https://github.com/expo/exp/pull/88) on Expo so that they ensure on their side the RN packager is reset on publish
