### ISSUE TITLE
create-react-native-app my-project not creating complete project

### ISSUE THREAD

**Issue by sohaibjaved44** [react-community/create-react-native-app#501]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description
I have just run the command create-react-native-app my-project  it created a director containing 3 items only (i) node modules (ii) Package.json (iii) package-lock.json so npm start obviously won't work.

So the create-react-native-app my-project not creating complete project

## Expected Behavior
It should have expo, app.js and other stuff which is necassary part of CRNA application.

What action did you perform, and what did you expect to happen?
I ran command create-react-native-app my-project 
and I was expecting a directory with all the mandatory files and folders to work for me by producing QR code on running npm start command
## Observed Behavior
npm start says "missing script: start"
What actually happened when you performed the above actions?
it did nothing just produced the error saying "npm Err! missing script: start
If there's an error message, please paste the *full terminal output and error message* in this code block:

```
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SOHAIB\AppData\Roaming\npm-cache\_logs\2017-12-06T16_57_16_387Z-debug.log
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: 1.8.1
* `npm ls react-native`: crnaSolution@0.1.0 E:\React Native\CRNA wiht Expo\crnaSolution -- (empty)
* `npm ls expo`: crnaSolution@0.1.0 E:\React Native\CRNA wiht Expo\crnaSolution -- (empty)
* `node -v`: v9.2.0
* `npm -v`: 5.5.1
* `yarn --version`:1.3.2
* `watchman version`:not isntalled

Also specify:

1. Operating system: Windows 10
2. Phone/emulator/simulator & version: iphone

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by tcdavis** [comment]
What's crnaSolution?

**Comment by sohaibjaved44** [comment]
its name of my-project

**Comment by steveHornseyDeveloper** [comment]
Same issue, also came up with an error saying NPM 5 isn't supported during install

**Comment by giorgim** [comment]
we have exactly same issue. what is latest best practice to avoid this issue?

**Comment by steveHornseyDeveloper** [comment]
It's marked as closed so it should be fixed in the latest version of create-react-native-app so ensure you're using it. Otherwise I guess downgrade npm just for set up and then upgrade again as this should only be an issue during project set up
