### ISSUE TITLE
Fresh CRNA install cannot import .jsx files

### ISSUE THREAD

**Issue by thomascothran** [react-community/create-react-native-app#502]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

Attempting to build the JavaScript bundle for the android emulator results in a bundling error for `*.jsx` files. Changing the file extension to `js` allows the bundle to compile.

## Expected Behavior

On performing the following commands, I expected the ability to import `jsx` files:

```
create-react-native-app test-crna
cd test-crna/
touch Test.jsx
```

In the `Test.jsx` file:

```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

const Test = () => {
    return (
        <View>
            <Text> Testing! </Text>
        <View>
    );
};

export default Test;
```

In the `App.js` file I add the line:

```
import Test from './Test.jsx';
```

## Observed Behavior

I run `yarn cache clean && yarn start` and I get:

```
21:45:27: Starting Android...

 › Press a to open Android device or emulator, or i to open iOS emulator.
 › Press q to display QR code.
 › Press r to restart packager, or R to restart packager and clear cache.
 › Press d to toggle development mode. (current mode: development)

/* I press "a" */

21:45:29: Failed building JavaScript bundle
21:45:29: Unable to resolve ./Test.jsx" from ".//App.js`: could not resolve `/home/default/dev/test-crna/Test.jsx' as a file nor as a folder","name":"UnableToResolveError","type":"UnableToResolveError","errors":[{}]},"type":"bundling_error"}"
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: `react-native-scripts@1.8.1`
* `npm ls react-native`: `react-native@0.50.3 `
* `npm ls expo`: `npm ls expo`
* `node -v`: `v8.5.0`
* `npm -v`: `4.6.1`
* `yarn --version`: `1.3.2`
* `watchman version`: `1.3.2`

Also specify:

1. Operating system: Ubuntu Mate 16.4
2. Phone/emulator/simulator & version: Genymotion - Galaxy Nexus 10 - 5.1.0 API 22

**Comment by brentvatne** [comment]
this is an intentional decision in react native -- you should use the .js extension: https://github.com/facebook/react-native/commit/0893d07db197b4f78752f982abbc568c6c0c7419
