### ISSUE TITLE
Cannot install "create-react-native-app" using npm

### ISSUE THREAD

**Issue by angelzerodie** [react-community/create-react-native-app#505]
Hello,

Could you please help me with below issue?

## Description

I can't install create-react-native-app using npm
- Node: v8.9.3
- OS: Mac Sierra
- command: sudo npm install -g create-react-native-app

and I got the error below

`59 verbose stack Error: ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/create-react-native-app/build/index.js'
60 verbose cwd /DATA/ReactNative/create_RN
61 verbose Darwin 16.7.0
62 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "create-react-native-app"
63 verbose node v8.9.3
64 verbose npm  v5.5.1
65 error path /usr/local/lib/node_modules/create-react-native-app/build/index.js
66 error code ENOENT
67 error errno -2
68 error syscall chmod
69 error enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/create-react-native-app/build/index.js'
70 error enoent This is related to npm not being able to find a file.
71 verbose exit [ -2, true ]
[2017-12-09T13_07_21_044Z-debug.log](https://github.com/react-community/create-react-native-app/files/1544695/2017-12-09T13_07_21_044Z-debug.log)
`

**Comment by kajm** [comment]
whats your npm version?
