### ISSUE TITLE
Error when attempting to eject fresh project

### ISSUE THREAD

**Issue by jonasgroendahl** [react-community/create-react-native-app#508]
npm: 4.6.1
node: 8.9.3
os: Windows 10 64 bit

I run create-react-native-app test
cd test
npm run eject

I get this error:
Ejected successfully!
Please consider letting us know why you ejected in this survey:
  https://goo.gl/forms/iD6pl218r7fn9N0d2
The batch file cannot be found.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@0.1.0 eject: `react-native-scripts eject`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@0.1.0 eject script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2017-12-12T19_58_35_368Z-debug.log

I tried this on several Windows systems, this seems to be creating problems later on when i try to run NPM start with my android setup

**Comment by jonasgroendahl** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'eject' ]
2 info using npm@4.6.1
3 info using node@v8.9.3
4 verbose run-script [ 'preeject', 'eject', 'posteject' ]
5 info lifecycle test@0.1.0~preeject: test@0.1.0
6 silly lifecycle test@0.1.0~preeject: no script for preeject, continuing
7 info lifecycle test@0.1.0~eject: test@0.1.0
8 verbose lifecycle test@0.1.0~eject: unsafe-perm in lifecycle true
9 verbose lifecycle test@0.1.0~eject: PATH: C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Admin\Desktop\react\test\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Embarcadero\Studio\18.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\18.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl\Win64;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\Admin\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Skype\Phone\;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files\nodejs\;C:\Users\Admin\AppData\Local\Microsoft\WindowsApps;C:\Users\Admin\AppData\Local\atom\bin;C:\Users\Admin\AppData\Local\Microsoft\WindowsApps;C:\Users\Admin\AppData\Roaming\Composer\vendor\bin;;C:\Program Files\Microsoft VS Code\bin;C:\Users\Admin\AppData\Roaming\npm
10 verbose lifecycle test@0.1.0~eject: CWD: C:\Users\Admin\Desktop\react\test
11 silly lifecycle test@0.1.0~eject: Args: [ '/d /s /c', 'react-native-scripts eject' ]
12 silly lifecycle test@0.1.0~eject: Returned: code: 1  signal: null
13 info lifecycle test@0.1.0~eject: Failed to exec eject script
14 verbose stack Error: test@0.1.0 eject: `react-native-scripts eject`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid test@0.1.0
16 verbose cwd C:\Users\Admin\Desktop\react\test
17 verbose Windows_NT 10.0.16299
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "eject"
19 verbose node v8.9.3
20 verbose npm  v4.6.1
21 error code ELIFECYCLE
22 error errno 1
23 error test@0.1.0 eject: `react-native-scripts eject`
23 error Exit status 1
24 error Failed at the test@0.1.0 eject script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by jonasgroendahl** [comment]
This is the error that you get if you try npm start or npm run android afterwards:

Looks like you installed react-native globally, maybe you meant react-native-cli?
To fix the issue, run:
npm uninstall -g react-native
npm install -g react-native-cli
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@0.1.0 android: `react-native run-android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@0.1.0 android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2017-12-12T20_33_31_201Z-debug.log

**Comment by trsh** [comment]
What's the solution?

**Comment by DraugDev** [comment]
Any comments about solution?

**Comment by trsh** [comment]
@DraugDev for me, it was not correct react native version package.json.

**Comment by Farham0** [comment]
I have the same issue. 
npm run eject :(
any solution ??

**Comment by brentvatne** [comment]
just tried this, works as expected, please create a new issue and follow the template if you're having a problem
