### ISSUE TITLE
Stuck at Starting Packager on Windows 10

### ISSUE THREAD

**Issue by karankashyap** [react-community/create-react-native-app#509]
## Description

Stuck at Starting Packager after `npm start` on Windows 10. Working on Atom and WebStorm. I have Bash on Ubuntu on Windows. Installed Watchman too

## Expected Behavior

Starting Packager generally starts the packager and loads the app on device via Expo. 

## Observed Behavior

After dependency graph is loaded, Starting Packager is stuck forever. Solutions elsewhere are for Linux and Mac as people are saying that installing watchman somehow solves this. 

* Error Message
Message (npm start)
```
> react-native-scripts start
15:07:30: Starting packager...
15:28:50: Stopping packager...
15:28:51: Packager stopped.
```
Message (yarn start): 
```
yarn run v1.2.1
$ react-native-scripts start
13:47:40: Starting packager...
14:58:30: Stopping packager...
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
```

## Environment

* `npm ls react-native-scripts`: 
react-native-redux-crypto-tracker@0.1.0 krypto\krypto-app\krypto-tracker
`-- react-native-scripts@1.8.1

* `npm ls react-native`:
react-native-redux-crypto-tracker@0.1.0 C:\Work\Studio\krypto\krypto-app\krypto-tracker
`-- react-native@0.50.3

* `npm ls expo`:
`-- expo@23.0.6

* `node -v`:
v8.7.0

* `npm -v`:
4.6.1

* `yarn --version`:
1.2.1

* `watchman version`:
{
    "version": "4.9.1",
    "buildinfo": "5cd39b6b10596bc23af169428b87313cfb350d14 2017-12-05T21:13:21.0000000Z"
}

* react-native info
```Environment:
  OS: Windows 10
  Node: 8.7.0
  Yarn: 1.2.1
  npm: 4.6.1
  Watchman: 4.9.1
  Xcode: N/A
  Android Studio: Version  2.1.0.0 AI-143.2821654

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.3 => 0.50.3
```

Tried (not in order)
```
watchman watch-del-all
watchman shutdown-server
react-native start --reset-cache
yarn start
npm cache clean
rm -rf node_modules
```
but nothing works, still stuck there. 

Specifications:

1. Operating system: Windows 10 x64
2. Phone/emulator/simulator & version: Samsung SMN9005 (Note 3 LTE)
3. Storage: SSD 512 GB

Possible Solution on Linux: 
`sudo sysctl -w fs.inotify.max_user_watches=10000` 
what is the windows equivalent of this?

**Comment by aalkz** [comment]
I'm having this issue as well, running `watchman.exe watch-dell-all` returns this output:
``` 
{
    "version": "4.9.1",
    "roots": []
}
``` 

And running watchman.exe shutdown-server returns:

``` 
{
    "version": "4.9.1",
    "shutdown-server": true
}
``` 

I don't understand how the solution for Linux works to try it on Windows, I have seen that has worked for most people on [other issue threads](https://github.com/facebook/react-native/issues/10188#issuecomment-251677161).

**Comment by brentvatne** [comment]
this is an upstream react-native issue as @aalkz has pointed out.

**Comment by dsuarezv** [comment]
@karankashyap, I know this is closed, but I had a similar problem and created a PR to fix, maybe it can be useful in this case. #674
