### ISSUE TITLE
Simulator version can't change as --simulator flag.

### ISSUE THREAD

**Issue by magichim** [react-community/create-react-native-app#512]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description
I tried to input 'react-native run-ios --simulator="iPhone 6". but Just started only iPhoneX(latest iphone)
What should I do to change simulator version?

## Expected Behavior
In terminal.
create-react-native-app AwesomeProject
cd AwesomeProject
react-native run-ios --simulator="iPhone 6" or "iPhone 4s" ...etc

but just only started iPhoneX simulator!

## Observed Behavior

What actually happened when you performed the above actions?

It only done as iPhoneX simulator.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@1.8.1 
* `npm ls react-native`: react-native@0.50.3
* `npm ls expo`: expo@23.0.6
* `node -v`: v8.9.1
* `npm -v`: 4.6.1
* `yarn --version`: not used
* `watchman version`: "version": "4.9.0"

Also specify:

1. Operating system: mac os / sierra
2. Phone/emulator/simulator & version: 

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by brentvatne** [comment]
we don't support that flag, feel free to submit a pr

**Comment by BillyFigueroa** [comment]
Did this ever get anywhere? was a feature request for this created? This is actually very useful to use for testing different layouts for different devices

**Comment by brentvatne** [comment]
@BillyFigueroa - you can open different simulators using the toolbar when you have the simulator app open

![](http://url.brentvatne.ca/hXSpow.png)

**Comment by BillyFigueroa** [comment]
@brentvatne I know I can select different devices, the problem is in code. When testing I need to check for example if (device == 'iPhone SE'). Device seems to always display "Simulator". Even when I try to pass the simulator flag, it still reads as Simulator (expo Constant.platform.ios.device). Should I be looking at a different variable or should I be reaching out to expo about this?

**Comment by EvanBacon** [comment]
@BillyFigueroa I think `Constants.platform.ios.model` is what you want. [It's listed in the docs](https://docs.expo.io/versions/latest/sdk/constants#model)
> The human-readable model name of this device, e.g. iPhone 7 Plus.

[Here is what's happening under the hood ](https://github.com/expo/expo/blob/master/ios/Exponent/Versioned/Core/Api/EXConstants.m#L175)

**Comment by BillyFigueroa** [comment]
@EvanBacon that is actually what I am using. I was going off the top of my head with the full path to the name. This is ALWAYS equal to "Simulator". But my guess is I might have to open an issue with them instead?

**Comment by EvanBacon** [comment]
react-community ~= expo 😜how about `Expo.Constants.platform.ios.platform`? [Looks to be pretty much the same](https://docs.expo.io/versions/latest/sdk/constants#platformthe-apple-internal-model-identifier-for-this)
> The Apple internal model identifier for this device, e.g. iPhone1,1.

**Comment by BillyFigueroa** [comment]
Something is off. None of these value read as they do in this file in the Simulator. I might need to reach out to expo instead
