### ISSUE TITLE
run (npm run eject)  Error!

### ISSUE THREAD

**Issue by GrowthCoder** [react-community/create-react-native-app#514]
## Error Log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "D:\\node\\node_global\\node_modules\\npm\\bin\\npm-cli.js" "run" "eject"
npm ERR! node v8.9.3
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-chat@0.1.0 eject: `react-scripts eject`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-chat@0.1.0 eject script 'react-scripts eject'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-chat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts eject
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-chat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-chat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\node_cache\_logs\2017-12-20T12_34_56_562Z-debug.log

## who can tell me, what should i do?

**Comment by VadimZP** [comment]
Use without `sudo` if you are on Windows

1. `sudo npm install npm@latest -g` 
2. `sudo npm install -g n`
3. `sudo n stable`

In the end commit all changes if error occurs

**Comment by jericbas** [comment]
@VadimZP I think `n` is not available in Windows.

**Comment by GrowthCoder** [comment]
It`s the truth that `n` is not avaliable in Windows! @jericbas

**Comment by VadimZP** [comment]
@GrowthCoder `n` is just an interactive node versions manager. 

Check second answer:
https://stackoverflow.com/questions/8191459/how-do-i-update-node-js

**Comment by brentvatne** [comment]
post the repo somewhere where we can try it out, can't do much without more info or repro case
