### ISSUE TITLE
npm start not working on hello world project

### ISSUE THREAD

**Issue by timboektoe** [react-community/create-react-native-app#515]
## Description

npm start on my very first hello world application fails

## Expected Behavior

I expected npm start to work

## Observed Behavior

I got an error during npm start.

```
6:41:34 PM: Unable to start server
See https://git.io/v5vcn for more information, either install watchman or run the following snippet:
  sudo sysctl -w kern.maxfiles=5242880
  sudo sysctl -w kern.maxfilesperproc=524288
        

npm ERR! Darwin 17.2.0
npm ERR! argv "/Users/timboektoe/.nvm/versions/node/v6.11.4/bin/node" "/Users/timboektoe/.nvm/versions/node/v6.11.4/bin/npm" "start"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-native-app@0.1.0 start: `react-native-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-native-app@0.1.0 start script 'react-native-scripts start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-native-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-native-scripts start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-native-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-native-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/timboektoe/Projects/2017/tmp/react-native-app/npm-debug.log
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@1.8.1 
* `npm ls react-native`: react-native@0.50.3 
* `npm ls expo`: expo@23.0.6 
* `node -v`: v6.11.4 & v7.10.1
* `npm -v`: 3.10.10 & 4.2.0
* `yarn --version`: yarn: command not found
* `watchman version`: not installed

**Comment by timboektoe** [comment]
I also found the solution already. Watchman was not installed. I installed watchman and it worked! Maybe a good idea to mention in the getting started?

**Comment by austinhale** [comment]
Same thing happened to me. I was a bit confused to find watchman deprecated on npm. To avoid confusion, [this](https://facebook.github.io/watchman/docs/install.html) is the one you need to install.

**Comment by durgeshdhalla** [comment]
Using below worked for me, try it out

sudo sysctl -w kern.maxfiles=5242880
sudo sysctl -w kern.maxfilesperproc=524288
