### ISSUE TITLE
I want to use Action menu built in typical react native into Expo. is it possible ?

### ISSUE THREAD

**Issue by LuckySambial** [react-community/create-react-native-app#518]
I have recently shifted to expo and create App successfully and I am very happy with Expo. It's really awesome.

Now, I am going to create new app and app required arc menu in it. I have found a example from https://github.com/geremih/react-native-circular-action-menu built in typical react native.

I want to use same circular menu in Expo app but I am not able to use getting error when I am trying to use that menu.

Error given below:-

undefined is not an object (evaluating '_react2.PropTypes.number')

please help!!!

**Comment by esamelson** [comment]
Hi, thanks for using Expo! Unfortunately we cannot provide support for external libraries - I would contact the author of that library or open an issue in their repo. It looks like it's rather old, so it may need to be updated for newer versions of React Native.

Best of luck!

**Comment by brentvatne** [comment]
that library actually works, it is just JS. the problem is that it is out of date and depends on an old version of react which used to export proptypes. use this one instead: https://github.com/mastermoo/react-native-action-button
