### ISSUE TITLE
Unable to link react-native-navigation after detach

### ISSUE THREAD

**Issue by James2516** [react-community/create-react-native-app#520]
## Description

I created a new project and detached it.

When I try to run the iOS project in XCode, it gives an error
>'React/RCTRootView.h' file not found

If I create a new project with `react-native init` instead, I'm able to build with [react-native-navigation](https://github.com/wix/react-native-navigation) successfully. Why does it fail with `create-react-native-app` / `expo`?

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@1.8.1
* `npm ls react-native`: 0.51.0
* `npm ls expo`: expo@24.0.2
* `node -v`: 8.6.0
* `npm -v`: 4.6.1
* `yarn --version`: 1.3.2
* `watchman version`: 4.7.0

Also specify:

1. Operating system: MacOS
2. Phone/emulator/simulator & version: Xcode 9.1

## Reproducible Demo

https://github.com/James2516/expo-native-nav
Run `npm install` and try building the iOS project in Xcode.

Or start a new project:
1. `create-react-native-app`
2. `exp detach`
3. `yarn add react-native-navigation`
4. `react-native-link`
5. `cd ios && pod install`

I have tried adding React to build target ![](https://i.imgur.com/OCQ30Tj.png)

**Comment by brentvatne** [comment]
not within the scope of this project to help with linking
