### ISSUE TITLE
error in npm start command during running hello program of reactjs

### ISSUE THREAD

**Issue by amolumesh12** [react-community/create-react-native-app#522]
hello
:am following " https://www.tutorialspoint.com/reactjs/reactjs_environment_setup.html " for running simple "hello world" program on reactjs but at last stage of above mentioned tutorial
when I run "npm start "command I face this error on node.js cmd...please help me to sort out the following error :

C:\Users\Umesh1\Desktop\reactApp>npm start
'CALL "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules
\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external com
mand,
operable program or batch file.

    reactapp@1.0.0 start C:\Users\Umesh1\Desktop\reactApp
    webpack-dev-server --hot

npm ERR! file C:\Program Files\Java\jdk1.8.0_144
npm ERR! path C:\Program Files\Java\jdk1.8.0_144
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Program Files\Java\jdk1.8.0_144
npm ERR! reactapp@1.0.0 start: webpack-dev-server --hot
npm ERR! spawn C:\Program Files\Java\jdk1.8.0_144 ENOENT
npm ERR!
npm ERR! Failed at the reactapp@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Umesh1\AppData\Roaming\npm-cache_logs\2018-01-04T08_27_53
_123Z-debug.log

**Comment by esamelson** [comment]
Hey there - sorry you're having trouble! It looks like you're following a tutorial for setting up a ReactJS environment for web development, but this repo is for `create-react-native-app`, a tool for setting up development of iOS and Android apps using React Native. If this is your intended platform, I'd suggest following this guide for setup: https://facebook.github.io/react-native/docs/getting-started.html . If you're wanting to do web development, you'll need to find somewhere else to ask this question. Hope this helps!
