### ISSUE TITLE
[Windows] Watchdog is sometimes doing nothing

### ISSUE THREAD

**Issue by daintycode** [react-community/create-react-native-app#528]
## Description

On saving files, the watchdog often does nothing. Saving it a few more times suddenly "wakes it up" and it bundles for any additional save.

## Expected Behavior

Bundle and reload on phone (Expo) with every save.

## Observed Behavior

The watchdog slept.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
```
wedo@0.1.0 D:\repos\wedo
`-- react-native-scripts@1.8.1
```
* `npm ls react-native`:
```
wedo@0.1.0 D:\repos\wedo
`-- react-native@0.50.3
```
* `npm ls expo`:
```
wedo@0.1.0 D:\repos\wedo
`-- expo@23.0.6
```
* `node -v`:
```
v8.6.0
```
* `npm -v`:
```
5.6.0
```
* `yarn --version`:
```
1.3.2
```
* `watchman version`:
```
Der Befehl "watchman" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
```
(which translates to command not found.)

Also specify:

1. Operating system: Windows 10 x64
2. Phone/emulator/simulator & version: OnePlus E1003, Android 6.0.1

## Reproducible Demo

Create new project, make a few changes, a custom Component, it basically happens here and there, I can't be the only one, this must've been there for everyone at least once.

**Comment by piu130** [comment]
As you can read [here](https://github.com/react-community/create-react-native-app#installation) `create-react-native-app` does not support npm v5 currently.

But I have the same problem with `node 7.9.0` and `npm 4.2.0`.

**Comment by brentvatne** [comment]
hi! I do not know what watchdog is. you could install watchman and that will likely solve your problem: https://facebook.github.io/watchman/

**Comment by daintycode** [comment]
Watchman is a watchdog.
But if it isn't installed within the react scripts, how does any auto recompiling work at all?
