### ISSUE TITLE
Tests fail to run on new project creation

### ISSUE THREAD

**Issue by christopherdiehl** [react-community/create-react-native-app#529]
## Description
`npm run test` fails with the error `this promise must be present when running with -o.`

1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior

What action did you perform, and what did you expect to happen?
I expected tests to run.

## Observed Behavior

What actually happened when you performed the above actions?
The tests failed.

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Determining test suites to run...Error: This promise must be present when running with -o.
    at /Users/chris/git/apps/FirstProject/node_modules/jest/node_modules/jest-cli/build/search_source.js:202:17
    at Generator.next (<anonymous>)
    at step (/Users/chris/git/apps/FirstProject/node_modules/jest/node_modules/jest-cli/build/search_source.js:19:362)
    at /Users/chris/git/apps/FirstProject/node_modules/jest/node_modules/jest-cli/build/search_source.js:19:592
    at /Users/chris/git/apps/FirstProject/node_modules/jest/node_modules/jest-cli/build/search_source.js:19:273
    at SearchSource.getTestPaths (/Users/chris/git/apps/FirstProject/node_modules/jest/node_modules/jest-cli/build/search_source.js:216:10)
    at /Users/chris/git/apps/FirstProject/node_modules/jest/node_modules/jest-cli/build/run_jest.js:44:29
    at Generator.next (<anonymous>)
```

## Environment

Mac v 10.12.6
Node v 7.10

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
react-native-scripts@1.8.1
* `npm ls react-native`:
react-native@0.50.3 
* `npm ls expo`:
* `node -v`:
* `npm -v`:
v4.2.0
* `yarn --version`:
* `watchman version`:
4.9.0

Also specify:

1. Operating system:
2. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by kavsingh** [comment]
Am having the same problem when trying to run tests after project init

**Comment by brentvatne** [comment]
it seems that jest changed under our feet such that `--watch` requires a git repo. we will disable this by default going forward. thanks!
