### ISSUE TITLE
react-native-elements - vector icons

### ISSUE THREAD

**Issue by wedelgaard** [react-community/create-react-native-app#53]
It seems like create-react-native app has some issues with "react-native-elements". I've tried 2 scenarios which both produces the same error:

#### Test 1
* created a new project with create-react-native-app
* `npm i react-native-elements --save`
* Added a react-native-elements button in App.js
* `npm run ios`

#### Test 2
* created a new project with create-react-native-app
* `npm i react-native-vector-icons --save && react-native link react-native-vector-icons`
* `npm i react-native-elements --save`
* Added a react-native-elements button in App.js
* `npm run ios`

In both test the simulator throws this warning. I've tried to run the commands described in the error message, but with no luck :(

<img width="315" alt="screen shot 2017-03-14 at 11 02 39" src="https://cloud.githubusercontent.com/assets/3899287/23896997/d13fb16e-08ab-11e7-9e03-f35375575b89.png">

**Comment by dikaiosune** [comment]
Hi! Thanks for the report. We're working on making it easier to use these transparently in CRNA.

If you first install https://www.npmjs.com/package/@expo/vector-icons and then try using react-native-elements, this should work for you. Note that if/when you eject to a regular RN project, you'll need to switch from Expo's vector icons to the regular react-native-vector-icons.

Let me know if that resolves your immediate issue. In the near future we hope to resolve this more transparently for users.

**Comment by wedelgaard** [comment]
@dikaiosune thx got me a little further. Now this issues arrises

![screen shot 2017-03-14 at 21 49 21](https://cloud.githubusercontent.com/assets/3899287/23921769/25934556-0900-11e7-8db2-167ea9875675.png)

**Comment by brentvatne** [comment]
Hello! Thanks for catching this, we'll add `ttf` as a default support asset extension in our next release this afternoon.

See this repo for a working example of react-native-elements: https://github.com/exponent/elements-example-crna

The most important part is this: https://github.com/exponent/elements-example-crna/blob/master/app.json#L4-L6 -- if you add it to your app.json and restart the packager (necessary to pick up the changes to the packager options) it should work

**Comment by binoy14** [comment]
@brentvatne In regards to https://github.com/react-native-community/react-native-elements/issues/221 I am trying to create documentation on how to use react-native-elements with create-react-native-app. Is the change in the app.json required only till the new release or will that change be required?

**Comment by dikaiosune** [comment]
@binoy14 I just released a temporary fix. Going to leave this open until I can fix upstream.

TODO: release new xdl version and update react-native-scripts to it.
