### ISSUE TITLE
npm run eject fails

### ISSUE THREAD

**Issue by atul-ojha** [react-community/create-react-native-app#531]
## Description
`npm run eject` fails while `npm start` runs successfully.
have tried with version 8 of node js as well but no luck.

## Expected Behavior
npm run eject should complete without error

## Observed Behavior
get the erorr message below:-

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "eject"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! firstApp@0.1.0 eject: `react-native-scripts eject`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the firstApp@0.1.0 eject script 'react-native-scripts eject'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the firstApp package,
npm ERR! not with npm itself.

**more details from C:\Users\\AppData\Roaming\npm-cache\_logs\2018-01-16T09_36_58_097Z-debug.log**

4 verbose run-script [ 'preeject', 'eject', 'posteject' ]
5 info lifecycle firstApp@0.1.0~preeject: firstApp@0.1.0
6 silly lifecycle firstApp@0.1.0~preeject: no script for preeject, continuing
7 info lifecycle firstApp@0.1.0~eject: firstApp@0.1.0
8 verbose lifecycle firstApp@0.1.0~eject: unsafe-perm in lifecycle true
9 verbose lifecycle firstApp@0.1.0~eject: PATH: ****
10 verbose lifecycle firstApp@0.1.0~eject: CWD: C:\Users\\Desktop\TempWrk\mobile\firstApp
11 silly lifecycle firstApp@0.1.0~eject: Args: [ '/d /s /c', 'react-native-scripts eject' ]
12 silly lifecycle firstApp@0.1.0~eject: Returned: code: 1  signal: null
13 info lifecycle firstApp@0.1.0~eject: Failed to exec eject script
14 verbose stack Error: firstApp@0.1.0 eject: `react-native-scripts eject`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid firstApp@0.1.0

## Environment
Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:  (empty)
* `npm ls react-native`: react-native@0.50.3
* `npm ls expo`: (empty)
* `node -v`: v7.10.1
* `npm -v`: 4.2.0
* `yarn --version`: not installed
* `watchman version`: tried installing this but, it says package no longer supported.

Also specify:
1. Operating system: Windows 10
2. Phone/emulator/simulator & version:

## Reproducible Demo
fails the last step below
`npm install -g create-react-native-app`
`create-react-native-app firstApp`
`npm run eject`

**Comment by zzq392342084** [comment]
@atul-ojha hey, I have the same issue,what was the solution for your problem?

**Comment by atul-ojha** [comment]
I tried with different node and npm versions. But I think what worked was installing yarn globally, which I did not have installed initially.

**Comment by Luismi74** [comment]
my solution: `npm install -g react-native-scripts ` then run `react-native-scripts eject` . this will do the same as npm run eject. hope it works!

**Comment by Santhoshsanto** [comment]
[android.dangerous]: withAndroidDangerousBaseMod: Source and destination must not be the same.
Error: [android.dangerous]: withAndroidDangerousBaseMod: Source and destination must not be the same.


This issue finding me after giving npm eject

how to fix this thanks in advance
