### ISSUE TITLE
migrate code create-react-native-app from react-native-cli

### ISSUE THREAD

**Issue by Jean-Jacques-Annaud** [react-community/create-react-native-app#534]
I made app using react-native-cli so when I have to use simulator, I should use Xcode or android studio.
and now I want to use create-react-native-app instead of react-native-cli
but after installing create-react-native-app, yarn run iOS(or yarn run android) has error
```
:error Command "ios" not found.
```
or
```
:error No command specified.
```
should I make app with create-react-native-app to use 'npm  run ios'  or 'npm run android'?

 - env

* `npm ls react-native-scripts`: 
└── (empty)

* `npm ls react-native`:
└── UNMET DEPENDENCY react-native@0.45.1
npm ERR! missing: react-native@0.45.1, required by EarlierDoctorHospital6@0.0.1

* `npm ls expo`:
└── (empty)

* `node -v`:  v9.4.0
* `npm -v`: 5.6.0
* `yarn --version`: 1.3.2
* `watchman version`: 
{
    "version": "4.9.0"
}

Also specify:

1. Operating system: macos
2. Phone/emulator/simulator & version:

**Comment by fxfactorial** [comment]
Hi to be clear, you did: 

```
create-react-native-app my_app
cd my_app
yarn run ios
```

And it didn't work?
