### ISSUE TITLE
ip have extra space when set EXPO_PACKAGER_HOSTNAME=192.168.191.1 && react-native-scripts start

### ISSUE THREAD

**Issue by deepkolos** [react-community/create-react-native-app#536]
## Description

```shell
> set EXPO_PACKAGER_HOSTNAME=192.168.191.1 && react-native-scripts start
```
```shell
> set EXPO_PACKAGER_HOSTNAME='192.168.191.1' && react-native-scripts start
```

## Expected Behavior

![correct ip](https://user-images.githubusercontent.com/12824616/35194633-4fbf22ae-fef1-11e7-8e4e-eb8b146deda9.png)

## Observed Behavior

![extra space](https://user-images.githubusercontent.com/12824616/35194626-3b4b753e-fef1-11e7-86ab-43ad65f39236.png)

![extra space with comma](https://user-images.githubusercontent.com/12824616/35194656-859716ac-fef1-11e7-8068-c3935ecfcc58.png)

## Environment

1. Operating system: windows 10 1073
2. Phone/emulator/simulator & version: "react-native-scripts": "1.9.0"

## Reproducible Demo

```
> create-react-native-app AwesomeProject
> cd AwesomeProject
> npm start
```

**Comment by yahveh** [comment]
`set EXPO_PACKAGER_HOSTNAME=192.168.191.1&& react-native-scripts start`
works for me

**Comment by dancinglone** [comment]
I came across with the same issue. And I didn't run with: "set EXPO_PACKAGER_HOSTNAME=192.168.191.1 && react-native-scripts start"   to specify the ip  ,  I just normally run : npm start.   I don't know why there's an extra space .

**Comment by fson** [comment]
Note that you need to omit the space before `&&`, that is:
```
set EXPO_PACKAGER_HOSTNAME=192.168.191.1&& react-native-scripts start
```
However, since this seems to be a common issue, we will trim the whitespace in the next version of `react-native-scripts`.
