### ISSUE TITLE
SSL23_GET_SERVER_HELLO:unknown protocol on mac behind firewall

### ISSUE THREAD

**Issue by digitaldivvy** [react-community/create-react-native-app#539]
## Description
Bash and Npm firwall is configured ok.
Starting  ios simulator for a basic app results in errors.

## Expected Behavior
Expect the simulator to show up with the app.

## Observed Behavior

The simulator starts up but there is no app. The console shows the following error:

```
14:15:09: Starting packager...
14:15:17: Starting simulator...
14:15:18: Failed to start simulator:

Error: write EPROTO 140735947440960:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:797:


Exiting...

```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
```
fingertips@0.1.0 /Users/n0110643/git/pidco/mobile-app/fingertips
└── react-native-scripts@1.11.0 

```
* `npm ls react-native`:
```
fingertips@0.1.0 /Users/n0110643/git/pidco/mobile-app/fingertips
└── react-native@0.50.3 
```
* `npm ls expo`:
```
fingertips@0.1.0 /Users/n0110643/git/pidco/mobile-app/fingertips
└── expo@23.0.6 
```

* `node -v`: v8.1.4

* `npm -v`: 5.0.3
* `yarn --version`: 0.27.5
* `watchman version`:     "version": "4.7.0"

Also specify:

1. Operating system: mac os 10.13.2
2. Phone/emulator/simulator & version:
Version 10.0 (SimulatorApp-835.2.1 CoreSimulator-494.22.7)

## Reproducible Demo

This is reproducible from behind a proxy - where the https and http proxy resolve to port 80.

**Comment by tolulopep** [comment]
Anyone has an idea on how to solve this? I am facing the same issue

**Comment by rlambrecht** [comment]
Same here, tried both XCode Tools v8.1.0 and 9.2.0 and same error. Also behind a proxy with configurations for npm/yarn set correctly.

**Comment by YJBeetle** [comment]
检查是否设置了http_proxy 和 https_proxy 环境变量

**Comment by the-nose-knows** [comment]
@brentvatne Can we get some input from the react community or team? This is not a Mac-only bug and it has been open for quite a long time.

**Comment by the-nose-knows** [comment]
I performed a workaround. I'm guessing someone needs to update the JSON dependencies to be appropriate.

I changed this `app.json`:

```sh
{
  "expo": {
    "sdkVersion": "27.0.0"
  }
}
```

to this `app.json`:
```sh
{
  "expo": {
    "sdkVersion": "25.0.0"
  }
}
```

Then I re-ran `npm install` and was able to `yarn start` without errors.

**Comment by digitaldivvy** [comment]
@the-nose-knows “https and http proxy resolve to port 80” is a description of how the proxy was setup - nowhere did I mention it is “related to port 80 only”. Your snark comment did not pass the smell test.

**Comment by the-nose-knows** [comment]
@digitaldivvy No snark =/ Just throwing it out there since it was mentioned in the write-up. Anything that can be removed from a repro iteration is a good thing, no?
