### ISSUE TITLE
`yarnpkg add --dev --exact react-native-scripts` failed

### ISSUE THREAD

**Issue by Wallace121980** [react-community/create-react-native-app#54]
I get this error when i want to create a new app.

Creating a new React Native app in /Users/williamschrauwen/ReactNative/willappreciate.

Installing packages. This might take a couple minutes.
Installing react-native-scripts...

yarn add v0.21.3
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning react-native-scripts > xdl > node-uuid@1.4.7: use uuid module instead
warning react-native-scripts > xdl > @exponent/ngrok > node-uuid@1.4.7: use uuid module instead
warning react-native-scripts > xdl > auth0-js > xtend > object-keys@0.4.0: 
[2/4] 🚚  Fetching packages...
error react-native-scripts@0.0.18: The engine "node" is incompatible with this module. Expected version ">=6".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
`yarnpkg add --dev --exact react-native-scripts` failed

**Comment by Wallace121980** [comment]
Sorry, i updated my node version and it worked. You can close this.

**Comment by lucasbento** [comment]
@Wallace121980: you can also close this issue since you are the creator.
