### ISSUE TITLE
Not signed in Expo when using CRNA

### ISSUE THREAD

**Issue by amosyuen** [react-community/create-react-native-app#540]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

When I use Expo's AuthSession API it complains that I'm not signed into expo.

## Expected Behavior

What action did you perform, and what did you expect to happen?

1. I signed into expo using `exp` command line
1. Started the app using `react-native-scripts start`
1. Called `AuthSession.getRedirectUrl()`

I expected the Expo APIs should use my expo account and generate a redirect URL for my account.

## Observed Behavior

What actually happened when you performed the above actions?

Expo generates a redirect URL for a person not signed in. And gives a warning:

You are not currently signed in to Expo on your development machine. As a result, the redirect URL for AuthSession will be "https://auth.expo.io/@anonymous/caregiver-39c27e47-48e1-448f-88cb-bce8d4e55f08". If you are using an OAuth provider that requires whitelisting redirect URLs, we recommend that you do not whitelist this URL -- instead, you should sign in to Expo to acquired a unique redirect URL. Additionally, if you do decide to publish this app using Expo, you will need to register an account to do it.

However, if I startup the app using `exp start`, no error happens and the redirect URL uses my signed in account.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: 1.8.1
* `npm ls react-native`: 0.50.4
* `npm ls expo`: 23.0.6
* `node -v`: 8.9.1
* `npm -v`: 5.5.1
* `yarn --version`: 1.3.2

Also specify:

1. Operating system: Windows 10
2. Phone/emulator/simulator & version: Samsung Galaxy S8 Android v7.0

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by ide** [comment]
This is currently the expected behavior -- to use Expo services like AuthSession and push notifications, you should use `exp start`. `react-native-scripts start` uses a logged-out, anonymous developer account. We might make this distinction more obvious, but it's important that developers who want to go back to a logged-out project can do that, and that's what create-react-native-app does.

**Comment by amosyuen** [comment]
Perhaps add a param to skip setting the anonymous developer account?

**Comment by ide** [comment]
CRNA works only in anonymous mode — there is nothing to skip with it. You can use the --offline flag with exp start if you wish to use just one program and switch between modes

**Comment by jrc** [comment]
I'm using `expo start` and signed in to Expo both in my browser and in the simulator, but only now did I figure out that one needs to `expo login` on the command-line.
