### ISSUE TITLE
Update versions.md to address react 51, 52.

### ISSUE THREAD

**Issue by EdJones** [react-community/create-react-native-app#543]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

Using Expo throws version errors. It's not easy to figure out root version and adjustments to make. React 51 and 52 are not in Version.md

## Expected Behavior

Adding react-sortable-hoc to my app caused "React native version mismatch" in Expo. Attempts to line up various versions fail because I don't know which is fixed and which need changed. 

## Observed Behavior
Expo says Javascript cersion 0.52.2 Native version 0.51.0
What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment
Yarn on Windows 10; Expo client 2.3.0 on ios 11.2.2
Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
* `npm ls react-native`:
* `npm ls expo`:
* `node -v`:
* `npm -v`:
* `yarn --version`:
* `watchman version`:

Also specify:

1. Operating system:
2. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by brentvatne** [comment]
done
