### ISSUE TITLE
There is no index.js in app file!

### ISSUE THREAD

**Issue by see2hao** [react-community/create-react-native-app#544]
## Description

After `create-react-native-app app2`, I got lots of files without#  **# index.js** in my project root file.Is this a bug?
![image](https://user-images.githubusercontent.com/18247492/35613949-660e8afe-06a8-11e8-95b1-474f0a15226b.png)

##reate-react-native-app version: 1.0.0
##npm 4.0.0

**Comment by yacinehmito** [comment]
It appears if you eject.

Before ejection the scripts know about your folder structure and will use `App.js`.

**Comment by ide** [comment]
See package.json and app.json for how your app is configured and how it points to App.js, which is intentionally the entry point component of the project.

**Comment by cyb3rsalih** [comment]
**I solved!** 
Declaration of App is here
 `./node_modules/react-native-scripts/build/bin/crna-entry.js`

There, you can see App's default location which 

`var _App = require('../../../../App');`

Then you can change it. I put it App.js in a src folder than it looks like this

`var _App = require('../../../../src/App');`

**Comment by girardiricardo** [comment]
@cyb3rsalih worked for me, thanks!

![image](https://user-images.githubusercontent.com/26393165/44305024-c4853280-a343-11e8-826c-a8947b42b3a1.png)

**Comment by brortao** [comment]
For anyone coming across this: you shouldn't change files in `node_modules`, since they'll get overwritten when you update the package.

**Comment by CarisL** [comment]
which i can do ? I want to hasve index.js

**Comment by Guang1234567** [comment]
@see2hao 
@CarisL 

`index.js` isnot nessary, you can specify the  name of `entry.js`  as you like!

Snapshot:

![123](https://user-images.githubusercontent.com/8240718/182313387-f6e8802d-bdab-4c9b-b681-573ecf654e1b.png)
