### ISSUE TITLE
Unable to debug app with 'No 'Access-Control-Allow-Origin' header is present' error

### ISSUE THREAD

**Issue by psyanite** [react-community/create-react-native-app#545]
When I start up my Android Samsung S8+ device over wifi or Genymotion S8 emulator on the same machine to access the expo project using expo XDE, in the Chrome console, I see the following errors:
```
Failed to load http://192.168.1.6:19004/node_modules/expo/AppEntry.delta?platform=android&dev=true&strict=false&minify=false&hot=false&assetPlugin=G:\Projects\bt\ff\node_modules\expo\tools\hashAssetFiles: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:19004' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
Uncaught (in promise) TypeError: Failed to fetch
```

I believe this could potentially be caused by updating sdkVersion from 24.0.0 to 25.0.0. @brentvatne Do you have any idea? Does anyone not have this issue?

I believe it could be related to this issue reported 9 days ago which seems similar to what @jugutier has:
https://github.com/facebook/react-native/issues/17618

I can't debug and see what's happening on Redux 😭

Okay, I think the CORS error that @jugutier and I are experiencing is different to the original issue...

It won't let me downgrade to 24.0.0 😭 If anyone knows how I can downgrade to 24.0.0 please let me know.

A few other users have reported this issue on this thread:
https://github.com/react-community/create-react-native-app/issues/392

And also here:
https://github.com/expo/expo/issues/1351

If this is an issue that is a duplicate of https://github.com/expo/expo/issues/1351, please feel free to close this issue.

**Comment by quinlanj** [comment]
hi, this is an issue that occurred upstream with react native and the fix will ship in the next SDK. Sorry for the inconvenience!

**Comment by psyanite** [comment]
Workarounds are provided https://github.com/expo/expo/issues/1351#issuecomment-361932735, but not sure if they will work with mobile apps....

**Comment by digitalmaster** [comment]
@psyanite  Worked for me! 🙏🏽

**Comment by arfa123** [comment]
try to install the extension "Allow-Control-Allow-Origin" in your chrome browser, from this my problem is solved, you may try this.

**Comment by inferusvv** [comment]
@arfa123 Or simply use React Native Debugger :)

**Comment by whhotw** [comment]
@arfa123 you save me

**Comment by proffnick** [comment]
> Allow-Control-Allow-Origin

How safe is this extension ?
