### ISSUE TITLE
Jest not working on fresh install

### ISSUE THREAD

**Issue by TheDutchCoder** [react-community/create-react-native-app#548]
## Description

`npm run test` fails on a new project (ejected)

## Expected Behavior

I'd expect Jest to be installed and to run when `npm run test` is called.

## Observed Behavior

I receive an error saying that jest/bin/jest.js can't be found. (I anonymized some data)

```
npm run test

> ---@0.1.0 test /Users/---/projects/---
> node node_modules/jest/bin/jest.js

module.js:327
    throw err;
    ^

Error: Cannot find module '/Users/---/projects/---/node_modules/jest/bin/jest.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ---@0.1.0 test: `node node_modules/jest/bin/jest.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ---@0.1.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/---/.npm/_logs/2018-02-01T14_59_32_916Z-debug.log
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
```
---@0.1.0 /Users/---/projects/---
└── (empty)
```
* `npm ls react-native`:
```
---@0.1.0 /Users/---/projects/---
└── react-native@0.52.0
```
* `npm ls expo`:
```
---@0.1.0 /Users/---/projects/---
└── (empty)
```
* `node -v`: `v6.12.3`
* `npm -v`: `3.10.10`
* `yarn --version`: `zsh: command not found: yarn`
* `watchman version`: `zsh: command not found: watchman`

Also specify:

1. Operating system: macOS High Sierra (10.13.3)
2. Phone/emulator/simulator & version: Simulator 10.0

## Reproducible Demo

N/A (it's a new, ejected, install)

**Comment by yacinehmito** [comment]
It's because jest is not included among the dev dependencies. I'll submit a PR shortly.

**Comment by TallOrderDev** [comment]
Should this still be open?

**Comment by TheDutchCoder** [comment]
Nope, was merged in!
