### ISSUE TITLE
Error running eject: TypeError: Cannot read property 'preset' of undefined

### ISSUE THREAD

**Issue by Zewkin** [react-community/create-react-native-app#554]
Hi,

I'm trying to eject the app like a regular React Native project, and getting this error.

* `npm ls react-native-scripts`: react-native-scripts@1.11.1 
* `npm ls react-native`: react-native@0.48.4 
* `npm ls expo`: expo@21.0.3 
* `node -v`: v. 9.4.0
* `npm -v`: 5.6.0
* `yarn --version`: 1.3.2
* `watchman version`: 4.9.0

Operating system: macOS High Sierra 10.13.3
Phone/emulator/simulator & version: iPhone X emulator

**Comment by LeoIannacone** [comment]
I have the same issue

**Comment by brentvatne** [comment]
seems to be related to https://github.com/react-community/create-react-native-app/commit/fcc9629b16265cd04a84c96516f13932c79aa793#diff-71cd56714c1de5f358b099bac7336916R200

you can add a jest key back to your package.json with just `"jest": {}` and run it again to fix the problem.

a PR to fix this would be appreciated
