### ISSUE TITLE
I cant' start npm run ios 

### ISSUE THREAD

**Issue by Wuyialex** [react-community/create-react-native-app#56]
I'am was very pleased at create react native-app
But I can't run npm run ios, instead got message like "osascript -e tell app "System Events" to count processes whose name is "Simulator"
IOS simulator was opened, But they didn't give me screen of react native app, but can see normal IOS Screen.
what's the problem?

**Comment by kevin-wolf** [comment]
I was running into the same problem but after a couple of minutes figured out that expo was being installed. Maybe the team needs to add a visual progress bar while Expo is getting installed on the Simulator?
