### ISSUE TITLE
Failed building JavaScript bundles, stuck on 99% and do not show the changes in the app. No detailed message of error.

### ISSUE THREAD

**Issue by Neeraj1108Yadav** [react-community/create-react-native-app#560]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior

What action did you perform, and what did you expect to happen?

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
* `npm ls react-native`:
* `npm ls expo`:
* `node -v`:
* `npm -v`:
* `yarn --version`:
* `watchman version`:

Also specify:

1. Operating system:
2. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by Neeraj1108Yadav** [comment]
npm ls react-native-scripts: `-- react-native-scripts@1.10.0'
npm ls react-native:  `-- react-native@0.52.0
npm ls expo: `-- expo@25.0.0
node -v: v8.9.4
npm -v: 4.6.1
watchman is not installed

Operating system: Windows 10 64 bit
Phone: Lenovo

Uploaded my, it is showing my previous development, but updating fresh changes, Not able to build javascript bundle is the only error I'm getting in cmd.
![image](https://user-images.githubusercontent.com/34931349/36042791-07b47c32-0df3-11e8-81ba-7599f72be227.png)

**Comment by fxfactorial** [comment]
Hi @Neeraj1108Yadav , I'm not quite clear, what is your issue?

**Comment by Neeraj1108Yadav** [comment]
This is my first screen of the app, I did the changes in the and when I'm running it using expo, it is not doing changes, but showing me the error as "Failed building Javascript bundle". Every time it is showing me the same screen even if I remove the <Text> tag of "LOGIN". I hope you understand my problem.

**Comment by Neeraj1108Yadav** [comment]
@jackmurray I think the problem of not updating the source code and showing 99% is due to react-navigation library ( in my case ). When I removed this library it worked perfectly.

**Comment by jackmurray** [comment]
Did you remember to `npm install --save react-navigation`? I forgot this step.

But I still have some other error somewhere that is causing the 99% problem, even if I remove react-navigation. I found that syntax error now (missing an equals sign).

I will try to add react-navigation in again. I finally was able to get an error message to expo.

I found it useful to quit expo, then kill every expo process in the background. I think this forced expo to remove the old version of the app, and it now displays a useful error message again.

**Comment by jackmurray** [comment]
Ok, that is working for me now.

Make sure you do `export default App` after your `const App = StackNavigator(...)`

It really helped after I was able to get the Expo errors showing again (fix above)

**Comment by Neeraj1108Yadav** [comment]
@jackmurray thanks for your suggestion. I'll implement it in my code and will let you know.

**Comment by Neeraj1108Yadav** [comment]
Help me with this error, I'm not able to solve this, don't know what is the problem. Below mention is my code. I want to navigate from "HomeScreen" to "Registration". When I do this the code stop updating the code and show me the error. Attached Image
![error](https://user-images.githubusercontent.com/34931349/36108839-c14ed17c-1043-11e8-90fd-5ae5bdda8933.JPG)

import React from 'react';
import { StyleSheet,View,Image, Text,ImageBackground, TextInput, Button, Alert} from 'react-native';
import { Navigation } from 'react-native-navigation';

Navigation.registerComponent('BttonWork.HomeScreen', () => HomeScreen);
Navigation.registerComponent('BttonWork.Registeration', () => Registeration);

export default class HomeScreen extends React.Component {

	SampleFunction1(){
 
    Alert.alert("Function Without Argument");
    
	}
  constructor(props) {
	  super(props);
	  this.state = {
		  username: '',
		  pasword: ''
	  };
  }
  render() {
	
    return (	
	<View style = {{flex: 1}}>
	  <ImageBackground style = {{flex: 1,height: null, width: null}} source = {require('./assets/backimage.jpg')}>
	  
		<View style = {{flex: 1, backgroundColor: '#000000A6', flexDirection: 'column'}}>
		
			<View style = {{height: 100, width: null}}></View>
			
			<Text style = {{textAlign: 'center', color: '#6CC829', fontSize: 18, fontWeight: 'bold'}}> LOGIN </Text>
			<Text style = {{textAlign: 'center', color: '#6CC829', fontSize: 14, marginTop: 3}}> Enter your credentials here </Text>
			
			<View style = {{height: 100, width: null}}></View>
			
			<View style = {{marginLeft: 20, marginRight: 20, flexDirection: 'column'}}>
			
				<Text style = {{color: '#fff', fontSize: 15}}> Username </Text>
				
				<TextInput style = {{color: '#fff',fontSize: 13, borderColor: 'white', borderBottomWidth: 1, marginTop: 3, marginLeft: 5}}
				 onChangeText = {(username) => this.setState({username})}
				 value = {this.state.username}
				 underlineColorAndroid = 'rgba(0,0,0,0)'/>
				 
				 <Text style = {{color: '#fff', fontSize: 15, marginTop: 10}}>Password</Text>
				 
				 <TextInput secureTextEntry={true} style = {{color: '#fff', fontSize: 13, borderColor: 'white', borderBottomWidth: 1, marginTop: 3, marginLeft: 5}}
				onChangeText = {(pasword) => this.setState({pasword})}
				value = {this.state.pasword}
				underlineColorAndroid = 'rgba(0,0,0,0)'/>
				
			</View>
			
			<View style = {{height: 100, width: null}}></View>
			
			<View style = {{marginLeft: 20, marginRight: 20, flexDirection: 'column'}}>
			
			<Button
			title = "Sign In"
			color = "#6CC829"
			onPress = {this.props.navigator.push({
			screen: 'BttonWork.Registeration',
			animated: true,
			animationType: 'fade' });}/>
			
			<Text style = {{textAlign: 'center', fontSize: 12, color: '#6CC829', marginTop: 5}}>Don't have an account? </Text>
			<Text style = {{textAlign: 'center', fontSize: 15, color: '#6CC829', marginTop: 5, fontWeight: 'bold'}}>SIGN UP</Text>
			
			</View>
			
		</View>
		
	  </ImageBackground>
	</View>
    );
  }
}

class Registeration extends React.Component {
	render()
	{
		return (
		<View style = {{flex: 1}}>
			<ImageBackground style = {{flex: 1, height: null, width: null}} source = {require('./assets/backimage.jpg')}>
			
				<View style = {{flex: 1, backgroundColor: '#000000A6', flexDirection: 'column'}}>
				
					<View style = {{height: 70, width: null}}></View>
					
					<Text style = {{textAlign: 'center', color: '#6CC829', fontSize: 18, fontWeight: 'bold'}}> REGISTER </Text>
					<Text style = {{textAlign: 'center', color: '#6CC829', fontSize: 14, marginTop: 3}}>  </Text>
					
					<View style = {{height: 70, width: null}}></View>
					
				</View>
			
			</ImageBackground>
		</View>
		);
	}
}

**Comment by venil7** [comment]
Having the same issue. `react-native` should print any compilation errors to the console, otherwise it's very hard to debug

**Comment by jcktm** [comment]
> I found it useful to quit expo, then kill every expo process in the background. I think this forced expo to remove the old version of the app, and it now displays a useful error message again.

**Comment by hpatel123** [comment]
@jcktm You are right. There was an issue with new class (Code). I'd remove it and run it and it works fine.

**Comment by iosdev-republicofapps** [comment]
Hi, I get this sometimes.  Is there no way to see the reason causing the "Failed building Javascript bundle"?  Isn't there a log somewhere where I could look to even get a hint?  :-)

**Comment by dakt** [comment]
Yeep, it's quite annoying not seeing the reason and then searching which import is wrong. I had major code cleanup and it was a horror show.

**Comment by impactcolor** [comment]
For me the error happened because of some bad syntax in one of my files.  I have a component file Input.js.  I was testing the app using yarn run ios and on the simulator it would crash expo and give me the "Failed building JavaScript bundles" at 99%.  There was no further error code.  I ran it on my iphone by using the QR code given and there it gave me the errors which pointed me to incorrect syntax.

**Comment by brunoreis** [comment]
This is also happening to me. Since debugging errors is one of the main activity of development and being able to see what is happening is fundamental to that, this is something that is taking me probably more than one hour of development time in just one day. Expo is a fantastic tool ant having this fixed would be really wonderful to keep up with the great productivity that expo allows us.

**Comment by brunoreis** [comment]
Usually, when this happens the build is a lot slower and indeed it stops on 99 (99.18%)

**Comment by immexerxez** [comment]
I find it so hard to believe there isn't a verbose option tucked away somewhere that we're missing? I seriously can't stand seeing this it's a huge waste of time.

**Comment by zachdixon** [comment]
Seems like the most common cause is syntax errors, for me it was a bad import path. Usually I get the error "can't find module" etc. but got the same thing described here instead.

**Comment by Haegin** [comment]
Currently the best solution I have for this is to stash my work to get back to a state where it still works, get the simulator running successfully, then unstash the bad changes. For some reason after it's built successfully the first time it can show errors correctly on subsequent builds.

**Comment by moaxaca** [comment]
The library maintainers need to throw the error up into the console. Debugging these issues are unbearable.

**Comment by Haegin** [comment]
If anyone can point me in the right direction to fix this I'm happy to give it a go. At the moment I'm losing so much time to this that it'd be well worthwhile.

**Comment by immexerxez** [comment]
@haegin the best I can do as well has been your comment from three days ago. The issue is the errors only printed to the simulator..and the only way to get to the simulator is a successful build

**Comment by moaxaca** [comment]
@Haegin I branched by RN app and ejected from expo then all the errors became visible. After reading the message I switch back to my expo branch.

**Comment by legarland** [comment]
Mine was caused by a bad import. I had pasted come code from another component into a new file and Webstorm attempted to generate the import statement for me but ended up locating it in the typings directory of the library. I believe this is why there were no specific errors being thrown since the packager thought it had located the package.

`import { createAnimatableComponent } from 'react-native-animatable/typings/react-native-animatable`

had to be changed to

`import { createAnimatableComponent } from 'react-native-animatable`

**Comment by nicolas-amabile** [comment]
Try to run it with Expo XDE. Logs there should give you a clue about the error you are having. In my case it was a missing plugin, but apparently it could be anything 🤷‍♂️

**Comment by iosdev-republicofapps** [comment]
Thanks @nicolas-amabile .  But a lot of us aren't using Expo XDE, we're using another IDE like VSCode.  So "use Expo XDE" can't be the answer here ...

Hey @terribleben, @brentvatne or @jesseruder - any ideas on this?  This is becoming a real blocker for a lot of us using Expo and personally I'm thinking of ejecting just to avoid this issue.  Any help would be much appreciated!  :-)

**Comment by nicolas-amabile** [comment]
@iosdev-republicofapps Sorry, what I meant to say is not a particular IDE but the other tool (not the CLI) expo provides to run the project.
From [their page](https://expo.io/tools#xde):
> If you don't prefer the Expo CLI, Expo XDE is a graphical development environment to serve, share, and publish your Expo projects.

Take a look at this example. I generated an error in one of my component to illustrate.
Terminal:
<img width="680" alt="screen shot 2018-06-18 at 21 08 22" src="https://user-images.githubusercontent.com/8633440/41568529-7d8ee628-733c-11e8-8686-2dc05a63dab2.png">
No clue about the error.
However with Expo XDE you can open the existing project and launch it from there. In this case this was the result:
<img width="1312" alt="screen shot 2018-06-18 at 21 09 04" src="https://user-images.githubusercontent.com/8633440/41568555-9cfd4572-733c-11e8-9d40-758b0f87a015.png">

Give it a try and let us know how did it go 😉

**Comment by dctucker** [comment]
I strongly agree with @iosdev-republicofapps, "just use Expo XDE" is not an acceptable solution to this problem. In order to use Expo XDE, I have to first modify composer.json from what is produced by `react-create-native-app` following [these directions](https://stackoverflow.com/questions/45187220/not-using-the-expo-fork-of-react-native). Then, when I discover what the problem is with Expo XDE and want to further debug my program, the output it produces is extremely mess compared to what the CLI offers, so I have to close that down and relaunch `yarn start` via the CLI.

It's a really clunky experience, and I'd really like to see this improve.

**Comment by fgagneten** [comment]
For me the error happened because of **some bad syntax in one of my files**. The **solution** for me was **force stop Expo app** and try to run again the project. After that, I could see the error.

**Comment by borch84** [comment]
I had the same issue. I got some error, did not find the error clearly so I commented some additional lines of code in order discard error, then I had to restart Expo in order to successfully launch the app again on my phone. This behavior should be corrected.

**Comment by quinlanj** [comment]
hi all, 
here are a couple workarounds for this issue:
1. use a linter
2. use `exp` tools, which has the updated code to print to console

to fix this problem, the `xdl` dependency needs to be bumped cc: @fson

**Comment by j0nscalet** [comment]
XDE is a decent workaround for the problem, as it seems most of the time the issue occurs due to a syntax error. However, it's definitely not ideal.

**Comment by Tvrqvoise** [comment]
Ugly and anecdotal workaround, but I've found that if I mock out my entire application, it'll let expo load, then if I put my application back, I'll get my error message.  So, for example, if my App.js looks like this:

```jsx
// App.js
import React, { PureComponent } from 'react'
import MyTopLevelComponent from 'path/to/component' // this is where my component tree starts

export default App extends PureComponent {
  render () {
    return <MyTopLevelComponent />
  }
}
```

Expo will crash and I won't get any error. However, if I change App.js to be this instead:
```jsx
// App.js
import React, { PureComponent } from 'react'
// import MyTopLevelComponent from 'path/to/component' // this is where my component tree starts

export default App extends PureComponent {
  render () {
    return null
    //return <MyTopLevelComponent />
  }
}
```

Then it will load an empty application in Expo.  Now, all I need to do is put back the real code and I'll get an errorbox in the simulator which details the real error.

**Comment by marcusmolchany** [comment]
If you build your project using the desktop XDE application, sometimes it will give you better error messages. I've gotten these error messages before when I forgot to import a file, or have a type in the import string.

**Comment by kmturley** [comment]
I was getting the JavaScript bundle failed. I solved by:
1) Ctrl-C to qui the `npm start`
2) Quit the `Expo` app on Android emulator
3) run again using: `npm start --reset-cache`
