### ISSUE TITLE
Hi im having a problem here and im very new to react native :( badly need help asap

### ISSUE THREAD

**Issue by hazzacookie** [react-community/create-react-native-app#562]
![27990602_1992297520785230_2062593919_o](https://user-images.githubusercontent.com/36332531/36070436-8276b87a-0f35-11e8-8c49-6cfc4cd15949.jpg)

**Comment by alexanderwallin** [comment]
Hi @hazzacookie. Check out the [Support and Contact](https://github.com/react-community/create-react-native-app#support-and-contact) section of the README. You'll find your way there.
