### ISSUE TITLE
Cannot install create-react-native-app

### ISSUE THREAD

**Issue by ghost** [react-community/create-react-native-app#563]
So I have started learning  react native but got stuck on the first step. 
The installation is failing and the error I am getting is:

npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! request to https://registry.npmjs.org/create-react-native-app failed, reason: write EPROTO 101057795:error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied:openssl\ssl\s23_clnt.c:802:
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\choudabh\AppData\Roaming\npm-cache\_logs\2018-02-13T07_40_39_944Z-debug.log

* `npm ls react-native-scripts`: C:\Users\choudabh\Desktop\React
`-- (empty)

* `npm ls react-native`: C:\Users\choudabh\Desktop\React
`-- (empty)

* `npm ls expo`: C:\Users\choudabh\Desktop\React
`-- (empty)

* `node -v`: v8.9.4 

* `npm -v`: 5.6.0

* `yarn --version`:  1.3.2

* `watchman version`:  watchman : The term 'watchman' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

1. Operating system: Windows 10

**Comment by ElNobDeTfm** [comment]
Seems more like a problem with your setup/internet connection than with this package. Did you try reinstalling Node/npm? Also the log indicates SSL errors, that may happen if you're behind a firewall or a corporate network.

**Comment by danielrodriguezb** [comment]
The cli doesn't currently support npm 5 due to npm bugs, this is stated in the readme. Maybe you can use something like nvm to go back and forth npm versions, between the create react native app projects and other projects you may have.
