### ISSUE TITLE
yarn test fails

### ISSUE THREAD

**Issue by watadarkstar** [react-community/create-react-native-app#568]
## Description

I want to run tests. Might be related to: https://github.com/react-community/create-react-native-app/issues/199

## Expected Behavior

Tests succeed.

## Observed Behavior

Tests always fail. With a variety of syntax errors.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: 1.11.1
* `npm ls react-native`: 0.52.0
* `npm ls expo`: 25.0.0
* `node -v`: v8.1.1
* `npm -v`: 5.0.3
* `yarn --version`: 1.3.2
* `watchman version`: 4.7.0

Also specify:

1. Operating system: Mac OSX High Sierra
2. Phone/emulator/simulator & version: N/A

## Reproducible Demo

I got only one test, it's the default test CRNA creates. 

I have created a minimal example of what makes CRNA fail when running `yarn test`.

It is after this commit where `yarn test` starts to fail https://github.com/watadarkstar/minimal-failing-crna-yarn-test/commit/94fdee722f773196f80b349f0d8ae970e4ed3d04

The minimal example can be found here: https://github.com/watadarkstar/minimal-failing-crna-yarn-test

I try to run it with `yarn test`

I get `SyntaxError: Unexpected token import` in many source files. I get this with the default `package.json`:

```
node_modules/native-base-shoutem-theme/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import connectStyle from "./src/connectStyle";
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      1 | import React from 'react';
    > 2 | import { Text, View } from 'native-base';
      3 | import { StackNavigator } from 'react-navigation';
      4 | import { Home, Quiz, Results } from './components/screens';
      5 |
```

My `.babelrc`:

```
{
  "presets": ["babel-preset-expo"],
  "env": {
    "development": {
      "plugins": ["transform-react-jsx-source"]
    }
  }
}
```

My `package.json`:

```
"test": "node node_modules/jest/bin/jest.js"
```

**Comment by anp** [comment]
Hi! It looks like you have other things in package.json than the default contents of a CRNA project. Can you paste the full package.json?

**Comment by watadarkstar** [comment]
@anp Sure, I have tried both of these `package.json` changing what the `test` script does:

```
{
  "name": "foo",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "babel-preset-react-native": "^4.0.0",
    "cross-env": "^5.1.3",
    "eslint-config-rallycoding": "^3.2.0",
    "jest-expo": "^25.1.0",
    "react-native-scripts": "1.11.1",
    "react-test-renderer": "16.2.0"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "cross-env NODE_ENV=development jest --config ./scripts/jest/config.source.js"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "expo": "^25.0.0",
    "native-base": "^2.3.9",
    "react": "16.2.0",
    "react-native": "0.52.0",
    "react-native-htmlview": "^0.12.1",
    "react-navigation": "^1.0.3",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
  }
}
```

and this:

```
{
  "name": "foo",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "babel-preset-react-native": "^4.0.0",
    "cross-env": "^5.1.3",
    "eslint-config-rallycoding": "^3.2.0",
    "jest-expo": "^25.1.0",
    "react-native-scripts": "1.11.1",
    "react-test-renderer": "16.2.0"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "expo": "^25.0.0",
    "native-base": "^2.3.9",
    "react": "16.2.0",
    "react-native": "0.52.0",
    "react-native-htmlview": "^0.12.1",
    "react-navigation": "^1.0.3",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
  }
}
```

**Comment by anp** [comment]
Can you try creating a new CRNA project and adding things until they fail? It's going to be difficult to reproduce this without a smaller list of dependencies or example source files. If you can find some combination of a couple of these factors which reliably triggers this error, can you upload it to GitHub and share it here?

**Comment by watadarkstar** [comment]
I can get my tests to pass if I add this to my `jest` config:

```
transformIgnorePatterns: [
    'node_modules/(?!react-navigation|react-native|expo|native-base-shoutem-theme|@shoutem/animation|@shoutem/ui|tcomb-form-native)'
  ]
```

to this:

```
'use strict';

module.exports = {
  // Only include files directly in __tests__, not in nested folders.
  testRegex: '/__tests__/[^/]*(\\.js|\\.coffee|[^d]\\.ts)$',
  moduleFileExtensions: ['js', 'jsx', 'json', 'node', 'coffee', 'ts'],
  rootDir: process.cwd(),
  modulePaths: [
      '<rootDir>/src',
      '<rootDir>/node_modules'
  ],
  preset: 'jest-expo',
  transformIgnorePatterns: [
    'node_modules/(?!react-navigation|react-native|expo|native-base-shoutem-theme|@shoutem/animation|@shoutem/ui|tcomb-form-native)'
  ]
};
```

**Comment by watadarkstar** [comment]
@anp 

I have created a minimal example of what makes CRNA to fail when running `yarn test`.

It is after this commit where `yarn test` starts to fail https://github.com/watadarkstar/minimal-failing-crna-yarn-test/commit/94fdee722f773196f80b349f0d8ae970e4ed3d04

The minimal example can be found here: https://github.com/watadarkstar/minimal-failing-crna-yarn-test

**Comment by ide** [comment]
It sounds like this is kind of working as expected. The default config doesn't whitelist the transformer for `native-base-shoutem-theme`. I think your solution is correct -- you must whitelist each package as needed.

One alternative for us is to whitelist all packages but we'd need to profile Jest on a large codebase to see how much longer it would take to run tests. In the meantime I think your approach is a good one.

**Comment by watadarkstar** [comment]
@ide I can agree from a technical perspective this works as expected once you dive into the issue. Although from a user's perspective, many people will run into this issue as soon as they add a package that doesn't need to be transpiled and then run `yarn test`. It would be nice if there was a more user-friendly solution.

Another alternative is to provide a more meaningful error message when these transpile errors occur in `node_modules` from Jest, but I don't know enough about how Jest works.

**Comment by ide** [comment]
I'm not sure we can provide a more user-friendly message. Do you have ideas for how we could practically do that?

One fix people could apply on their own, if they want to bear the cost of more transforms, is to set `transformIgnorePatterns: []`.
