### ISSUE TITLE
Not able to run tests "Modal.js: Unexpected token"

### ISSUE THREAD

**Issue by dgrcode** [react-community/create-react-native-app#577]
## Description

I cannot run tests

## Expected Behavior

I should be able to run tests

## Observed Behavior

When I try to run tests I always get the following error.

```
 ● Test suite failed to run

    /{path to my project}/node_modules/react-native/Libraries/Modal/Modal.js: Unexpected token (30:12)
        28 |   new NativeEventEmitter(NativeModules.ModalManager) : null;
        29 | 
      > 30 | import type EmitterSubscription from 'EmitterSubscription';
           |             ^
        31 | 
        32 | /**
        33 |  * The Modal component is a simple way to present content above an enclosing view.
```

I'm not even importing that `Modal` component on my test. Not even in my app actually.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@1.11.1
* `npm ls react-native`: react-native@0.52.3
* `npm ls expo`: expo@25.0.0
* `node -v`: v8.2.1
* `npm -v`: 5.3.0
* `yarn --version`: 1.3.2
* `watchman version`: "version": "4.7.0"

1. Operating system: MacOS

## Reproducible Demo

This is part of my `package.json`. I don't recall touching any jest configuration there.

```
"devDependencies": {
    "babel-eslint": "^8.0.0",
    "eslint": "^4.7.1",
    "eslint-config-react": "^1.1.7",
    "eslint-plugin-react": "^7.6.1",
    "jest-expo": "^21.0.2",
    "react-native-scripts": "^1.11.1",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
```

**Comment by brentvatne** [comment]
if you create a brand new project do the tests run? did you change the babelrc?

**Comment by dgrcode** [comment]
Creating a brand new project it runs the tests. I didn't touch any babelrc file. In fact, I don't have one.

I copied the same babelrc file from the brand new project to my project and now tests work.

I don't know how or when the file went missing, but this definitely solved my problem.

Thanks! 🎉
