### ISSUE TITLE
Expo says invalid SDK version

### ISSUE THREAD

**Issue by holywyvern** [react-community/create-react-native-app#579]
## Description

When you just make a fresh new app, Expo throws an error saying than the SDK version 18.0.0 is invalid.

## Expected Behavior

The app should start running on the device with the Expo client.

## Observed Behavior

The APP is compiled and it's sended to the device  but it won't load. 

```
Uncaught Error: 18.0.0 s not a valid SDK version.
Options are 25.0.0, 24.0.0, 23.0.0, 22.0.0, 21.0.0, 20.0.0, 19.0.0, UNVERSIONED.
```

## Environment

* `npm ls react-native-scripts`:  -- react-native-scripts@1.11.1
* `npm ls react-native`: -- react-native@0.52.0
* `npm ls expo`: -- expo@25.0.0
* `node -v`: v9.7.1
* `npm -v`: 5.6.0
* `yarn --version`: 1.5.1
* `watchman version`: ERROR: (it's not a command)

Also specify:

1. Operating system: Windows 10 PRO
2. Phone& version: Motorola G4 Play  - Android: 6.0.1 
3. Expo  Apk version: 2.3.0

## Reproducible Demo

```
create-react-native-app my-apk
cd my-apk
yarn start
# Then press a to run it on my phone connected to the USB, using the QR code also fails
```

The expo client starts to load the app, but then it shows that error.

**Comment by brentvatne** [comment]
what is in your app.json?

**Comment by holywyvern** [comment]
```json
{
  "expo": {
    "sdkVersion": "27.0.0"
  }
}
```

**Comment by joshbedo** [comment]
I get this error intermittently as well, i had an app running fine the other day and now i'm trying to run it again and it's showing that error. I'm at sdkVersion: 25.0.0

**Comment by theTechie** [comment]
Using `Install iOS Simulator App`  from Expo XDE menu fixed it !

**Comment by dagher778** [comment]
how can i opene Expo XDE ?? @joshbedo

**Comment by Osama92** [comment]
Update to the latest version of Expo
