### ISSUE TITLE
Socket.io not working in CRN, so frustrating.

### ISSUE THREAD

**Issue by rockmandash** [react-community/create-react-native-app#581]
![image](https://user-images.githubusercontent.com/7580792/37072320-baa2bfea-21fb-11e8-83b4-471e9d465f00.png)
```
import React from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';
import io from 'socket.io-client';

const socket = io('http://localhost:5000');
socket.on('greeting-from-server', function(message) {
  console.log(message.greeting);
  socket.emit('greeting-from-client', {
    greeting: 'Hello Server'
  });
});

```

I use expo app on android, when I open browser, my server receive data, however, it didn't work on create-react-app, so frustrating.
The console has completely no error.
Please help~~~

**Comment by brentvatne** [comment]
you can't access localhost from your phone

**Comment by rockmandash** [comment]
@brentvatne Cool !!
Didn't know that.
