### ISSUE TITLE
App is stuck in loading loop

### ISSUE THREAD

**Issue by stefanvonderkrone** [react-community/create-react-native-app#584]
## Description

The app is stuck in a loading loop when starting development on the iOS simulator.

## Expected Behavior

The App should only reload, when a change occured.

## Observed Behavior

I start the development with `yarn start` und app constantly reloads although there were no changes to the code.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@1.11.1 
* `npm ls react-native`: react-native@0.52.0
* `npm ls expo`: expo@25.0.0 
* `node -v`: v8.9.1
* `npm -v`: 5.5.1
* `yarn --version`: 1.3.2
* `watchman version`: 4.9.0

Also specify:

1. Operating system: Mac OS X 10.12.6
2. Phone/emulator/simulator & version: Simulator, iOS 11.2, iPad (12.9 inch)

## Reproducible Demo

```
$ create-react-native-app rn-test --package-manager=yarn
$ cd rn-test
$ yarn start
```

wait until the simulator is launched, see how the App constantly reloads

**Comment by jtwhite14** [comment]
Same is happening to me. Any news here?

**Comment by Alastair-smith2** [comment]
Seen a similar thing on occasion, found hitting CMD+R fixes the loop when it occurs but doesn't resolve the underlying issue.
