### ISSUE TITLE
npm start does not work

### ISSUE THREAD

**Issue by codingWithA** [react-community/create-react-native-app#586]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request
I have been trying desperately for 2 days to install React Native to no avail...
## Expected Behavior

What action did you perform, and what did you expect to happen?
I ran npm start, expecting the QR Code to be printed
## Observed Behavior

What actually happened when you performed the above actions?
Unfortunately, there is an error message,
If there's an error message, please paste the *full terminal output and error message* in this code block:

```
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alwis/.npm/_logs/2018-03-10T02_02_35_334Z-debug.log```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
PleaseWork@0.1.0 /Users/alwis/Desktop/PleaseWork
└── react-native-scripts@1.11.1 

* `npm ls react-native`:
PleaseWork@0.1.0 /Users/alwis/Desktop/PleaseWork
└── (empty)


* `npm ls expo`:
PleaseWork@0.1.0 /Users/alwis/Desktop/PleaseWork
└── (empty)


* `node -v`:
v8.10.0


* `npm -v`:
5.6.0


* `yarn --version`:
I don't have yarn installed


* `watchman version`:
{
    "version": "4.9.0"
}


Also specify:

1. Operating system: macOS High Sierra v10.13.1
2. Phone/emulator/simulator & version: Not using any.

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.
It's just that whenever I npm start, it prints the error, tried reinstalling NPM, Node, downgrading all the way to npm v4, but nothing works

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by AtomStar** [comment]
npm 5 is not supported. Downgrade to npm 4.6.1, ` npm i -g npm@4.6.1`,  or install yarn.  Then delete project folder and recreate it.
