### ISSUE TITLE
npm 5 not support bug!

### ISSUE THREAD

**Issue by xgqfrms-gildata** [react-community/create-react-native-app#590]
# npm 5 not support bug

![image](https://user-images.githubusercontent.com/29531779/37326282-5334846c-26cc-11e8-80d8-c0a3d61ad672.png)

**Comment by xgqfrms-gildata** [comment]
https://github.com/npm/npm/issues/16991

**Comment by roryj-degould** [comment]
@xgqfrms-gildata that issue on the npm repo is now locked and closed. I am running npm 5.5.1 which I've yet to have any issues with. I don't want to have to mess about with rolling back npm to 4.6.1 and if I use nvm to switch node versions, then I have to go all the way back to 6.13.1 to get away from npm@5 - and that puts me back to npm@3! I think it's worth removing this blocker at this point, or at least changing the message as the known issues are no longer being tracked there.

**Comment by brentvatne** [comment]
you don't have to change node versions to use a different npm version, you can just do `npm i -g npm@version-here`

**Comment by brentvatne** [comment]
updated supported npm version info in next release, will be out soon

**Comment by ahetawal-p** [comment]
May I know what will be the `updated npm version` which will be supported going forward please.
@brentvatne
