### ISSUE TITLE
Error running adb: No Android device found - Cannot connect to Visual Studio Emulator for Android

### ISSUE THREAD

**Issue by AtomStar** [react-community/create-react-native-app#591]
## Description

I am trying to use the Visual Studio Emulator for Andoid since the Android Studio AVDs need Hyper-V disabled. 
In the project folder I run: `npm run android` and the get the message: `Error running adb: No Android device found`
Also get the same when I do `npm start` and then pressing `a` to open in Android.  I do see a device listed if I run the `adb devices` command in Android/Sdk/platform-tools

## Expected Behavior

Enter the `npm run android` command from the project folder and have it connect to and run in the Visual Studio Emulator for Android.

## Observed Behavior

I receive the following error message:

```
Error running adb: No Android device found
```
![image](https://user-images.githubusercontent.com/4679371/37396338-4938b04a-2781-11e8-9030-fc5a95077c62.png)

## Environment

* `npm ls react-native-scripts`: react-native-scripts@1.11.1
* `npm ls react-native`: react-native@0.52.0
* `npm ls expo`: expo@25.0.0
* `node -v`: v8.9.4
* `npm -v`: 4.6.1
* `yarn --version`: not installed
* `watchman version`: not installed

Also specify:

1. Operating system: `Windows 10`
2. Phone/emulator/simulator & version: `Visual Studio Emulator for Android - 5" Marshmellow (6.0.0) XHDPI Phone, API Level 23 (Marshmellow 6.0.0)`

**Comment by ide** [comment]
Thanks for trying adb from the CLI and the succinct write-up. I don't think we've looked into running the Visual Studio Emulator for Android and the issue could be with a mismatch of adb versions (react-native-scripts uses its own copy if it can't find the system copy for whatever reason.)

**Comment by AtomStar** [comment]
@ide Thanks for your comment! Do you know where react-native-scripts looks to find the adb? I have set the user variable ANDROID_HOME to the Android Sdk location and changed the registry setting for the Visual Studio Emulator for Android to the same location. Does react-native-scripts use the ANDROID_HOME location? 
I have now disabled Hyper-V on my machine and tried using an Android Studio AVD.  Unfortunately, it only pops up with an Expo app settings screen which is not the default app screen that should show. See my screenshot for details:

![image](https://user-images.githubusercontent.com/4679371/37448191-f321c7d4-282d-11e8-9343-91b2e3c5a511.png)

I expected to see this:
![image](https://user-images.githubusercontent.com/4679371/37448235-29e7d33a-282e-11e8-8873-e8d75dc41e55.png)

**Comment by ide** [comment]
adb scripting and all that is going to be in this package: https://github.com/expo/xdl

**Comment by pinchez254** [comment]
Try android 7 emulator. I think Expo client is having issues with latter versions. I went over to play store in the emulator and viewed expo to see whether i could update it, and I found a message that " this version us not supported in your device". Try different emulators..for me only android 7 emulator instead and That worked for me in Linux. I think in mac its pretty stable.

**Comment by JohnTheo13** [comment]
It's looking for an Android device since none is connected, it gives this message, if you first open your virtual device and then run your script, you should be fine, it worked for me at least..

**Comment by androidDeveloperOne** [comment]
fgg
