### ISSUE TITLE
EXPO not able to read app

### ISSUE THREAD

**Issue by vondracekt** [react-community/create-react-native-app#592]
## Description

I have followed quick start https://facebook.github.io/react-native/docs/getting-started.html. I tried to use EXPO as it is written.

## Expected Behavior

npm install -g create-react-native-app
create-react-native-app AwesomeProject
cd AwesomeProject
npm start

I tried to open app by EXPO in android by reading QR code

## Observed Behavior

```
EXPO says
Uncaught Error: Time out, no manifest in cache
```
I tried to open the same on http from android and it works, so I report bug as it is written in troubleshooting

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:react-native-scripts@1.11.1
* `npm ls react-native`:react-native@0.52.0
* `npm ls expo`:expo@25.0.0
* `node -v`:v8.4.0
* `npm -v`:5.3.0
* `yarn --version`:
* `watchman version`: I dont have watchman

Also specify:

1. Operating system: Andriod 5.1.1
2. Phone/emulator/simulator & version: Samsung Galaxy J3 (2016)

**Comment by brentvatne** [comment]
you phone needs to be on the same wifi network as your computer and it can't be behind a nat

**Comment by vondracekt** [comment]
i dont undertand your explanation.it is in the same network.why do you think
it is behind nat?

---------- Původní zpráva ----------
Od: Brent Vatne 
Datum: 30. 3. 2018 v 00:09:00
Předmět: Re: [react-community/create-react-native-app] EXPO not able to read
app (#592)


you phone needs to be on the same wifi network as your computer and it can't
be behind a nat

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
(https://github.com/react-community/create-react-native-app/issues/592#issuecomment-377387602)
, or mute the thread
