### ISSUE TITLE
eject built in xcode resulted in "SyntaxError: Use of const in strict mode."

### ISSUE THREAD

**Issue by jc1dev** [react-community/create-react-native-app#594]
## Description

Created app using crna cli, yarn eject using expo sdk, open xcode using ios project workspace, in xcode clean run build, resulted in JavaScript "SyntaxError: Use of const in strict mode." with chalk module

## Expected Behavior

Expected to build with xcode successfully for yarn eject code

What action did you perform, and what did you expect to happen?

creact-react-native app
yarn eject, follow eject instruction and select the expo sdk one
go into ios folder, pod install
open ios project with xcode
in xcode, run clean and build

## Observed Behavior

What actually happened when you performed the above actions?

SyntaxError: Use of const in strict mode.

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
.nvm/versions/node/v7.10.1//lib/node_modules/exp/node_modules/chalk/index.js:2
const escapeStringRegexp = require('escape-string-regexp');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@1.11.1
* `npm ls react-native`: react-native@0.52.0
* `npm ls expo`: expo@25.0.0
* `node -v`: v7.10.1
* `npm -v`: 4.2.0
* `yarn --version`: 1.5.1
* `watchman version`: 4.7.0

Also specify:

1. Operating system: osx sierra 10.12.6
2. Phone/emulator/simulator & version: xcode 9.2

## Reproducible Demo

1. creact-react-native app
2. yarn eject, follow eject instruction and select the expo sdk one
3. go into ios folder, pod install
4. open ios project with xcode
5. in xcode, run clean and build

**Comment by jc1dev** [comment]
btw, I figured out an alternative solution, don't use xcode IDE but build it through command line with xcodebuild then it will work

**Comment by brentvatne** [comment]
you can update node version as well to resolve this problem

**Comment by jc1dev** [comment]
@brentvatne I disagree, this is not a node version issue, I've also tested this on node v8.11.1 and v9.10.x, same problem

Did you just close this issue without even attempt to reproduce this?

**Comment by TylerLH** [comment]
Seeing this issue as well, even using Node 10.6.0. Is there a reason this was closed without any reproduction attempts?
