### ISSUE TITLE
Expo is not loading my app

### ISSUE THREAD

**Issue by viganzeqiri** [react-community/create-react-native-app#595]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

Expo is not loading my react app in Iphone

1. Both the pc and the phone use the same network
2. I'm getting a message saying: "It looks like you may be using a LAN url. Make sure ur device is on the same network as the server or try using a tunnel.
## Expected Behavior
I'm excepting to use my phone as a emulator

What action did you perform, and what did you expect to happen?

## Observed Behavior
I scanned the qr code in my console

What actually happened when you performed the above actions?
i get an error with the msg above

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
There was a problem loading the experience. It looks like you may be using a LAN url. Make sure your device is on the same network as the server or try using a tunnel.
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:1.11.1
* `npm ls react-native`:0.52.0
* `npm ls expo`: 25.0.0
* `node -v`: 9.8.0
* `npm -v`: 4.6.1
* `yarn --version`:
* `watchman version`:

Also specify:

1. Operating system: Windows 10
2. Phone/emulator/simulator & version: Expo app on ios

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by EvanBacon** [comment]
does your URL look something like this: 
`Your URL is: exp://192.168.1.73:19000`
as opposed to this:
`exp://9h-hcy.bacon.tickle_me_elmo.exp.direct:80`
if so then try running:
`exp start --tunnel` and check to make sure you have a pretty solid wifi connection 💙🌝

**Comment by viganzeqiri** [comment]
it worked perfectly. Thanks a lot. Could you give me some details why it wouldnt work in normal conditions?

**Comment by brentvatne** [comment]
because you need to be on the same wifi network and the network cannot be behind a nat. if it is then you can't access other computers on the network

**Comment by William-Unosquare** [comment]
I had this issue when running Docker. 

The URL given in the command line may not be the correct one. For me, it was using docker's IP instead of my actual networks local ip. I've worked around it for now by entering my local address followed by port 19000 in safari. EG: `exp://192.168.1.151:19000`

**Comment by raminghaderi** [comment]
What you need to do is:
Go to cmd and type "ipconfig" and see which network is using the ip shown in your expo app. if it's not your router IP address then what you need to do is to go and disable the network which expo is using:
Control Panel -> Network and Internet -> Network Connections
and here disable the network that expo is using. (it should be a LAN network connection)
try to run "npm start" again, it should be working now.
If my solution is not clear feel free to ask me.

**Comment by Gift-Stack** [comment]
I am getting a message "The internet connection appears to be offline" whereas it is online. What could be the issue? This has been persisting for days

**Comment by Collins1738** [comment]
So I had this problem on my iPhone and I was getting worked up about it and then I used a friend's iPhone and everything worked. Turns out it had something to do with the Expo-app's permissions. When you first download Expo Go, it asks for some permission roughly about allowing your device to connect with other devices in the network. Looks like I overlooked the permission the first time and clicked "No". Clicking "Allow" instead fixed it. I deleted and redownloaded Expo to see the permission again because I didn't want to search through settings to find it. Hope this helps.

**Comment by mertdeveci5** [comment]
Anyone found any solution for this? Above solution from thinkcapo is unrelated as I think most of us are connected to the same Wifi we are trying to launch the expo app in

**Comment by phillipjfry93** [comment]
My issue was a VPN that was placed on my network through one of my other apps I installed. I'm not sure why, but it seems to be affecting the connection with expo.

**Comment by maniac-tech** [comment]
I am still experiencing this.

My devices are connected to the same wifi-network

**Comment by riveraluis** [comment]
im also still experiencing this, any luck?

**Comment by Saadhya** [comment]
I'm also facing this

**Comment by anand20-eng** [comment]
when is scan qr code its not seen application run........many time i do uninstall and install app.....
it not work.........could you please sovle problems

**Comment by Saadhya** [comment]
use this command on cmd :-
npx expo start --tunnel

**Comment by iqlong** [comment]
> 

works for me

**Comment by iqlong** [comment]
放到

**Comment by ofelipesant** [comment]
hey guys

i was having the same problem, and the CMD commands didn't work. I just uninstalled Expo and installed it again and it worked again (iphone)

**Comment by BooprApp** [comment]
Hi, I was experiencing this issues but using the tunnel appears to have worked... for now

Thanks! :)

**Comment by bennycode** [comment]
I am running Expo on **WSL: Ubuntu** and **Windows 11**. It generated a URL like `exp://172.20.29.200:8081` (which is a private IP address). Executing `expo start --tunnel` helped. Thanks a lot! 👍

**Comment by sudomuli** [comment]
I had the same issue using simulator.
You can find the solution from here: https://docs.expo.dev/more/expo-cli/
>Server URL
By default, the project is served over a LAN connection. You can change this behavior to localhost-only by using the flag npx `expo start --localhost`.

So start expo using: `expo start --localhost`
