### ISSUE TITLE
`react-native-scripts/src/bin/crna-entry.js` should not assume relative location of `App.js`

### ISSUE THREAD

**Issue by vjpr** [react-community/create-react-native-app#596]
https://github.com/react-community/create-react-native-app/blob/5067fb85c6d58f1609394c4ca9e50d133a4c36f1/react-native-scripts/src/bin/crna-entry.js#L2

When using `pnpm` package manager, the packages are stored in a different folder structure (when resolved using realpath).

```
/node_modules/.registry.npmjs.org/react-native-scripts/1.11.1/node_modules/react-native-scripts/build/bin/crna-entry.js

vs.

/node_modules/react-native-scripts/build/bin/crna-entry.js
```

This error is caused:

```
Unable to resolve 

../../../../App" from 

".//node_modules/.registry.npmjs.org/react-native-scripts/1.11.1/node_modules/react-native-scripts/build/bin/crna-entry.js`: 

The module `../../../../App` could not be found"
```

A more robust approach should be used to locate the project root. E.g. `process.cwd()` or `require.main.filename`.

**Comment by vjpr** [comment]
Workaround: https://github.com/react-community/create-react-native-app/issues/152#issuecomment-366237641

**Comment by EvanBacon** [comment]
@vjpr does the workaround resolve/close this issue?

**Comment by vjpr** [comment]
@EvanBacon Nope. The default entry point doesn't work out-of-the-box for pnpm users.

**Comment by brentvatne** [comment]
you are welcome to change the `"main"` in package.json to whatever you like.

**Comment by vjpr** [comment]
@brentvatne But this means that out of the box crna doesn't work for pnpm. It's a bad user experience.

**Comment by brentvatne** [comment]
we don't explicitly support pnpm @vjpr - if you'd like to fix it you're welcome to submit a pr
