### ISSUE TITLE
Expo Time out, no manifest in cache

### ISSUE THREAD

**Issue by thebakerdev** [react-community/create-react-native-app#598]
## Description

Created a project using the create-react-native-app then scanned the QR code using an android phone but I get a timeout error on expo app. **There was an unhandled error: Timed out, no manifest in cache**

## Expected Behavior

Create a project using create-react-native-app and run npm start
Scanned the QR code
It's supposedly built the project on my phone

## Observed Behavior

I get this error on the expo at without a stack trace: **There was an unhandled error: Timed out, no manifest in cache**

## Environment

Please run these commands in the project folder and fill in their results:

* react-native-scripts@1.11.1
* react-native@0.52.0
* expo@25.0.0
* 8.10.0
* 5.6.0
* 1.5.1

Windows 10
Samsung Phone

**Comment by ianchanning** [comment]
I had the same issue using `yarn` on Windows 10. Following the trouble shooting my http:// version timed out too. I then switched to using the mobile hotspot as suggested and this gives the same errors as described here

**Comment by thebakerdev** [comment]
I think this has something to do with the network and virtual host. I have a virtualbox host besides my wifi connection. So what's currently happing is when I use npm start it uses the virtualbox host instead of the wifi connection. So basically they are using different network thus expo can't connect to the app. 

One solution that I did was to disable the virtual host network the do npm or yarn start. Another is change some network settings as stated in https://github.com/react-community/create-react-native-app/issues/60#issuecomment-317104728. 

This solved the problem in my case.

**Comment by ianchanning** [comment]
@thebakerdev fantastic, thanks! That solves the problem for me.

Although actually I don't have Virtual Box installed but I had a couple of other old VPN network connections. I deleted both of those and followed the steps in the [#60 comment](https://github.com/react-community/create-react-native-app/issues/60#issuecomment-317104728). I probably didn't need to do both.

One thing I noticed that changed was the IP switched from something like 10.8.0.14 (didn't work) to 192.168.1.7 (now works).

**Comment by anp** [comment]
Hi! Sorry you're having issues with this. Unfortunately this is a common problem on Windows, and the main way we can work around it without having a lot of fragile logic for retrying all network interfaces is to provide [these troubleshooting instructions in the generated project's README](https://github.com/react-community/create-react-native-app/tree/master/react-native-scripts/template#networking). Please post back if that's still not working for you though!

**Comment by pranavb** [comment]
I had this same issue, while running a few Docker instances. The trick is to ensure that the IP address that the packager sees is the one that's associated with your WiFi adapter.

## Quick Solution 

@jimmylee had an excellent [solution](https://github.com/expo/expo/issues/438#issuecomment-330706307) that I've included below.

* Run `ipconfig`
* Your WiFi adapter (called something like 'Wireless LAN adapter Wi-Fi') will probably not be first in the list (that's the whole problem, because Expo only looks at the first entry in this list).
* Set the `REACT_NATIVE_PACKAGER_HOSTNAME` environment variable to the IPv4 address of your WiFi adapter
* Say the IPv4 address associated with your Wireless LAN adapter Wi-Fi is X.X.X.X
  * Set an environment variable for a relatively permanent solution. There's a quick run down of how to do this at [ComputerHope](https://www.computerhope.com/issues/ch000549.htm).  
  * For a solution that will work for one session of the Command Prompt use:
`SET REACT_NATIVE_PACKAGER_HOSTNAME=X.X.X.X`
* Rerun the packager
  * `yarn start`

## Best Solution

You could also change the 'Automatic metric' value for all your network adapters so that the WiFi adapter has the lowest value (highest priority). This is probably the best solution. 

Full credit to @Himujjal for this. Check out his detailed answer [here](https://github.com/react-community/create-react-native-app/issues/60#issuecomment-317104728).

**Comment by jhalborg** [comment]
Also a problem on macOS, and an issue is open on the [Expo client repo](https://github.com/expo/expo/issues/1508) - it seems that 2.3.1 and 2.3.2 are affected.

**Comment by gitteraz** [comment]
I have tried all proposed Solutions, Upgrade, Downgrade, set Environment Variables, Disable Virtual box and so on. 

Only thing that worked for me was changing my computer and mobile IP addresses.

**Comment by lsiden** [comment]
I started from a fresh create-react-native-app on Ubuntu Linux 4.4.0.  When I run ifconfig, my Wireless network indeed shows up as the last interface.  In my browser, I can open http://192.168.1.9 (my wireless IP) and I see a manifest. 

So I ran "REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.9 yarn start" but I only get a timeout.

Here's the actual manifest:

```
{
  "sdkVersion": "25.0.0",
  "name": "crna-baseline",
  "slug": "crna-baseline",
  "version": "0.1.0",
  "xde": true,
  "developer": {
    "tool": "crna",
    "projectRoot": "/home/lsiden/proj/crna-baseline"
  },
  "packagerOpts": {
    "hostType": "tunnel",
    "lanType": "ip",
    "dev": true,
    "minify": false,
    "urlRandomness": null
  },
  "env": {
    "REACT_NATIVE_PACKAGER_HOSTNAME": "192.168.1.9"
  },
  "bundleUrl": "http://192.168.1.9:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=/home/lsiden/proj/crna-baseline/node_modules/expo/tools/hashAssetFiles",
  "debuggerHost": "192.168.1.9:19001",
  "mainModuleName": "./node_modules/react-native-scripts/build/bin/crna-entry",
  "logUrl": "http://192.168.1.9:19000/logs",
  "id": "@anonymous/crna-baseline-676eb673-21e6-404f-9599-dc8f465f5846"
}
```

I do notice that hostType is set to "tunnel".  Wny not "lan"?  Isn't tunnel for working with an emulator?

**Comment by SourceCipher** [comment]
The issue is still here

**Comment by bLuka** [comment]
I spent several hours trying to fix it, and I have still not a single clue.

I run React-Native with Expo on Gentoo/Linux.

The bug appears with no apparent reason, sometimes on a fresh project, sometimes not.

I tried the `REACT_NATIVE_PACKAGER_HOSTNAME` fix, with no result.

**Comment by baba43** [comment]
I get this error even when using `exp publish`. How can that be?

**Comment by bLuka** [comment]
I tried a lot of things, I don't know which one fixed this issue.

I ran into multiple random issues (sometimes this one: https://github.com/facebook/react-native/issues/15025), and tried downgrading `npm` as told in the discussion (`npm i -g npm@4.6.1`).

I will follow any details if I run into this issue again.

**Comment by richnavarro** [comment]
I have been getting this error recently. A quick workaround going to the project directory and running "exp start" and using expo via the command line. Seems to work fine without any issues this way for me.

**Comment by fiowak** [comment]
Run cmd as administrator and set `netsh int ip reset` - after that just restart
