### ISSUE TITLE
Packager is not running at http://192.168.122.99:19001

### ISSUE THREAD

**Issue by lucaszanella** [react-community/create-react-native-app#602]
I'm running an emulator and a VM in parallel to each other. When I do npm start on the VM, I get `exp://192.168.122.99:80` as the path. I then try this on the android emulator and it doesn't work. Then it automatically changes itself to `exp://192.168.122.99:19000` and when I try again to connect with expo it works, but after some time automatic code update stops working and even restarting the emulator and the npm service don't make it work. I have to restart the entire computer. The error says:

`Packager is not running at http://192.168.122.99:19001/`

I've found some solutions here in the issues but they won't work for me. I can always access `192.168.122.99:19000` even when these errors are showing.

If I can always access `http://192.168.122.99:19000` then I guess there's no problem with my IP bindings, right? Or is it possible that npm always binds `19000` to `192.168.122.99` but `19001` to another thing?

That would be very strange and I'd even call it a bug, because sometimes everything works and sometimes not.

**Comment by lucaszanella** [comment]
update: when I press `r` to restart, and run netstat, I see:

**Comment by lucaszanella** [comment]
Now it won't get out of port 80. I don't know what to do to make it go to 19000. I try to restart many times but sometimes it randomly gives me 19000 again. However, this isn't working even in this case anymore.

**Comment by brentvatne** [comment]
you can use `REACT_NATIVE_PACKAGER_HOSTNAME='my-custom-ip-address-or-hostname' npm start` if you know what ip the packager can be reached from and we can't guess it correctly. the way we guess is pretty basic and we don't explicitly support running it in vms. open to a pr that thoughtfully handles this situation

**Comment by lxm7** [comment]
@brentvatne - this works and was the last step after installing expo, crna and standalone react-native-debugger. Over wifi. Same answer here - https://github.com/react-community/create-react-native-app/issues/81
