### ISSUE TITLE
Expo app - can't load project with message : This is taking much longer than it should...

### ISSUE THREAD

**Issue by RomanSurface** [react-community/create-react-native-app#611]
I have 

- installed Node 8.11.0 on Windows 8
- installed `npm install -g create-react-native-app`
- created successfully a test project 
```
create-react-native-app AwesomeProject
cd AwesomeProject
npm start

```
- installed expo client app on my iphone 5s, iOS 9.2
- sent the app url using email to my phone

I 
- connect my iphone on the same network of my windows machine (wifi)
- click on the link contained in the email message
- accept to open the link in the Expo app
- the Expo app tries to launch the procjet but gets stuck givin this message 

> This is taking much longer than it should. You might want to check your interenet connection

- Expo app crashes 
It seems  like the project is too heavy to be loeaded in the app, due to the list of node_modules installed.

How can i solve this problem?
I am stuck in development.

![img_8410](https://user-images.githubusercontent.com/6842434/38114997-bee34d98-33aa-11e8-86d9-f73a897d694d.PNG)

**Comment by RomanSurface** [comment]
i am on the same wifi network, and it is not a public one. it is my private house wifi

**Comment by brentvatne** [comment]
copy the url to your phone and open it in safari,

**Comment by brentvatne** [comment]
thanks for the followup @RomanSurface! i'd also recommend updating the version of react-native-scripts in your project -- `npm i react-native-scripts@1.13.1 --save` -- this fixes a small bug (that may or may not impact you) with loading projects that have spaces in the project path

**Comment by soundofsilence75** [comment]
Experienced the same exact issue as @RomanSurface on both Linux Mint and Windows 10. Turing off my firewall fixed it for me.

**Comment by miraydamartinez** [comment]
Hi! I seem to be having this issue at the moment (new to react) but turning off my firewall still hasn't fixed anything. It still says "taking much longer than it should..." are there any other steps you all took?

**Comment by Azambadar** [comment]
I m having the same problem, turned off firewall and done all troubleshotting but still project is not opening in expo app

**Comment by manu-dikzit** [comment]
@Azambadar I faced the same problem. Turns out I was creating a "LAN" connection on the desktop expo server. Switching to "Tunnel" solved it for me

**Comment by Azambadar** [comment]
Hi @manu-dikzit , my wifi connection was not supporting expo and expo worked fine with mobile phone hotspot.

**Comment by AmanGupta-tech** [comment]
same problem can't able to open

**Comment by LHowlett97** [comment]
> @Azambadar I faced the same problem. Turns out I was creating a "LAN" connection on the desktop expo server. Switching to "Tunnel" solved it for me

How do you do this though?

**Comment by mollyAC** [comment]
I just started using expo-cli so here is what I found out.

Windows: 
1. Use the same wi-fi connection for both laptop and phone
2. Enable the Node.js JavaScript Runtime in "Control Panel\System and Security\Windows Defender Firewall\Allowed apps"
![image](https://user-images.githubusercontent.com/15723574/148664476-93707e22-9b56-4d86-ba6f-02e8742a0b9d.png)
By default, Node.js JavaScript Runtime is enabled in private network connection. So you will need to enable it in the public network connection.

Hope it helps!

**Comment by SaraLozoZaho** [comment]
Perfect! Thank you

**Comment by chris1797** [comment]
@mollyAC Thank you!!!!!

**Comment by cukuralii** [comment]
@mollyAC thank you brother !!!

**Comment by shadowwinter** [comment]
> 

Thank you! This was exactly what I needed :)

**Comment by AjithChitturi** [comment]
Thank You So much :)

**Comment by NourBenz** [comment]
I tried this but it said that windows defender cant change the prameters for node js javascript runtime 
By default its its public not private

**Comment by joevabean** [comment]
@mollyAC You just saved me 😭 thank you so much

**Comment by Dnvas** [comment]
@mollyAC saved me even in 2026!!!
