### ISSUE TITLE
yarn run ios error

### ISSUE THREAD

**Issue by yzStrive** [react-community/create-react-native-app#612]
# READ THIS FIRST, PLEASE!

The App Store version of the Expo iOS client recently had to remove the QR code scanner from the app. If you intend to load your app on a physical iOS device, please install the latest version of react-native-scripts to your app (`yarn add react-native-scripts@latest` or `npm install react-native-scripts@latest`). It adds the "s" key to the interactive prompt, which asks you to enter an email address or phone number and then sends the URL to your device.

Read more at https://blog.expo.io/upcoming-limitations-to-ios-expo-client-8076d01aee1a. We apologize for any inconvenience this may cause you!

# Required format for issues

Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

yarn run ios:
```
yarn run v1.5.1
$ react-native-scripts ios
12:06:22: Starting packager...
12:06:36: Starting simulator...
12:07:29: Failed to start simulator:

Error: read ETIMEDOUT

Exiting...
✨  Done in 66.93s
```

## Expected Behavior

What action did you perform, and what did you expect to happen?

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@1.4.0
* `npm ls react-native`:react-native@0.52.0
* `npm ls expo`:expo@25.0.0
* `node -v`:v9.8.0
* `npm -v`:
* `yarn --version`:1.5.1
* `watchman version`:4.9.0

Also specify:

1. Operating system: macOS 10.12.6
2. Phone/emulator/simulator & version: iphoneX-11.2

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by miaojiuchen** [comment]
same problem

**Comment by bigxigua** [comment]
same problem

**Comment by zl810881283** [comment]
same problem

**Comment by yinxin630** [comment]
same problem

**Comment by ykx456654** [comment]
same problem

**Comment by shinux** [comment]
same problem

**Comment by skcks** [comment]
same problem

**Comment by codeandproduce** [comment]
same problem

**Comment by abdyfranco** [comment]
same problem

**Comment by ArvoGuo** [comment]
### **I close my vpn , and restart all** , **it works fine now!**
Maybe the network cause this problem

**Comment by abdyfranco** [comment]
@ArvoGuo You just broke a magical chain.
