### ISSUE TITLE
npm installation fails indicating `nmp.debug.log` is missing

### ISSUE THREAD

**Issue by kalanka29** [react-community/create-react-native-app#614]
Here when I run the first command( after dowloading and getting into that directory)it outputs the foll
owing result:

`$ npm install -g create-react-native-app
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "create-react-native-app"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! path C:\Users\donka\AppData\Roaming\npm\node_modules\create-react-native-app\build\index.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\donka\AppData\Roaming\npm\node_modules\create-react-native-app\build\index.js'
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\donka\AppData\Roaming\npm\node_modules\create-react-native-app\build\index.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     E:\My work\react-native\With Expo\create-react-native-app-master\npm-debug.log
`

what should be done inorder to fix this..

**Comment by szholdiyarov** [comment]
can you paste the info from the npm-debug.log file please?
Also, you say " after dowloading and getting into that directory", could you clarify after downloading what?

**Comment by abSarpong** [comment]
[npm-debug.log](https://github.com/react-community/create-react-native-app/files/2041237/npm-debug.log)
