### ISSUE TITLE
fresh install crashes expo if using debug JS after a bug

### ISSUE THREAD

**Issue by theonlydaleking** [react-community/create-react-native-app#618]
## Description

Fresh install of create-react-native-app will crash expo if debug remote js is enabled after a bug is hit and then fixed. 

## Expected Behavior

Steps to Reproduce: 

- install create react native app
- `create-react-native-app test`
- `cd test`
- `yarn start` 
- Send the code to iPhone to open expo app and view the standard app. 
- shake iPhone and enable Debug Remote JS. 
- open your text editor of choice. 
- Introduce a bug (eg. just remove the last closing Text tag) 
- Bundle fails to build, 
- fix the error, 
- Bundle reloads fine and the app is displayed fine. 
- Change anything else (even just a simple text change) 

The app should reload with the last change but it fails to rebuild

## Observed Behavior

- Rebuilding bundle gets stuck at 100% 
- If you shake and refresh (Or close the app and reopen), the app will crash back to the home screen after getting to 100% rebuilding js package. 
- The app continues to crash every time you open it

The only way to get back to it working is to disable debug remote js mode. 

No error message displayed in console or terminal 

## Environment

* `npm ls react-native-scripts`: 1.13.1
* `npm ls react-native`: 0.54.0
* `npm ls expo`: 26
* `node -v`: 9.9
* `npm -v`: 5.8 
* `yarn --version`: 1.5.1
* `watchman version`: 4.9.0

Also specify:

1. Operating system: Tested on both Ubuntu 17.10 and OSX 10.13.3
2. Phone/emulator/simulator & version: iOS 11.2.6

**Comment by llamorinjason** [comment]
in your package.json update  "react-native": "0.54.0" to  "react-native": "0.54.4",
Fixes the issues related here [#18209](https://github.com/facebook/react-native/issues/18209)
You could also try     "react": "16.3.0.alpha.1" to    "react": "16.3.0" for a stable react. Been working with it no issues so far

**Comment by theonlydaleking** [comment]
Can Confirm Updating to react-native 0.54.4 fixes the issue. Thanks @llamorinjason

**Comment by joshsiegl1** [comment]
@theonlydaleking I'm seeing the exact same issue

**Comment by ispadoto** [comment]
I'm seeing that issue too
"dependencies": {
    "native-base": "^2.4.4",
    "react": "16.3.1",
    "react-native": "~0.55.2",
    "react-native-navigation": "^1.1.458",
    "react-native-vector-icons": "^4.6.0",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "remote-redux-devtools": "^0.5.12"
  }
