### ISSUE TITLE
Error running adb: read ECONNRESET

### ISSUE THREAD

**Issue by zzq392342084** [react-community/create-react-native-app#619]
when I execute  "npm run andriod" in windows10 power shell,it outputs:

16:15:39: Starting packager...
16:16:15: Starting Android...
16:16:47: Packager started!

....

Logs from serving your app will appear here. Press Ctrl+C at any time to stop.

Error running adb: read ECONNRESET

![default](https://user-images.githubusercontent.com/12469232/38304951-aefda260-383d-11e8-944d-6cc2cf33056f.png)
![default](https://user-images.githubusercontent.com/12469232/38304979-cd15b7e2-383d-11e8-9628-27db707bdacc.png)

**Comment by Mrzwb** [comment]
i have the same problem

**Comment by hiquanta** [comment]
i have the same problem too

**Comment by krave1986** [comment]
I have the same error. My android emulator is genymotion. After I installed api 26 (I originally use api 23) in genymotion and run `npm run android`, I get this error.

**Comment by krave1986** [comment]
To the ones who have met this error, if you have been set Android Studio adb in windows environment variable - PATH, here is my solution:

For windows 10 & windows 8
1. In Search, search for and then select: System
2. Click the Advanced system settings link.
3. Click Environment Variables. In the section System Variables, find the PATH environment variable and select it. Click Edit. 
4. In the Edit System Variable window, replace `Andorid Studio adb path` with `Genymotion adb path`.
Take my machine as an example, replace `C:\Users\YourUserName\AppData\Local\Android\Sdk\platform-tools` with `C:\Program Files\Genymobile\Genymotion\tools`. 
All you need to do to locate your adb path is to search `adb.exe` in explorer.
5. Click OK. Close and Reopen cmd. Run `npm run android`.
