### ISSUE TITLE
Created Utils folder for helper functions and got: Module does not exist in the module map

### ISSUE THREAD

**Issue by yynnooot** [react-community/create-react-native-app#620]
I am trying to create a utilities folder to contain all of my helper functions, but when I import the helper function into my Component the app crashes.

My structure:
 - Components
    |--- Component1
    |--- Component2
 - Utils
    |--- HelperFunc1

*** By the way, a lot of example projects have a src folder with the Components/Redux/Utils folders within it. My create-react-native-app did not create a src folder. ***

## Expected Behavior
I export the HelperFunctions and import it into a Component to be used on an onPress event.

## Observed Behavior
The app crashes and the message I get is: 
```
Unable to resolve module 'react-native-router' from '[path to helperFunction]': Module does not exist in the module map.
This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following: 
  1) Clear watchman watches: `watchman watch-del-all`
  2) Delele the `node_modules` folder: `rm -rf node_modules && npm install`
  3) Reset Metro Bundler cache: `rm -rf $TMPDIR/react-*` or `npm start -- --reset-cache`
  4) Remove haste cache: `rm -rf $TMPDIR/haste-map-react-native-packager-*`
```
*** I was able to run all of the above EXCEPT for #4. When I run #4, I get: `zsh: no matches found: /var/folders/0z/r98whyzj4qjg7mg0sysnh02h0000gn/T//haste-map-react-native-packager-*` 
***

## Environment
* `npm ls react-native-scripts`: react-native-scripts@1.12.0
* `npm ls react-native`: react-native@0.52.0
* `npm ls expo`: expo@25.0.0
* `node -v`: v8.10.0
* `npm -v`: 4.6.1
* `yarn --version`: 1.5.1
* `watchman version`: "version": "4.9.0"

1. Operating system: MacOS High Sierra
2. Phone/emulator/simulator & version: Version 10.0 (SimulatorApp-835.5 CoreSimulator-494.33)

**Comment by esamelson** [comment]
Hi @yynnooot - it looks like the packager is having trouble finding the `react-native-router` package. Is that something you installed? If so, could you check and see if the `node_modules/react-native-router` folder exists? You may need to make sure `react-native-router` is listed as a dependency in your package.json and then run `yarn` again.

**Comment by esamelson** [comment]
Hi @yynnooot - it looks like something in your `helperFunction` file is trying to use that module (going off of the error message `Unable to resolve module 'react-native-router' from '[path to helperFunction]'`). I would check in there for a rogue `import` or `require` statement.

**Comment by yynnooot** [comment]
@esamelson, you are absolutely right! Wow, I was importing from 'react-native-router' instead of 'react-native-router-flux'...  I am an idiot! Thanks for your help though Eric!
