### ISSUE TITLE
npm i create-react-app code 128

### ISSUE THREAD

**Issue by naivedeveloper95** [react-community/create-react-native-app#621]
# READ THIS FIRST, PLEASE!

I tried creating a new app in react. Also tried it with sudo permission but failed with these errors. Please help me. I have added the image file of the entire process. I have also added the log file in case you may find it useful. 

![error](https://user-images.githubusercontent.com/15083393/38407343-b170d71a-3996-11e8-80b7-32925e2b5871.png)

[logfile.txt](https://github.com/react-community/create-react-native-app/files/1883045/logfile.txt)

**Comment by jasonleonhard** [comment]
#### The command you list on the top of this page is incorrect. 

#### Reviewing the readme on the mage page:
https://github.com/react-community/create-react-native-app 

#### You will note the correct commands to use
npm install -g create-react-native-app 
create-react-native-app my-app 
cd my-app/ 
npm start
