### ISSUE TITLE
Currently, starting a new project throws the error "Error: Invalid sdkVersion."

### ISSUE THREAD

**Issue by Devhound** [react-community/create-react-native-app#622]
## Description

Following the instructions in the read.me gives the error "Invalid sdkVersion" 

## Expected Behavior

If someone is following instructions from the readme shouldn't it work? 

## Observed Behavior

I had to change the sdkversion of expo and react-native. I also had to clear the watchman cache and delete node_modules and reinstall packages. This could have been avoided if the sdk version was set to version that worked. 

```
Error: Invalid sdkVersion. Valid options are 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0, 16.0.0, 17.0.0, 18.0.0, 19.0.0, 20.0.0, 21.0.0, 22.0.0, 23.0.0, 24.0.0, 25.0.0, 7.0.0, 8.0.0, 9.0.0
```
## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: 1.13.1
* `npm ls react-native`: 0.54.0
* `npm ls expo`:  26.0.0
* `node -v`: 9.8.0
* `npm -v`: 5.6.0
* `yarn --version`: 1.5.1
* `watchman version`:  4.9.0

Also specify:

1. Operating system: Mac high sierra 10.13
2. Phone/emulator/simulator & version: iOS sim v10

Changing expo to v25 and react-native to v52 fixed this error. Just wondering why it's set to an unsupported sdk version. 

## Reproducible Demo

Just follow the readme.
`create-react-native-app my-app`
`cd my-app`
`npm run start`

**Comment by EvanBacon** [comment]
Can you share the results of running the following in the terminal: `exp -V`, mine is `51.4.0` and it works fine... 0.0

**Comment by Devhound** [comment]
Mine is ‘50.0.5’

**Comment by Devhound** [comment]
Updated exp to 51.4.0 and still get the following error. 

`Error: Invalid sdkVersion. Valid options are 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0, 16.0.0, 17.0.0, 18.0.0, 19.0.0, 20.0.0, 21.0.0, 22.0.0, 23.0.0, 24.0.0, 25.0.0, 7.0.0, 8.0.0, 9.0.0`

**Comment by brentvatne** [comment]
try `rm -rf ~/.expo/cache`

**Comment by Devhound** [comment]
Doing that in addition to also reseting and reinstalling the expo app on the ios sim made it work. Thanks for the quick reply.
