### ISSUE TITLE
npm run eject failed

### ISSUE THREAD

**Issue by zzq392342084** [react-community/create-react-native-app#625]
enviroments:
**os: windows10
npm@5.5.1
node@v8.9.3**

when exec "npm run ",it outputs : 

![default](https://user-images.githubusercontent.com/12469232/38545633-12588e44-3cdd-11e8-87e6-2b7062b5ea47.png)
![default](https://user-images.githubusercontent.com/12469232/38545654-20a3fbfa-3cdd-11e8-9483-eab8c7cbeadb.png)

**npm log:**

_0 info it worked if it ends with ok
1 verbose cli [ 'E:\\tools\\nodejs\\node.exe',
1 verbose cli   'E:\\tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'eject' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose run-script [ 'preeject', 'eject', 'posteject' ]
5 info lifecycle cv@0.1.0~preeject: cv@0.1.0
6 info lifecycle cv@0.1.0~eject: cv@0.1.0
7 verbose lifecycle cv@0.1.0~eject: unsafe-perm in lifecycle true
8 verbose lifecycle cv@0.1.0~eject: PATH: E:\tools\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\dell.dell-pc\Desktop\demos\cv\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;";E:\tools\jdk\jdk1.8.0_102\bin;E:\tools\jdk\jdk1.8.0_102\jre\bin";E:\tools\TortoiseSVN\bin;E:\tools\nvm;E:\tools\nodejs;E:\tools\Git\bin;E:\tools\nodejs\;E:\tools\nodejs\node_global;E:\tools\Android\SDK\platform-tools;E:\tools\Android\SDK\tools;C:\ProgramData\chocolatey\bin;C:\Users\dell.dell-pc\AppData\Local\Microsoft\WindowsApps;E:\tools\nvm;E:\tools\nodejs;C:\Users\dell.dell-pc\AppData\Roaming\npm
9 verbose lifecycle cv@0.1.0~eject: CWD: C:\Users\dell.dell-pc\Desktop\demos\cv
10 silly lifecycle cv@0.1.0~eject: Args: [ '/d /s /c', 'react-native-scripts eject' ]
11 silly lifecycle cv@0.1.0~eject: Returned: code: 1  signal: null
12 info lifecycle cv@0.1.0~eject: Failed to exec eject script
13 verbose stack Error: cv@0.1.0 eject: `react-native-scripts eject`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (E:\tools\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (E:\tools\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid cv@0.1.0
15 verbose cwd C:\Users\dell.dell-pc\Desktop\demos\cv
16 verbose Windows_NT 10.0.16299
17 verbose argv "E:\\tools\\nodejs\\node.exe" "E:\\tools\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "eject"
18 verbose node v8.9.3
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error cv@0.1.0 eject: `react-native-scripts eject`
22 error Exit status 1
23 error Failed at the cv@0.1.0 eject script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]_

**Comment by Prithvi45** [comment]
If your code is connected to github , commit it and then try to eject

**Comment by Luismi74** [comment]
my solution: `npm install -g react-native-scripts ` then run `react-native-scripts eject` . this will do the same as npm run eject. hope it works!
