### ISSUE TITLE
getting error while scanning the QR code, something went wrong

### ISSUE THREAD

**Issue by KrishnaJoshii** [react-community/create-react-native-app#627]
# READ THIS FIRST, PLEASE!

The App Store version of the Expo iOS client recently had to remove the QR code scanner from the app. If you intend to load your app on a physical iOS device, please install the latest version of react-native-scripts to your app (`yarn add react-native-scripts@latest` or `npm install react-native-scripts@latest`). It adds the "s" key to the interactive prompt, which asks you to enter an email address or phone number and then sends the URL to your device.

Read more at https://blog.expo.io/upcoming-limitations-to-ios-expo-client-8076d01aee1a. We apologize for any inconvenience this may cause you!

# Required format for issues

Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request

I was able to create the folder react native project but I am facing issue while scanning the QR code.

## Expected Behavior

What action did you perform, and what did you expect to happen?

I scanned the QR code by using the EXPO app on the phone I  expected something to happen like opening an app with some random information

## Observed Behavior

What actually happened when you performed the above actions?

But it said instead that something went wrong and didn't open any thing

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Something went wrong.

Could not load
exp://10.182.249.251:19000.
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:`-- (empty)
* `npm ls react-native`:`-- (empty)
* `npm ls expo`:`-- (empty)
* `node -v`:v8.11.1
* `npm -v`:5.6.0
* `yarn --version`:'yarn' is not recognized as an internal or external command,
operable program or batch file.
* `watchman version`:'watchman' is not recognized as an internal or external command,
operable program or batch file.

Also specify:

1. Operating system: Windows 10, 64 bit operating system 
2. Phone/emulator/simulator & version: Phone Xiomi redme note 4

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.
Something went wrong.

Could not load
exp:/10.182.249.251:19000.

There is home button and replay button.

And when I click on the error log I am seeing this message
![screenshot_2018-04-10-19-53-51-205_host exp exponent](https://user-images.githubusercontent.com/17729162/38590805-1ff708c0-3cf9-11e8-8d19-7e2d408a4052.png)
![screenshot_2018-04-10-19-54-01-076_host exp exponent](https://user-images.githubusercontent.com/17729162/38590806-200a2504-3cf9-11e8-9f67-dc554efc45b9.png)

uncaught error: java.net.NoRouteToHostException: No route to host

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by adhik97** [comment]
### Temporary solution

**Step 1 :**  Get the local IPv4 address of your computer
   (windows) Type `ipconfig` in Command Prompt
   (Mac) Type `ifconfig -a` in Terminal

**Step 2 :** Create a QR code with text **exp://YOUR_LOCAL_IP_ADDRESS:19000**

**Step 3 :** Scan the QR Code

**Comment by quinlanj** [comment]
your local network may not support accessing other machines over LAN.

you can solve this by doing what @adhik97 said, or the solution here: https://forums.expo.io/t/expo-not-working-on-home-network/5664

**Comment by oshyam** [comment]
Tried but failed!
Any Solution for specifically Linux Users??

**Comment by DeHerro1** [comment]
for windows and expo running on android switching the connection to Tunnel works for me.

**Comment by darkman13web** [comment]
I am using windows what can i do to?

**Comment by Nash0509** [comment]
For anyone using the windows and the android, this command worked for me 'expo start --tunnel' ...
