### ISSUE TITLE
Undeclared dependency: Watchman

### ISSUE THREAD

**Issue by iMerica** [react-community/create-react-native-app#639]
## Description
Following the getting started instructions exactly as written does not work because watchman is required. Even the issue template for this repo references Watchman although watchman is not mentioned anywhere in the README.

## Expected Behavior

I expect the readme instructions to work exactly as written.

## Observed Behavior

The [Quickstart](https://github.com/react-community/create-react-native-app#quick-overview) instructions do not work and the following error occurs

```
8:40:29 PM: Unable to start server
See https://git.io/v5vcn for more information, either install watchman or run the following snippet:
  sudo sysctl -w kern.maxfiles=5242880
  sudo sysctl -w kern.maxfilesperproc=524288
```

## Environment

* `npm ls react-native-scripts`:  react-native-scripts@1.13.2
* `npm ls react-native`: react-native@0.54.4
* `npm ls expo`: expo@26.0.0
* `node -v`: v7.10.1
* `npm -v`: 4.2.0
* `yarn --version`: yarn --version
* `watchman version`: LOL (See description)

1. Operating system: macOS 10.13.4
2. Phone/emulator/simulator & version:

**Comment by brentvatne** [comment]
on some machines you don't need watchman. on others you do. the error message explains how to work around it. feel free to submit a PR to clarify in docs if you like
