### ISSUE TITLE
Packager hangs on invalid JS — more helpful error logging?

### ISSUE THREAD

**Issue by lazerwalker** [react-community/create-react-native-app#640]
## Description

When I try to build my app for iOS (either simulator on-device), the packager consistently hangs at 99% on the "Building JavaScript Bundle" step. 

This is consistent with issues such as https://github.com/react-community/create-react-native-app/issues/560, which make me assume the error is somewhere in my own JS code (TS code in my case). 

Rather than me shooting blind trying to find where my error is, is there a flag or something that will spit out compilation error messages?

## Expected Behavior

When running `yarn start` and either connect via a physical device or an iOS simulator (or run `yarn ios`, `npm start`, etc), and my app fails to compile because of my own error, I'd expect to see (or be able to manually enable) output from Babel/Webpack/etc telling me what the error is.

At the very least, I'd assume it would fail out completely, rather than hanging silently?

## Observed Behavior

The packager hangs indefinitely with the text "Building JavaScript: 99%". No error messaging shows up. Eventually, the connected client times out, but the terminal yarn/npm command remains stuck at 99%.

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
```
rn@0.1.0 /Users/lazerwalker/Code/word-temple/rn
└── react-native-scripts@1.13.2
```

* `npm ls react-native`:
```
rn@0.1.0 /Users/lazerwalker/Code/word-temple/rn
└── react-native@0.54.0
```

* `npm ls expo`:

```
rn@0.1.0 /Users/lazerwalker/Code/word-temple/rn
└── expo@26.0.0
```

* `node -v`: `v9.11.1`
* `npm -v`: `5.6.0`
* `yarn --version`: `1.6.0`
* `watchman version`: `{  "version": "4.9.0" }`

Also specify:

1. Operating system: macOS 10.13.4 (reproduced on multiple Mac devices, same OS version)
2. Phone/emulator/simulator & version: Reproduced both on a physical iPhone 8 Plus and in the 8 Plus simulator (Xcode 9.3)

## Reproducible Demo

Can try to throw together a more minimal reproducible demo in a bit if it'd be helpful. Happy to help debug in any way that I can!

**Comment by lazerwalker** [comment]
I've found I was able to help nail down my issues by just manually running `tsc` and seeing TypeScript compiler output, but it still feels like a pretty nasty bug that errors aren't being threaded through properly to `yarn start` output.

**Comment by anp** [comment]
Hi! As of right now Typescript support is maintained separately at https://github.com/mathieudutour/create-react-native-app-typescript AFAIK, can you please open this issue there? Thanks!
