### ISSUE TITLE
SDK

### ISSUE THREAD

**Issue by Nasrallah1997** [react-community/create-react-native-app#642]
i cannot make my project
![screenshot_20180425202647](https://user-images.githubusercontent.com/37748047/39265468-9eecd630-48c7-11e8-9d27-7b887a40c0c2.png)

**Comment by esamelson** [comment]
Hi @Nasrallah1997 - from reading the error message, it looks like you need to start up Android Studio GUI at least once so that you can accept a license agreement inside of it. Have you tried that?
