### ISSUE TITLE
Ability to pass entry file to CLI

### ISSUE THREAD

**Issue by kevinwolfcr** [react-community/create-react-native-app#645]
Hello guys. I did noticed the lack of ability to pass an entry file to `react-native-scripts`. Is there any option that I can pass to change it? Something like `react-native-scripts start --entry src/index.js`.

I don't like to keep my .js files on the root folder. Also, I am using storybook to create visual stories for the components, so this would be helpful here since I will be using the command `react-native-scripts start --entry storybook/index.js`

**Comment by jcsmesquita** [comment]
Same issue here, trying to setup storybook with CRNA https://github.com/storybooks/storybook/tree/master/app/react-native#create-react-native-app-crna

Can't find a decent solution for being able to run storybook with a script that won't interfere with the local dev flow.
