### ISSUE TITLE
Running CRNA app after detach from expo goes to wrong port in emulator

### ISSUE THREAD

**Issue by dorelm** [react-community/create-react-native-app#646]
I am trying to do a detach from expo. I am using sdk 26.
I build the project with android studio and gradle.
I am running the app on genymotion ammulator. The app builds and is installed, I can see the splash screen, but then get a network error:

![image](https://user-images.githubusercontent.com/7999283/39385749-65243de4-4a7a-11e8-9766-d8840e88a033.png)

I thing the post should be 19000, which the emulator is able to access.

I am starting the project with this command:
exp start -a --lan --dev

I get this input:

00:15:37 [exp] Using project at C:\workspaces\yedidim-bot\volunteers-app
00:15:49 [exp] Warning: 'firebase' peer dependency missing. Run `npm ls` in C:\workspaces\yedidim-bot\volunteers-app to see full warning.
00:15:49 [exp]
00:15:49 [exp] If there is an issue running your project, please run `npm install` in C:\workspaces\yedidim-bot\volunteers-app and restart.
00:15:51 [exp] Starting Metro Bundler on port 19001.
00:15:51 [exp] Metro Bundler ready.
00:15:54 [exp] Expo is ready.

00:15:54 [exp] Your URL is: exp9bda8a95913e4729a578d25e2b535a57://192.168.56.1:19000
00:16:10 [exp] Couldn't start project on Android: Error running adb: This computer is not authorized to debug the device. Please follow the instructions here to enable USB debugging:
https://developer.android.com/studio/run/device.html#developer-device-options. If you are using Genymotion go to Settings -> ADB, select "Use custom Android SDK tools", and point it at your Android SDK directory.
00:16:10 [exp] Logs for your project will appear below. Press Ctrl+C to exit.
00:16:20 [exp] Metro Bundler failed to start. (code: EPERM)

There is an error, how ever loading the project url in the browser (http://192.168.56.1:19000), works on my computer and also on a browser in the emulator, returning:

{"name":"ידידים מתנדבים","slug":"yedidim-volunteers","sdkVersion":"25.0.0","splash":{"resizeMode":"cover","image":"./assets/icons/splash.png","backgroundColor":"#ffffff","imageUrl":"http://192.168.56.1:19001/assets/./assets/icons/splash.png"},"icon":"./assets/icons/icon.png","notification":{"icon":"./assets/notification/icon.png","iconUrl":"http://192.168.56.1:19001/assets/./assets/notification/icon.png"},"scheme":"yddmva","hooks":{"postPublish":[{"file":"sentry-expo/upload-sourcemaps","config":{"organization":"startach","project":"yedidim-volunteers","authToken":"b1c4ef08fddd49fabb4fbc4d8190e51c8108d1d8986d4e1caf7bc1c3e98315e4"}}]},"extra":{"AmplitudeAPI":"2e1ccff4946b3318c47b05aeaaf7db16","SentryAPI":"https://e075960424d7484ab62d767a844a9502:422a3b4e953b4c7a84cd9811bb71fc90@sentry.io/266660"},"ios":{"bundleIdentifier":"com.startach.yedidim.volunteers.detached"},"android":{"package":"com.startach.yedidim.volunteers.detached","publishBundlePath":"android\\app\\src\\main\\assets\\shell-app.bundle","publishManifestPath":"android\\app\\src\\main\\assets\\shell-app-manifest.json"},"version":"2.0.1","isDetached":true,"detach":{"scheme":"exp9bda8a95913e4729a578d25e2b535a57","androidExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v2.3.0-sdk25.0.0-0c32461b-a7c6-4ddc-b85b-32a80c4f18d9.tar.gz"},"xde":true,"developer":{"tool":"exp","projectRoot":"C:\\workspaces\\yedidim-bot\\volunteers-app"},"packagerOpts":{"hostType":"lan","lanType":"ip","dev":true,"minify":false,"urlRandomness":"null"},"env":{},"bundleUrl":"http://192.168.56.1:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=C%3A%5Cworkspaces%5Cyedidim-bot%5Cvolunteers-app%5Cnode_modules%5Cexpo%5Ctools%5ChashAssetFiles","debuggerHost":"192.168.56.1:19001","mainModuleName":"./node_modules/react-native-scripts/build/bin/crna-entry","logUrl":"http://192.168.56.1:19000/logs","hostUri":"192.168.56.1:19000","iconUrl":"http://192.168.56.1:19001/assets/./assets/icons/icon.png"}

What am I missing?

**Comment by Gytree** [comment]
hi, i have the same issue with expo. the expo exposed url is **exp://192.168.100.102:19000** but the client in the android emulator try to get the url with the port 19001.
i run the emulator in a ubuntu machine, and launc the expo with the 
exp start 
Any idea why?

**Comment by esamelson** [comment]
@Gytree that is expected behavior -- expo serves the JS package from port 19001 while it serves other project information & metadata from port 19000.

Are you getting an error message when trying to load your app in the Expo client?

**Comment by Gytree** [comment]
@esamelson i solved my issue creating another avd instance. I don't know why this happened
