### ISSUE TITLE
I get an error when I run  create-react-native-app my-app

### ISSUE THREAD

**Issue by hminaee** [react-community/create-react-native-app#648]
Hi everyone,

I am using windows 10 with nodejs installed.
As soon as I run this command: 
` create-react-native-app my-app`

I get the following errors:

 `   npm ERR! path D:\test\my-app\node_modules\import-local\fixtures\cli.js
     npm ERR! code ENOENT
     npm ERR! errno -4058
     npm ERR! syscall chmod
     npm ERR! enoent ENOENT: no such file or directory, chmod 'D:\test\my-app\node_modules\import- 
        local\fixtures\cli.js'
         npm ERR! enoent This is related to npm not being able to find a file.
        npm ERR! enoent
      npm ERR! A complete log of this run can be found in:
      npm ERR!     C:\Users\hamed\AppData\Roaming\npm-cache\_logs\2018-04-28T14_43_47_183Z- 
      debug.log
       Failed to install`

At this point I am stuck and cannot proceed at all. Any idea?

![nodeerror](https://user-images.githubusercontent.com/4450635/39398189-65aff420-4abf-11e8-8f0f-990001d11f8b.png)

**Comment by Osama92** [comment]
Are you sure you installed the package well?
Try running node-v and npm-v (you should get the versions of installed packages).
