### ISSUE TITLE
New app not running in simulator

### ISSUE THREAD

**Issue by gjhughes** [react-community/create-react-native-app#649]
## Description
Created a new app but cannot get it to run via iOS simulator.

## Expected Behavior

What action did you perform, and what did you expect to happen?

yarn ios
expected simulator to run app but get an error message.

## Observed Behavior

What actually happened when you performed the above actions?

get these warnings on creating the app:
warning "expo > react-native-maps@0.21.0" has incorrect peer dependency "react-native@^0.51 || ^0.52 || ^0.53 || ^0.54".
warning "react-native > eslint-plugin-react-native@3.2.1" has unmet peer dependency "eslint@^3.17.0 || ^4.0.0".
warning "jest-expo > babel-jest@22.4.3" has unmet peer dependency "babel-core@^6.0.0 || ^7.0.0-0".

Console reads this after 'yarn ios':
17:14:52: Warning: 'react' peer dependency missing. Run `npm ls` in /Users/Gavin/Desktop/myapp to see full warning.
17:14:52:
17:14:52: If there is an issue running your project, please run `npm install` in /Users/Gavin/Desktop/myapp and restart.

Console reads this after 'npm ls':
npm ERR! peer dep missing: react@16.3.1, required by react-native@0.55.3
npm ERR! extraneous: node-pre-gyp@0.9.1 /Users/Gavin/Desktop/test_app/node_modules/node-pre-gyp
npm ERR! extraneous: websql@0.4.4 /Users/Gavin/Desktop/test_app/node_modules/websql
npm ERR! missing: websql@https://github.com/expo/node-websql/archive/18.0.0.tar.gz, required by expo@27.0.1
npm ERR! peer dep missing: react-native@^0.51 || ^0.52 || ^0.53 || ^0.54, required by react-native-maps@0.21.0
npm ERR! peer dep missing: eslint@^3.17.0 || ^4.0.0, required by eslint-plugin-react-native@3.2.1

## Environment

Please run these commands in the project folder and fill in their results:

react-native-scripts@1.14.0
react-native@0.55.3
expo@27.0.1
v8.4.0
4.6.1
1.5.1
"version": "4.9.0"

Also specify:

1. Operating system: macOS High Sierra 10.13.4
2. Phone/emulator/simulator & version: Simulator Version 10.0

**Comment by nicoceledon** [comment]
I have a similar problem on android. Later i'll provide more info. Also, i tried `npm install`, and the warning is out but still cannot load on emulator.

**Comment by gavinjhughes** [comment]
@nicoceledon thanks, just done the same.  Still getting warnings but the app is now building and running.  Thanks very much!

**Comment by gjhughes** [comment]
@nicoceledon thanks, just done the same. Still getting warnings but the app is now building and running. Thanks very much!

**Comment by XMalatji** [comment]
I'm still getting these problems. It was working a few weeks ago but this week i'm getting the same problems @gjhughes is having.

**Comment by XMalatji** [comment]
How do you remove expo from the simulator?

**Comment by XMalatji** [comment]
Im good nvm thanks.

**Comment by thomashrabe** [comment]
Same problem. How do I start again at zero?

**Comment by thomashrabe** [comment]
@rss81 So did your steps solve the `react-native@^0.51 || ^0.52 || ^0.53 || ^0.54, required by react-native-maps@0.21.0` issue. It's not 100% clear to me

**Comment by rss81** [comment]
no, the problem is if you install 0.54 then you have a lot of problems as the build with expo require 0.55

**Comment by thomashrabe** [comment]
yes. I think the problem is in the `react-native-maps` package that needs to be updated...?

**Comment by bedakb** [comment]
I'm experiencing the same problem as described in first post - If I use yarn to install dependencies.However If I use npm to install dependencies and start server, I only get error related to the react-native-maps.

`npm ERR! peer dep missing: react-native@^0.51 || ^0.52 || ^0.53 || ^0.54, required by react-native-maps@0.21.0`

https://github.com/react-community/react-native-maps/issues/2259

**Comment by Osama92** [comment]
if you're using Expo, Update to a new version. same applies to the simulator, Delete the Expo client app from the simulator, and redownload from the command line **yarn run ios.**

**Comment by tonjack** [comment]
You can also use Expo XDE, it will automatically update the Expo client for the simulator.

**Comment by thomashrabe** [comment]
@tonjack 
Unfortunately did not work for me on an entirely blank system:

thomas@rethina ;) npm install react-native-maps --save
```
/Users/thrabe/test1
├─┬ expo@27.0.1
│ ├── UNMET PEER DEPENDENCY react-native@^0.51 || ^0.52 || ^0.53 || ^0.54
│ └── websql@0.4.4
├─┬ UNMET PEER DEPENDENCY react-native@0.55.2 invalid
│ └── UNMET PEER DEPENDENCY eslint@^3.17.0 || ^4.0.0
└─┬ react-native-maps@0.21.0
  └─┬ babel-preset-react-native@1.9.0
    └── babel-plugin-react-transform@2.0.2
```

**Comment by JoasE** [comment]
Deleting the `node_modules` and running `yarn install` instead of `npm install` solved the problem for me.
