### ISSUE TITLE
Changing gitignore node_modules/**/* into just node_modules/

### ISSUE THREAD

**Issue by scmx** [react-community/create-react-native-app#65]
My editor doesn't like that `react-native-scripts/template/gitignore` contain `node_modules/**/*` instead of `node_modules/`. 

Is there a particular reason why it's like that? If not I'd be happy to submit a pull request to change it.

Nice project! I was just gonna check out react native for the first time this week! 🌟

**Comment by dikaiosune** [comment]
I have no idea why I did that! I'd definitely merge a PR to fix that (if you want to remove the .expo glob pattern that'd be cool too!).
