### ISSUE TITLE
Debugger execution flow erratic, can't set breakpoints

### ISSUE THREAD

**Issue by mikecg** [react-community/create-react-native-app#650]
## Description

1. When debugging in Chrome, I am unable to add a breakpoint for some lines of code. Ctrl-b simply does not work... the line sort of just flashes, but no breakpoint is added.

1. Even when I can add a breakpoint, and the breakpoint gets hit, after hitting F10 to step to the next line, instead, the line of the function declaration gets highlighted instead. After pressing F10 a few more times, that line remains highlighting, until finally control will switch contexts completely. It seems as if the code is working, but for some reason the debugger is not aware of what line is being run.

I saw some old threads about source maps and async methods, and that may be the issue here, but most of those threads are old, and I haven't seen any new ones about these issues. 

I feel like I am the only one with this issue, and it is making me reconsider using react native as I cannot do any work like this.

## Expected Behavior

I expect the debugger to work. 

## Observed Behavior

The debugger behaves unpredictably.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@1.14.0
* `npm ls react-native`: react-native@0.55.3
* `npm ls expo`: expo@27.0.1
* `node -v`: v8.9.4
* `npm -v`: 5.6.0
* `yarn --version`: 1.6.0
* `watchman version`: no such command

Also specify:

1. Operating system: Windows 10
2. Phone/emulator/simulator & version: Genymotion Version 2.12.0 with Google Nexus 5

## Reproducible Demo
I will try to come up with one if the community has no ability to help. This seems like it may be environment specific.

**Comment by brentvatne** [comment]
you need to enable sourcemaps in chrome and in visual studio code.

i don't know how to do this in vsocde but in chrome it's like this ![](http://url.brentvatne.ca/QiiEYk.png)

**Comment by lhrolim** [comment]
I Have the same problem here on top of:

npm ls react-native: react-native@0.55.4
node -v: v10.1.1
npm -v: 6.1.0
yarn --version: 1.7.0
watchman version: 4.7.0

Running on ubuntu 16.0.4

It seems to only affect async/await functions though. I believe it's related, somehowe, to a bad generated sourcemap
