### ISSUE TITLE
Для всех жителей России, которые столкнулись с незаконными блокировками РКН // For all Russian users which collided with a unlawful RKN blocks

### ISSUE THREAD

**Issue by p0liper** [react-community/create-react-native-app#653]
Hello to all.
Due to unlawful RKN blocks, I'd like to start a transparent proxy server for exp.host and expo.io.
This server **is not, was not and will not** collect your data (this server is a just transparent proxy).
You should modify your /etc/hosts (%windir%\system32\drivers\etc\hosts) file, appending that:
```
185.28.103.178 exp.host
185.28.103.178 expo.io
185.28.103.178 docs.expo.io

```

===
Привет всем.
Ввиду незаконной блокировки ресурса Роскомнадзором, я запустил свой транспарентный сервер для проектов exp.host и expo.io.
Данный сервер **не собирает, не собирал и не будет собирать** Ваши данные (этот сервер является всего лишь прозрачным прокси сервером, который подтвержден SSL сертификатом exp.host и expo.io)
Вы должны отредактировать Ваш файл /etc/hosts (%windir%\system32\drivers\etc\hosts), путем добавления следующих строк:
```
185.28.103.178 exp.host
185.28.103.178 expo.io
185.28.103.178 docs.expo.io

```

Спасибо за внимание!

**Comment by nickerlan** [comment]
Thant you very much! 
BTW it solves  "Starting Packager..." stuck issue (https://github.com/react-community/create-react-native-app/issues/203)

**Comment by p0liper** [comment]
@nickerlan You're welcome. 
If you have websites which blocked due to unknown reasons (such as developer android), paste it here and I will create a tunnel for it on my proxy.

**Comment by p0liper** [comment]
If some of hosts are blocked, we can tunnel them via our proxy without packet loss or send any SSL certificates. Just fill info in this issue:
https://github.com/p0liper/unrkn/issues/1
