### ISSUE TITLE
Stuck with create-react-native-app now, something wrong with yarn or npm

### ISSUE THREAD

**Issue by 129emma** [react-community/create-react-native-app#660]
## Description

Suddenly got this issue when I was trying to create a new RN project.
I tried many ways still cannot solve it.
Thanks

```
xxx$ create-react-native-app shopping-cart
Creating a new React Native app in /Users/xxx/ReactNative/shopping-cart.

Using package manager as yarnpkg with yarn interface.
Installing packages. This might take a couple minutes.
Installing react-native-scripts...

yarn add v1.6.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
info There appears to be trouble with your network connection. Retrying...
```

## Environment

Please run these commands in the project folder and fill in their results:
* `macOS`: 10.13.4
* `node -v`: 8.11.2
* `npm -v`: 5.6.0
* `yarn --version`: 1.6.0
* `watchman version`: 4.9.0

**Comment by YSGoh** [comment]
Facing the exact same issue on Ubuntu 16.04LTS right now.

**Comment by jayrexacilo** [comment]
Same issue here:

- 

> node -v : v8.11.2

- 

> npm -v : 5.6.0

- 

> windows 10

**Comment by 129emma** [comment]
I think something wrong with npm now, looks they are solving it right now
https://status.npmjs.org/incidents/b307lbjrdql7

**Comment by FlorianTousch** [comment]
I updated react-native (sudo npm i -g react-native) and run again, work now.

**Comment by brentvatne** [comment]
looks like a npm bug indeed. probably fixed now
