### ISSUE TITLE
create react-native app json parse error

### ISSUE THREAD

**Issue by ggepenyan** [react-community/create-react-native-app#661]
I'm creating new app and getting **json parse error**
I'm on windows. Here is what I get in Powershell.

```
Creating a new React Native app in ....

Using package manager as npm with npm interface.
Installing packages. This might take a couple minutes.
Installing react-native-scripts...

npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm ERR! registry error parsing json
```

my **npm version is 4**.
I tryed to use **yarn** but it failed also.
in project folder I can see package json file added(only that file). I don't know what to do, because I tryed everything I think. I have cleaned npm cache also. I have updated npm version and tryed on that version too. But nothing helped. Any help please

**Comment by brentvatne** [comment]
looks like a npm bug. might want to clear cache and try again
