### ISSUE TITLE
Npm start gets stuck at Starting Packager...

### ISSUE THREAD

**Issue by roy2393** [react-community/create-react-native-app#666]
## Description

npm start gets stuck on Starting packager

## Expected Behavior

It should give the QR code on the terminal

## Observed Behavior

A few days back it was working fine. Then it worked after I deleted all node_modules file and installed again. But now it doesn't work at all.

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@1.13.1
* `npm ls react-native`: react-native@0.54.0
* `npm ls expo`: expo@26.0.0
* `node -v`:v10.0.0
* `npm -v`: 6.0.0
* `yarn --version`: 1.7.0
* `watchman version`: 4.7.0

Also specify:

1. Operating system: Ubuntu 16.04

**Comment by sanderlooijenga** [comment]
I have the same, on;

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@1.14.1 
* `npm ls react-native`: react-native@0.55.4
* `npm ls expo`: expo@27.0.2 
* `node -v`: v10.3.0
* `npm -v`: 6.1.0
* `yarn --version`: n.a.
* `watchman version`: 4.9.0

Also specify:

1. Operating system: macOS High Sierra 10.13.4

**Comment by sanderlooijenga** [comment]
For me the following fixed it;

Uninstalling create-react-native-app & reinstalling it again.

**Comment by KHeeney5** [comment]
Same issue for me, using npm.

Worth noting that I ran `create-react-native-app` to create a new project and `npm run start` works as expected.

## Environment
Please run these commands in the project folder and fill in their results:

`npm ls react-native-scripts`: react-native-scripts@1.14.0
`npm ls react-native`: react-native@0.55.4
`npm ls expo`: expo@27.1.0
`node -v`: v8.11.3
`npm -v`: 5.6.0
`yarn --version`: 1.7.0
`watchman version`: n/a

Also specify:

Operating system: Windows 10

**Comment by roy2393** [comment]
I got the issue.
The issue was in the

> /proc/sys/fs/inotify/max_user_watches = 8192
> 
> /proc/sys/fs/inotify/max_queued_events = 16384

Basically, max_user_watches impacts how many dirs you can watch across all watched roots and max_queued_events impacts how likely it is that your system will experience a notification overflow. So while building the native app, these limits used to exceed because of which build process got stuck.

Just increasing these limits makes it work.

To increase the limit use:

> echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf

**Comment by KHeeney5** [comment]
@esamelson Yes, no luck...
