### ISSUE TITLE
Eject failed with exit code 1, see above output for any issues.

### ISSUE THREAD

**Issue by motogod** [react-community/create-react-native-app#669]
I face the error when using `npm run eject`(regular react native project) after CRNA.

Can't figure it out why the error happen suddenly.

## Description
My project created by CRNA and npm run eject with regular react native projecty.

I find i can't see any message from Chrome debug mode recently. It just keeps flashing one line message that is `<img>    code?id=105&subid=51824_7009_:1`

![videotogif_2018 05 28_23 03 19](https://user-images.githubusercontent.com/17781603/40633283-54bd981e-6321-11e8-9e7d-f0ed977aa0ce.gif)

<img width="1433" alt="2018-05-28 11 29 43" src="https://user-images.githubusercontent.com/17781603/40634017-804d365c-6325-11e8-902d-a89f6057995f.png">

I try to reboot my mac machine or run my older project, the issue is still there.

I still try use debug mode with visual studio code console, when i run `Debug ios` i see the error:

`Could not debug. Another debugger is already connected to packager. Please close it before trying to debug with VSCode.` , but i have closed Chrome and emulator's debug JS remotely.

So i try to create a new project to see what is going on.    When using `npm run eject` after CRNA i see the error `Eject failed with exit code 1, see above output for any issues.` 

I found that `code 1` may be just like the problem that keeps flashing code `<img>    code?id=105&subid=51824_7009_:1` on Chrome debug console

## Expected Behavior

It should be create a react native project succeed when using `npm run eject` after CRNA. 

## Observed Behavior

What actually happened when you performed the above actions?

With the error full message:
```
Eject failed with exit code 1, see above output for any issues.
You may want to delete the `ios` and/or `android` directories.

npm ERR! Darwin 17.5.0
npm ERR! argv "/Users/motogod19/.nvm/versions/node/v6.2.1/bin/node" "/Users/motogod19/.nvm/versions/node/v6.2.1/bin/npm" "run" "eject"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! tchrome@0.1.0 eject: `react-native-scripts eject`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tchrome@0.1.0 eject script 'react-native-scripts eject'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tchrome package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-native-scripts eject
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tchrome
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tchrome
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/motogod19/ReactNativeTutorial/tchrome/npm-debug.log
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: 1.14.0
* `npm ls react-native`: @~0.55.2
* `npm ls expo`:  @^27.0.1
* `node -v`: v6.2.1
* `npm -v`: 3.9.3
* `yarn --version`: 1.5.1
* `watchman version`: 4.7.0

Also specify:

1. Operating system: macOs 10.13.4（17E202）
2. Phone/emulator/simulator & version: simulator Iphone 6

**Comment by motogod** [comment]
I find it is chrome setting problem not the issue with CRNA.

**Comment by motogod** [comment]
@Islamaim Which problem do you have ?  If is `It just keeps flashing one line message that is <img> code?id=105&subid=51824_7009_:1`. I solve it by removing some Chrome expansion tool, i remove `Xpath` and `Postman` (I think may be the `Postman` cause the issue).

And if you mean `Eject failed with exit code 1, see above output for any issues. ` , it is another problem , may be the `Node` version have to upgrade.  I still can't figure it out, consider open another issue some day.

Hope it helps.

**Comment by Islamaim** [comment]
Many thanks. Now it is solved. it was postman.
