### ISSUE TITLE
npm run ios fails because Error: Process exited with non-zero code: 107

### ISSUE THREAD

**Issue by NirBenya** [react-community/create-react-native-app#67]
Starting packager...
Starting simulator...
Failed to start simulator:

Error: Process exited with non-zero code: 107

Exiting...

**Comment by NirBenya** [comment]
solved by doing Simulator --> Reset Content and Settings, and then restarting the simulator.

**Comment by dikaiosune** [comment]
Thanks! Need to add a "troubleshooting iOS simulator" section to the user guide.

**Comment by somsin** [comment]
2:36:16 PM: Failed to start simulator
Process exited with non-zero code: 194

**Comment by nimish-gupta** [comment]
Same here error 194

**Comment by Charliekenney23** [comment]
If you're on the Xcode 9 beta: Simulator -> Hardware -> Erase all content and settings

**Comment by Inlesco** [comment]
Yep - on Xcode 9, in Simulator's action tab, nav to `Hardware -> Erase all content and settings`.

**Comment by ahmedu007** [comment]
Instead of `Erase all content and settings` I just removed `expo` from the simulator and it built fine. Saves time and doesnt Erase everything on the device

**Comment by inferusvv** [comment]
I simply quit simulator and press `i` after `yarn start`.

**Comment by AAwaisYaseen** [comment]
If you are not able to boot the simulator and the option for Reset Content and Settings is greyed out, You can try this

Mac --- > System Settings --- > Storage --- > Developer --- > Delete Xcode Caches.

Restart the simulator, it will work fine.

**Comment by d0sc** [comment]
For everyone still experiencing this error, @AAwaisYaseen answer is still valid. (Using Expo)
Thanks a lot!

**Comment by alexlop29** [comment]
@AAwaisYaseen, @d0sc Thank you! - The solution is still applicable while using Expo in 2024.
