### ISSUE TITLE
npm ls shows missing dependencies

### ISSUE THREAD

**Issue by rss81** [react-community/create-react-native-app#671]
# READ THIS FIRST, PLEASE!

The App Store version of the Expo iOS client recently had to remove the QR code scanner from the app. If you intend to load your app on a physical iOS device, please install the latest version of react-native-scripts to your app (`yarn add react-native-scripts@latest` or `npm install react-native-scripts@latest`). It adds the "s" key to the interactive prompt, which asks you to enter an email address or phone number and then sends the URL to your device.

Read more at https://blog.expo.io/upcoming-limitations-to-ios-expo-client-8076d01aee1a. We apologize for any inconvenience this may cause you!

# Required format for issues

Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description
When I create a new app with create-react-native-app and then run npm ls I get a list of errors

## Expected Behavior

I would expect no errors on the initial start

## Observed Behavior

Here are the error messages I'm getting:
```
npm ERR! peer dep missing: react-native@^0.51 || ^0.52 || ^0.53 || ^0.54, required by react-native-maps@0.21.0
npm ERR! peer dep missing: react-native-web@*, required by react-native-web-maps@0.1.0
npm ERR! peer dep missing: react@15.5.4, required by react-google-maps@7.3.0
npm ERR! peer dep missing: react-dom@15.5.4, required by react-google-maps@7.3.0
npm ERR! peer dep missing: react@^0.14.6 || ^15.0.0-0, required by react-prop-types-element-of-type@2.2.0
npm ERR! peer dep missing: eslint@^3.17.0 || ^4.0.0, required by eslint-plugin-react-native@3.2.1
npm ERR! missing: mkdirp@0.5.1, required by node-pre-gyp@0.10.0
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: minimatch@3.0.4, required by ignore-walk@3.0.1
npm ERR! missing: brace-expansion@1.1.11, required by minimatch@3.0.4
npm ERR! missing: balanced-match@1.0.0, required by brace-expansion@1.1.11
npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.11
npm ERR! missing: console-control-strings@1.1.0, required by npmlog@4.1.2
npm ERR! missing: inherits@2.0.3, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.1, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.1, required by string_decoder@1.1.1
npm ERR! missing: console-control-strings@1.1.0, required by gauge@2.7.4
npm ERR! missing: string-width@1.0.2, required by gauge@2.7.4
npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
npm ERR! missing: code-point-at@1.1.0, required by string-width@1.0.2
npm ERR! missing: is-fullwidth-code-point@1.0.0, required by string-width@1.0.2
npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
npm ERR! missing: number-is-nan@1.0.1, required by is-fullwidth-code-point@1.0.0
npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
npm ERR! missing: string-width@1.0.2, required by wide-align@1.1.2
npm ERR! missing: inherits@2.0.3, required by glob@7.1.2
npm ERR! missing: minimatch@3.0.4, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
npm ERR! missing: minipass@2.2.4, required by tar@4.4.1
npm ERR! missing: mkdirp@0.5.1, required by tar@4.4.1
npm ERR! missing: safe-buffer@5.1.1, required by tar@4.4.1
npm ERR! missing: yallist@3.0.2, required by tar@4.4.1
npm ERR! missing: minipass@2.2.4, required by fs-minipass@1.2.5
npm ERR! missing: safe-buffer@5.1.1, required by minipass@2.2.4
npm ERR! missing: yallist@3.0.2, required by minipass@2.2.4
npm ERR! missing: minipass@2.2.4, required by minizlib@1.1.0
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:  -- react-native-scripts@1.14.0
* `npm ls react-native`: -- react-native@0.55.4
* `npm ls expo`: -- expo@27.0.2
* `node -v`: v8.10.0
* `npm -v`: 6.0.1
* `yarn --version`: yarn' is not recognized
* `watchman version`: watchman' is not recognized

Also specify:

1. Operating system: Windows 10
2. Phone/emulator/simulator & version: expo

## Reproducible Demo

create-react-native-app test-app

**Comment by pankaja92** [comment]
@rss81 Did you get this fixed ? I ran ` npm list -g --depth 0` to clean up my npm packages. Got some of these NPM errors

**Comment by aleen42** [comment]
It seems the problem of node?

**Comment by rezder** [comment]
I have the similar errors in a total different system arch Linux and not native. npm version 6.2.0. To me it looks like a problem with nmp ls or npm list when the missing package is globally installed.

**Comment by illusive-man** [comment]
I have the same problem. Some research I did led me to `npm dedupe` which is temporarily solves the issue until you install/uninstall any module. Sure you can do it again, but I suppose it's not normal. Looking forward to hearing the news about fixing that.
