### ISSUE TITLE
iOS CLI hangs on "Starting simulator..."

### ISSUE THREAD

**Issue by crobinson42** [react-community/create-react-native-app#672]
## Description

Installed `create-react-native-app` cli on a new OSX machine that has never ran Xcode or react-native projects before.

Creating a new project with `create-react-native-app myProjectName` then attempting to start it on iOS simulator via `yarn ios` hangs at "Starting simulator..." indefinitely with no errors or descriptions.

## Expected Behavior

When attempting to run the project on iOS simulator on OSX the command line script `yarn ios` should not hang without some descriptive information.

## Observed Behavior

I managed to resolve the issue with these steps:

1. run `yarn eject` and chose react-native project structure
2. run `yarn ios`
3. iOS simulator runs as expected

After running an ejected project, I created another demo project using the CRNA cli and then it successfully ran on the simulator.  

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: 1.14
* `npm ls react-native`: 0.55.4
* `npm ls expo`: 27.0.2
* `node -v`: 8.11.2
* `npm -v`: 6.1
* `yarn --version`: 1.6
* `watchman version`: 4.9

Also specify:

1. Operating system: OSX 10.13
2. Phone/emulator/simulator & version: iPhone 8 & iOS 11.3

**Comment by shinux** [comment]
same here

npm -v: 5.7.1
node -v: 8.11.2

**Comment by skcks** [comment]
same here
npm -v: 6.0.1
node -v: v9.9.0

**Comment by skcks** [comment]
set a proxy will fix that problem，maybe stuck at downloading expo.

**Comment by michaelmota** [comment]
Hi,
I had the same problem and after doing this:
`sudo chmod -R 777 ~/.expo/`
It's a problem with the permissions of Expo, try it out hope it works.

**Comment by dpett** [comment]
Same here. Any other fixes?
