### ISSUE TITLE
Jest tests fail to run

### ISSUE THREAD

**Issue by dmzobel** [react-community/create-react-native-app#673]
## Description

Jest tests do not run when I use `npm test`. I have not ejected, and the only test that is currently written is the default `App.test.js`.

## Expected Behavior

The tests should run and currently be passing.

## Observed Behavior

```
 FAIL  ./App.test.js
  ● Test suite failed to run

    /Users/dmzobel/Fullstack/senior-phase/capstone/scavenger-hunt/node_modules/native-base-shoutem-theme/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import connectStyle from "./src/connectStyle";
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import

      13 |
      14 |   render() {
    > 15 |     const { currentUser } = this.props;
      16 |     return (
      17 |       <Fab
      18 |         active={this.state.active}

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:316:17)
      at Object.<anonymous> (node_modules/native-base/dist/src/index.js:1:1115)
      at Object.<anonymous> (components/Toolbar.js:15:19)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        32.449s
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
├── react-native-scripts@1.14.0
└── UNMET PEER DEPENDENCY redux@4.0.0
* `npm ls react-native`:
├─┬ react-native@0.55.3
│ └── UNMET PEER DEPENDENCY eslint@^3.17.0 || ^4.0.0
└── UNMET PEER DEPENDENCY redux@4.0.0
* `npm ls expo`:
├─┬ expo@27.0.1
│ └── UNMET PEER DEPENDENCY react-native@^0.51 || ^0.52 || ^0.53 || ^0.54
└── UNMET PEER DEPENDENCY redux@4.0.0
* `node -v`: v7.7.4
* `npm -v`: 4.1.2

## Reproducible Demo

Here are the relevant lines from my `package.json`. I tried installing `babel-jest` and `babel-preset-env`, which haven't worked.

```
{
  "devDependencies": {
    "jest-expo": "~27.0.0",
  },
  "scripts": {
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "babel-jest": "^23.0.1",
    "babel-preset-env": "^1.7.0",
  }
}
```

And here is my `.babelrc`:

```
{
  "presets": ["babel-preset-expo", "react-native", "env"],
  "env": {
    "development": {
      "plugins": ["transform-react-jsx-source"]
    },
    "test": {
      "presets": ["react-native"]
    }
  }
}
```

**Comment by gkemp94** [comment]
Also having this issue, I have tried everything, and nothing seems to be fixing it.

**Comment by nhayfield** [comment]
i also have this issue
