### ISSUE TITLE
App is faster from expo than local. Is normal?

### ISSUE THREAD

**Issue by gersonmontenegro** [react-community/create-react-native-app#677]
I wrote this [snack](https://snack.expo.io/@gersonmontenegro/select-favorite-example-with-drawer) in local and it's go slow on my device (android or iOS), so I put it online with Expo, and the same app goes faster from this online tool. Is normal this behavior?

**Comment by tcdavis** [comment]
Do you mean the app takes a while before it starts running on the phone, or the app is slow once you get it running?
The first is expected, snack uses a different process to get apps onto you phone than the local development flow and we've put a lot of effort into making it as fast as possible :)

**Comment by gersonmontenegro** [comment]
No, I mean, the is slow once starting to running

**Comment by tcdavis** [comment]
I see.  No, I would expect roughly the same performance in snack and locally.  Do you have the debugger attached when doing your local development?

**Comment by gersonmontenegro** [comment]
Sorry, I don't know what's that :(

**Comment by tcdavis** [comment]
This bit https://docs.expo.io/versions/v27.0.0/workflow/debugging#debugging-javascript can affect your performance
