### ISSUE TITLE
Please upgrade xdl to support custom ports

### ISSUE THREAD

**Issue by yanni4night** [react-community/create-react-native-app#678]
## Description

The packager use 19000&19001 ports by default which are not reachable on Mac OS.

**Please upgrade `xdl` to _50.x_** ASAP

## Expected Behavior

Developers can define custom packaging port by configuring *app.json*:

```json
{
  "expo": {
    "sdkVersion": "27.0.0",
    "packagerOpts": {
        "port": 8082
    }
  }
}
```

## Observed Behavior

19000 can be replaced by configuring an *.exprc* file:

```json
{
    "manifestPort": 8080
}
```
But 19001 cannot, configuring *app.json* is not useful right now.

> xdl >= 50.1.0 already fix that

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: 1.14.0
* `npm ls react-native`: 0.55.4
* `npm ls expo`: 27.0.2
* `node -v`: v8.11.2
* `npm -v`: 5.6.0
* `yarn --version`:1.5.1
* `watchman version`: 4.7.0

Also specify:

1. Operating system: macOS High Sierra
2. Phone/emulator/simulator & version: iOS 11

**Comment by brentvatne** [comment]
context on what it takes to update xdl: https://github.com/react-community/create-react-native-app/pull/664
