### ISSUE TITLE
react-native link not working..

### ISSUE THREAD

**Issue by kyejune** [react-community/create-react-native-app#679]
## Description

"react-native link" not working...
only scaned node_modules directory. and.... nothing.........

## Expected Behavior

react-native-video liking

## Observed Behavior
```
Error: TypeError: TypeError: undefined is not an object (evaluating '_reactNative.NativeModules.UIManager.RCTVideo.Con
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
└── (empty)
* `npm ls react-native`:
└── UNMET DEPENDENCY react-native@0.55.4 
* `npm ls expo`:
└── UNMET DEPENDENCY expo@27.0.2 
* `node -v`: v8.7.0
* `npm -v`: 5.7.1
* `yarn --version`: 1.2.1
* `watchman version`:{
    "version": "4.9.0"
}

Also specify:

1. Operating system: Mac OS High Sierra
2. Phone/emulator/simulator & version:iPhone X Simulator

## Reproducible Demo

create-react-native-app test && cd test
yarn add react-native-video
react-native link

using <Video/> and run App

**Comment by maximten** [comment]
Same issue.  

On a fresh project, I did
``` yarn add react-native-linear-gradient```   
and 
``` react-native link ```

Got only 
``` Scanning folders for symlinks in ...```


Environment:
```
react-native-cli: 2.0.1
react-native: 0.55.4
yarn: 1.6.0
node: 8.11.2
npm: 5.6.0
```
