### ISSUE TITLE
Eject Hangs

### ISSUE THREAD

**Issue by firrae** [react-community/create-react-native-app#682]
# Required format for issues

Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

When ejecting CRNA app it simply hangs and does nothing for hours until manually stopped.

## Expected Behavior

I would expect it to eject from CRNA.

## Observed Behavior

I had this issue on a slightly further along project so I just went back and created a new CRNA app to test and found I get this issue even on a fresh app with nothing else in it.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: C:\Users\stlam
`-- (empty)
* `npm ls react-native`: C:\Users\stlam
`-- (empty)
* `npm ls expo`: C:\Users\stlam
`-- (empty)
* `node -v`: v10.4.1
* `npm -v`: 6.1.0
* `yarn --version`: Not Installed
* `watchman version`: Windows beta was wonky last time I tried.

Also specify:

1. Operating system: Windows 10 (latest updates)
2. Phone/emulator/simulator & version: N/A

## Reproducible Demo

1. Create new CRNA
2. `npm run eject`
3. Select either regular or ExpoKit
4. Sit and watch it run infinetly into the ether with no errors, no returns, and no file changes.

Please let me know what else you might need to know. This is a hard stopper for me at this point.

**Comment by firrae** [comment]
Also to note. I have rebooted and updated this computer twice since this issue was first noticed.

**Comment by firrae** [comment]
After running an `npm update` it seems to work now. Not sure what actually changed to make it happen though.

**Comment by asd-ftw** [comment]
I'm facing the same issue and **npm update** doesn't seem to fix it. :(

**Comment by Darker** [comment]
Doesn't fix for me either.

**Comment by Aid19801** [comment]
Also happening for me.
