### ISSUE TITLE
Can't do react-native link with CRNA

### ISSUE THREAD

**Issue by fhernandezj** [react-community/create-react-native-app#691]
After I do 
`npm install --save react-navigation
npm install native-base --save`
when I type
`react-native link`
I get this error
`rnpm-install info Linking assets to ios project
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'pbxprojPath' of null`
Apparently it doesn't work when you create a project with `create-react-native-app` but it does work when you use `react-native init`.

**Comment by brentvatne** [comment]
you need to eject to link native dependencies, this is documented in the project readme
