### ISSUE TITLE
Cannot open in Expo

### ISSUE THREAD

**Issue by ppwillp** [react-community/create-react-native-app#692]
## Description

After sending the URL to my phone to open within the Expo app, it fails to open.

## Expected Behavior

I expected the app to open within Expo

## Observed Behavior

It appears to time out

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
There was a problem loading the requested app. It looks like you may be using a LAN URL. Make sure your device is on the same network as the server or try using a tunnel.

exp://192.168.0.3:19000

The request timed out
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@1.14.0
* `npm ls react-native`: react-native@0.55.4
* `npm ls expo`: expo@27.1.0
* `node -v`: v6.11.5
* `npm -v`: 6.1.0
* `yarn --version`: NA
* `watchman version`: NA

Also specify:

1. Operating system: WIndows PC
2. Phone/emulator/simulator & version: iPhone 7+

**Comment by ppwillp** [comment]
after running ipconfig:

Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . :
   IPv6 Address. . . . . . . . . . . : 2600:8804:180:6e00:ed8d:9303:839e:a8bc
   Temporary IPv6 Address. . . . . . : 2600:8804:180:6e00:fcd0:e14c:44d1:b3b8
   Link-local IPv6 Address . . . . . : fe80::ed8d:9303:839e:a8bc%13
   IPv4 Address. . . . . . . . . . . : 192.168.0.3
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.0.1

**Comment by RuruCon** [comment]
Same after I updated the expo app.

**Comment by raminghaderi** [comment]
What you need to do is:
Go to cmd and type "ipconfig" and see which network is using the ip shown in your expo app. if it's not your router IP address then what you need to do is to go and disable the network which expo is using:
Control Panel -> Network and Internet -> Network Connections
and here disable the network that expo is using. (it should be a LAN network connection)
try to run "npm start" again, it should be working now.
If my solution is not clear feel free to ask me.

**Comment by animator** [comment]
Please go through this solution and see if it works:
https://github.com/react-community/create-react-native-app/issues/264
