### ISSUE TITLE
Can't start application

### ISSUE THREAD

**Issue by with-a-k** [react-community/create-react-native-app#695]
## Description

App won't start when running `npm start`.

## Expected Behavior

App would start.

## Observed Behavior

What actually happened when you performed the above actions?

A `Starting packager...` message was displayed, followed by five minutes of nothing happening at all, at which time I interrupted the process.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: 1.14.0
* `npm ls react-native`: 0.55.4
* `npm ls expo`: 28.0.0
* `node -v`: 8.9.1
* `npm -v`: 6.1.0
* `yarn --version`: N/A
* `watchman version`: N/A

Also specify:

1. Operating system: Windows 10
2. Phone/emulator/simulator & version: N/A

## Reproducible Demo

This was a new app; reproducing should be no trouble.

**Comment by ratskin** [comment]
Did you try `yarn start`?

**Comment by sscotth** [comment]
Your versions are wrong. A brand new app as of today should give you:

- `npm ls react-native-scripts`: 1.14.0
- `npm ls react-native`: 0.55.4
- `npm ls expo`: 27.1.0

https://github.com/react-community/create-react-native-app/blob/4881f5d5051ad2704d18febe3688dba34b52916f/react-native-scripts/src/scripts/init.js

https://github.com/react-community/create-react-native-app/blob/master/VERSIONS.md
