### ISSUE TITLE
stuck on "Starting packager..."

### ISSUE THREAD

**Issue by dillon** [react-community/create-react-native-app#697]
## Description

When I start a new project and run `yarn run ios` it opens the simulator. But as soon as the second or third time I try to use `yarn run ios` again while working on the app it hangs on `Starting packager...` for over 5 minutes.

## Expected Behavior

Run the ios simulator (again)

## Observed Behavior

I've started over 4 times now and it always has a problem at a different, seemingly random stage in me building the app when I try to use `yarn run ios`. It works and works and works and then eventually it stops working and I have to start over again. IT doesn't seem to be a consistant point in which things stop working. I _was_ using npm to install and run processes but now I'm using yarn. Both have the same issue. I'm following instructions in [this guide](https://medium.com/react-native-training/bitcoin-ripple-ethereum-price-checker-with-react-native-redux-e9d076037092) by the way, both as-is and with yarn instead of npm. Even when I revert to my git history when it was working, and `rm -rf node_modules && yarn install` / `npm install` the problem persists

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@1.14.0 
* `npm ls react-native`: react-native@0.55.4 
* `npm ls expo`: expo@27.1.0
* `node -v`: v10.4.1
* `npm -v`: 6.1.0
* `yarn --version`: 1.7.0
* `watchman version`: "version": "4.9.0"

Also specify:

1. Operating system: macOS High Sierra 10.13.5
2. Phone/emulator/simulator & version: Version 10.0 (SimulatorApp-851.2 CoreSimulator-518.22)

## Reproducible Demo

This is reproducable by following the steps in the guide linked above.

**Comment by dpett** [comment]
I've tried `rm -rf node_modules npm install`,
`echo 999999 | sudo tee -a /proc/sys/fs/inotify/max_user_watches && echo 999999 | sudo tee -a /proc/sys/fs/inotify/max_queued_events && echo 999999 | sudo tee -a /proc/sys/fs/inotify/max_user_instances && echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`,
`watchman watch-del-all && watchman shutdown-server`,

**Comment by trentbrooks** [comment]
Same issue on mac. This 'starting packager...' problem spans many issues on github - i've tried every fix listed, but still not working.

**Comment by dpett** [comment]
@trentbrooks I ended up giving up and using [Expo's XDE](https://docs.expo.io/versions/latest/introduction/installation.html) And didn't have any problems.

**Comment by lukeliasi** [comment]
I created a fresh project with crna and noticed there were security vulnerabilities from the npm audit so I ran` npm audit fix`. When I try and run the app I get stuck on starting packager. 

If I do not run the `npm audit fix` command it works fine.

**Comment by yxh10** [comment]
This happened to me too. But it happened after I tried to run 
`npm install antd-mobile-rn --save`

**Comment by yxh10** [comment]
I managed to find the solution. 

There could be multiple reasons. For the most recent version of react-native, what you might need to do is just press 'q', it displays the QR code, but it won't display the QR code automatically.

After you use the expo app scan the qr code, it should start to bundle the scripts and load to your phone.

If not, you have might another issue which is caused by incompatibility among, React-Native and Expo. If you are using Expo 27, you should use react-native 0.55.

There is a complete matrix here, https://github.com/react-community/create-react-native-app/blob/master/VERSIONS.md

Anyone who face problem after running 
`npm audit fix`, that is because it will try to install react-native 0.56 which doesn't work with Expo 27 well.

**Comment by cngodles** [comment]
Still happens to me once I do an audit fix. This is on Windows using the Expo XDE tool. react-native 0.55.2 works just fine, but bumping to 0.56.0 seems to keep it from starting.

**Comment by cngodles** [comment]
#674 has a fix I believe.

**Comment by yxh10** [comment]
@cngodles , hm... I think you read my answer too fast. I was saying running 
`npm audit fix` **will cause a problem**, and the reason was incompatibility, and the link I put there shows the matrix about what version works with what.

**Comment by cngodles** [comment]
@yxh10 I had ran a npm audit fix, and then I was not able to get past the packager line until I applied that fix. Its something to do with RN 0.56.0. Either way, I end up having to apply that fix often until that pull request gets placed into the latest code.

**Comment by ooow** [comment]
I did:
```
- npm cache clean --force
- rm -rf node_modules
- npm install
- npm run ios (or another key, what do you have for entrypoint) p.s. needs waiting for first start ~1 minutes
```
And everything work fine.
I hope that helps others 👍

**Comment by cngodles** [comment]
And this is why its failing:

![image](https://user-images.githubusercontent.com/5685764/44583006-876cd600-a771-11e8-8ffe-45ad3ca7ea9a.png)

The newest version wasn't looking for the Metro Bundler. You can go into the file, which the pull request mentions and write the fix yourself if you want.

`react-native-scripts/src/util/packager.js`

https://github.com/react-community/create-react-native-app/pull/674/commits/684a6414b35b29310c9eda6d72a75b5211759fe8

**Comment by turnerguo** [comment]
I can start the Simulator but nothing happened in the Simulator, no app started, no errors, no messages...

**Comment by turnerguo** [comment]
Finally, I found the problem with my simulator, it's not installed the Expo automatically, because of the GWF in china...
So, follow the Expo installation guide "https://docs.expo.io/versions/v29.0.0/introduction/installation#ios-simulator", and install the Expo client manually to solve this issue.
Hopes it helps someone.

**Comment by Hypothesis-github** [comment]
I have the same issue and I literally have tried all above + all other topics. is there a log on this thing ?

**Comment by tweeklabs-isaac** [comment]
I had a problem with the npm audit fix, on the project where I did that it's stuck on starting package manager. Then I tried creating a new project w/o doing the npm audit fix. and now its working
