### ISSUE TITLE
app:bundleReleaseJsandAssets stuck at this and always gives an error for every build

### ISSUE THREAD

**Issue by jamils82** [react-community/create-react-native-app#699]
I have tried many solutions but it always give the same problem on every project. I am stuck at this for more then 3 days. The possible solutions that i have tried are as follow
1: ./gradlew assembleRelease -x bundleReleaseJsAndAssets
2: { "presets": ["react-native"], "ignore": ["index.ios.js","index.android.js"] }
3: gradlew assembleRelease --console plain

Tried all these but no solution found for generating.
![capture](https://user-images.githubusercontent.com/20075485/42230223-d774a95e-7f01-11e8-91ea-4957fa9f7eea.PNG)

**Comment by aspcsharp9** [comment]
I also have this problem! 
![reactproblem](https://user-images.githubusercontent.com/15157982/42535028-a6e799f8-848e-11e8-9a0d-cdee96ba2a60.jpg)

I'm try clear cache and other solution but not working.

**Comment by anp** [comment]
Hi! Could you provide more information about your project here? What have you tried so far to resolve this?

**Comment by aspcsharp9** [comment]
> Hi! Could you provide more information about your project here? What have you tried so far to resolve this?

Hi, anp!  I'm try 
`npm start -- -reset-cache  `
`react-native-git-upgrade`
`react-native upgrade`

**Comment by happy32x** [comment]
same problem here. i get stuck since 1 week

**Comment by happy32x** [comment]
**How to reproduce the problem ?**
1) react-native init <project_name> 
2) cd <project_name>
3) react-native run-android --deviceId H80xxx

**Problem**
After step 3 i get 

:app:bundleReleaseJsAndAssets
Scanning folders for symlinks in X:\xxxxxxxxx\node_modules (56ms)
Scanning folders for symlinks in X:\xxxxxxxxx\node_modules (63ms)
warning: the transform cache was reset.
Loading dependency graph, done.

Unable to resolve module `AccessibilityInfo` from `X:\xxxxxxxxx\node_modules\react-native\Libraries\react-native\react-native-implementation.js`: Module `AccessibilityInfo` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.

:app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

**note**
- The physical device is connected
- OS: windows 8.1
- android Studio is update
- nodeJS is update
- python2 is update


So what's wrong ?
