### ISSUE TITLE
Eject stops on the first step

### ISSUE THREAD

**Issue by MinskLeo** [react-community/create-react-native-app#700]
# Problem with ejecting

## Description

Execution of
`npm run eject`
OR
`yarn run eject`
stops on first step. 

## Expected Behavior

It should correctly ask me all questions, but it asks only first and then stops.

## Observed Behavior

There is no any errors... There is no nothing!
Console just ask me first question
`How would you like to eject from create-react-native-app? React Native: I'd like a regular React Native project.`
and then...
![image](https://user-images.githubusercontent.com/30799765/42347051-4e9de494-80ad-11e8-9a22-4296277d2c36.png)
and then nothing...

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
![image](https://user-images.githubusercontent.com/30799765/42347140-9c278a6c-80ad-11e8-920b-d224fd78cf39.png)
* `npm ls react-native`:
![image](https://user-images.githubusercontent.com/30799765/42347126-91c36eb0-80ad-11e8-8b8e-35a72d1b500b.png)
* `npm ls expo`:
![image](https://user-images.githubusercontent.com/30799765/42347114-87d0658e-80ad-11e8-9b0b-62c754b3cad6.png)
* `node -v`:
![image](https://user-images.githubusercontent.com/30799765/42347403-7ed4eb3e-80ae-11e8-8150-38b19308d984.png)
* `npm -v`:
![image](https://user-images.githubusercontent.com/30799765/42347409-85a020d2-80ae-11e8-8b87-d2ce9ddd7d8a.png)
* `yarn --version`:
![image](https://user-images.githubusercontent.com/30799765/42347422-8bb87d52-80ae-11e8-91be-e1c50bb72908.png)
* `watchman version`:
There is no watchman on my PC.
![image](https://user-images.githubusercontent.com/30799765/42347485-b4240ae0-80ae-11e8-81a4-c66b501f2004.png)

Also specify:

1. Operating system:
Windows 10 Pro
2. Phone/emulator/simulator & version:
I'm using real phone Samsung S5 with original Android 6.0.1

## Reproducible Demo

No need special demo: I get this bug every time, when I create new project from
`create-react-native-app any-name`
and then use
`npm run eject`
OR
`yarn run eject`

**Comment by ansarikhurshid786** [comment]
I am also facing same problem. Now I am planning to install react-native-cli package. 

it is very though to setup.

**Comment by asd-ftw** [comment]
Same Problem. can anyone help with this?

**Comment by asd-ftw** [comment]
Worked when I changed the node version from Current to the LTS version.

**Comment by Darker** [comment]
Same issue here. @asd-ftw  How/where did you change the Node version? Do you mean re-install node (not possible for me atm)?
