### ISSUE TITLE
Question - flow

### ISSUE THREAD

**Issue by daniele-zurico** [react-community/create-react-native-app#701]
Why flowconfig has been removed from the default configuration? the new version of react-native should support better flow.
How to configure it properly? Which version? 
I think that most of the people have these questions
a working exaple of the .flowconfig?

**Comment by hally9k** [comment]
@daniele-zurico - I agree it does seem weird that `react-native init` supports flow out of the box now but this repo doesn't. I unfortunately don't have the flow knowledge to jump on this one, a little help anyone?

**Comment by daniele-zurico** [comment]
Hi @hally9k I figure out to configure it... have a look on the post I wrote: https://www.dzurico.com/react-native-and-flow/

**Comment by farskid** [comment]
@daniele-zurico Please close the issue if it's solved 👍

**Comment by daniele-zurico** [comment]
@farskid it's for me... I was leaving there for doc honestly... but I can close

**Comment by farskid** [comment]
@daniele-zurico It actually helped me a few seconds ago, thanks for the great post 👍 I just think that if it's opened, people might think that it's not solved :) But that's my imagination, can be false :)
