### ISSUE TITLE
Error when starting react native app

### ISSUE THREAD

**Issue by ablionbiplob** [react-community/create-react-native-app#702]
I am using 
Nodejs version - v10.6.0
npm version - 6.1.0

sh: 1: react-native-scripts: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! my_app@0.1.0 start: `react-native-scripts start`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the my_app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Please help to rectify...

**Comment by anp** [comment]
Hi! It looks like you have some issues with filesystem permissions on your computer. Googling for the error messages suggests a few things you can try: https://www.google.com/search?q=permission+denied+elifecycle+npm. If you're still having issues with this after resolving the filesystem issues, please post back! Thanks.

**Comment by ablionbiplob** [comment]
Thank you.
