### ISSUE TITLE
Unexpected identifier

### ISSUE THREAD

**Issue by mdshowrov** [react-community/create-react-native-app#703]
![capture](https://user-images.githubusercontent.com/29330421/42507160-fa7ac596-8465-11e8-840e-157a6d651f7a.PNG)
gettin this  error

**Comment by anp** [comment]
Hi! Please follow the issue template in the future so we can know how to reproduce the issue you're facing. Please feel free to post the info here and I'll reopen, thanks!

For what it's worth, I would recommend trying to delete and reinstall node_modules.

**Comment by MateusGabi** [comment]
Hello, follow the issue template. This error is not an error related to the create-react-native-apps. It's a syntactic error.
