### ISSUE TITLE
Try the version 0.56, error

### ISSUE THREAD

**Issue by seasolzombie** [react-community/create-react-native-app#704]
OS: windows10
npm: 6.1
node: 8.93
react-native: 0.56
I do according to the docs between, but simulator and cli show error.
https://facebook.github.io/react-native/docs/getting-started.html
The error is strange. What's the problem? Here is the screenshot for the error. This error only happends in version 0.56
![_20180712035620](https://user-images.githubusercontent.com/9005737/42596372-fb8506f4-8587-11e8-97dd-370d136db5cc.png)

**Comment by seasolzombie** [comment]
I have tried to clear the npm cache and reinstall the packages, the same problem

**Comment by seasolzombie** [comment]
react-native init ProjectName --version 0.55.4
react-native run-android

It works。So it is the version 0.56 that make the error.

**Comment by ihsankatmer** [comment]
I have same problem

**Comment by eahang** [comment]
Downgrade to 0.55.* instead. I also got error in my window 10 environment.

**Comment by Pratikkakkad** [comment]
It's mentioned on the ticket itself, for some of them only downgrading worked. So create a new project with .55 version.

Create a project with .55 version.

react-native init --version="react-native@version" project_name

Example:- react-native init --version="react-native@0.55.0" myapp.
