### ISSUE TITLE
So hard to just create and start native application

### ISSUE THREAD

**Issue by arsensaruhanyan2611** [react-community/create-react-native-app#706]
## Description

I have so much problems with just creating a SIMPLE application. I tried to use React Native/React (I know, this is create-app repo, btw I don't want to create multiple topics in different repos, so..) on Windows 10 (why not) and Ubuntu 16.04.

## Expected Behavior

I just installed node.js and then installed react-native's packages to start develop apps on React. On linux I got so much troubles that I'm just confused.

## Observed Behavior

Well, when I tried to use it on Windows I just tried to use ``npm start`` and it always stuck on Starting Packager. I found some ways to solve it, but they were for Linux/macOS. So, when I tried to use it on Ubuntu I got even more errors. First of all, ``npm start`` just didn't want to execute with messages that I have to use ``sudo sysctl -w fs.inotify.max_user_instances=1024`` and something else (I forgot, sorry). Okay, when I did that I had to, I got endless "Starting Packager" like on Windows. Tried to find a solution for this problem and as someone mentioned here, I need to 
``sudo sysctl -w fs.inotify.max_user_watches=10000``
Well, after that I got my first problem with ``sudo sysctl -w fs.inotify.max_user_instances=1024``. Just like a loop .0.
Okay, then I installed watchman (0.4.7 because of 0.4.9 gave me an error after ``./configure`` like I dont have this file). These problems with sysctl are ended, but I GOT LOOPED "Starting Packager". I just want to ask you - why? Why it is so hard to use React/Native on the fresh OS without any extra programs which could mess it up inside of it? I think that logs are not needed, because the problem did not occur only with me alone and not so rarely as we would like. You can just find it by similar commands in google if you say 'Endless Starting Packager React Native Linux' or 'Unable to start server React Native'.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@1.14.0 
* `npm ls react-native`: react-native@0.56.0
* `npm ls expo`: expo@28.0.0
* `node -v`: v10.6.0 (also, I checked out LTS version, but I had same problems)
* `npm -v`: 6.1.0
* `yarn --version`: not installed
* `watchman version`: 4.7.0

Also specify:

1. Operating system: Ubuntu 16.04 LTS, Linux x64
2. Phone/emulator/simulator & version: Android 8.0 

## Note
After that I don't even know if I want to continue it.

**Comment by Jturpijn** [comment]
I wholeheartedly agree with you. I stuck to Windows after facing the 'starting packager' loop but was faced with even more errors and now I'm just stuck with [this error](https://github.com/react-community/create-react-native-app/issues/401) and I don't know how to continue. I've tried a lot and at this point, it's just becoming more and more of a drag.

**Comment by arsensaruhanyan2611** [comment]
@Jturpijn the same problem. I just stuck to this problem with 'development server' and that's it. And the whole thing is that nobody cares.

**Comment by Jturpijn** [comment]
@arsensaruhanyan2611 I've tried literally everything, deleting node modules, using example code, resetting IP's environments and emulators. I've even downloaded XDE which doesn't really do anything. I'm gonna try the exp cli and then I'm going to look for something else... any recommendations?

**Comment by arsensaruhanyan2611** [comment]
I don't really know. I had same problems as you had, so I've tried everything too. Well, I replaced my system twice to fix this. But even after that, I can only use crna-template. But it's not enough to make normal application. So I have to use ``react-native init``.

The only thing I know is that ``react-native init`` doesn't work with Expo. So, I just started to use Flutter. There ain't so many libraries (Like even i18n at the moment), but it's much easier and I think it'll develop. I guess you can do that too (come to the light side), but if you're not gonna do this then please tell me about how to fix these problems, if you'll find the solution. I'd be thankful.

Well, I'm really sorry, but that's all I can do. I hope that at least you will find a solution, because as you correctly noticed, no one solution in existing issues does not work.

**Comment by arsensaruhanyan2611** [comment]
Uhm, I'm testing different platforms for now (like Xamarin, React Native and Flutter). I like Flutter because it's easier and faster in development (especially compared to Android-native development), but it's really has no support for so many things, thus I wanted to use React. Btw, I'll try your solution, thanks!

**Comment by Jturpijn** [comment]
I hope everything worked out! Could you close this issue? You can create a new one when running into a new problem.
