### ISSUE TITLE
Expo doesn't work from real devices

### ISSUE THREAD

**Issue by SilencerWeb** [react-community/create-react-native-app#712]
Expo doesn't work from real devices, but it works fine using expo XDE and in emulators.

Here are errors:
iOS:
![image](https://user-images.githubusercontent.com/20713191/43032821-ef6dcbaa-8cd8-11e8-9c55-f62067a26525.png)
Android (I have no idea why it is trying to connect to 19001 port when the application is running on 19000):
![image](https://user-images.githubusercontent.com/20713191/43032823-f39fed3e-8cd8-11e8-8c10-74395d89c9fc.png)
![image](https://user-images.githubusercontent.com/20713191/43032825-f8979544-8cd8-11e8-9915-1fcf00d6bb4b.png)

node - v10.4.1
expo - 27.0.1
sdkVersion - 27.0.0
react-native-scripts - 1.14.0

**Comment by wagnerjt** [comment]
Also getting the same error. Started within the past 6 hours

**Comment by wagnerjt** [comment]
After messing around for like 7 hours, updating node to the latest version, and using my android device 4.4, expo seems to be working. However, it is still not working for my android 7.0 device

**Comment by MateusGabi** [comment]
Do your phone and notebook at the same network/modem?
