### ISSUE TITLE
Can i edit android:launchMode="singleTask" with Expo ?

### ISSUE THREAD

**Issue by osvaldoalvaradodev** [react-community/create-react-native-app#715]
Hi.

I search this issue, but i dont find the solution.

I need edit android manifest or equivalent in expo, with this:
android:launchMode="singleTask"

Is posible edit this in expo ? in android project native i edit androidmanifest.xml

But in react native with expo , i dont have manifest.xml 

Help please :(

**Comment by fabiancarlos** [comment]
If you are trying to handle deeplinks or notifications, do this:
Hi guys, wrap yours deeplink handle on a `InteractionManager` like so:
```
componentDidMount() {
  InteractionManager.runAfterInteractions(() => {
     this._addLinkingListener();
  });
}
```
Dont forget to import `InteractionManager` on react-native.

**Comment by osvaldoalvaradodev** [comment]
Mi problem is in android devices.

I change from my reactApp to other app and when i run again reactApp this restart...
