### ISSUE TITLE
Network Response Timedout. Java.SocketTimedOutException,Could not load the appliction using Qr scanner or by opening Android Device

### ISSUE THREAD

**Issue by varunreddycs** [react-community/create-react-native-app#716]
## Description

Could not load the appliction using Qr scanner or by opening Android Device
## Expected Behavior

Text on the screen of an application
## Observed Behavior
Note that I did change the React_Native_Packager_Hostname to the ipv4 address whenever I did run the Application and as per the requirements the mobile and laptop are connected to either same wifi router or the mobile hotspot
**When the application is run on the wifi**
![wifi_timedout](https://user-images.githubusercontent.com/31946590/43128982-f5befbc6-8f50-11e8-8825-fb2f26f32d0b.jpg)

![wifi_timedout_exception](https://user-images.githubusercontent.com/31946590/43129080-364bfb94-8f51-11e8-8137-eba84d8609d8.jpg)

But when I tried to connect the port using localhost (this is not mentioned in docs though).

![localhost_response](https://user-images.githubusercontent.com/31946590/43129199-7d96c63c-8f51-11e8-80e0-b1d5c5992737.jpg)

**When my wifi is connected to mobile Hotspot**

![mobile_timedout](https://user-images.githubusercontent.com/31946590/43129464-188729d4-8f52-11e8-99f5-eaa7b0e94475.jpg)

When I did run the LocalHost 
![localhost_response](https://user-images.githubusercontent.com/31946590/43129780-c40acab8-8f52-11e8-9768-72f5b0b5c3fe.jpg)

It is unusual that  I got a response from LocalHost:19000 but not (customip):19000

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@1.14.0
* `npm ls react-native`:react-native@0.55.4
* `npm ls expo`:expo@27.1.0
* `node -v`:v8.9.0
* `npm -v`:6.0.0-next.0

Also specify:

1. Operating system: Windows 10
2. Phone/emulator/simulator & version:Android 8.1.0

## Reproducible Demo
$ npm install -g create-react-native-app
$ create-react-native-app my-app
$ cd my-app/
$ npm start
set  REACT_NATIVE_PACKAGER_HOSTNAME=(customop;which is ipv4 address when connected to a Network)

**Comment by kennychangca** [comment]
I am running to the same issue as well

**Comment by kennychangca** [comment]
@varunreddycs  Could be that windows firewall is blocking the port. Try disabling windows firewall.
