### ISSUE TITLE
Running URL using port 80!

### ISSUE THREAD

**Issue by navidnabavi** [react-community/create-react-native-app#720]
My running URL using port 80!  exp://192.168.1.119:80. It is happening in refresh projects. Can't connect to the server.

**Comment by navidnabavi** [comment]
I Think it happens when server is not ready yet.

**Comment by MateusGabi** [comment]
Hello, could you use the [issue template](https://github.com/react-community/create-react-native-app/blob/master/ISSUE_TEMPLATE.md)?
