### ISSUE TITLE
The development server returned response error code: 500

### ISSUE THREAD

**Issue by hdamis** [react-community/create-react-native-app#721]
Hi,
I am new to react-native and I installed all required program as https://facebook.github.io/react-native/docs/getting-started.html
but when I create a new project as the follwoing:

react-native init AwesomeProject
cd AwesomeProject
react-native run-android
I got an error as the below image
<img width="848" alt="react-native" src="https://user-images.githubusercontent.com/3616900/43369850-a7a02862-937d-11e8-8cee-446a69d2d7fb.PNG">

windows 10
jdk8
node version v10.7.0
react-native-cli: 2.0.1

I tried everything recommended on internet, nothing is working. I am totally stuck on it. Please help.

**Comment by lemontizz** [comment]
same problem

**Comment by hdamis** [comment]
it is a bug in react-native version 56.0
so resolve this problem you have to edit package.josn and change the version of react native as below:
"react-native": "^0.55.4",
and in android\app\build.gradle add 
dependencies {
…
... 
   compile ("com.facebook.react:react-native:0.55.4") { force = true }
}
Hope this will help you ….

**Comment by bradrar** [comment]
@hdamis I tried your solution but it doesn;t work. 

here is what it says after I run react-native run-android

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.facebook.react:react-native:0.55.4.
     Required by:
         project :app
   > Could not find com.facebook.react:react-native:0.55.4.
     Required by:
         project :app

**Comment by isaacghorbani** [comment]
edite app.json to solve this problem:
{
  "expo": {
    "sdkVersion": "23.0.0" // your device android sdk ver!
  }
}

**Comment by NicWickman** [comment]
I'm having the same issue, and also the same issue following hdamis' advice. Isaac, your suggestion does not work for me.

**Comment by bradrar** [comment]
Isaac,  still not working. but thanks for commenting.

**Comment by NicWickman** [comment]
bradrar, I am on to new errors now but I just resolved this particular 500 error in the following way:

delete node_modules folder
clean npm cache
change react-native version to 0.55.4 in packages.json
npm install

**Comment by hermanomark** [comment]
I'm having the same issue tride solution above still not working!

**Comment by NicWickman** [comment]
This looks like an ongoing issue. I'm avoiding it by now for running a
react project initialized on 0.55.4

**Comment by qweasdzxc23** [comment]
hello , fast solution is :

**Comment by jerrychong25** [comment]
@hermanomark methods works for me, thanks a lot!

**Comment by MuhammadUsman786786** [comment]
@qweasdzxc23  works for me, Thanks alot!

**Comment by osnersanchez** [comment]
I had the same problem, and solve it with the suggested by @qweasdzxc23, but ¿I would like to know why this problem occurs and what is the reason for this solution?

**Comment by ZubairAkber** [comment]
Thanks @qweasdzxc23 @hermanomark @NicWickman your solution really works

**Comment by venkataramanaj** [comment]
I am also getting same issue, I tried many ways, but didn't work

**Comment by MrCEO63** [comment]
But why should we do all this.. can't the react guy fix this issues from their end also react v 56.0 is having issues too

**Comment by kevinzhangftw** [comment]
lol, just tried build this on 0.57 still fails

**Comment by mrkmg** [comment]
Also getting this error with 0.57

**Comment by Neck1T** [comment]
@phprad , @kevinzhangftw , @mrkmg 
I don't know, Have You found the solution already, but try this if You still need it
https://github.com/react-community/create-react-native-app/issues/401

It's work for me

**Comment by juliocmalvares** [comment]
I tried all the ways you said. The error still persists.

**Comment by J0nats** [comment]
> I tried all the ways you said. The error still persists.

@juliocmalvares if all the solutions didn't work for you. You can initialized a new project with a specific version =>  $ react-native init newproject --version react-native@0.55.4

**Comment by juliocmalvares** [comment]
@J0nats thks, bro !
