### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by stevefan1999** [react-community/create-react-native-app#722]
Expo SDK 29 has come out but CRNA hasn't been updated to reflect this SDK update, although it's an in-place update, I'm doubting at the longevity of CRNA that there haven't been any commits for the last 2 months.

**Comment by mfgabriel92** [comment]
Maybe. I'm having problems with CRNA being stuck at the damn "starting packager" message and not a single solution I found here solved for me. Maybe RN is also finding its end. It will if the so-called "starter package" has such difficulties.

**Comment by brentvatne** [comment]
hi! we are going to be rolling out a re-write of much of the internals of this shortly, until then I suggest using `exp` (`npm i -g exp`). the project is not dead
