### ISSUE TITLE
Expo Packager | Android Expo app can't access port 19001

### ISSUE THREAD

**Issue by pcgeek86** [react-community/create-react-native-app#724]
## Description

I'm trying to run the basic project template. However, the computer I'm using has a company-managed firewall that blocks access to TCP port 19001. I need the Expo Packager to run on a custom port, besides 19001. How can I configure this?

## Expected Behavior

Follow getting started tutorial. Project is accessible from Expo Android app, per the directions.

## Observed Behavior

Expo app was unable to connect to the packager port, because it's not user-configurable.

## Environment

* MacBook Pro
* MacOS High Sierra
* LG G6 Android device

**Comment by MateusGabi** [comment]
It happened to me just one time. I resolved closing Expo, closing packager, running `npm install`and `npm start`.
