### ISSUE TITLE
Eject command fails on Expo login/account creation

### ISSUE THREAD

**Issue by wojtekmaj** [react-community/create-react-native-app#727]
# Required format for issues

Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

Eject command fails just after choosing an option in "How would you like to authenticate?"

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

![obraz](https://user-images.githubusercontent.com/5426427/43701337-2002b80a-9956-11e8-8df9-caa82a23b3f0.png)

I tried selecting other options, like registering, but it fails too, right after printing the first question in register form.

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: -- react-native-scripts@1.14.0
* `npm ls react-native`: -- react-native@0.56.0
* `npm ls expo`: (updating to 29 doesn't help)
* `node -v`: v10.4.0
* `npm -v`: 6.1.0 
* `yarn --version`: 1.7.0 (running command with npm and yarn doesn't make any difference)
* `watchman version`: command not found

Also specify:

1. Operating system: Windows 10
2. Phone/emulator/simulator & version: just starting my journey, used Expo

**Comment by dogofpavlov** [comment]
hello I also have a very similar problem. Curious what you did to resolve it if anything. or have you been stuck these 15 days?

**Comment by wojtekmaj** [comment]
Sorry @dogofpavlov, I'm still completely stuck. :(
