### ISSUE TITLE
Native component does not exist

### ISSUE THREAD

**Issue by mannyhenri** [react-community/create-react-native-app#73]
I tried using react-native-material-kit with the CRNA and some of it works but the app screams about MKTouchable & TickView when using...

`import { MKTextField, MKColor, MKButton } from 'react-native-material-kit';`

And it gives me this error....

`$ Warning: Native component for "MKTouchable" does not exist`

for both of the above mentioned.

Also reported this issue on [React-native-material-kit repo ](https://github.com/xinthink/react-native-material-kit/issues/307)

**Comment by brentvatne** [comment]
This library requires react-native link, which is not supported without ejecting. It would be nice if material-kit would remove native dependencies or make them optional. Either way, CRNA works as expected here.

**Comment by malikgenius** [comment]
still no solution to this ? CRNA doesnt work with this amazing library ??? its a shame

**Comment by brentvatne** [comment]
@malikgenius - they could remove the dependency on custom native components, should be able to implement any of the stuff they're using native components for with react-native-gesture-handler and built-in primitives in react-native, you could post an issue on that repo about it

**Comment by rochapablo** [comment]
```
Invariant Violation: Native component for "MKTouchable" does not exist
```

```
import { MKButton, MKColor } from 'react-native-material-kit';

<MKButton
  backgroundColor={MKColor.Teal}
  shadowRadius={2}
  shadowOffset={{width:0, height:2}}
  shadowOpacity={.7}
  shadowColor="black"
  onPress={() => {
    console.log('hi, raised button!');
  }}
>
```
