### ISSUE TITLE
ios: Unable to verify Xcode and Simulator installation.

### ISSUE THREAD

**Issue by schickling** [react-community/create-react-native-app#74]
I'm getting the following error when running `npm run ios`:

```
yarn run v0.20.3
$ react-native-scripts ios
Starting packager...
Starting simulator...
Unable to check Xcode version: Error: Process exited with non-zero code: 1
Failed to start simulator:

Unable to verify Xcode and Simulator installation.

Exiting...
```

**Comment by schickling** [comment]
Turned out there weren't any "Command Line Tools" selected in the Xcode settings. After selecting some it worked for me. Here is how it should look like:

![image](https://cloud.githubusercontent.com/assets/1567498/23970903/efe0a670-09cb-11e7-9bdd-f9132cc57541.png)


Hope this helps others running into the same problem 🙂

**Comment by brentvatne** [comment]
@fson - just ran into this setting up a new machine, can we provide a better error message here?

<img width="510" alt="screen shot 2017-08-08 at 5 10 08 pm" src="https://user-images.githubusercontent.com/90494/29099813-734e7f52-7c5c-11e7-8d5f-5310c85e904e.png">

**Comment by fson** [comment]
@brentvatne We certainly can. Perhaps when we detect that Xcode is installed but command line tools are not, we could display a message like:
> Xcode Command Line tools not found. Run the command `xcode-select --install` to install them.

**Comment by brentvatne** [comment]
@fson - i think latest xcode installs command line tools by default, in this case all that's needed is what @schickling mentioned above. not sure what the command would be to run to do that without involving a GUI, we may need to make a quick docs page on the repo that shows the two situations.

**Comment by fson** [comment]
I think the CLI equivalent of selecting the path from the dropdown is `xcode-select -s /Applications/Xcode-beta.app/Contents/Developer` (`-s` is a shorthand for `--switch`). It would be cool if we could do this automatically somehow, but I think it might require `sudo`, so maybe not. 

In any case, once this is implemented, we should test the full flow (no Xcode – Xcode installed – command line tools installed/selected) and verify that the error message makes sense after each intermediate step.

**Comment by jackkinsella** [comment]
I ran into this problem after Apple auto-updated my system. Even though I had xCode etc. working previously, the simulator stopped working with React Native because I had not agreed to Apple's latest terms and conditions. The fix in my case was simply to open xCode and hit "agree".

**Comment by ivivanov18** [comment]
Same solution as for jackkinsella worked in my case.

**Comment by pndirpaya** [comment]
@schickling Thanks for the fix! 🙌🏾👍🏾

**Comment by AbrantesMar** [comment]
I solved the problem Locations->Command Line Tools for version the xCode line

**Comment by rdewolff** [comment]
Thanks for sharing, that did the trick!

**Comment by coocon** [comment]
Thanks for sharing！

**Comment by cseparveen** [comment]
It is working for me..Thanks

**Comment by athulmurali** [comment]
Thanks @schickling  
Your solution worked!

**Comment by michaelroevievictoria** [comment]
@schickling how to get there in my mac, sorry noob here!

**Comment by tpmccallum** [comment]
Thank you, this worked for me.

**Comment by webchick** [comment]
@fson's suggestion at https://github.com/expo/create-react-native-app/issues/74#issuecomment-321302466 still seems worth doing. The current error message left me stumped until I hit up Google for why this was happening and found my way here.

**Comment by expelledboy** [comment]
I feel like the expo package should add a suggestion when this error occurs. Kinda obvious this is a recurring problem. 😄

**Comment by jpfcruz** [comment]
> I solved the problem Locations->Command Line Tools for version the xCode line

This worked for me. The solution was in the XCode Preferences on the Menu Bar (on the Locations Tab, then the Command Line Tools dropdown).

**Comment by AnthonyNasser** [comment]
Same problem, updating expo-cli worked for me: 
npm install -g expo-cli
or 
yarn equivalent

**Comment by fzchriha** [comment]
Since things have changed after years, this is what worked for me in your terminal run: `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

Then run `expo start` again

**Comment by xTobu** [comment]
> Since things have changed after years, this is what worked for me in your terminal run: `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`
> 
> Then run `expo start` again

Thanks @fzchriha 
Your solution is working for me.
Really appreciate 😭

**Comment by Olayinka19** [comment]
Thanks guys it worked!

**Comment by josips9** [comment]
> Since things have changed after years, this is what worked for me in your terminal run: `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`
> 
> Then run `expo start` again

Thanx @xTobu. This solution works out for me. I did have under the locations Xcode in Command Line Tools but still didn't work. After running: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer it works perfectly!

Thank you once again.
