### ISSUE TITLE
Rename repo to create-react-native-expo-app

### ISSUE THREAD

**Issue by onmyway133** [react-community/create-react-native-app#742]
Hi, sorry if this gives any offence. I've just started looking into creating RN apps from native background, so correct me if I'm wrong. 

As stated by https://facebook.github.io/react-native/docs/getting-started.html there's are 2 recommended ways to bootstrap projects: `create-react-native-app` via `expo` or `react-native init`.

At first, `create-react-native-app` gave me impression that it bootstraps toolset like https://github.com/facebook/create-react-app, while offers something more than `react-native init`, but it turned out it's just a limited experience in Expo with opinionated services like Expo push notification https://docs.expo.io/versions/latest/guides/push-notifications.html and connectivity to Google Cloud Platform and AWS

I understand the benefit of Expo and its [caveats](https://facebook.github.io/react-native/docs/getting-started.html#caveats), but the nature of it and the name `create-react-native-app` are not really related.

I would suggest rename this repo to something else, like `create-react-native-expo-app` to better describe its use case, and to avoid confusion

Here are some articles that tell more about this confusion

- https://dev.to/kylessg/ive-released-over-100-apps-in-react-native-since-2015-ask-me-anything-1m9g
- https://dev.to/gaserd/why-i-do-not-use-expo-for-react-native-dont-panic-1bp
- https://hackernoon.com/understanding-expo-for-react-native-7bf23054bbcd
- https://docs.expo.io/versions/latest/introduction/why-not-expo
- https://github.com/react-community/create-react-native-app/issues/516

**Comment by brentvatne** [comment]
Thanks for the feedback!

> At first, create-react-native-app gave me impression that it bootstraps toolset like https://github.com/facebook/create-react-app, while offers something more than react-native init, but it turned out it's just a limited experience in Expo with opinionated services like Expo push notification https://docs.expo.io/versions/latest/guides/push-notifications.html and connectivity to Google Cloud Platform and AWS

Not actually true because you can eject/detach if you need to. The idea is that it's a very quick way to get started.

That said, we're proposing to change to `expo-cli` and this project would then just become a wrapper for that. Read more info at https://github.com/react-native-community/discussions-and-proposals/issues/23
