### ISSUE TITLE
'create-react-native-app' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by gosaingourav17** [react-community/create-react-native-app#743]
# READ THIS FIRST, PLEASE!

The App Store version of the Expo iOS client recently had to remove the QR code scanner from the app. If you intend to load your app on a physical iOS device, please install the latest version of react-native-scripts to your app (`yarn add react-native-scripts@latest` or `npm install react-native-scripts@latest`). It adds the "s" key to the interactive prompt, which asks you to enter an email address or phone number and then sends the URL to your device.

Read more at https://blog.expo.io/upcoming-limitations-to-ios-expo-client-8076d01aee1a. We apologize for any inconvenience this may cause you!

# Required format for issues

Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior

What action did you perform, and what did you expect to happen?

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the *full terminal output and error message* in this code block:

```
Error text goes here!
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
* `npm ls react-native`:
* `npm ls expo`:
* `node -v`:
* `npm -v`:
* `yarn --version`:
* `watchman version`:

Also specify:

1. Operating system:
2. Phone/emulator/simulator & version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by gosaingourav17** [comment]
Description
I used yarn global add create-react-native-app followed by create-react-native-app.The result was error-'create-react-native-app' is not recognized as an internal or external command,
operable program or batch file.

environment:
yarn:1.9.4
os:windows
console:cmd(administrator)

**Comment by rullymartanto** [comment]
I have same problem here
npm ls react-native
-- (empty) 
wonder why npm install -g react-native-cli successfull 

 npm -v
6.4.1
node -v
v10.11.0
Windows 10
console:cmd(administrator)
any help ?

**Comment by rullymartanto** [comment]
I have fix the problem.. 
ADD this path into environment variable C:\Program Files\Git\usr\local

**Comment by gaurangjindal** [comment]
this does not work i tried 

npm -v
6.4.1
node -v
v10.11.0
Windows 10
console:cmd(administrator)
any help ?

**Comment by 16sweetyjain** [comment]
I am getting the same error while running create-react-native-app on my Windows Machine
