### ISSUE TITLE
The host Activity doesn't implement PermissionAwareActivity

### ISSUE THREAD

**Issue by Jing-L** [react-community/create-react-native-app#747]
## Description

When I try to use PermissionsAndroid to require some permissions with my app, I have an error that says:
`Tried to use permissions API but the host Activity doesn't implement PermissionAwareActivity.`

I've used the example code from the React-Native doc.

## Expected Behavior

Android Permissions management

## Observed Behavior

I've done some research that tell me to eject my app from Expo and modify manually the main activity, however, I prefer not do to that for now.

Looking for another solution. 

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: react-native-scripts@1.14.0
* `npm ls react-native`: react-native@0.55.4
* `npm ls expo`: expo@27.1.1
* `node -v`: v8.11.3
* `npm -v`: 6.4.0
* `yarn --version`:
* `watchman version`:

Also specify:

1. Operating system: MACOS
2. Phone/emulator/simulator & version: Galaxy s8 on expo app

**Comment by sangbpark94** [comment]
+1

**Comment by laodimos** [comment]
+1
