### ISSUE TITLE
Errors on 1st start: Unable to perform cache refresh / ECONNREFUSED

### ISSUE THREAD

**Issue by mosesoak** [react-community/create-react-native-app#75]
After creating a fresh project, both `yarn start` and `yarn ios` resulted in the following error:

```
$ react-native-scripts start
Starting packager...
Error starting packager: Error: Unable to perform cache refresh for /Users/mosesgunesch/.expo/cache/versions.json: Error: connect ECONNREFUSED 104.155.140.179:443
    at /xdl/src/tools/FsCache.js:101:15
    at throw (native)
    at step (/Users/mosesgunesch/Documents/projects/creaternapp-starter/node_modules/xdl/build/tools/FsCache.js:32:191)
    at /Users/mosesgunesch/Documents/projects/creaternapp-starter/node_modules/xdl/build/tools/FsCache.js:32:402
error Command failed with exit code 1.
```

After ~2 tries `yarn ios` worked.

**Comment by dikaiosune** [comment]
Hi! Thanks for the report! This is a file that one of CRNA's dependencies downloads on the first run, but I should probably work to make sure this file is cached with the distribution.

**Comment by flarnie** [comment]
Hi @dikaiosune and @mosesoak - I'm also getting this error on my first attempt to use `create-react-native-app` on Windows 10.
Is there a work-around to handle this?
```
Error starting packager: Error: Unable to perform cache refresh for C:\Users\flarnie\AppData\Local\Expo\versions.json: Error: connect ETIMEDOUT 35.184.55.1:443
    at C:\xdl\src\tools\FsCache.js:101:15
    at throw (native)
    at step (C:\Users\flarnie\Code\gumshoe\node_modules\xdl\build\tools\FsCache.js:32:191)
    at C:\Users\flarnie\Code\gumshoe\node_modules\xdl\build\tools\FsCache.js:32:402
error Command failed with exit code 1.
```

I'm going to be helping students use `create-react-native-app` and they may also run into this.

**Comment by dikaiosune** [comment]
@flarnie sorry about that! Expo's site is having a wee bit of downtime at the moment, and this is the last remaining vestige of API interaction that CRNA needs to work. It should work very soon (once things are back up), and I'll reprioritize bundling the JSON this needs with the npm package.

**Comment by flarnie** [comment]
Great to hear - thanks for responding so fast! ⚡️  😄

**Comment by dikaiosune** [comment]
:D 

Looks like things are back online right now, I'll post back once the versions and schema information is bundled on npm.

**Comment by Benxu-Huang** [comment]
Hi every one
I'm also getting this error  on Windows 7.

`
Error starting packager: Error: Unable to perform cache refresh for C:\Users\ben\AppData\Local\Expo\versions.json: Error: getaddrinfo ENOTFOUND exp.host
exp.host:443
    at D:\xdl\src\tools\FsCache.js:101:15
    at Generator.throw (<anonymous>)
    at step (D:\react\createApp\node_modules\xdl\build\tools\FsCache.js:32:191)
    at D:\react\createApp\node_modules\xdl\build\tools\FsCache.js:32:402
error Command failed with exit code 1.
`

Thanks for helping~~

**Comment by smilejos** [comment]
Hi, I get a error message as blow.
Do you have any idea ?

```
Error starting packager: 
Error: Unable to perform cache refresh for C:\Users\user\AppData\Local\Expo\versions.json: 
Error: unable to get local issuer certificate
    at C:\xdl\src\tools\FsCache.js:101:15
    at Generator.next (<anonymous>)
    at step (C:\Users\jtung\workspace\Euro28\node_modules\xdl\build\tools\FsCache.js:32:191)
    at C:\Users\jtung\workspace\Euro28\node_modules\xdl\build\tools\FsCache.js:32:361
```

**Comment by dikaiosune** [comment]
The changes that will resolve this issue have landed: https://github.com/expo/xdl/commit/c7af151dbf8411a2b450ffbd4ccf01bbcfe23399. I'll close this for now, should be resolved in a release later this week.

**Comment by AyoubTorabi** [comment]
hi,
I get a error message as blow(expo on windows10 and on expo ios-app)
2:29:20 PM
Failed to publish package: connect ETIMEDOUT 35.184.55.1:443

**Comment by mark0978** [comment]
I had to create the cache directory in .expo
```
mkdir .expo/cache
```
