### ISSUE TITLE
"User Guide" link is 404 in main README.md

### ISSUE THREAD

**Issue by mo** [react-community/create-react-native-app#752]
![image](https://user-images.githubusercontent.com/7117/44984069-beb26280-af7b-11e8-8958-c3c5e27fa9c1.png)

if you view the README.md for create-react-native-app via github, then the "User Guide" link is 404 ?!

**Comment by xuanus** [comment]
404 for this link 
https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/template/README.md
