### ISSUE TITLE
New CRNA projects uses Expo 27 and not latest expo

### ISSUE THREAD

**Issue by edoantonioco** [react-community/create-react-native-app#756]
## Description

When creating a new project with create-react-native-app, it creates a new project using Expo version 27

## Expected Behavior

[Expo 29 has been around since July](https://blog.expo.io/expo-sdk-v29-0-0-is-now-available-f001d77fadf), and CRNA still uses Expo 27.
I was expecting it to use the latest version.

## Observed Behavior

It uses an old version of Expo

## Environment

1. Operating system: Linux
2. Phone/emulator/simulator & version: Emulator

## Reproducible Demo

Just create a new project using CRNA and check the package.json

**Comment by ericvicenti** [comment]
I've noticed this as well.

cc @brentvatne, how difficult is this to update?

**Comment by brentvatne** [comment]
As per https://github.com/react-native-community/discussions-and-proposals/issues/23, CRNA will be going away and it will be replaced by expo-cli. Follow the link for more info!
