### ISSUE TITLE
npm start stuck forever

### ISSUE THREAD

**Issue by Hypothesis-github** [react-community/create-react-native-app#757]
**Is this a bug report?**
Yes

**Did you try recovering your dependencies?**
So far I have changed the npm version, react native version and expo version with no results.
I have tried that with multiple packages and even applications that previously used to work but no results

**Which terms did you search for in User Guide?**
I have read related topics suggesting me to vary my react native version and alter expo version, but none of them solved the issue.

**Environment**
Environment:
  OS:  Windows 10
  Node:  10.10.0
  Yarn:  1.6.0
  npm:  6.2.0-next.1
  Watchman:  Not Found
  Xcode:  N/A
  Android Studio:  Version  3.1.0.0 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
**Steps to Reproduce
(Write your steps here:)**

npm install -g create-react-native-app
create-react-native-app AwesomeProject
cd AwesomeProject
npm start
**Expected Behavior**
the packager to not get stuck in the start mode

**Actual Behavior**
it does not change state from Starting packager...

**Reproducible Demo**
any new project would do.

**Comment by Hypothesis-github** [comment]
Turns out it is not stuck, it takes 11 minutes on my set up with 12 gb of ram and i7 to run, any suggestions ?

**Comment by geminiyellow** [comment]
same when i upgrade xcode to **Version 10.0 (10A255)**

before upgrade , everything is good. but when updated, all thing suck.
i try to use `crna` create a new project and check if it working.
but,  this screen, 

![image](https://user-images.githubusercontent.com/929878/45729082-cd4c7b00-bc05-11e8-8404-6447b2a6dff6.png)

and nothing happen.

**Comment by YanvegHD** [comment]
Press Q, it'll show the QR Code and URL for expo, happened to me too
