### ISSUE TITLE
CRNA user guide link broken

### ISSUE THREAD

**Issue by AyushG3112** [react-community/create-react-native-app#758]
[https://facebook.github.io/react-native/docs/upgrading](https://facebook.github.io/react-native/docs/upgrading) says:

> Upgrading your Create React Native App project to a new version of React Native requires updating the react-native, react, and expo package versions in your package.json file. Please refer to this document to find out what versions are supported. You will also need to set the correct sdkVersion in your app.json file.
> 
> See the [CRNA user guide](https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/template/README.md#updating-to-new-releases) for up-to-date information about upgrading your project.

The CRNA user guide text links to https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/template/README.md#updating-to-new-releases which is broken.

**Comment by devmetal** [comment]
+1 Its broken for me also. Where is the new? I cannot find :(

**Comment by AyushG3112** [comment]
@devmetal I was able to find the missing file in git history, here's the link

**Comment by AyushG3112** [comment]
https://github.com/react-community/create-react-native-app/tree/58d41288859e6f0e3be801537e355b954fac7c5f/react-native-scripts/template#updating-to-new-releases

**Comment by devmetal** [comment]
@AyushG3112 Thank you :)
