### ISSUE TITLE
"User Guide" link is not working

### ISSUE THREAD

**Issue by atshakil** [react-community/create-react-native-app#765]
## Description

The second link on the [repo homepage](https://github.com/react-community/create-react-native-app) is not working! Is React Community busy with some other more interesting project?

![s1](https://user-images.githubusercontent.com/14325309/45586045-15278580-b91a-11e8-8e38-d34a000d13a6.png)

**Comment by vpontis** [comment]
Find it here: https://github.com/react-community/create-react-native-app/blob/1808872a1f5b69d09ed977a9a04ae689427df095/react-native-scripts/template/README.md
