### ISSUE TITLE
CRNA a new project and upgrade to 0.57 shows error.

### ISSUE THREAD

**Issue by motogod** [react-community/create-react-native-app#766]
## Description

1. CRNA a new project and change it to be a pure react native project.

2. type command `react-native-git-upgrade` and then `npm run ios`

3. the terminal shows error: `error: bundling failed: Error: ENOENT: no such file or directory, open '/Users/motogod19/MyWork/test_up2/node_modules/react-native/node_modules/create-react-class/index.js'`

4. then type `npm install create-react-class` and run the project that shows another error: `error: bundling failed: Error: Unable to resolve module mixInEventEmitter from /Users/motogod19/MyWork/test_up2/node_modules/react-native/Libraries/vendor/document/selection/DocumentSelectionState.js: Module mixInEventEmitter does not exist in the Haste module map`

5. try to change `babel-preset dependency` from official document and turn off terminal.

6. run the project again shows error: `error: bundling failed: TypeError: Cannot read property 'filename' of undefined at PluginPass.JSXOpeningElement (/Users/motogod19/MyWork/test_up2/node_modules/babel-plugin-transform-react-jsx-source/lib/index.js:32:39)` 

What a nightmare if I just want upgrade the new project to 0.57 :(

## Expected Behavior

type command `react-native-git-upgrade` should be successfully upgraded.

## Environment

package.json:
```
{
  "name": "test_up2",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "metro-react-native-babel-preset": "^0.45.0",
    "jest": "^23.6.0",
    "jest-react-native": "^18.0.0",
    "react-test-renderer": "16.3.1"
  },
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "test": "jest"
  },
  "jest": {
    "preset": "react-native"
  },
  "dependencies": {
    "create-react-class": "^15.6.3",
    "react": "^16.5.0",
    "react-native": "^0.57.0"
  }
}
```

.babelrc:
```
{
  "presets": [
    "module:metro-react-native-babel-preset"
  ],
  "env": {
    "development": {
      "plugins": [
        "transform-react-jsx-source"
      ]
    }
  }
}
```

**Comment by eggnukes** [comment]
After checking [VERSIONS.md](https://github.com/react-community/create-react-native-app/blob/master/VERSIONS.md) it seems that react-native 0.57 is not yet supported.
I also wanted to upgrade since support for `textTransform` has been added in `StyleSheet`.

**Comment by motogod** [comment]
Thanks for your information, I got it.  I don't have ant question now. Close it.
