### ISSUE TITLE
--with-web-support in create-react-native-app v2

### ISSUE THREAD

**Issue by arzynik** [react-community/create-react-native-app#769]
Does the v2 release remove web support?

I cant seem to find a way to use it.

**Comment by Taras-Tymchiy** [comment]
Same issue here.
create-react-native-app v2 ignores `--with-web-support` flag
downgrading to create-react-native-app v1 doesn't work either. looks like after publishing v2  the v1 is constantly crashing (It was ok 6 days ago)

So I'm wondering whether
- the create-react-native-app v1 is going to be fixed
- the `--with-web-support` flag will be supported in v2

**Comment by Taras-Tymchiy** [comment]
*UPDATE*
create-react-native-app v1 doesn't crash when used with `--scripts-version 1.14.1
` flag (the latest scripts version before v2)

So the question now is whether the `--with-web-support` is going to be supported in create-react-native-app v2
