### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Cannot find module 'init.js'

### ISSUE THREAD

**Issue by pikapikaa** [react-community/create-react-native-app#770]
## Description

The command create-react-native-app app-name cannot complete the installation process successfully

## Expected Behavior

I expect the installation to complete successfully , a message of "Happy hacking" should appear.

## Observed Behavior

I've tried to completely uninstalling node,  but nothing has changed.

```
$ create-react-native-app plathat
Creating a new React Native app in C:\Users\Bato\Desktop\reactApp\plathat.

Using package manager as yarnpkg with yarn interface.
Installing packages. This might take a couple minutes.
Installing react-native-scripts...

yarn add v1.9.4
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 20 new dependencies.
info Direct dependencies
└─ react-native-scripts@2.0.1
info All dependencies
├─ ansi-styles@3.2.1
├─ babel-runtime@6.26.0
├─ chalk@2.4.1
├─ color-convert@1.9.3
├─ color-name@1.1.3
├─ core-js@2.5.7
├─ cross-spawn@5.1.0
├─ escape-string-regexp@1.0.5
├─ has-flag@3.0.0
├─ isexe@2.0.0
├─ lru-cache@4.1.3
├─ minimist@1.2.0
├─ pseudomap@1.0.2
├─ react-native-scripts@2.0.1
├─ regenerator-runtime@0.11.1
├─ shebang-command@1.2.0
├─ shebang-regex@1.0.0
├─ supports-color@5.5.0
├─ which@1.3.1
└─ yallist@2.1.2
Done in 20.16s.
(node:3528) UnhandledPromiseRejectionWarning: Error: Cannot find module 'C:\Users\Bato\Desktop\reactApp\plathat\node_modules\react-native-scripts\build\scripts\init.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at _callee2$ (C:\Users\Bato\AppData\Roaming\npm\node_modules\create-react-native-app\build\index.js:128:32)
    at tryCatch (C:\Users\Bato\AppData\Roaming\npm\node_modules\create-react-native-app\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\Users\Bato\AppData\Roaming\npm\node_modules\create-react-native-app\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\Bato\AppData\Roaming\npm\node_modules\create-react-native-app\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (C:\Users\Bato\AppData\Roaming\npm\node_modules\create-react-native-app\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\Bato\AppData\Roaming\npm\node_modules\create-react-native-app\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13
(node:3528) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3528) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`:
-- (empty)
* `npm ls react-native`:
-- (empty)
* `npm ls expo`:
-- (empty)
* `node -v`:
v8.12.0
* `npm -v`:
6.4.1
* `yarn --version`:
1.9.4
* `watchman version`:
bash: watchman: command not found

1. Operating system:
Windows 8.1
2. Phone/emulator/simulator & version:
Redmi 6a, Android 8.1

**Comment by ar-maged** [comment]
Same here on macOS HIgh Sierra 👍

**Comment by EVALIJANI** [comment]
because it is over, shame , you have to use the new create-react-native-app with new expo cli instead of react-native-scripts and it is a mess

**Comment by kumudug** [comment]
Having the same issue

**Comment by leakingtapan** [comment]
I was so shocked after finding this fact.

**Comment by m1771vw** [comment]
@EVALIJANI can you explain how to use it with the new expo cli?

**Comment by ujjalacharya** [comment]
I'm getting this error
'Input is required, but expo is in non-interactive mode.'
Can somebody please help me out

**Comment by AnkithVijay** [comment]
I solved it running

npm install -g create-react-native-app

select blank project

create-react-native-app AwesomeProject

**Comment by morenoh149** [comment]
Why aren't docs updated in sync with changes? @hramos 

@pikapikaa fix is to update the docs with new instructions.

**Comment by hramos** [comment]
@morenoh149 please send a PR to https://github.com/facebook/react-native-website to update the docs

**Comment by morenoh149** [comment]
@hramos should https://facebook.github.io/react-native/docs/upgrading refer to crna or expo-cli?

**Comment by KingGeneral** [comment]
First Dont run in `git bash` program, run in `cmd.exe`.

i start to install it globally, like :
- `npm install -g expo-cli`
- `npm install -g watchman`

then i start to install the project using this : 
- `npm install -g create-react-native-app`
- `create-react-native-app AwesomeProject`

it solved for me.

**Comment by MohitKumarMandhre** [comment]
@ujjalacharya try
expo init youappfolder --template blank

**Comment by pakjiddat** [comment]
The error occurs, because the create-react-native-app is using the wrong version of react-native-scripts. It uses the last stable version of react-native-scripts, which is 2.01. This version does not contain the init.js file mentioned in the error message.

To fix the error, we need to use a version of react-native-scripts that is compatible with create-react-native-app. Version 1.4.0 of react-native-scripts seems to be compatible as it was released a few months after create-react-native-app.

So to create a new project using create-react-native-app, use the command: create-react-native-app --scripts-version 1.4.0 [project-name]. This solution worked with create-react-native-app version 1.0.0
