### ISSUE TITLE
How to  Upload 5sec Videos in react-native With PHP and MYSQL

### ISSUE THREAD

**Issue by NickyMwangi** [react-community/create-react-native-app#776]
I really need someone to show me how i can upload to upload a video in react-native to php and mysql. I want to save a 5min video

**Comment by fson** [comment]
This is the issue tracker for Create React Native App, a command-line tool for developing React Native apps. For help with React Native, please check out https://forums.expo.io and https://facebook.github.io/react-native/help instead!
