### ISSUE TITLE
Cannot run application after eject

### ISSUE THREAD

**Issue by ronce96** [react-community/create-react-native-app#777]
## Description
After running `npm run eject` de android project cannot resolve ReactApplication and ReactNativeHost and it does not compile.

## Expected Behavior
I can compile the android project generated by `npm run eject` and execute it in the androi emulator

## Observed Behavior
The project has some errors in the imports, like ReactApplication or ReactNativeHost. The MainActivity does not implement the method `getUseDeveloperSupport()` that is required as it extends `ReactActivity`

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-scripts`: empty
* `npm ls react-native`: react-native@0.55.4
* `npm ls expo`: empty
* `node -v`: v8.11.3
* `npm -v`: 5.6.0
* `yarn --version`: 1.9.4
* `watchman version`: The term 'watchman' is not recognized as the name of a cmdlet

Also specify:

1. Operating system: Microsoft Windows 10 Enterprise
2. Phone/emulator/simulator & version: Android emulator, API 27, Android 8.1 (Google APIs)

## Reproducible Demo
```
$ npm install -g expo-cli
$ expo init my-app
$ cd my-app/
$ npm run eject
```
Then open Android Studio and try to compile the Android project generated after `npm eject`

**Comment by Aximem** [comment]
Same issue, I tried to not use expo CLI and use : 
`react-native eject`
(with defining app.json)
and I have the same issue

**Comment by e1ferapontov** [comment]
Same issue using both new syntax (expo cli) and old

**Comment by iamchathu** [comment]
I think it's because there is no index.js file after eject. Still, there is no update to `.gitignore` after eject too.

**Comment by iamchathu** [comment]
This issue still exists!
