### ISSUE TITLE
Add .flowconfig?

### ISSUE THREAD

**Issue by jevakallio** [react-community/create-react-native-app#79]
Is there interest in adding Flowtype support to the generated app? If yes, I can contribute it. Just want to take a temperature check before doing the work :)

### Steps

What's needed is to figure out the correct local Flow version that matches the underlying `exponent-sdk`'s react-native version, and add the generated `.flowconfig` and `flow-bin` dependency. That's pretty much it.

### Problems

In addition, we need to fix a few issues (or add [ignore]s for them). Currently, for Expo 14.x (React Native 0.41), flow@0.37, there are following issues:
- `.*/node_modules/xdl/build/*` and `.*/node_modules/reqwest/tests/*` need to be ignored.
- `node_modules/react-native/Libraries/EventEmitter/` and `node_modules/fbemitter/` have duplicate @providesModule declarations. Not sure how to fix this beyond ignoring.
- `node_modules/expo/src/Audio.js` as `@flow` declaration, but no type definitions, causing "Missing annotations" error. This can be fixed with either adding types to the file in Expo, or removing the annotation.

**Comment by brentvatne** [comment]
Hi @jevakallio! This would be really nice. I think rather than shipping with a flowconfig we should provide instructions in the README for how to do this, [like with create-react-app]( https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-flow).

Mapping a react-native version to Expo version can be done [with this handy chart](https://docs.expo.io/versions/latest/sdk/index.html#sdk-version).

- re: xdl, sounds good to me.
- re: fbemitter, I think ignoring that is correct.
- re: expo-sdk I think expo-sdk itself needs some more work to make it work seamlessly with Flow. @skevy we should chat about this.

**Comment by jevakallio** [comment]
@brentvatne might I propose a halfway solution: Bundle `.flowconfig` with the template, and include adding the flow-bin dependency as a documentation step.

Reasoning behind this:
1. Flow is already part of the React Native toolchain, so it's more rightful first class citizen for CRNA than CRA.
2. For non-flow users, it is (AFAIK?) harmless, and we already have .watchmanconfig and .babelrc in there, so what's one more dotfile? 😛 
3. The React Native `.flowconfig` tends to be version-specific, so finding the right config will be complicated:
    1. Figure out exponent-sdk version
    2. Figure out matching react-native version (using handly table)
    3. Find the correct tagged version from react-native repo
    4. Find the template .flowconfig
    5. Figure out what fails and add Expo-specific ignores

### Pros
To me it would be a lot easier if we could do this work for people, and then the "Enabling flow" instructions can be as simple as:

1. yarn add --dev flow-bin@(version from .flowconfig)
2. add `flow` npm script step

This will give a lot more flexibility in terms of gradually adding flowtypes to expo-sdk itself, though, as the .flowconfig can control specific configs you may need to set

### Cons

CRNA maintainers will need to update the templated .flowconfig every time they upgrade expo-sdk. 


Thoughts?

**Comment by dikaiosune** [comment]
@jevakallio this is exactly what I had a half-typed proposal for!

I think if we go this route we'll need to have a RELEASES/UPDATING doc because it will probably push the versioning tasks outside what my normal working set is.

**Comment by jevakallio** [comment]
@dikaiosune @brentvatne  I submitted https://github.com/react-community/create-react-native-app/issues/80 with the above-mentioned strategy. Let me know if there's anything you need from me to land it.

**Comment by jevakallio** [comment]
Closed by https://github.com/react-community/create-react-native-app/pull/80
