### ISSUE TITLE
npm WARN deprecated node-uuid@1.4.7: use uuid module instead

### ISSUE THREAD

**Issue by JohannLai** [react-community/create-react-native-app#86]
hello,
  when I ran `create-react-native-app` ,I got this warning.

**Comment by dikaiosune** [comment]
Specifically:

```
warning react-native-scripts > xdl > node-uuid@1.4.7: use uuid module instead
...
warning react-native > xcode > node-uuid@1.4.7: use uuid module instead
```

The first issue is one I can fix upstream very easily. The latter means that this line https://github.com/facebook/react-native/blob/master/package.json#L210 needs an upgrade and to get tests passing and merged.

**Comment by dikaiosune** [comment]
The new version of xdl (0.40) has moved to the bare uuid package, so that's one issue down. I believe RN 0.44 or 0.45 will include a fix for the xcode dependency.

**Comment by ye4ever** [comment]
so we have to install uuid and npm ?? if yes 
what is command for install uuid ?
thanks

**Comment by dikaiosune** [comment]
@ye4ever you shouldn't need to take any steps. These are just warnings.

**Comment by veljkoo** [comment]
The eaisiest way to solve deprecated uuid is:
Type: npm install uuid

**Comment by brentvatne** [comment]
this warning is gone now
