### ISSUE TITLE
TypeScript?

### ISSUE THREAD

**Issue by sberan** [react-community/create-react-native-app#87]
Any ideas for ways to use typescript instead of flow?

**Comment by dikaiosune** [comment]
I believe most of the instructions in [this article](https://medium.com/react-weekly/react-native-and-typescript-ad57b7413ead#.s13wts6yr) will work for CRNA projects, with some caveats.

1. Instead of using react-native-cli, you'd want to init your project with CRNA and use its scripts for starting the RN packager.
2. In the section 'Prepare React Native app,' I think you'd need to use a different filename than `index.tsx` maybe something like `RealRoot.tsx`. Then, in your project's `App.js` file, you would just import your TypeScript component from your build directory (`build/RealRoot`, for example), and re-export it as the default component. As of right now, the `App.js` entry point is hardcoded in CRNA, but I expect I'll add the ability to override that path with an environment variable in the future. Until that happens, you'll need to perform this extra layer of indirection.
3. Don't overwrite CRNA's scripts with the calls to local-cli.js that the article shows.
4. Run iOS and Android as you normally would for CRNA.

If this works for you, let me know and I'll work on including this in the official user guide. If not, let me know what problems you run into.

**Comment by pierre-H** [comment]
Thank you @dikaiosune for your explanation. I tried it and I've got this error : 

> $ tsc
> error TS6059: File 'C:/Users/pp/Documents/app/App.js' is not under 'rootDir' 'C:/Users/pp/Documents/app/src'. 'rootDir' is expected to contain all source files.
> error TS6059: File 'C:/Users/pp/Documents/app/App.test.js' is not under 'rootDir' 'C:/Users/pp/Documents/app/src'. 'rootDir' is expected to contain all source files.

**Comment by pierre-H** [comment]
I added App.js and App.test.js in the exclude array in tsconfig and now I've got many errors like : 

> typings/modules/react-native/index.d.ts(8421,4): error TS2503: Cannot find namespace 'React'.

**Comment by dalcib** [comment]
In `tsconfig.json` with Typescript 2.2 you can use `"jsx": "react-native"` to generate only js files, and not jsx.

**Comment by dikaiosune** [comment]
Cool! If you have a complete example to reference and a full list of the steps you took, I'd be interested in writing a doc about this.

**Comment by pierre-H** [comment]
I did this : 
```shell
react-native init app
cd app
tsc --init
yarn add @types/react @types/react-native
```

Use this tsconfig : 
```json
{
    "compilerOptions": {
        "target": "es2016",
        "module": "commonjs",
        "jsx": "react-native",
        "outDir": "build",
        "rootDir": "src",
        "allowSyntheticDefaultImports": true,
        "noImplicitAny": true,
        "experimentalDecorators": true,
        "preserveConstEnums": true,
        "allowJs": true,
        "sourceMap": true,
        "forceConsistentCasingInFileNames": true,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "strictNullChecks": true,
        "suppressImplicitAnyIndexErrors": true,
        "noUnusedLocals": true,
        "skipLibCheck": true,
        "moduleResolution": "node"
    },
    "exclude": [
        "App.js",
        "App.test.js",
        "build",
        "node_modules"
    ],
    "compileOnSave": false
}
```

Then I create **src/AppRoot.tsx**, the react component root of the app, and in the **App.js** I import **build/AppRoot**.

This works perfectly. You only have to launch `tsc` to recompile ts to js or to do `tsc --watch`.

**Comment by dalcib** [comment]
I use almost the same tsconfig.json, but I use `"module": "es2015",` that produce code with import and export, like a normal code in react-native.

Another trick is to use the package `tslib` with the follow options in the tsconfig.json:
`"noEmitHelpers": true, 
 "importHelpers": true,`
It produces a cleaner code because don't include helpers like decorators, etc.
https://blog.mariusschulz.com/2016/12/16/typescript-2-1-external-helpers-library

**Comment by pierre-H** [comment]
One limitation : can't use apparently console.log https://docs.expo.io/versions/v16.0.0/guides/logging.html

**Comment by pavloko** [comment]
@dalcib @pierre-H What are you strategies for resolving `import Component from './component` when `component.android.js` or `compoent.ios.js`?

**Comment by pierre-H** [comment]
@pavloko with CRNA, I don't use `.android.js` and `.ios.js` files. One advantage of CRNA and Expo is that you can write the same code for iOS and Android. So I think you should do something like this : 

```typescript
import { Platform } from 'react-native';

if (Platform.os === 'ios') {
    import ComponentIOS as Component from './component.ios.js';
} else {
    import ComponentAndroid as Component from './component.android.js';
}
```
Please, note that your question is not directly related to the initial question (use of typescript instead of flow). So the next time, please open a new issue. Thanks !

**Comment by dalcib** [comment]
I published the [jest-expo-ts](https://github.com/dalcib/jest-expo-ts) package, wich allows using Jest with Typescript in create-react-native-app and Expo. I am looking forward to the next Expo version with react-native 0.45 to use [react-native-typescript-transformer](https://github.com/ds300/react-native-typescript-transformer). I think with both packages, the problem of use Typescript with react-native will be solved.

**Comment by brentvatne** [comment]
cool stuff @dalcib! will this play nicely with `babel-preset-expo`? one important thing that the expo preset provides is an alias for react-native-vector-icons: https://github.com/expo/babel-preset-expo/blob/ed0162c7e24fea6f304f34db40807f44e868f565/index.js#L3-L12

**Comment by wcandillon** [comment]
@dalcib Thank you so much for working on this 🙏 this is amazing

**Comment by dalcib** [comment]
@brentvatne,  `babel-preset-expo` is used in the transpile process, but it doesn't apply to Jest. Expo uses `babel-jest`preset in Jest with `jest-expo` package.
I am trying to implement the module aliasing with `jest-alias-preprocessor` but it isn't working yet.

**Comment by preetb123** [comment]
@dalcib I am beginner in react-native and js. Can you please explain what is react-native-typescript-transformer and how will it solve problem of using typescript in RN projects?

**Comment by dalcib** [comment]
@preetb123, it allows to use Typescript whit minimal configuration without need to generate js files. The best away to use Typescript today is to transpile the ts/tsx files to js, and then let react-native to observe the js files. It will not be need with this package in react-native 0.45.

**Comment by dalcib** [comment]
@brentvatne, it is done. With the new version of `jest-expo-ts` you can test your Expo app with Jest and the package `react-native-vector-icons` will be aliased to `@jest/vector-icons`

**Comment by zunder** [comment]
@dalcib But react-native 0.45 is already being released. Does it mean we can use react-native-typescript-transformer in order to launch with expo?

**Comment by dalcib** [comment]
@zunder, `expo@17:0:0` depends on `react@0.44.0`. So, we need to wait for `expo@18.0.0`.

**Comment by preetb123** [comment]
Hi @dalcib expo@18.0.0 is released. Can you please create an example that demonstrates how to use typescript with CRNA or Expo with jest-expo-ts integrated?

**Comment by dalcib** [comment]
Hi @preetb123, take a look in [https://github.com/dalcib/expo-ts-exemple](https://github.com/dalcib/expo-ts-exemple)

**Comment by CervantesVive** [comment]
For the life of me I cannot get this to work.

I get

`undefined is not an object (evaluating 'react_1.default.Component')`

**Comment by dalcib** [comment]
To use react-native-typescript-transformer you should use this configuration:
```
{
  "compilerOptions": {
    "target": "es2015",
    "module": "es2015",
    "jsx": "react-native",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true
  }
}
```
I am going to clarify it in the Readme.md

**Comment by CervantesVive** [comment]
Thanks @dalcib ! 

I had to disable `sourceMap` as well as I was getting 

`Error: Got at least one module with a full source map, but /Users/cv/project/node_modules/core-js/library/fn/object/get-prototype-of.js has raw mappings`

Does appear to work now.

**Comment by bigradish** [comment]
@dalcib you said by using react-native-typescript-transformer, .ts files do not need to be complied to .js files. But one of advantages of Typescript is finding syntactic errors during the compiling process. How do you think of this?

**Comment by dalcib** [comment]
@bigradish , just to clarify, what I wanted to say is that before react-native-typescript-transformer the better way to use react-native with typescript was compiled .ts files to .js files and let the react-native packager to watch the .js files. With react-native-typescript-transformer the compilation is made in memory.

**Comment by bigradish** [comment]
@dalcib thanks for response. If there are syntactic errors in the .ts files, can react-native-typescript-transformer point them out just like Typescript?

**Comment by dalcib** [comment]
@bigradish, take a look at this: 
https://github.com/ds300/react-native-typescript-transformer/issues/13#issuecomment-309208994

**Comment by bigradish** [comment]
@dalcib just a limit support for detecting syntax errors.
Using  react-native-typescript-transformer also means an extra overhead for converting ts code to js code whenever running your app, right?

**Comment by mathieudutour** [comment]
I made a small thing for people who want to get started with create-react-native-app and typescript: https://github.com/mathieudutour/create-react-native-app

**Comment by danieloprado** [comment]
https://github.com/ds300/react-native-typescript-transformer

Works like a charm!

**Comment by lslima91** [comment]
hey guys, check this out 
http://artsy.github.io/blog/2017/11/27/Babel-7-and-TypeScript/

**Comment by pranav-pandey** [comment]
Hi, I followed everything but the build folder is not being generated for me on npm start (through Expo). this is the script that's being fired up
`  "scripts": {
    "start": "react-native-scripts start"
}
`
devDependencies
`  "devDependencies": {
    "jest-expo": "25.0.0",
    "react-native-scripts": "1.11.1",
    "react-test-renderer": "16.2.0",
    "tslint": "^5.9.1",
    "typescript": "^2.7.1",
    "typings": "^2.1.1"
  },
`

**Comment by preetb123** [comment]
@pranav-pandey if you want to use typescript without much configuration, below are the two options
1. With CRNA: https://github.com/mathieudutour/create-react-native-app-typescript (you should upgrade the dependencies)
2. Without CRNA: https://github.com/huestack/create-react-native-typescript-app
