### ISSUE TITLE
"Create a React Native app on any OS..." is that really true or misleading?

### ISSUE THREAD

**Issue by neminovno** [react-community/create-react-native-app#89]
"Create a React Native app on **any OS** with no build config."
Do you mean any mobile OS or?

**Comment by dikaiosune** [comment]
It's meant as "on any desktop OS with significant enough market share to be compatible at all with React Native's dependencies," so pretty much Linux, Mac, and Windows. That, however, is a big mouthful and nuance rarely does well in a slogan. Right now Android and iOS are supported, and other mobile OSes aren't.

**Comment by neminovno** [comment]
Thank you. After reading docs, it looks like Windows 7 is not supported, but it still has larger market share than Windows 10 (which is supported by React Native). Is that true? Is it possible to build native app with React Native for Windows 7?

**Comment by dikaiosune** [comment]
What section of the docs are you referring to? I test regularly on Windows 10, but don't have the bandwidth to also test against Windows 7/8. That said I'm not immediately aware of anything that will prevent CRNA from working on Windows 7.

**Comment by neminovno** [comment]
Well I would say all docs that I can find.. Just can't find how to build Windows 7 native application with using React. For example official ones "forces" mobile dev when you see this:
http://facebook.github.io/react-native/releases/0.42/docs/getting-started.html
where windows OS is only considered as development platform:
![image](https://cloud.githubusercontent.com/assets/1468887/24076945/edcc3592-0c3d-11e7-9dd5-e541bcd434cc.png)

Also there is no proper answer for [this reddit](https://www.reddit.com/r/reactnative/comments/3plf8g/react_native_for_windows_7/).

Then, there is [react-native-windows](https://github.com/Microsoft/react-native-windows) where Windows 7 is not supported.

On these pages one can't find word "windows":
https://github.com/react-community/create-react-native-app
https://github.com/react-community/create-react-native-app/blob/master/react-native-scripts/template/README.md

That is why I asked is it really for "any OS"?
Simple _Guide for Windows_ would be great. Where to find it? I would really like to try to move some large projects to React, with targeting still most used OS in the world - Windows 7.

**Comment by zusamann** [comment]
@neminovno CRNA is for creating Mobile Native Apps not Desktop Native Apps. So no, you can't create a native Windows 7 App with it.

Also the tagline says "Create a React Native app on any OS..."
which means you can use the tool CRNA on any OS

it doesn't say "Create a React Native app for any OS..."
which would mean you can create an app for any OS

**Comment by neminovno** [comment]
@zusamann Thank you, that makes it clear.

**Comment by sasivarnan** [comment]
Any plans to support [react-native-windows](https://github.com/Microsoft/react-native-windows/)?

**Comment by brentvatne** [comment]
@sasivarnan - not at the moment, it would be a massive undertaking because we would need to build Expo client (http://github.com/expo/expo) for UWP and we don't have bandwidth for that
