### ISSUE TITLE
Wrong Server IP

### ISSUE THREAD

**Issue by maxjf1** [react-community/create-react-native-app#90]
When i run npm start, the IP Address selected to be the server is wrong.
I have VirtualBox installed on my PC and it creates a local network, with a different IP address. The Server is started on this IP Address, not my real IP Address.
To get it working, i need to disable the virtual box network and restart the server.

**Comment by dikaiosune** [comment]
Hi! Thanks for the report. This looks like a duplciate of #60 to me. There is a workaround in that thread, and I have plans to improve this in the near future.
