### ISSUE TITLE
Querying device orientation

### ISSUE THREAD

**Issue by jpke** [react-community/create-react-native-app#93]
Is it possible to enable a way to determine if device is in landscape or portrait view? Currently, the only way I see to it is ejecting and linking a third-party library into the app.

**Comment by scmx** [comment]
Yes, see https://corbt.com/posts/2016/03/16/detecting-orientation-in-react-native.html

Use `<View onLayout={this._onLayout}>` and then
```
const { width, height } = event;
const orientation = (width > height) ? 'LANDSCAPE' : 'PORTRAIT';
```

**Comment by jpke** [comment]
Oh, gotcha, thanks! Sorry, don't know how I missed that in google.
