### ISSUE TITLE
Stopping packager doesn't wait for forked process

### ISSUE THREAD

**Issue by chrislloyd** [react-community/create-react-native-app#94]
Every time I press CTRL-C, it appears as though the main process exits and yields back to the user, while another process prints "PACKAGER STOPPED". I'd expect that line to be printed _before_ the main process exits.

<img width="303" alt="screen shot 2017-03-18 at 8 15 55 pm" src="https://cloud.githubusercontent.com/assets/718/24077855/3cc5087a-0c18-11e7-9b17-090bcf0d1c0d.png">

**Comment by dikaiosune** [comment]
We just released a new version with some different logging stuff (thanks again @brentvatne!) and I'm no longer seeing this behavior on my mac. If you update and still see it, please let me know and I'll reopen.
