### ISSUE TITLE
Need a common font abstraction between vanilla React Native & Expo

### ISSUE THREAD

**Issue by ArashMotamedi** [react-community/create-react-native-app#96]
Thank you for this excellent tool.

As many React Native UI libraries come bundled with custom fonts (or require them to be present), would it be possible to include an easy way to supply the fonts? E.g. a specific folder at the root of the project whose content would be loaded and linked appropriately to the target device?

**Comment by brentvatne** [comment]
Hello there! This is possible already using the Expo Font API: https://docs.expo.io/versions/v15.0.0/guides/using-custom-fonts.html - check out an example of it here: https://github.com/brentvatne/custom-font-example

@dikaiosune and I are considering building a version of this that isn't tied to Expo at all so you can eject from CRNA without going to ExpoKit and not have to change your font loading code at all.

**Comment by dikaiosune** [comment]
Reopening as tracking issue for building this hypothetical font API.

**Comment by joelgetaction** [comment]
@brentvatne - curious why this issue was closed?  I just ejected from CRNA and expo to regular react native and now all of my fonts are broken.  It would be really handy to have a better solution than "do it all over again once you eject" ... :-)  I can help if you can give me some suggestions!
