### ISSUE TITLE
Error while fleshing a new app using create-react-native-app

### ISSUE THREAD

**Issue by unicodeveloper** [react-community/create-react-native-app#98]
It fails to finish install due to this error below. What could be wrong? It's coming from ngrok

![error-react-native](https://cloud.githubusercontent.com/assets/2946769/24088503/665a3430-0d2b-11e7-910d-75c71674f629.png)

**Comment by unicodeveloper** [comment]
@dikaiosune  Please could you advise on what to do here? Thanks

**Comment by dikaiosune** [comment]
Are you on a reliable internet connection? My guess is that the tarball failed to download on your connection.

**Comment by unicodeveloper** [comment]
Alright. Let me retry it on a better connection. Thanks

**Comment by unicodeveloper** [comment]
It worked @dikaiosune . Thanks
